### ISSUE TITLE
Dockerfile does not use correct environment variable for config path

### ISSUE THREAD

**Issue by mandiwise** [apollographql/router#1008]
The latest release of the router ([v0.9.0-rc.0](https://github.com/apollographql/router/releases/tag/v0.9.0-rc.0)) indicates that the `CONFIGURATION_PATH` environment variable has been renamed `APOLLO_ROUTER_CONFIG_PATH`. However, this variable was changed to `APOLLO_ROUTER_CONFIGURATION_PATH` in `Dockerfile.router`:

https://github.com/apollographql/router/blob/c11f4778e0f236d68e99bb75d36550e875a66124/dockerfiles/Dockerfile.router#L31

As a result, the router no longer loads the `router.yaml` file when started in a Docker container.

**Comment by abernix** [comment]
Fixed by #1013.  Thanks for reporting this!
