### ISSUE TITLE
Usage reporting: add error stats 

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1011]
There's a couple fields in our `reports.proto` that we are not populating right now that would help power the `https://studio.apollographql.com/graph/{GRAPH_ID}/operations?tab=errors&variant={VARIANT}` page that we would be good to add to the Router.  These include:

- `root_error_stats`
- `requests_with_errors_count`

## Needs to be investigated

* We should look at how Apollo Server and Apollo Gateway capture this information.

**Comment by abernix** [comment]
@jsegaran @sachindshinde Are we correct in understanding the purpose of these fields and their importance?

**Comment by abernix** [comment]
Relates to #74

**Comment by abernix** [comment]
We do now capture this information and this was accomplished as part of #74.  We do not yet populate `Error` itself, but that will be tracked in another issue.
