### ISSUE TITLE
Zipkin must not have an agent endpoint configuration option

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1024]
currently Zipkin is configured like other telemetry options, with either an agent endpoint or a collector endpoint.
But the aagent endpoint part is actually setting the address with [`with_service_address`](https://docs.rs/opentelemetry-zipkin/latest/opentelemetry_zipkin/struct.ZipkinPipelineBuilder.html#method.with_service_address), which is actually used as metadata in the trace, not as the address of the Zipkin service
https://github.com/apollographql/router/blob/b7d90eda521dc5b7bd522d94b6311e32cc0f99b4/apollo-router/src/plugins/telemetry/tracing/zipkin.rs#L50-L54

So the agent endpoint should be removed, and possibly service address metadata should be configurable

**Comment by BrynCooke** [comment]
After changes make sure to check the generated json schema behaves nicely.

**Comment by Geal** [comment]
how do I verify it behaves nicely?

**Comment by BrynCooke** [comment]
The files in https://github.com/apollographql/router/tree/main/apollo-router/src/configuration/testdata need updating and maybe extending. Just adding similar files will cause the tests to verify that they validate against schema.
