### ISSUE TITLE
Remove `apollo-key` as CLI flag argument, require env variable

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1054]
Currently, `StructOpt` allows us to easily have matching environment variable and CLI flags.  For the `apollo-key`, **we should disable** the CLI part of it since that property — unlike the environment variable — can be seen in the running process list (e.g., via `ps`).

https://github.com/apollographql/router/blob/53e49e58430640adaaa867c818c6101910c4c7b4/apollo-router/src/plugins/telemetry/apollo.rs#L14-L16

**Comment by BrynCooke** [comment]
Suggest using the `skip` option. Unfortunately this means that the env variable will be removed from help, so if graph ref is set and `APOLLO_KEY` as not been set we should print a nice error message?

**Comment by abernix** [comment]
I believe that the default router experience says something about these environment variables, which can help.  I agree that it's unfortunate that we'd lose that automatic feature, so I would support a nice error message in the event of someone passing `apollo-greph-ref` without `apollo-key`.  We'd perhaps want to introduce some other help stuff in the future, possibly even a command that explicitly talks about the environment variables that the Router supports.

Since these are environment variables that are meant to be set together though, should we also remove `apollo-graph-ref` from the CLI flags?

**Comment by BrynCooke** [comment]
Seems reasonable to me
