### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by yanns** [apollographql/router#1065]
**Describe the bug**
The federation router's memory consumption goes very high suddenly.

**To Reproduce**
We can reproduce this issue on two different environments.
- On a Kubernetes cluster, we set a maximum of memory.
  After start, during some minutes, the memory consumption is stable.
  Then it suddenly goes high. Kubernetes kills the pod and restarts it.
  Example of memory usage of one pod:
  <img width="1277" alt="Screenshot 2022-05-16 at 17 23 48" src="https://user-images.githubusercontent.com/51669/168627845-5916e134-99d2-41d0-b747-83559c075ccf.png">
We cannot really observe the memory going high, and this goes very fast.

- Locally, on mac, I can reproduce this behavior with some tests. When the router starts, it consumes about 250 Mi of memory. After some tests, the memory goes very high. Here is one sample.
  [Sample of federation-router.txt](https://github.com/apollographql/router/files/8701358/Sample.of.federation-router.txt)
  I don't know if it helps. I can try to use http://www.cmyr.net/blog/rust-profiling.html to provide more data.

**Expected behavior**
The memory consumption can go higher, but should stay stable.

**Additional context**
I've tried with different versions, and it does not make any difference. We are now using the version `v0.9.0`.

**Comment by garypen** [comment]
Hi @yanns. Thanks for filing the issue. Could I request a some additional information:

 - what are you setting the memory limit to? Ideally, I'd like to know: `requests.memory` and `limits.memory`
 - approx how many clients are driving the failing instance? 10s, 100s, 1000s ?
 - are there any ERROR or WARN messages in the router logs?

**Comment by yanns** [comment]
> Hi @yanns. Thanks for filing the issue. Could I request a some additional information:
> 
>     * what are you setting the memory limit to? Ideally, I'd like to know: `requests.memory` and `limits.memory`

I'm using `requests.memory` = `limits.memory` = `"400Mi"`
I've already tried giving several Gi memory, and it does not change anything.
When the router starts consuming more memory, its consumption grows continuously, without any end that I could set.
Locally I have to kill the process that is using always more memory.
It's as if a recursive data structure was starting using itself without any boundary.

>     * approx how many clients are driving the failing instance? 10s, 100s, 1000s ?

10s

>     * are there any ERROR or WARN messages in the router logs?

Only WARN about `apollo_router_core::plugins::csrf: request is preflighted`. (and I've noticed that this was changed to trace recently)

**Comment by yanns** [comment]
I can reproduce this issue locally with some mutations. One GraphQL query with such mutation is enough to reproduce this behavior.
The federation router never answers, it starts consuming more & more memory, and the client times out at some point.

The mutation contains a field value of type String that contains an escaped json, like: `value: "\"aValue\""`.

**Comment by yanns** [comment]
I've added some `println!` in the `fn subgraph_service` to trace the SubgraphResponse.
In normal cases, I can observe those `SubgraphResponse` being output.
In the issue with the `"\"abc\""` string, I cannot observe any response from the subgraph.
The issue might be when parsing the GraphQL mutation.

**Comment by yanns** [comment]
I've tried to reproduce this case by changing an [existing integration test](https://github.com/apollographql/router/blob/main/apollo-router/tests/integration_tests.rs#L161), but no luck so far.

**Comment by Geal** [comment]
is a request actually sent to the subgraph (as seen from the nhetwork or the subgraph point of view) or does it actually stop at the router?

**Comment by garypen** [comment]
It's almost certainly an issue in the parser. I'm just trying to figure out a good way to reproduce it in our test setup so that I can confirm this.

**Comment by yanns** [comment]
@Geal The subgraph does not receive any request. It seems to stop at the router.

**Comment by garypen** [comment]
That fits with parser issues. Can you give us an example of the mutation you found which is failing (as long as it's not confidential/private)?

**Comment by yanns** [comment]
The mutation is very simple:
```
          mutation {
            createStore(draft: {
              name: [{ locale: "en", value: "\"my store\"" }]
            }) {
              name(locale: "en")
            }
          }
```

I find it strange that I cannot reproduce it with the integration tests.

**Comment by garypen** [comment]
I can't reproduce it in the router, but I did the following.
1. Create a new rust project `my-parser` which uses `apollo-rs` to parse the provided mutation.
2. run `my-parser` and watch my memory disappear (let it get to 13G before terminating)

Sample program:
```
fn main() {
    use apollo_parser::Parser;

    let input = r#"mutation {
            createStore(draft: {
              name: [{ locale: "en", value: "\"my store\"" }]
            }) {
              name(locale: "en")
            }
          }"#;
    let parser = Parser::new(input);
    let ast = parser.parse(); // <- This will never return until memory exhausted.
}
```

**Comment by garypen** [comment]
@yanns  I've filed an issue against `apollo-parser`. Once we have a fix available, we'll release a patch for the router.

**Comment by yanns** [comment]
Thanks for the quick release.
I've tested with https://github.com/apollographql/router/releases/tag/v0.9.1, and the issue is now fixed. ❤️
