### ISSUE TITLE
Be more specific about cargo-deny targets

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#107]
followup to #89 , we're currently running checks on every available target.

We're however only releasing for x86_64, linux, osx and windows.

We might want to [add our targets to cargo-deny.toml](https://github.com/EmbarkStudios/cargo-deny/blob/d0ea0a2e7d7376ee212faec756cb12ab05f55c4d/examples/08_target_filtering/README.md#description)

**Comment by abernix** [comment]
Running it on all targets is pretty defensive, albeit maybe not the most efficient.  I'll close this as we've deferred this for a while now.  Let's re-open if we decide we need to.  Thanks!
