### ISSUE TITLE
Change the Context::upsert() interface

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1070]
**Is your feature request related to a problem? Please describe.**

The existing interface requires a callback to set the default value of the new entry.

**Describe the solution you'd like**

Require `upsert()` values to be `Default`:

```
-    pub fn upsert<K, V>(
-        &self,
-        key: K,
-        upsert: impl Fn(V) -> V,
-        default: impl Fn() -> V,
-    ) -> Result<(), BoxError>
+    pub fn upsert<K, V>(&self, key: K, upsert: impl Fn(V) -> V) -> Result<(), BoxError>
     where
         K: Into<String>,
-        V: for<'de> serde::Deserialize<'de> + Serialize,
+        V: for<'de> serde::Deserialize<'de> + Serialize + Default,
     {
```
This simplifies the API and makes it more approachable. Also, slightly easier to interact with from `Rhai`. If we ever find a use case for a `default` parameter, we can add a new function `add_with_default` which basically restores the existing fn with the new name.

**Describe alternatives you've considered**

Leave things as they are.

**Additional context**
N/A

**Comment by abernix** [comment]
Closed by https://github.com/apollographql/router/pull/1073
