### ISSUE TITLE
__typename for query type results in invalid query causing introspection error

### ISSUE THREAD

**Issue by DoumanAsh** [apollographql/router#1099]
**Describe the bug**
When specifying `__typename` for `query <name>`, query planner fails with introspection error:
```
{"errors":[{"message":"introspection error : Cannot return null for non-nullable field Query.meType.","locations":[],"path":null}]
```

**To Reproduce**
You can use my repo example https://github.com/DoumanAsh/graphql-router-example/pull/2
Query in question: https://github.com/DoumanAsh/graphql-router-example/blob/query_typename_fail/tests/router.rs#L378=

```graphql
    fragment TypeBase on UserType {
      __typename
      description
    }
    query Query {
      __typename
      meType {
        ...TypeBase
      }
    }
```

**Expected behavior**
Successfully work
`__typename` for `query` should be valid and return name of query:

**Comment by DoumanAsh** [comment]
@bnjjj I was looking at code and it seems to be coming from here https://github.com/apollographql/federation-rs/blob/main/federation-2/router-bridge/src/introspect.rs#L85-L93=

I tried to pull `graphql.js` repo and write small test to reproduce it, but doesn't seem to trigger errors...

**Comment by DoumanAsh** [comment]
Ah I see what you mean... it is not just introspection query and so shouldn't be propagated to JS bridge...

**Comment by bnjjj** [comment]
Exactly, I made a PR to fix it :) Thanks for your issue

**Comment by DoumanAsh** [comment]
Ok, do you plan to release new version soon?
I can write test for this PR then

**Comment by DoumanAsh** [comment]
As a side note, router service doesn't propagate top `__typename` so `it will not return it in response.
Not sure how critical it is (We normally do not need it, but our graphql client library inserts `__typename` there for some reason)

**Comment by bnjjj** [comment]
You're right, issue https://github.com/apollographql/router/issues/1101 created
