### ISSUE TITLE
unable to download binary 

### ISSUE THREAD

**Issue by manjeettahkur** [apollographql/router#1109]
**Describe the bug**

**To Reproduce**

Downloading release info for 'https://github.com/apollographql/router/releases'
Found router-0.9.1.exe-x86_64-windows.tar.gz
Downloading router from https://github.com/apollographql/router/releases/download/v0.9.1/router-0.9.1.exe-x86_64-windows.tar.gz
curl: (22) The requested URL returned error: 404
Failed to download https://github.com/apollographql/router/releases/download/v0.9.1/router-0.9.1.exe-x86_64-windows.tar.gz

**Expected behavior**

I think it should work 

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS:  Microsoft Windows 10 Pro for Workstations
 - Version: Version	10.0.19044 Build 19044

**Comment by Geal** [comment]
Hi! this is fixed by #1098 and should be available for the next release
