### ISSUE TITLE
How can we ignore SSL error in ApolloRouter

### ISSUE THREAD

**Issue by cli00004** [apollographql/router#1111]
**Is your feature request related to a problem? Please describe.**
Previously in ApolloFederation, we could override the fetcher config to ignore SSL errors like this. How do we achieve the same result in ApolloRouter now? 
```
buildService({ url, name }) {
    return new (class extends RemoteGraphQLDataSource {
      fetcher = require('make-fetch-happen').defaults({
        strictSSL: false
      });
    })({
      url,
      name
    });
  },
```

**Describe the solution you'd like**
Is there a config I can set in the router.yaml?

**Describe alternatives you've considered**

**Additional context**

**Comment by Geal** [comment]
hello! what kind of SSL error are you getting?

**Comment by cli00004** [comment]
hi @Geal  i'm using a company/self signed certificate as the subgraph urls are internal and we are getting invalid cert error. We'd like to be able to skip checking the cert error like the previous federation
![image](https://user-images.githubusercontent.com/94087985/169512147-952380b3-c1a4-472a-980c-76e519562215.png)

**Comment by Geal** [comment]
I see. In that case, deactivating SSL verification is not the right solution: it exposes the connection to man in the middle attacks where someone would try to pass as the subgraph by serving a different certificate.

In the router we use the [rustls-native-certs](https://crates.io/crates/rustls-native-certs) library to load the list of trusted root certificates from your OS, that can be stored in various places (example: in `/etc/ca-certificates` or `/usr/lib/ssl/certs`), so you can add the self signed certificate to the trusted roots, or alternatively use the `SSL_CERT_FILE=/path/to/the/certificate` environment variable when starting the router.

If you do that the router will accept the self signed certificate, and will also be able to verify it, protecting the subgraph connection against attacks.

**Comment by cli00004** [comment]
Thanks a lot @Geal  i'm trying to do what you suggest now. However, after i added the file to the folder you specified, i'm still getting the same error. Do i need to run update-ca-certificates or other configs? I didn't specify SSL_CERT_FILE and i'm running the router file in a debian docker container
![image](https://user-images.githubusercontent.com/94087985/169526509-9acf1285-bb64-48a8-9353-c7df00e2a359.png)
![image](https://user-images.githubusercontent.com/94087985/169526571-4dbc14be-c371-4afa-af44-55b14efd217c.png)

**Comment by Geal** [comment]
it looks like ``/etc/ca-certificates` is not the right place. You should try with `SSL_CERT_FILE`  instead, so you won't lose time looking for the certificates list. If you want to search for the folder, here's a list of possible locations: https://github.com/alexcrichton/openssl-probe/blob/master/src/lib.rs#L27-L42 (depending on the OS, dfistribution or even version of the distribution it might change)

**Comment by cli00004** [comment]
@Geal Yes, got it working with this env variable, thanks so much !

**Comment by Geal** [comment]
awesome :)

**Comment by Oleshkooo** [comment]
Hi! In any case, is it still possible to disable SSL checking for subgraphs? I have some issues with one of the subgraphs and would like to make requests without strict SSL. In Apollo Gateway, we have solved this in the following way:

```typescript
class CustomRemoteGraphQLDataSource extends RemoteGraphQLDataSource {
  constructor(config) {
    super(config);
    this.fetcher = fetcher.defaults({
      maxSockets: Infinity,
      strictSSL: false,
      retry: false,
    });
  }
}

const GATEWAY_CONFIG = {
  // ...
  buildService({ url }) {
    return new CustomRemoteGraphQLDataSource({
      // ...
    });
  }
  // ...
};
```

But how can this be done in Apollo Router and is it possible at all?
