### ISSUE TITLE
Subscriptions config

### ISSUE THREAD

**Issue by joshpauline** [apollographql/router#1123]
I am using Apollo router to route requests to my numerous graphql endpoints hosted on AWS Appsync.

Each of my appsync endpoints have a websocket address for subscriptions to our frontend client.

I cannot seem to find an area in the docs that shows where to put this ws url to proxy websocket connections via the router.

I know its not set up correctly thats why im getting this error

<img width="421" alt="Screen Shot 2022-05-23 at 10 57 29 am" src="https://user-images.githubusercontent.com/36560907/169724630-2f3f4197-fa29-437b-a359-1710bf980e5a.png">

Ideally I will be able to proxy all requests through a load balancer to an ecs cluster running the router. 

Also, I was wondering if apollo are planning on releasing a hosted endpoint for customers in the pipeline?

**Comment by BrynCooke** [comment]
Hi @joshpauline 
Neither Apollo Router or Gateway support subscriptions yet. It's something we're thinking about, but it is tricky to do subscriptions in a federated context.

Pinging @prasek to add this as a datapoint.

**Comment by joshpauline** [comment]
ahh I see, thats all good. was just a bit confused by the ws endpoint in the apollo studio for the supergraph. thank you for letting me know
