### ISSUE TITLE
Prometheus docs should indicate that the endpoint is unsecured

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1128]
Prometheus metrics, once enabled are not secured.
Call this our in the documentation and give suggestions to user about securing at ingress or service mesh.

**Comment by o0Ignition0o** [comment]
fixed by #1174

**Comment by abernix** [comment]
Just for future context — I want to confirm that this was fixed **not** by documenting that anything was insecure, but by **instead** making the default not be exposing Prometheus on the same interface as GraphQL requests are served on and therefore making the default configuration secure — is that right, @o0Ignition0o? (Is the above issue the right "fixed" reference?)

**Comment by o0Ignition0o** [comment]
It is right, the default configuration is now secure because Prometheus exposes it's entpoint to `127.0.0.1:9090/metrics` instead of `0.0.0.0:4000/plugins/apollo.telemetry/prometheus`.

The key point being the switch from `0.0.0.0` to `127.0.0.1`

**Comment by abernix** [comment]
Thank you! Fixed by https://github.com/apollographql/router/pull/1654, right?
