### ISSUE TITLE
API 1.0 stabilization

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1131]
- [ ] #1138
- [x] #1139
- [x] #1140
- [x] #1141
- [ ] #1142
- [x] #1143
- [x] #1144
- [x] #1145
- [x] #1146
- [x] #1147
- [x] #1148
- [ ] #1149
- [ ] #1150
- [x] #1151
- [ ] #1152
- [x] #1153
- [x] https://github.com/apollographql/router/pull/1303
- [x] https://github.com/apollographql/router/pull/1267
- [ ] More principled terminology for request and response on each "side"? Upstream/subgraph v.s. downstream/supergraph

**Comment by SimonSapin** [comment]
I feel this tracking issue is not useful anymore, let’s use the `api/1.0` label instead:

* https://github.com/apollographql/router/labels/api%2F1.0
* https://github.com/orgs/apollographql/projects/18/views/19?filterQuery=label%3A%22api%2F1.0%22
