### ISSUE TITLE
API 1.0 - Service Request/Response naming

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1139]
Currently we have:

* Router - RouterRequest, RouterResponse
* QueryPlanning - QueryPlannerRequest, QueryPlannerResponse
* Execution - ExecutionRequest, ExecutionResponse
* Subgraph - SubgraphRequest, SubgraphResponse

Relates to #1138 

In particular QueryPlanner request/response don't match the service name.

**Comment by garypen** [comment]
Merged into #1138.
