### ISSUE TITLE
API 1.0 - Asymmetry in request response datastructures

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1140]
RouterResponse currently has an enum that allows it to deal with non grpahql responses. This is a pain for users when writing tests.

Either we need to improve the API and add failable casting of the enum, or better yet remove the enum altogether.

Removal of the enum could involve adding another service to plugins to deal with non-graphql requests.

Do this before #1138

**Comment by SimonSapin** [comment]
This turned out less hard than I first expected as there was no need to touch how custom endpoints work: https://github.com/apollographql/router/pull/1307
