### ISSUE TITLE
API 1.0 - Maybe introduce apollo-router-plugin-apis

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1145]
Should we introduce an APIs module to facilitate plugin writing and testing.
Main discussion should happen in #1144 until this is decided. We can then either close this ticket or continue the work if we are going to proceed.

**Comment by garypen** [comment]
We think that a plugin author requires access to functionality that is almost everything public in apollo-router (apart from the executable stuff), so no real merit in identifying "plugin" apis.
