### ISSUE TITLE
API 1.0 - Public API audit

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1150]
We've made far too many structures public. Let's remove as much as possible and re-introduce carefully.

* [x] Consider removing the `prelude::graphql` module since it's the same as `apollo_router` https://github.com/apollographql/router/issues/1214
* [x] Reconsider reexports at the crate top-level https://github.com/apollographql/router/issues/1217
* [ ] Make everything private then see what's needed to make plugins we know about compile?

**Comment by SimonSapin** [comment]
For https://github.com/apollographql/router/pull/1242 I’ve hacked together a way to list all public items:

```sh
cargo +nightly rustdoc --lib -p apollo-router -- -Z unstable-options --output-format json
< target/doc/apollo_router.json jq '.paths[] | .path | join("::")' -r | grep ^apollo_router | sort
```

<details>
<summary>Output</summary>
<pre>
apollo_router
apollo_router::ApolloRouter
apollo_router::ConfigurationKind
apollo_router::ConfigurationKind::File
apollo_router::ConfigurationKind::Instance
apollo_router::ConfigurationKind::Stream
apollo_router::Context
apollo_router::Executable
apollo_router::ExecutionRequest
apollo_router::ExecutionResponse
apollo_router::ExecutionService
apollo_router::PluggableRouterServiceBuilder
apollo_router::QueryPlannerRequest
apollo_router::QueryPlannerResponse
apollo_router::Request
apollo_router::Response
apollo_router::ResponseBody
apollo_router::ResponseBody::GraphQL
apollo_router::ResponseBody::RawJSON
apollo_router::ResponseBody::Text
apollo_router::RouterRequest
apollo_router::RouterResponse
apollo_router::RouterService
apollo_router::Schema
apollo_router::SchemaKind
apollo_router::SchemaKind::File
apollo_router::SchemaKind::Instance
apollo_router::SchemaKind::Registry
apollo_router::SchemaKind::Stream
apollo_router::ShutdownKind
apollo_router::ShutdownKind::CtrlC
apollo_router::ShutdownKind::Custom
apollo_router::ShutdownKind::None
apollo_router::SubgraphRequest
apollo_router::SubgraphResponse
apollo_router::SubgraphService
apollo_router::configuration
apollo_router::configuration::ApolloPlugins
apollo_router::configuration::Configuration
apollo_router::configuration::ConfigurationError
apollo_router::configuration::ConfigurationError::CannotReadSecretFromEnv
apollo_router::configuration::ConfigurationError::CannotReadSecretFromFile
apollo_router::configuration::ConfigurationError::DeserializeConfigError
apollo_router::configuration::ConfigurationError::InvalidConfiguration
apollo_router::configuration::ConfigurationError::InvalidEnvironmentVariable
apollo_router::configuration::ConfigurationError::LayerConfiguration
apollo_router::configuration::ConfigurationError::LayerUnknown
apollo_router::configuration::ConfigurationError::Metrics
apollo_router::configuration::ConfigurationError::MissingEnvironmentVariable
apollo_router::configuration::ConfigurationError::MissingFeature
apollo_router::configuration::ConfigurationError::OtlpTracing
apollo_router::configuration::ConfigurationError::PluginConfiguration
apollo_router::configuration::ConfigurationError::PluginShutdown
apollo_router::configuration::ConfigurationError::PluginStartup
apollo_router::configuration::ConfigurationError::PluginUnknown
apollo_router::configuration::Cors
apollo_router::configuration::ListenAddr
apollo_router::configuration::ListenAddr::SocketAddr
apollo_router::configuration::ListenAddr::UnixSocket
apollo_router::configuration::NewConfigurationBuilder
apollo_router::configuration::NewCorsBuilder
apollo_router::configuration::NewServerBuilder
apollo_router::configuration::Server
apollo_router::configuration::UserPlugins
apollo_router::configuration::generate_config_schema
apollo_router::configuration::validate_configuration
apollo_router::error
apollo_router::error::CacheResolverError
apollo_router::error::CacheResolverError::RetrievalError
apollo_router::error::Error
apollo_router::error::FetchError
apollo_router::error::FetchError::ExecutionFieldNotFound
apollo_router::error::FetchError::ExecutionInvalidContent
apollo_router::error::FetchError::ExecutionPathNotFound
apollo_router::error::FetchError::MalformedResponse
apollo_router::error::FetchError::SubrequestHttpError
apollo_router::error::FetchError::SubrequestMalformedResponse
apollo_router::error::FetchError::SubrequestNoResponse
apollo_router::error::FetchError::SubrequestUnexpectedPatchResponse
apollo_router::error::FetchError::ValidationInvalidTypeVariable
apollo_router::error::FetchError::ValidationPlanningError
apollo_router::error::FetchError::ValidationUnknownServiceError
apollo_router::error::JsonExtError
apollo_router::error::JsonExtError::InvalidFlatten
apollo_router::error::JsonExtError::PathNotFound
apollo_router::error::Location
apollo_router::error::NewErrorBuilder
apollo_router::error::ParseErrors
apollo_router::error::PlannerError::WorkerError
apollo_router::error::PlannerError::WorkerGraphQLError
apollo_router::error::PlannerErrors
apollo_router::error::QueryPlannerError
apollo_router::error::QueryPlannerError::CacheResolverError
apollo_router::error::QueryPlannerError::EmptyPlan
apollo_router::error::QueryPlannerError::JoinError
apollo_router::error::QueryPlannerError::PlanningErrors
apollo_router::error::QueryPlannerError::RouterBridgeError
apollo_router::error::QueryPlannerError::SchemaValidationErrors
apollo_router::error::QueryPlannerError::SpecError
apollo_router::error::QueryPlannerError::UnhandledPlannerResult
apollo_router::error::SchemaError
apollo_router::error::SchemaError::Api
apollo_router::error::SchemaError::IoError
apollo_router::error::SchemaError::MissingSubgraphUrl
apollo_router::error::SchemaError::Parse
apollo_router::error::SchemaError::UrlParse
apollo_router::error::ServiceBuildError
apollo_router::error::ServiceBuildError::QueryPlannerError
apollo_router::http_compat
apollo_router::http_compat::FakeNewRequestBuilder
apollo_router::http_compat::IntoHeaderName
apollo_router::http_compat::IntoHeaderName::HeaderName
apollo_router::http_compat::IntoHeaderName::String
apollo_router::http_compat::IntoHeaderValue
apollo_router::http_compat::IntoHeaderValue::HeaderValue
apollo_router::http_compat::IntoHeaderValue::String
apollo_router::http_compat::NewRequestBuilder
apollo_router::http_compat::Request
apollo_router::http_compat::Response
apollo_router::json_ext
apollo_router::json_ext::Object
apollo_router::json_ext::Value::Array
apollo_router::json_ext::Value::Bool
apollo_router::json_ext::Value::Null
apollo_router::json_ext::Value::Number
apollo_router::json_ext::Value::Object
apollo_router::json_ext::Value::String
apollo_router::layers
apollo_router::layers::ServiceBuilderExt
apollo_router::layers::ServiceExt
apollo_router::layers::async_checkpoint
apollo_router::layers::async_checkpoint::AsyncCheckpointLayer
apollo_router::layers::async_checkpoint::AsyncCheckpointService
apollo_router::layers::cache
apollo_router::layers::cache::CachingLayer
apollo_router::layers::cache::CachingService
apollo_router::layers::instrument
apollo_router::layers::instrument::InstrumentLayer
apollo_router::layers::instrument::InstrumentService
apollo_router::layers::map_future_with_context
apollo_router::layers::map_future_with_context::MapFutureWithContextLayer
apollo_router::layers::map_future_with_context::MapFutureWithContextService
apollo_router::layers::sync_checkpoint
apollo_router::layers::sync_checkpoint::CheckpointLayer
apollo_router::layers::sync_checkpoint::CheckpointService
apollo_router::main
apollo_router::mock_service
apollo_router::plugin
apollo_router::plugin::DynPlugin
apollo_router::plugin::Handler
apollo_router::plugin::Plugin
apollo_router::plugin::PluginFactory
apollo_router::plugin::plugins
apollo_router::plugin::register_plugin
apollo_router::plugin::utils
apollo_router::plugin::utils::serde
apollo_router::plugin::utils::serde::deserialize_header_name
apollo_router::plugin::utils::serde::deserialize_header_value
apollo_router::plugin::utils::serde::deserialize_option_header_name
apollo_router::plugin::utils::serde::deserialize_option_header_value
apollo_router::plugin::utils::serde::deserialize_regex
apollo_router::plugin::utils::test
apollo_router::plugin::utils::test::IntoSchema
apollo_router::plugin::utils::test::IntoSchema::Canned
apollo_router::plugin::utils::test::IntoSchema::Schema
apollo_router::plugin::utils::test::IntoSchema::String
apollo_router::plugin::utils::test::NewPluginTestHarnessBuilder
apollo_router::plugin::utils::test::PluginTestHarness
apollo_router::plugin::utils::test::mock
apollo_router::plugin::utils::test::mock::subgraph
apollo_router::plugin::utils::test::mock::subgraph::MockSubgraph
apollo_router::plugin::utils::test::service
apollo_router::plugin::utils::test::service::ExecutionService
apollo_router::plugin::utils::test::service::MockExecutionService
apollo_router::plugin::utils::test::service::MockQueryPlanningService
apollo_router::plugin::utils::test::service::MockRouterService
apollo_router::plugin::utils::test::service::MockSubgraphService
apollo_router::plugin::utils::test::service::QueryPlanningService
apollo_router::plugin::utils::test::service::RouterService
apollo_router::plugin::utils::test::service::SubgraphService
apollo_router::plugin::utils::test::service::__mock_MockExecutionService
apollo_router::plugin::utils::test::service::__mock_MockExecutionService_ExecutionService
apollo_router::plugin::utils::test::service::__mock_MockExecutionService_ExecutionService::__call
apollo_router::plugin::utils::test::service::__mock_MockExecutionService_ExecutionService::__call::Expectation
apollo_router::plugin::utils::test::service::__mock_MockQueryPlanningService
apollo_router::plugin::utils::test::service::__mock_MockQueryPlanningService_QueryPlanningService
apollo_router::plugin::utils::test::service::__mock_MockQueryPlanningService_QueryPlanningService::__call
apollo_router::plugin::utils::test::service::__mock_MockQueryPlanningService_QueryPlanningService::__call::Expectation
apollo_router::plugin::utils::test::service::__mock_MockRouterService
apollo_router::plugin::utils::test::service::__mock_MockRouterService_RouterService
apollo_router::plugin::utils::test::service::__mock_MockRouterService_RouterService::__call
apollo_router::plugin::utils::test::service::__mock_MockRouterService_RouterService::__call::Expectation
apollo_router::plugin::utils::test::service::__mock_MockSubgraphService
apollo_router::plugin::utils::test::service::__mock_MockSubgraphService_SubgraphService
apollo_router::plugin::utils::test::service::__mock_MockSubgraphService_SubgraphService::__call
apollo_router::plugin::utils::test::service::__mock_MockSubgraphService_SubgraphService::__call::Expectation
apollo_router::plugins
apollo_router::plugins::csrf
apollo_router::plugins::csrf::CSRFConfig
apollo_router::plugins::csrf::Csrf
apollo_router::plugins::override_url
apollo_router::plugins::rhai
apollo_router::plugins::rhai::Conf
apollo_router::plugins::rhai::Rhai
apollo_router::plugins::telemetry
apollo_router::plugins::telemetry::ROUTER_SPAN_NAME
apollo_router::plugins::telemetry::Telemetry
apollo_router::plugins::telemetry::apollo
apollo_router::plugins::telemetry::apollo::Config
apollo_router::plugins::telemetry::config
apollo_router::plugins::telemetry::config::AttributeArray
apollo_router::plugins::telemetry::config::AttributeArray::Bool
apollo_router::plugins::telemetry::config::AttributeArray::F64
apollo_router::plugins::telemetry::config::AttributeArray::I64
apollo_router::plugins::telemetry::config::AttributeArray::String
apollo_router::plugins::telemetry::config::AttributeValue
apollo_router::plugins::telemetry::config::AttributeValue::Array
apollo_router::plugins::telemetry::config::AttributeValue::Bool
apollo_router::plugins::telemetry::config::AttributeValue::F64
apollo_router::plugins::telemetry::config::AttributeValue::I64
apollo_router::plugins::telemetry::config::AttributeValue::String
apollo_router::plugins::telemetry::config::Conf
apollo_router::plugins::telemetry::config::GenericWith
apollo_router::plugins::telemetry::config::Metrics
apollo_router::plugins::telemetry::config::MetricsCommon
apollo_router::plugins::telemetry::config::Propagation
apollo_router::plugins::telemetry::config::Sampler
apollo_router::plugins::telemetry::config::Sampler::AlwaysOff
apollo_router::plugins::telemetry::config::Sampler::AlwaysOn
apollo_router::plugins::telemetry::config::SamplerOption
apollo_router::plugins::telemetry::config::SamplerOption::Always
apollo_router::plugins::telemetry::config::SamplerOption::TraceIdRatioBased
apollo_router::plugins::telemetry::config::Trace
apollo_router::plugins::telemetry::config::Tracing
apollo_router::prelude
apollo_router::prelude::CacheResolver
apollo_router::prelude::QueryPlanner
apollo_router::prelude::WithCaching
apollo_router::reexports
apollo_router::register_plugin
apollo_router::subscriber
apollo_router::subscriber::RouterSubscriber
apollo_router::subscriber::RouterSubscriber::JsonSubscriber
apollo_router::subscriber::RouterSubscriber::TextSubscriber
apollo_router::subscriber::is_global_subscriber_set
apollo_router::subscriber::replace_layer
apollo_router::subscriber::set_global_subscriber
</pre>
</details>

**Comment by SimonSapin** [comment]
Some more filtering: `grep -v -E '::([A-Z].*::|__)'` leaves 143 items:


<details>
<summary>Output</summary>
<pre>
apollo_router
apollo_router::ApolloRouter
apollo_router::ConfigurationKind
apollo_router::Context
apollo_router::Executable
apollo_router::ExecutionRequest
apollo_router::ExecutionResponse
apollo_router::ExecutionService
apollo_router::PluggableRouterServiceBuilder
apollo_router::QueryPlannerRequest
apollo_router::QueryPlannerResponse
apollo_router::Request
apollo_router::Response
apollo_router::ResponseBody
apollo_router::RouterRequest
apollo_router::RouterResponse
apollo_router::RouterService
apollo_router::Schema
apollo_router::SchemaKind
apollo_router::ShutdownKind
apollo_router::SubgraphRequest
apollo_router::SubgraphResponse
apollo_router::SubgraphService
apollo_router::configuration
apollo_router::configuration::ApolloPlugins
apollo_router::configuration::Configuration
apollo_router::configuration::ConfigurationError
apollo_router::configuration::Cors
apollo_router::configuration::ListenAddr
apollo_router::configuration::NewConfigurationBuilder
apollo_router::configuration::NewCorsBuilder
apollo_router::configuration::NewServerBuilder
apollo_router::configuration::Server
apollo_router::configuration::UserPlugins
apollo_router::configuration::generate_config_schema
apollo_router::configuration::validate_configuration
apollo_router::error
apollo_router::error::CacheResolverError
apollo_router::error::Error
apollo_router::error::FetchError
apollo_router::error::JsonExtError
apollo_router::error::Location
apollo_router::error::NewErrorBuilder
apollo_router::error::ParseErrors
apollo_router::error::PlannerErrors
apollo_router::error::QueryPlannerError
apollo_router::error::SchemaError
apollo_router::error::ServiceBuildError
apollo_router::http_compat
apollo_router::http_compat::FakeNewRequestBuilder
apollo_router::http_compat::IntoHeaderName
apollo_router::http_compat::IntoHeaderValue
apollo_router::http_compat::NewRequestBuilder
apollo_router::http_compat::Request
apollo_router::http_compat::Response
apollo_router::json_ext
apollo_router::json_ext::Object
apollo_router::layers
apollo_router::layers::ServiceBuilderExt
apollo_router::layers::ServiceExt
apollo_router::layers::async_checkpoint
apollo_router::layers::async_checkpoint::AsyncCheckpointLayer
apollo_router::layers::async_checkpoint::AsyncCheckpointService
apollo_router::layers::cache
apollo_router::layers::cache::CachingLayer
apollo_router::layers::cache::CachingService
apollo_router::layers::instrument
apollo_router::layers::instrument::InstrumentLayer
apollo_router::layers::instrument::InstrumentService
apollo_router::layers::map_future_with_context
apollo_router::layers::map_future_with_context::MapFutureWithContextLayer
apollo_router::layers::map_future_with_context::MapFutureWithContextService
apollo_router::layers::sync_checkpoint
apollo_router::layers::sync_checkpoint::CheckpointLayer
apollo_router::layers::sync_checkpoint::CheckpointService
apollo_router::main
apollo_router::mock_service
apollo_router::plugin
apollo_router::plugin::DynPlugin
apollo_router::plugin::Handler
apollo_router::plugin::Plugin
apollo_router::plugin::PluginFactory
apollo_router::plugin::plugins
apollo_router::plugin::register_plugin
apollo_router::plugin::utils
apollo_router::plugin::utils::serde
apollo_router::plugin::utils::serde::deserialize_header_name
apollo_router::plugin::utils::serde::deserialize_header_value
apollo_router::plugin::utils::serde::deserialize_option_header_name
apollo_router::plugin::utils::serde::deserialize_option_header_value
apollo_router::plugin::utils::serde::deserialize_regex
apollo_router::plugin::utils::test
apollo_router::plugin::utils::test::IntoSchema
apollo_router::plugin::utils::test::NewPluginTestHarnessBuilder
apollo_router::plugin::utils::test::PluginTestHarness
apollo_router::plugin::utils::test::mock
apollo_router::plugin::utils::test::mock::subgraph
apollo_router::plugin::utils::test::mock::subgraph::MockSubgraph
apollo_router::plugin::utils::test::service
apollo_router::plugin::utils::test::service::ExecutionService
apollo_router::plugin::utils::test::service::MockExecutionService
apollo_router::plugin::utils::test::service::MockQueryPlanningService
apollo_router::plugin::utils::test::service::MockRouterService
apollo_router::plugin::utils::test::service::MockSubgraphService
apollo_router::plugin::utils::test::service::QueryPlanningService
apollo_router::plugin::utils::test::service::RouterService
apollo_router::plugin::utils::test::service::SubgraphService
apollo_router::plugins
apollo_router::plugins::csrf
apollo_router::plugins::csrf::CSRFConfig
apollo_router::plugins::csrf::Csrf
apollo_router::plugins::override_url
apollo_router::plugins::rhai
apollo_router::plugins::rhai::Conf
apollo_router::plugins::rhai::Rhai
apollo_router::plugins::telemetry
apollo_router::plugins::telemetry::ROUTER_SPAN_NAME
apollo_router::plugins::telemetry::Telemetry
apollo_router::plugins::telemetry::apollo
apollo_router::plugins::telemetry::apollo::Config
apollo_router::plugins::telemetry::config
apollo_router::plugins::telemetry::config::AttributeArray
apollo_router::plugins::telemetry::config::AttributeValue
apollo_router::plugins::telemetry::config::Conf
apollo_router::plugins::telemetry::config::GenericWith
apollo_router::plugins::telemetry::config::Metrics
apollo_router::plugins::telemetry::config::MetricsCommon
apollo_router::plugins::telemetry::config::Propagation
apollo_router::plugins::telemetry::config::Sampler
apollo_router::plugins::telemetry::config::SamplerOption
apollo_router::plugins::telemetry::config::Trace
apollo_router::plugins::telemetry::config::Tracing
apollo_router::prelude
apollo_router::prelude::CacheResolver
apollo_router::prelude::QueryPlanner
apollo_router::prelude::WithCaching
apollo_router::reexports
apollo_router::register_plugin
apollo_router::subscriber
apollo_router::subscriber::RouterSubscriber
apollo_router::subscriber::is_global_subscriber_set
apollo_router::subscriber::replace_layer
apollo_router::subscriber::set_global_subscriber
</pre>
</details>

**Comment by BrynCooke** [comment]
I think these should be private:
```
apollo_router::prelude (probably remove this altogether?)
apollo_router::plugins
apollo_router::configuration
```

`apollo_router::mock_service` seems out of place, possibly move to `plugin::utils::test`

**Comment by SimonSapin** [comment]
The `configuration::Configuration` struct is used to construct `ConfigurationKind::Instance` enum values, but we could reexport the struct and make the module (and the rest of its items) private.

**Comment by SimonSapin** [comment]
`Configuration` could be a public type with no public API other than implementing `serde::Deserialize`. I’ll look into making that happen (possibly with a wrapper type).

**Comment by SimonSapin** [comment]
`cargo doc` emits warnings for links in doc comments to types that have recently been made private. In some cases those types also appears in public fields, which seems inconsistent.

Should we make such types public? Or maybe make fields private? Probably this is a case-by-case decision.

**Comment by SimonSapin** [comment]
We have a few reexports of items from other crates, for example:
```rust
pub use router_bridge::planner::{PlanError, PlannerError};
```
```rust
pub use serde_json_bytes::Value;
```

Do we want to keep them (and maybe add more in the same spirit), or remove them and have users depend on those crates themselves?

**Comment by garypen** [comment]
> We have a few reexports of items from other crates, for example:
> 
> ```rust
> pub use router_bridge::planner::{PlanError, PlannerError};
> ```
> 
> ```rust
> pub use serde_json_bytes::Value;
> ```
> 
> Do we want to keep them (and maybe add more in the same spirit), or remove them and have users depend on those crates themselves?

I'd prefer to remove them, but it's not a strong preference.

**Comment by SimonSapin** [comment]
These reexports are being removed in https://github.com/apollographql/router/pull/1487.

As for the wider API audit, it is still ongoing but let’s file issues for individual issues. It doesn’t seem useful to keep this one open.
