### ISSUE TITLE
API 1.0 - Remove the cache layer

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1152]
Decision below is to remove the cache layer

---

Original body:

---

What layers do we want to expose to plugin authors?
We currently have:
* checkpoint
* instrument
* cache
* map_future_with_context (what an awful name)

Do we need higher level constructs?
Revisit what we have.

**Comment by garypen** [comment]
Re-examine requirements for `ServiceBuilderExt` and `ServiceExt` and ensure that if both are still required they are consistent and everything is well-named.

**Comment by garypen** [comment]
Should we remove:
 - cache
?

**Comment by abernix** [comment]
@SimonSapin @BrynCooke I moved this from "Needs design" to "Todo", but let me know if you feel differently — not sure if the summary needs refinement, but feel free to edit.
