### ISSUE TITLE
SubrequestHttpError

### ISSUE THREAD

**Issue by krisztian-sala** [apollographql/router#1163]
We have a query similar to this:
```graphql
query QueryName($param: String!) {
  queryName(filter: {param: $param}) {
    __typename
  }
}
```

If I execute this through the federation, it works well. But if I change it to use the router instead, I get the following error:
```json
{"data":null,"errors":[{"message":"HTTP fetch failed from 'service-name': service 'service-name' response was malformed: service 'service-name' response was malformed: expected value at line 1 column 1","locations":[],"path":[],"extensions":{"type":"SubrequestHttpError","service":"service-name","reason":"service 'service-name' response was malformed: service 'service-name' response was malformed: expected value at line 1 column 1"}}]}
```

Can it be solved somehow? Based on this message, I don't know where to start. 
I also enabled debug logging, but didn't see any useful details about this.

**Comment by bnjjj** [comment]
Hello @krisztian-sala Could you give us more info to be able to reproduce ? Your subgraph configuration, your schema for example might be very useful. If you're also able to log the request you receive in your subgraph it might be very useful for us to debug. Thanks a lot
