### ISSUE TITLE
Cannot built Router Service with federation 0.x graph

### ISSUE THREAD

**Issue by dakshas** [apollographql/router#1165]
**Describe the bug**
While attempting to move to the Apollo Router from @apollo/gateway, I was trying to start the router with managed federation as described below.

```
 * Fetch a registered schema from Apollo Studio by setting
    these environment variables:

      $ APOLLO_KEY="..." APOLLO_GRAPH_REF="..." ./router

      For details, see the Apollo docs:
      https://www.apollographql.com/docs/router/managed-federation/setup
```
From what I see in the [compatibility compatibility section](https://www.apollographql.com/docs/federation/federation-2/backward-compatibility/#compatibility-table) it looks like the Apollo router should work with federation 0.x, but I get invalid schema errors seen below.

```
could not create the HTTP pipeline: couldn't build Router Service: couldn't instantiate query planner; invalid schema: schema validation errors: Error extracting subgraph <redacted> from the supergraph: this might be due to errors in subgraphs that were mistakenly ignored by federation 0.x versions but are rejected by federation 2.
Please try composing your subgraphs with federation 2: this should help precisely pinpoint the problems and, once fixed, generate a correct federation 2 supergraph.

Details:
[<subgraph name>] On field "WorkGroup.workItems", for @provides...<redacted> Invalid empty selection set for field "WorkItem.assignedQueue" of non-leaf type WorkQueue
caused by
```

Is this expected behavior? these don't seem to be the [breaking changes ](https://www.apollographql.com/docs/federation/federation-2/backward-compatibility/#breaking-changes) between federation 0.x and 2.x.

**To Reproduce**
I'm using a private graph so reproducing this externally is not an option, hopefully the error has sufficient information to help

**Expected behavior**
based on the composibility compatibility I expect the router to be be able to compose the federation 0.x compatible schema

**Output**
Error messages added in description 

**Desktop (please complete the following information):**
 - OS: macos Monterey 12.2.1 (Intel Macbook)
 - Version-  
```
./router --version
0.9.2
```

**Additional context**

**Comment by bnjjj** [comment]
Hello @dakshas Could you copy/paste the part of your schema related to the error message you have (`WorkGroup`)  ? It might help us to reproduce/debug and find the root cause.

**Comment by dakshas** [comment]
```
type WorkGroup {
  entity: WorkGroupEntity
  id: ID
  type: String
  docScore: Float
  workScore: WorkScore

  workItems: [WorkItem]
    @provides(
      fields: "assignedFrom assignedQueue combinedEntity completedAt createdAt decisionTreeTrace entityType escalatedQueue evaluatedQueues evaluationData groupedEntity groupedEntityType id isActivelyWorking isPriority mostRecentSnoozeReasonCode mostRecentlySnoozedUntil note owner priorityScore priorityScoreUpdatedAt queue snoozeReasonCode snoozedUntil sortDecisionTreeTrace sortTime type"
    )
}
```
@bnjjj there you go, thanks for looking into this!

**Comment by bnjjj** [comment]
It could be interesting to have the schema of `WorkItem` the error message tells us the router is expecting a different type for `WorkItem.assignedQueue`

**Comment by dakshas** [comment]
```
extend type WorkItem @key(fields: "id") {
  id: ID @external
  assignedFrom: AssignedFrom @external
  assignedQueue: WorkQueue @external
  combinedEntity: CombinedEntity @external
  completedAt: Date @external
  createdAt: Date @external
  decisionTreeTrace: String @external
  entityType: EntityType @external
  escalatedQueue: WorkQueue @external
  evaluatedQueues: [WorkQueue] @external
  evaluationData: NonProdRawObject @external
  groupedEntity: Shipment @external
  groupedEntityType: EntityType @external
  isActivelyWorking: Boolean @external
  isPriority: Boolean @external
  mostRecentSnoozeReasonCode: SnoozeReasonCode @external
  mostRecentlySnoozedUntil: Date @external
  note: String @external
  owner: User @external
  priorityScore: Float @external
  priorityScoreUpdatedAt: Date @external
  queue: WorkQueue @external
  snoozeReasonCode: SnoozeReasonCode @external
  snoozedUntil: Date @external
  sortDecisionTreeTrace: String @external
  sortTime: Date @external
  type: WorkType @external
}

type WorkQueue {
  assignedCount: Float
  assignmentCount: Float
  createdAt: Date
  deprecatedAt: Date
  escalationCount: Float
  id: ID
  itemCount: Float
  name: String
  priorityCount: Float
  snoozedCount: Float
  suggestedTransferQueueId: String
}
```

let me know if this helps!

**Comment by bnjjj** [comment]
I didn't manage to reproduce for now, did you do some unusual things in your query ? Could you show me the interesting part of your query please ? Also did you try to run the same schema/query on federation 2 with the gateway ?

**Comment by dakshas** [comment]
Can't really query anything because it errors out when I try to run the router with managed federation with the command below.
`APOLLO_KEY="..." APOLLO_GRAPH_REF="..." ./router `
I'm using  `"@apollo/gateway": "0.28.3",` to use federation 2 I'll have to upgrade to gateway 2.x which is a migration I was hoping to skip by directly migrating to the router.

**Comment by bnjjj** [comment]
Ok thanks for all the information, did you already try to migrate to a fed 2 schema following this [documentation](https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2/) ? Just skip the gateway part but try using rover to upgrade to fed 2 and check if it works. I can't reproduce on my side then I try another option :)

**Comment by abernix** [comment]
I'll close this as we haven't heard back, but please do try composing with Federation 2 (at least experimentally) and see if you get any new errors.   The new Federation 2 composition tooling (in Rover, and Studio) has vastly improved validations and error messaging (including hints), that would be really useful to see.  Happy to re-open with more information and a minimal runnable reproduction!  Thanks!

**Comment by mihir-mehta** [comment]
I am getting similar error. My schema look like this 

SUBGRAPH 1 

```
type Asset @key(fields: "assetID") {
  assetID:ID!
  movieTitle: String
}

type Channel @key(fields: "channelID") {
  channelID: ID!
  name: String!
  asset:Asset 
}
```

SUBGRAPH 2

**Comment by abernix** [comment]
@mihir-mehta Did you try the suggestion in the error message to get more information?

> Please try composing your subgraphs with federation 2: this should help precisely pinpoint the problems and, once fixed, generate a correct federation 2 supergraph.

**Comment by mihir-mehta** [comment]
So there were multiple attributes from asset that is @require for assetTile, i will need to mention those individually. It solves the problem.
