### ISSUE TITLE
Cannot set telemetry.tracing.otlp.grpc.metadata

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#1166]
**Bug Description**

This config: 
```yaml
telemetry:
  tracing:
    otlp:
      endpoint: otlp.nr-data.net:4317
      grpc:
        metadata:
          "api-key": ${NEW_RELIC_LICENSE_KEY}
```
causes this error at startup:
```
2022-05-26T20:39:30.605914Z ERROR apollo_router::router_factory: plugin apollo.telemetry could not be configured: invalid type: map, expected a sequence
2022-05-26T20:39:30.606164Z ERROR apollo_router::state_machine: cannot create the router: plugin apollo.telemetry could not be configured: invalid type: map, expected a sequence
2022-05-26T20:39:30.606245Z DEBUG apollo_router::state_machine: transitioned to state errored
2022-05-26T20:39:30.606255Z DEBUG apollo_router::state_machine: stopped
2022-05-26T20:39:30.606331Z  INFO apollo_router: stopped with error
2022-05-26T20:39:30.606508Z ERROR apollo_router::executable: could not create the HTTP pipeline: plugin apollo.telemetry could not be configured: invalid type: map, expected a sequence
Error: could not create the HTTP pipeline: plugin apollo.telemetry could not be configured: invalid type: map, expected a sequence
```

I couldn't figure out how to send a "sequence". I also tried `metadata: {}` and `metadata: "api-key: ${NEW_RELIC_LICENSE_KEY}` and got the same error.

**Versions**
 - router 0.9.2

**Additional context**
I was able to send traces to newrelic by using a collector, so this isn't a high-priority bug.

**Comment by bnjjj** [comment]
I think the issue might come from here https://github.com/apollographql/router/blob/main/apollo-router/src/plugins/telemetry/otlp.rs#L223 I don't know why we're using a `Vec<HashMap<String, String>>` instead of just a `HashMap<String, String>`

**Comment by me-diru** [comment]
Hello @bnjjj, this looks like an interesting issue. May i work on this?

**Comment by bnjjj** [comment]
Yes sure ! I'm available if you need help !

**Comment by bnjjj** [comment]
@me-diru I assigned the issue to yourself

**Comment by bnjjj** [comment]
@me-diru Are you still on the issue ? Do you need some help ?

**Comment by me-diru** [comment]
Hey @bnjjj, I was a bit occupied, will take a stab at it and update my progress/thoughts/questions here asap, sorry for the delay.

**Comment by me-diru** [comment]
hey @bnjjj,

Thanks for checking in!

> I think the issue might come from here https://github.com/apollographql/router/blob/main/apollo-router/src/plugins/telemetry/otlp.rs#L223 I don't know why we're using a Vec<HashMap<String, String>> instead of just a HashMap<String, String>

At first look, the serialize function is creating a Vec<HashMap<String, String>> https://github.com/apollographql/router/blob/main/apollo-router/src/plugins/telemetry/otlp.rs#L209-L218  and deserialize function is consistent with that, i.e using the same Vec<HashMap<String, String>> type to deal with data. I am unsure how to replicate the error, as I see consistent data structure used in both the functions dealing with metadata.

If any changes are to be made, it should be done in both functions? like changing from Vec<HashMap<String, String>> to  HashMap<String, String>, I am also not sure why a  Vec<HashMap<String, String>> is used instead of a direct  HashMap<String, String> to store the metadata key-value details

Please correct me if I made any wrong assumptions.

**Comment by bnjjj** [comment]
Yes that's basically the issue, you just have to switch from a `Vec<HashMap<String, String>>` to a `HashMap<String, String>` you're right

**Comment by sgsharma** [comment]
Following up here; I'm trying to use the OTLP export with the router - config file here:

```
telemetry:
  tracing:
    trace_config:
      service_name: "router"
      service_namespace: "apollo"
      sampler: 1
    otlp:
      protocol: grpc
      endpoint: "api.honeycomb.io:443"
      grpc:
        metadata:
          x-honeycomb-team: ${HONEYCOMB_API_KEY}

headers:
  all:
    request:
      - propagate:
          matching: .*
```

When trying to run the router with this config
`./router --config router.yaml --supergraph supergraph-schema.graphql --log debug`

I'm still seeing an issue with it expecting a sequence:
```
2022-09-29T17:22:25.165341Z DEBUG apollo_router::router_factory: plugins list: ["apollo.include_subgraph_errors", "apollo.csrf", "apollo.telemetry", "apollo.headers"]
2022-09-29T17:22:25.165350Z ERROR apollo_router::router_factory: plugin apollo.telemetry could not be configured: invalid type: string "<REDACTED>", expected a sequence
2022-09-29T17:22:25.166170Z ERROR apollo_router::state_machine: cannot create the router: plugin apollo.telemetry could not be configured: invalid type: string "<REDACTED>", expected a sequence
```

**Comment by sgsharma** [comment]
@bnjjj or @me-diru Any chance you have any feedback or updates? Happy to help with reproducing or anything else.

**Comment by joatkh** [comment]
@bnjjj @me-diru,

We're hitting the same issue as describe here

Our Router version is 1.2.0

FYI, I look the the tests you've done and the following works

```
telemetry:
  tracing:
    otlp:
      endpoint: otlp.nr-data.net:4317
      grpc:
        metadata:
          "api-key": 
             - ${NEW_RELIC_LICENSE_KEY}
```

But not 

```
telemetry:
  tracing:
    otlp:
      endpoint: otlp.nr-data.net:4317
      grpc:
        metadata:
          "api-key": ${NEW_RELIC_LICENSE_KEY}
```
Should we reopen the issue?

**Comment by bnjjj** [comment]
Is it related to #1976 ? I think so. You should try to upgrade the router to `1.2.1`. Let me know if it works
