### ISSUE TITLE
Defer: move the stream of responses inside ExecutionResponse and RouterResponse

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1188]
Instead of using `BoxStream<ExecutionResponse>` everywhere, we could move the stream inside of `ExecutionResponse`, as follows:

```diff
-pub struct ExecutionResponse {                             
-    pub response: http_compat::Response<Response>,         
+pub struct ExecutionResponse<T: Stream<Item = Response>> { 
+    pub response: http_compat::Response<T>,                
                                                            
     pub context: Context,                                  
 }                                                                                                         
```

This is explored in the branch https://github.com/apollographql/router/tree/geal/les-epinards-cest-plein-defer

Right now this is running into multiple issues:
- https://github.com/BrynCooke/buildstructor/issues/60
- we cannot make `ExecutionResponse` generic over the stream in `DynPlugin::execution_service`, because then the trait is not object safe: https://github.com/apollographql/router/blob/geal/les-epinards-cest-plein-defer/apollo-router-core/src/plugin/mod.rs#L128-L133

**Comment by BrynCooke** [comment]
@Geal I updated buildstructor on main, so can you check to see if you still have issues with trait bounds?
