### ISSUE TITLE
Release Binaries for ARM-based Architectures 

### ISSUE THREAD

**Issue by medelman17** [apollographql/router#1192]
**Describe the solution you'd like**
As a developer building supergraphs on and or for deployment to `ARM`-based architectures/environments, I need suitable static binaries to be made at the ready for each release so that I can get up and running on my Apple silicon, RaspberryPi, Graviton-backed cloud functions, etc, quickly and without fanfare.  

**Describe alternatives you've considered**
I can build binaries from source that target the above mentioned environments no problem; however, that's a point of friction that I could do without. Running `x86_64` in an emulated environment is a non-starter. 

**Additional context**
Writing this issue whilst building `router` on a [RaspberryPi Zero 2W](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/) (1GHz quad-core 64-bit Arm Cortext-A53 CPU). So, suffice it to say, lots of idle time on my hands. 
<img width="574" alt="Screen Shot 2022-06-05 at 9 06 58 PM" src="https://user-images.githubusercontent.com/14793389/172078895-f01e82c6-a3ab-4f0b-9a56-4681899dc797.png">

See also #65

**Comment by hobbsh** [comment]
@medelman17 Trying to understand what the blockers are for this as it's a huge issue for us running the `router` locally. Do you have any pointers on how to potentially cross-compile the `router` and build our own docker image? Could it be as simple as something like `RUN cargo build --release --target aarch64-unknown-linux-gnu` in a separate dockerfile? I notice there's `--platform linux/amd64` all over the existing dockerfiles so am anticipating it could be a headache to untangle that web of dependencies, but maybe not?
