### ISSUE TITLE
router scaffold support not working after crate merge

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1193]
The merge of `apollo-router-core` into `apollo-router` means the scaffold stuff is currently broken. Explanation: The scaffold has been updated to now only refer to `apollo-router`, which is locked to use `apollo-router` with a git tag of the current release `0.9.3`. This means that if you generate a project right now, the generated `Cargo.toml` will only refer to `apollo-router`, but in `0.9.3` it should also be referring to `apollo-router-core`.

I think the fix is that we need to revert the recent changes to the scaffold generating parts until we cut a release. To prevent this kind of problem in future, we should only update the scaffold generating parts when we cut a release. I'm going to wait for someone more scaffold knowledgeable than I to address this.

**Comment by BrynCooke** [comment]
We could also update the docs to get cargo-scaffold to use a particular release. Pinning to 0.9.3.
When the release happens we have to bump the docs.

**Comment by BrynCooke** [comment]
I think this is fixed as part of #1247
