### ISSUE TITLE
APQ: Move the layer to a plugin

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1205]
APQ is one of the few remaining layers; we want to make it a plugin.

While we're at it, it would be nice to investigate the Cache size aware eviction feature.

**Comment by tatsuya6502** [comment]
Hi. Thank you for using Moka cache as the default in-memory cache for the APQ. Please feel free to ask me any questions about Moka and its size aware eviction feature. (I am the Moka author)

**Comment by o0Ignition0o** [comment]
Hey, it's nice to meet you!

I sure will, thanks for your time :)

**Comment by abernix** [comment]
Duplicate of #1125
