### ISSUE TITLE
API 1.0 - Remove apollo_router::prelude::graphql reexports

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1214]
This is part of https://github.com/apollographql/router/issues/1150

Since https://github.com/apollographql/router/pull/1189 this module is only:

```rust
pub mod prelude {
    // …

    pub mod graphql {
        pub use crate::*;
    }
}
```

… which isn’t particularly useful.

**Comment by o0Ignition0o** [comment]
this looks good to me as well (sorry i didnt notice)
