### ISSUE TITLE
API 1.0 - Reconsider reexports from the crate top-level ?

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1217]
This is part of https://github.com/apollographql/router/issues/1150

## Update as of https://github.com/apollographql/router/pull/1242

The remaining reexports that I think we should still reconsider (but haven’t removed yet because they have very many users) are:

```rust
pub use router::{ApolloRouter, ConfigurationKind, SchemaKind, ShutdownKind};
pub use services::http_compat;
pub use services::PluggableRouterServiceBuilder;
pub use services::ResponseBody;
pub use services::{ExecutionRequest, ExecutionResponse, ExecutionService};
pub use services::{QueryPlannerRequest, QueryPlannerResponse};
pub use services::{RouterRequest, RouterResponse, RouterService};
pub use services::{SubgraphRequest, SubgraphResponse, SubgraphService};
pub use spec::Schema;
pub(crate) use spec::*;
```

## Original description

`apollo-router/src/lib.rs` contains:

```rust
pub use cache::*;
pub use context::*;
pub use error::*;
pub use introspection::*;
pub use json_ext::*;
pub use layers::*;
pub use plugin::*;
pub use query_cache::*;
pub use query_planner::*;
pub use request::*;
pub use response::*;
pub use router::*;
pub use service_registry::*;
pub use services::*;
pub use spec::*;
pub use traits::*;
```

This makes the public API flat(er). Note that some (but not all) of these modules are also public, making the same items available at (at least) two different paths each.

Is this what we want? Or should the public API have modules to categorize related items together?

**Comment by garypen** [comment]
I prefer modules for grouping. Maybe we need a poll?

**Comment by BrynCooke** [comment]
We should definitely eliminate multiple paths for the same items.

Personally like having modules, but could be convinced for flat if there is a good argument for it.

**Comment by SimonSapin** [comment]
While I tend to prefer modules, when removing reexports the migration of existing code that relies on them is painful since it’s not obvious which module a given item should be imported from instead

**Comment by SimonSapin** [comment]
I’ve updated the [issue description](https://github.com/apollographql/router/issues/1217#issue-1266359949) with the state after PR https://github.com/apollographql/router/pull/1242

**Comment by SimonSapin** [comment]
As of  https://github.com/apollographql/router/pull/1277 the remaining reexports are:

```rust
pub use configuration::Configuration;
pub use context::Context;
pub use executable::{main, Executable};
pub use request::Request;
pub use response::Response;
pub use router::{ApolloRouter, ConfigurationKind, SchemaKind, ShutdownKind};
pub use services::http_compat;
pub use spec::Schema;
```

… which feels reasonable to me. Should we reduce still, or are we happy to close this?
