### ISSUE TITLE
Incomplete support for introspection queries

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1230]
In the selections parsing, we recognize introspection fields using the `__` prefix:

https://github.com/apollographql/router/blob/440b59b397b5cc4da1556049039f556bc6c38c86/apollo-router/src/spec/selection.rs#L88-L111

But it is not enough for introspection queries. With the following query:

```graphql
query {
  __schema {
    queryType {
      name
    }
  }
}
```

We would recognize `__schema`, but then `queryType` is unknown because we do not know the fields of the `__Schema` type.

To fix that, the schema object should carry by default the introspection object types

**Comment by bnjjj** [comment]
We need to support these types https://spec.graphql.org/October2021/#sec-Schema-Introspection.Schema-Introspection-Schema
