### ISSUE TITLE
Since 0.9.4, the context's changes on subgraph_service are not visible in router_service

### ISSUE THREAD

**Issue by yanns** [apollographql/router#1244]
**Describe the bug**
Since 0.9.4, the context's changes on `subgraph_service` are not visible in `router_service`.

**To Reproduce**
In one plugin, inside `subgraph_service`, we read some information from `SubgraphResponse` and put it into the context.
```
    fn subgraph_service(
        &mut self,
        _name: &str,
        service: BoxService<SubgraphRequest, SubgraphResponse, BoxError>,
    ) -> BoxService<SubgraphRequest, SubgraphResponse, BoxError> {
        ServiceBuilder::new()
            .map_response(|res: SubgraphResponse| {
                if let Some(duration) = res.response.headers().get("Server-Timing") {
                    let _ = res
                        .context
                        .insert("Server-Timing", String::from(duration.to_str().unwrap()))
                        .unwrap();
                }
                res
            })
            .service(service)
            .boxed()
    }
```

We read that information in `router_service`:
```
    fn router_service(
        &mut self,
        service: BoxService<
            RouterRequest,
            RouterResponse<BoxStream<'static, ResponseBody>>,
            BoxError,
        >,
    ) -> BoxService<RouterRequest, RouterResponse<BoxStream<'static, ResponseBody>>, BoxError> {
        ServiceBuilder::new()
            .map_response(
                |mut res: RouterResponse<BoxStream<'static, ResponseBody>>| {
                    if let Some(duration) =
                        res.context.get::<&str, String>("Server-Timing").unwrap()
                    {
                        res.response.headers_mut().insert(
                            "Server-Timing",
                            http::HeaderValue::from_str(duration.as_str()).unwrap(),
                        );
                    }
                    res
                },
            )
            .service(service)
            .boxed()
    }
```

This is working in v0.9.3. In v0.9.4, it stops working.
In `router_service`, we don't observe the context's changes that are made in `subgraph_service` .

**Expected behavior**
If we are using the API correctly, I'd expect the code to continue working.
But maybe we're not using it correctly.

**Comment by o0Ignition0o** [comment]
Hey Yanns and thanks a lot for raising this issue!

Our recent changes to stream management introduced quite a fair bit of complexity.

I have put together a [plugin example](https://github.com/o0Ignition0o/quick-stream-example/blob/3a861aa21667711733ddd585fbca3b6729b205f5/src/plugins/test_plugin.rs#L122) that uses streams and `map_future_with_context` to show how to push timings to the context and print it, which should get you closer to your goal.

It's worth noting that given the Body of the response is now a stream, we need to wait until we receive the first response before we have a look at the context.

Using `map_future_with_context` in the `router_service` may allow you to put the timings in the headers, but I'll need to dig a bit futher to make sure it's the case.

Regardless, I'd like to let you know that while stream support is very important to us, we acknowledge that there's a lot of induced complexity, and we're trying to find ways to provide Plugin users with APIs that are easier to use.

Raising issues helps us a lot in this respect.

**Comment by o0Ignition0o** [comment]
https://github.com/apollographql/router/pull/1260 once merged should ease this by a substantial amount!
I'll update the plugin example once it's merged on main

**Comment by o0Ignition0o** [comment]
I've updated my plugin example [to target the branch](https://github.com/o0Ignition0o/quick-stream-example/pull/1/files), and it does show timings in the response headers 🎉 

```bash
curl -v \
--header 'content-type: application/json' \
--url 'http://127.0.0.1:4000/' \
--data '{"query":"query Me {\n  me {\n    name\n  }\n}","variables":{}}'


*   Trying 127.0.0.1:4000...
* Connected to 127.0.0.1 (127.0.0.1) port 4000 (#0)
> POST / HTTP/1.1
> Host: 127.0.0.1:4000
> User-Agent: curl/7.79.1
> Accept: */*
> content-type: application/json
> Content-Length: 63
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< subgraph-response-time-accounts: 151.496791ms
< content-type: application/json
< content-length: 39
< vary: origin
< vary: access-control-request-method
< vary: access-control-request-headers
< date: Wed, 15 Jun 2022 13:28:02 GMT
<
* Connection #0 to host 127.0.0.1 left intact
{"data":{"me":{"name":"Ada Lovelace"}}}
```

We'll try to get this merged and cut a release soon. Thanks again for raising the issue

**Comment by yanns** [comment]
💯 
Thanks a lot for the quick response!

**Comment by yanns** [comment]
fixed by https://github.com/apollographql/router/pull/1260
