### ISSUE TITLE
Add request_timeout to traffic shaping plugin

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1275]
This needs to be configurable at the overall router_service and at the subgraph level.
Config could follow the shape recently discussed in #1162

**Comment by deweyjose** [comment]
This would be extremely useful for our use-cases as well.

**Comment by bnjjj** [comment]
Hello @deweyjose ! It's currently in progress. Hopefully it will be available soon

**Comment by deweyjose** [comment]
> Hello @deweyjose ! It's currently in progress. Hopefully it will be available soon

Just to confirm - we'll have the ability to apply timeout configuration for all requests as well as customize timeouts per sub-graph?

**Comment by bnjjj** [comment]
Yes exactly ! You can take a look at this PR https://github.com/apollographql/router/pull/1347
