### ISSUE TITLE
Query including fragments return null

### ISSUE THREAD

**Issue by xsoufiane** [apollographql/router#1290]
**Describe the bug**
We have a query using fragments
```
{
  ...ShoppingListFragmentTest
}

fragment ShoppingListFragmentTest on ShoppingListQueryInterface {
shoppingLists {
  results {
    id
  }
  total
}
```
the router returns data:null for it, although the sub-service returns a valid non-null response. We are assuming that there is an issue in assembling the response. The query plan for the query is:
```
query plan is: QueryPlan {
   usage_reporting: UsageReporting { 
 	stats_report_key: "# -\nfragment ShoppingListFragmentTest on ShoppingListQueryInterface{shoppingLists{results{id}total {...ShoppingListFragmentTest}", 
        referenced_fields_by_type: {
           "ShoppingListQueryInterface": ReferencedFieldsForType { field_names: ["shoppingLists"], is_interface: true }, 
           "ShoppingListQueryResult": ReferencedFieldsForType { field_names: ["results", "total"], is_interface: false },            
           "ShoppingList": ReferencedFieldsForType { field_names: ["id"], is_interface: false }
        } 
    },
     root: Fetch(FetchNode { service_name: "sphere", requires: [], variable_usages: [], operation: "{shoppingLists{results{id}total}}", operation_name: None, operation_kind: Query }) }
```

**Expected behavior**
router should be able to assemble the response and return non-null data.

**Comment by xsoufiane** [comment]
for info we are using router-v0.9.3

**Comment by Geal** [comment]
thanks! That looks like #1286, no?

**Comment by Geal** [comment]
@xsoufiane does this look like the schema you are working with?
https://github.com/apollographql/router/pull/1296/files#diff-ca21c6c2d8f5eacbc8fd08524c17571552b1ec649c2911b908b03b94b2c7c99fR4578-R4603
Maybe with the `object` field set to non null?

**Comment by Geal** [comment]
Great, then I have a good idea of the cause. May I ask why you go through a fragment then an interface on the query object? This feels a bit weird to me so there's probably a use case I don't know about

**Comment by yanns** [comment]
Yes we use interfaces on query so that one can re-use the same queries on the top field, or on another sub-field:
```
{
  orders { // all orders
     ....
  }
}
```

```
{
  store(key: "store-DE") {
    orders { // orders in the store in Germany
       ....
    }
  }
}
```

**Comment by Mithras** [comment]
While this is an open issue. Is there a reason router silently returns null instead of propagating an exception or something? I have another case than router returns null (not radiated to fragments) and the lack of feedback damages my soul

**Comment by Geal** [comment]
@yanns thanks, that's interesting :)
@Mithras yes, that's not great for now, we're planning to add error messages along with the nullability rules. Could you post another issue for your other case? I'd be happy to take a look

**Comment by Geal** [comment]
@Mithras making a note of the error message for nullified fields in https://github.com/apollographql/router/issues/1304

**Comment by xsoufiane** [comment]
thank you @Geal
