### ISSUE TITLE
Upgrading from crossbeam-utils 0.7

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1318]
Dependabots reports that we may be affected by https://github.com/advisories/GHSA-qc84-gqf4-9926. In order to remove crossbeam-utils 0.7.x from our dependency graph we would need for `moka` to upgrade its `crossbeam-epoch` dependency, which is unfortunately blocked at the moment.

https://github.com/moka-rs/moka/blob/v0.8.6/Cargo.toml#L52-L55
https://github.com/moka-rs/moka/issues/34#issuecomment-1168682179

However this crossbeam-utils 0.7 issue only occurs on 32-bit platform. It is unlikely that any router user targets such a platform, but we could add something to artificially make compilation warn or fail in that case.

**Comment by tatsuya6502** [comment]
I did a bit of digging on this, and now I believe Apollo router is not affected by https://github.com/advisories/GHSA-qc84-gqf4-9926 at all, even for those target platforms. I am currently confirming this to the creators of `crossbeam-*` crates via https://github.com/crossbeam-rs/crossbeam/issues/860.

Here is a summary:

- Dependency graph:
   - `router` → `moka` v0.8.6 → `crossbeam-epoch` v0.8.2 → `crossbeam-utils` v0.7.2 with https://github.com/advisories/GHSA-qc84-gqf4-9926.
- From the advisory:
   - > Crates using `fetch_*` methods with `AtomicCell<{i,u}64>` are affected by this issue.
   - I found that `crossbeam-epoch` v0.8.2 does not use `crossbeam_utils::AtomicCell`, so it is not affected.

I am also asking the crossbeam creators if they can publish a new v0.8.x of `crossbeam-epoch`, which depends on a fixed version of `crossbeam-utils` (although `crossbeam-epoch` v0.8.2 is not affected). I think this will be an easy way to make GitHub Dependabot happy.

I will let you know if I get any response from them.

**Comment by tatsuya6502** [comment]
Hi. I fixed the blocking issue in `moka` (https://github.com/moka-rs/moka/issues/34#issuecomment-1188887352). So I was able to upgrade `moka`'s `crossbeam-epoch` dependency to the latest version to remove `crossbeam-utils` 0.7.x from the dependency graph.

I published `moka` [v0.9.2](https://crates.io/crates/moka/0.9.2) to crates.io with the fix for the issue and the upgraded dependency. Please upgrade your `moka` dependency to v0.9.2 when you have a chance.

**Comment by SimonSapin** [comment]
This is great, thank you!
