### ISSUE TITLE
OpenTelemetry semantic attributes

### ISSUE THREAD

**Issue by kroehre** [apollographql/router#1322]
Hi! Semantic otel attributes have been added for GraphQL, it would be great to follow those conventions. 

**Describe the solution you'd like**

On the `router` span:
- Change `operation_name` attribute to `graphql.operation.name`
- Change `query` attribute to `graphql.document`
- Add `graphql.operation.type`

**Additional context**

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/graphql.md

**Comment by bnjjj** [comment]
Thanks for creating this issue, this will be solved in the same PR than #1270
