### ISSUE TITLE
metrics: add support of resources

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#1325]
Especially with the service name for example. Also related to #1162

**Comment by abernix** [comment]
My understanding is that this an exporter specific attribute that is more global 🌐  than attributes.  While this refers to the "service name" (e.g., `service.name` in metrics but `service_name` in tracing, we **think**), the _service name_ isn't the only thing that matters, it just so happens that _service name_ is one of the properties that is supported by most exporters.
