### ISSUE TITLE
Rename `variables_deduplication` to `deduplicate_variables`

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1330]
`deduplicate_variables` is less ambiguous.

**Comment by garypen** [comment]
I can't remember why we thought this was less ambiguous. It doesn't seem that ambiguous to me right now. Maybe some of the other api-1.0 cleanup stuff we've done has had that effect or ...

Also: there is `query_deduplication` which I think we would also want to rename for consistency reasons.

Proposal:  We close this as `won't fix` unless we can remember why we thought it was less ambiguous. If we do want to do it, then we should also rename `query_deduplication` to `deduplicate_query`.

**Comment by BrynCooke** [comment]
Variables deduplication sounds wrong (due to the variable being made plural via deduplication e.g word deduplication Vs words deduplication) and variable deduplication is ambiguous.

**Comment by garypen** [comment]
Ok: so we should do it, and for consistency I should do `deduplicate_query`.
