### ISSUE TITLE
Fields missing when using a fragment on a union

### ISSUE THREAD

**Issue by danburtenshaw** [apollographql/router#1334]
**Describe the bug**
We would like to replace our Apollo Gateway with the Apollo Router however a specific query has stopped working.

See the example below:

Schema
```graphql
extend type AccountLocation @key(fields: "id") {
  id: ID! @external
}

union ServiceLocation = AccountLocation | Address

type ServiceSettings {
  …
  location: ServiceLocation
}

type Query {
  settings: ServiceSettings
}
```

Query
```graphql
query getSettings {
  settings {
    location: {
      …SettingsLocation
    }
  }
}

fragment SettingsLocation on ServiceLocation {
  ... on Address {
    city
    …
  }
   ... on AccountLocation {
     id
     address {
       city
       …
     }
   }
}
```

When running this query the `location` field is empty even though we are returning the following in the resolver. 
```js
{
  __typename: 'AccountLocation',
  id: ‘1234’,
}
```

If we move the contents of the fragment directly under `location` then the query does work as expected.
This also seems to occur even if we use the `Address` type which is specified in the same subgraph.
This same query works on our existing Apollo Gateway instance.

Any ideas what could be going wrong here?

**Additional context**
Apollo Router Version:  tested v0.9.5 and latest main (b98477e)
Subgraph: Federation 2

**Comment by Geal** [comment]
do you see a difference between the test I wrote and your schema that could be relevant? https://github.com/apollographql/router/commit/7ba8ce0fce905e3083eb8a38ff4f77fda5178fd5#diff-ca21c6c2d8f5eacbc8fd08524c17571552b1ec649c2911b908b03b94b2c7c99fR4852

**Comment by danburtenshaw** [comment]
I did try to simplify the example to make the issue easier to understand so our schema does look a little different.
These are the differences I notice although may not be relevant.
1. `AccountLocation` is resolved from a different subgraph
2. The `ServiceLocation` union consists of 3 types
3. The fragment is nested within another fragment (`Basket` fragment uses `SettingsLocation`)

Below is a more accurate example.

Schema
```graphql
extend type AccountLocation @key(fields: "id") {
  id: ID! @external
}

type NewAccountLocation {
  label: String
  address: Address!
}

union ServiceLocation = AccountLocation | Address | NewAccountLocation

type ServiceSettings {
  …
  location: ServiceLocation
}

type GmBasket @key(fields: "id") {
  id: ID!
  ...
  settings: ServiceSettings!
}

type Query {
  basket: GmBasket
}
```
Query
```graphql
query getSettings {
  basket {
    ...Basket
  }
}

fragment Basket on GmBasket {
  id
  settings {
    location {
      ...SettingsLocation
      ... on AccountLocation {
        instructions
      }
    }
  }
}

fragment SettingsLocation on ServiceLocation {
  ... on Address {
    city
    …
  }
   ... on AccountLocation {
     id
     address {
       city
       …
     }
   }
   ... on NewAccountLocation {
     id
     address {
       city
       …
     }
   }
}
```

If I remove the second level of nesting by including `Address`, `AccountLocation` and `NewAccountLocation` directly within the `Basket` fragment then it does work as expected.

**Comment by bnjjj** [comment]
Hello @danburtenshaw I tried to reproduce your bug by creating this test https://github.com/apollographql/router/compare/main...bnjjj/fix_1334 and it works. Did I miss something ? Are you sure your subgraph is returning the right payload with the `__typename` ?

**Comment by danburtenshaw** [comment]
Hi @bnjjj,
That test looks okay to me so unsure why we are seeing different behaviour.
I have added additional logging to see exactly what payload is returned from the `location` resolver. See below.
```js
{
  flatOrBuilding: null,
  street: 'Fulham Palace Road',
  postcode: 'W6 8RF',
  city: 'London',
  country: 'United Kingdom',
  latitude: 51.4868889,
  longitude: -0.2195543,
  __typename: 'Address'
}
```

I have checked the payload for all the following cases and they are all identical but still fail on the router. 
✅ Apollo Gateway with one level of nesting (fragment `Basket`)
✅ Apollo Gateway with two levels of nesting (fragment `Basket` and `SettingsLocation`)
✅ Apollo Router with one level of nesting (fragment `Basket`)
❌  Apollo Router with two levels of nesting (fragment `Basket` and `SettingsLocation`)

If it helps I have added some links to the Apollo Sandbox so you can see what we are seeing.

[Apollo Gateway](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fstage.feedr.co%2Fapi%2Fgraphql&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAOYIoBCAhgM4DW5AFACQCWY6RAkgCICEASiLAAOkiJEARrQYpOJONXpN2nNmCGjxEogDp9S2WIkBfMWaRiAZnioLkKIofJEI4gOKKZLrRPbGiGnIUViQSGmEAiQAbaCoQt0jtHT19AFUgvGcUAGVg0PCAGTiEy2SiC1NzMWtbe1QiDPxsvJQQsJpiqHjWRMTPPLwAN1YoBC6exN9U3VdxAEEwMDwEGgjpiSto%2BIB5LJhWaLACqKIoVhQCU6gIGFRCU4AHCBoUG7AEU9eV8lPtkJQMA%2BfzcJAuQM%2B5QA%2BlDLo9kFREAELCYQAAaEBDKh4VhUSTRVYYEAAemJRAAFm1HjR0KTXnYELorAgEMtdDdiVRHqxiSRbI9yVhoiI8GJSRSqTTSSQhbp6WQmSy2Ry%2BVzBcLRZZNaJNRJxfMoDc7igJqURQFxSIQP4MEQrQA2ABMVAA7AAGF1gPFUACMVA9brdPp9ABYqCGABz2%2B1W81ai1kxbLVY0OMSK02zgOx2SBCSENWADMIbAjqg9oQgeDwZzAFYYyA46iTEA) two levels of nesting (working)
[Apollo Router](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgql.stage.feedr.co%2Fgraphql&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAOYIoBCAhgM4DW5AFACQCWY6RAkgCICEASiLAAOkiJEARrQYpOJONXpN2nNmCGjxEogDp9S2WIkBfMWaRiAZnioLkKIofJEI4gOKKZLrRPbGiGnIUViQSGmEAiQAbaCoQt0jtHT19V3EAQTAwPAQaCN8UnSto%2BIB5PAoYVmiwUJIooqhWFAJGlKgIGFRCdp0ABwgaFE6wBD6JYdzyCaJSkJQYMdnYsJal8eSigH1t1v7kKkQ%2BixTTogsLMQBiIhs7RFQiAFUgyu8UAGVg%2BpoAGTiCXEiU83zwADdWFAEACoPFWIktLcJPpdOkiFkcnkCjciiVypVqrV6riOi02khkTpOt0UL1KUVBsNRpsqZM6QgZgyUvN1stuTpViQ%2BaydnsCAckEdRaZcSYQAAaEDgqh4VhUSTRPIYEAAel1RAAFigUP0aOh9cM7AhdFZOTldJ1dVR%2BqxdSRbP1DVhoiI8GJ9UaTWaLe6fborWRbfa8I6IO7Pd7ff7LCnRCmJIHMbl8n6AiIQP4MEQCwA2ABMkgQkgALFYAMw1sDlqClhAABnbAEYe13KwBWUsFvNIeUmIA) one level of nesting (working)
[Apollo Router](https://studio.apollographql.com/sandbox/explorer?endpoint=https%3A%2F%2Fgql.stage.feedr.co%2Fgraphql&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAOYIoBCAhgM4DW5AFACQCWY6RAkgCICEASiLAAOkiJEARrQYpOJONXpN2nNmCGjxEogDp9S2WIkBfMWaRiAZnioLkKIofJEI4gOKKZLrRPbGiGnIUViQSGmEAiQAbaCoQt0jtHT19AFUgvGcUAGVg0PCAGTiEy2SiC1NzMWtbe1QiDPxsvJQQsJpiqHjWRMTPPLwAN1YoBC6exN9U3VdxAEEwMDwEGgjpiSto%2BIB5LJhWaLACqKIoVhQCU6gIGFRCU4AHCBoUG7AEU9eV8lPtkJQMA%2BfzcJAuQM%2B5QA%2BlDLo9kFREAELCYQAAaEBDKh4VhUSTRVYYEAAemJRAAFm1HjR0KTXnYELorAgEMtdDdiVRHqxiSRbI9yVhoiI8GJSRSqTTSSQhbp6WQmSy2Ry%2BVzBcLRZZNaJNRJxYtlqsaCKAiIQP4MEQzQA2ABMkgQkgALFYAMxOsC2qDWhAABl9AEYgwH7QBWa1mk1IVEmIA) two level of nesting (not working)
