### ISSUE TITLE
Open a Slack Channel

### ISSUE THREAD

**Issue by Archisman-Mridha** [apollographql/router#1380]
**Is your feature request related to a problem? Please describe.**
Currently i see no way to communicate with the existing maintainers and contributors of this project and learn more about it so that i can also become a contributor.

**Describe the solution you'd like**
I suggest creating a slack channel where everyone can communicate with each other and discuss more about the project, get help if they get stuck etc

**Comment by Geal** [comment]
the [Discussions tab](https://github.com/apollographql/router/discussions) is meant for more general chat about the project, and wil be a better fit to communicate with the team, as we are mainly on european timezones and work asynchonously
