### ISSUE TITLE
pre-built binaries should include fully qualified target

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/router#1385]
our pre-built binaries are just called "linux" "macos" and "windows" - it does not call out anything about underlying architectures (`x86` vs. `ARM`) nor about the toolchain (`gnu` vs `musl` vs `msvc`). this information should be included in the tarball release directories.

**Comment by EverlastingBugstopper** [comment]
check out [rover's release page](https://github.com/apollographql/rover/releases) to see the convention we use there

**Comment by Geal** [comment]
right, we show the architecture but not the full triplet, we should fix that
