### ISSUE TITLE
 no http client error with OpenTelemetry Tracing 

### ISSUE THREAD

**Issue by cli00004** [apollographql/router#1386]
**Describe the bug**
I'm getting the following error in the ApolloRouter when using OpenTelemetry tracing 

{"timestamp":"2022-07-12T00:12:55.237902Z","level":"ERROR","fields":{"message":"OpenTelemetry trace error occurred: Exporter otlp encountered the following error(s): no http client, you must select one from features or provide your own implementation"},"target":"apollo_router::plugins::telemetry"}

This is my Router.yaml 
![image](https://user-images.githubusercontent.com/94087985/178390341-2ea7302f-cb71-4065-a52e-a2da54b51aeb.png)

**To Reproduce**
1. Setup services '...'
2. Submit request '....'
3. See error

**Expected behavior**

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: kubernetes
 - Version 0.9.0

**Additional context**

**Comment by Geal** [comment]
thanks for the report, that should be easy to fix
