### ISSUE TITLE
Specifying origins manually doesn't set response headers properly

### ISSUE THREAD

**Issue by hchockarprasad** [apollographql/router#1390]
**Describe the bug**
Specifying origins doesn't set `Allow Origin Headers` to specified values even the default apollo studio url will not be applied if specified manually, whereas omitting origins field sets the default header to apollo studio properly

**To Reproduce**
1. Specify few origins under cors section on router config file (can specify apollo studio url also).
2. Open apollo studio and try to connect the router
3. Error will be seen on network window and inspect the response header it will not contain the expected origin set.

**Expected behavior**
Specifying origins should properly set Allow Origin Headers to specified values in response headers

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**

**Comment by Geal** [comment]
hi, thanks for the report, could you show us the configuration file you are using?

**Comment by hchockarprasad** [comment]
Hi,
This is the config that i tried.
![routerconfig](https://user-images.githubusercontent.com/22501803/178905045-e5f38cf4-5311-4aae-bb17-717d9e43ba92.png)

**Comment by john-dodson** [comment]
I have this issue, too. The only time `access-control-allow-origin` is returned as a response header is when I set `allow_any_origin: true`

**Comment by o0Ignition0o** [comment]
Hi!

I've just tweaked our configuration a bit in #1444, so I'll try to reproduce and fix the issue while at it!

**Comment by o0Ignition0o** [comment]
I m going to mark this issue as resolved, feel free to reopen if it doesn't work with the next release (which will be out in a couple of hours!)
