### ISSUE TITLE
external cache for APQ

### ISSUE THREAD

**Issue by deweyjose** [apollographql/router#1401]
**Describe the solution you'd like**
Support external storage of APQ cache to help limit the frequency of full APQ handshakes. Currently the NodeJS Gateway implementation supports this, and we saw a huge reduction in additional requests once rolled out. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Geal** [comment]
this is a planned feature, and there's work in #1281 to support it. How large is the APQ cache you are using? number of entries, estimate byte size overall?

**Comment by abernix** [comment]
Just noting that this relates to  #329

**Comment by deweyjose** [comment]
great thx @abernix

**Comment by deweyjose** [comment]
Follow up question - thoughts on APQ lifecycle events? 

Why - Currently researching a replacement for operations safelisting. If we had an opportunity to map in a query on the original `persistedQuery` GET request we can validate the hash is registered, map in the registered query, save an additional round trip.

**Comment by chandrikas** [comment]
Hi @deweyjose - [this feature](https://www.apollographql.com/blog/announcement/backend/apollo-router-v1-12-improved-router-security-performance-and-extensibility/#maximize-performance-at-scale) is now GA! Hope you can try it out soon and send us your feedback :pray:
