### ISSUE TITLE
Custom plugin checkpoints should execute on OPTIONS requests

### ISSUE THREAD

**Issue by john-dodson** [apollographql/router#1425]
**Describe the bug**
I have a custom plugin to handle some specific CORS configuration. The checkpoint I added in `router_service` executes properly when actually performing a GraphQL query, but when making an OPTIONS requests it does not execute at all. My checkpoints should run with all request methods because I should be able to return Unauthorized errors for OPTIONS requests if I want to. I can't seem to locate where in the router the request is terminating early or else I would create a PR to fix it myself.

**To Reproduce**
1. Add custom plugin
```
use std::ops::ControlFlow;

use apollo_router::layers::ServiceBuilderExt;
use apollo_router::plugin::Plugin;
use apollo_router::{register_plugin};
use apollo_router::services::{RouterRequest, RouterResponse};
use tower::{util::BoxService, BoxError, ServiceBuilder, ServiceExt};
use schemars::JsonSchema;
use serde::Deserialize;

#[derive(Debug, Default, Deserialize, JsonSchema)]
struct Conf;

// We are storing the configuration, but not using it. Hence the allow dead code.
#[derive(Debug, Default)]
struct PrintCheckpoint;


#[async_trait::async_trait]
impl Plugin for PrintCheckpoint {
    type Config = Conf;

    async fn new(_configuration: Self::Config) -> Result<Self, BoxError> {
        return Ok(Self {})
    }

    fn router_service(
        &self,
        service: BoxService<
            RouterRequest,
            RouterResponse,
            BoxError,
        >,
    ) -> BoxService<RouterRequest, RouterResponse, BoxError> {

        ServiceBuilder::new()
            .checkpoint(move |req: RouterRequest| {
                println!("Checkpoint");
                Ok(ControlFlow::Continue(req))
            })
            .service(service)
            .boxed()
    }
}

register_plugin!("plugins", "print", PrintCheckpoint);
```
2. Compile router
3. Start router
4. Run 
```
curl -XOPTIONS -s -D - -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://localhost:3000' --data-binary 'YOUR QUERY HERE' --compressed http://localhost:4000/graphql
```

**Expected behavior**
It prints `Checkpoint`

**Output**
It did not print anything

**Desktop (please complete the following information):**
 - OS: [macOS 12.4]
 - Version [0.12.0, (main commit sha a05f08654fd950443ad55ca4ac75cd9a55a20bb5)]

**Comment by john-dodson** [comment]
Alternatively it would be great if we could load custom axum middleware plugins. I had to fork this repo and add one to appropriately handle and OPTIONS request for my needs.

**Comment by o0Ignition0o** [comment]
Hi, thanks for submitting this issue!

If I’m getting it right, you’re looking for more advanced settings for CORS than [what we currently provide](https://www.apollographql.com/docs/router/configuration/cors#all-cors-options)

Could you please give us more info as to what customizations would help?

For example would the ability to provide regex based host matching in YML be sufficient?
