### ISSUE TITLE
update the embedded sandbox

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1426]
the current one does not ship with support for `@defer` (added in https://github.com/mdg-private/studio-ui/pull/6373)

**Comment by o0Ignition0o** [comment]
Marked as blocked while waiting for a sandbox update, this should upgrade automatically on the routers side (as soon as the cdn gets the update)

**Comment by abernix** [comment]
@Geal Do you know if this has happened? The referenced ticket is closed.

**Comment by Geal** [comment]
I have not tested yet, but if it's been published, it should work directly in the router

**Comment by abernix** [comment]
Yeah, I have no idea how to tell if it was published.

**Comment by Geal** [comment]
I tested it, it works now
