### ISSUE TITLE
Why router need libz.so.1?

### ISSUE THREAD

**Issue by thetruechar** [apollographql/router#1430]
As the Dockerfile https://github.com/apollographql/router/blob/main/dockerfiles/Dockerfile.router#L29
```
# Copy in the extracted/created files
COPY --from=libz-required /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
```

**Comment by o0Ignition0o** [comment]
Hi!
One of the features provided by the router is [http compression support](https://www.apollographql.com/docs/router/configuration/traffic-shaping/).

This effectively means you can set up the router to use compression (`gzip`, `br`, or `deflate`) when sending requests to subgraphs.

`deflate` relies on [flate2](https://github.com/rust-lang/flate2-rs), which is a wrapper over Libz, hence the requirement.

I hope this helps, feel free to reopen if it doesn't!
