### ISSUE TITLE
Slow response times with large documents

### ISSUE THREAD

**Issue by Mithras** [apollographql/router#144]
**Describe the bug**
Performance on large responses is even worse than with gateway. This makes federation unusable if you need to query large amounts of data.
 E.g.
router (it doesn't gzip but it's all running on localhost so size is not the reason it's 10 times slower):
![image](https://user-images.githubusercontent.com/2098029/141851039-c7c28dfa-eef0-4d31-8d0c-79cbbc91f71e.png)
gateway:
![image](https://user-images.githubusercontent.com/2098029/141851237-300d10ea-5951-4706-a96b-dbfa8c6bfe37.png)
direct:
![image](https://user-images.githubusercontent.com/2098029/141851967-b69b5853-eec8-4a7d-b1af-f1f466aad80f.png)

**To Reproduce**
1. Setup subgraph that returns a few Mb of any objects.
2. Query it directly
3. Query it through gateway/router. Gateway adds over 2x overhead. Router adds over 10x overhead.

**Expected behavior**
Router overhead at least shouldn't be worse than gateway.

**Desktop (please complete the following information):**
 - OS: [node:](https://hub.docker.com/_/node)
 - Version: 16-bullseye

**Additional context**
See https://github.com/graphql/graphql-js/issues/723
>I think the TL;DR of this issue is that GraphQL has some overhead and that reducing that overhead is non-trivial and removing it completely may not be an option. Ultimately GraphQL.js is still responsible for making API boundary guarantees about the shape and type of the returned data and by design does not trust the underlying systems. In other words GraphQL.js does runtime type checking and sub-selection and this has some cost.

It would be amazing to have an option to disable whatever "guarantees" gateway/router is "responsible" for. I can guarantee everything I need at a subgraph level, I don't need gateway/router to double guarantee it at a 10x cost.

**Comment by Geal** [comment]
hi! Just to check something: do you do a few queries to the router first, or launch the benchmark directly on it? It includes a caching step for the query planning, and that step can take a while, but afterwards queries are much faster.

**Comment by Mithras** [comment]
The difference between the first query and subsequent is like 46 seconds vs 45 seconds. And that's while underlying subgraph takes only 3 seconds.

**Comment by Geal** [comment]
I see. Another thing to check, this is with the router from the release package, not built from source?

I'll look into those perf issues

**Comment by Mithras** [comment]
Yes, this is what I used for testing:
```
FROM debian:bullseye

WORKDIR /opt/apollo-router

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y curl \
    && curl -OL https://github.com/apollographql/router/releases/download/v0.1.0-alpha.0/router-0.1.0-alpha.0-x86_64-linux.tar.gz \
    && tar -xf ./router-0.1.0-alpha.0-x86_64-linux.tar.gz

CMD ["/opt/apollo-router/dist/router"]
```

**Comment by Geal** [comment]
Alright. What's the shape of the data? A few very large fields, lots of different fields, a deeply nested structure ?

**Comment by Mithras** [comment]
I'm pretty sure it'll repo on any big collection. Here is a good investigation https://github.com/graphql/graphql-js/issues/723#issuecomment-357474466 on this.

**Comment by Geal** [comment]
looks like it's spending most of the time on deserialization (tested on main at d9b3c43)

![Screenshot from 2021-11-22 10-59-09](https://user-images.githubusercontent.com/119296/142841141-4707f4fc-08a4-40c1-942f-6d0fd75af9c1.png)

**Comment by Geal** [comment]
@Mithras could you test again building the router from the main branch? #172 should have improved things

**Comment by Geal** [comment]
@Mithras I'm closing this now, let me know if the problem appears again
