### ISSUE TITLE
Cannot compile router-bridge v0.1.0 used by v0.14.0

### ISSUE THREAD

**Issue by yanns** [apollographql/router#1467]
When updating to v0.14.0, I got the following error during compilation:

```
warning: Updating router-bridge
warning: running `npm install`

error: failed to run custom build command for `router-bridge v0.1.0 (https://github.com/apollographql/federation-rs.git?branch=geal/defer#4cdcd574)`

Caused by:
  process didn't exit successfully: `/Users/yannsimon/dev/src/graphql-gateway/federation-router/target/debug/build/router-bridge-1dea9e325a835e7d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=js-src
  cargo:warning=Updating router-bridge
  cargo:warning=running `npm install`

  --- stderr
  npm ERR! code E404
  npm ERR! 404 Not Found - GET https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals
  npm ERR! 404 
  npm ERR! 404  '@apollo/federation-internals@https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals' is not in this registry.
  npm ERR! 404 
  npm ERR! 404 Note that you can also install from a
  npm ERR! 404 tarball, folder, http url, or git url.

  npm ERR! A complete log of this run can be found in:
```

I've tried manually to access https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals, and also got a 404.

**Comment by abernix** [comment]
We're acknowledging that this happens right now, but we don't have an answer as to why that CodeSandbox registry tarball just randomly disappeared.  The other packages (say, `@apollo/composition`, which sits along side it on the same commit hash, [still exists](https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals)) .

This was all only meant to be temporary anyhow, as part of https://github.com/apollographql/router/pull/1182 and will go away soon, so not going to over-index on solving it at this moment.

If you need a near-term solution, you could change the `branch` in https://github.com/apollographql/router/blob/main/apollo-router/Cargo.toml#L110 from `geal/defer` to `abernix/geals-defer` and you'll be able to get it to build thanks to my 🩹  https://github.com/apollographql/federation-rs/pull/150:

https://github.com/apollographql/router/blob/6c1426df1e092c3eb3300dbb4240f829d1c869e1/apollo-router/Cargo.toml#L110

**Comment by yanns** [comment]
Thanks for the workaround. 
I've tried that, but cargo still wants to compile both versions.
In `Cargo.lock`:
```
[[package]]
name = "router-bridge"
version = "0.1.0"
source = "git+https://github.com/apollographql/federation-rs.git?branch=abernix/geals-defer#281aae2a1abc642266e3316b2514c5e9a3e74026"
dependencies = [...]

[[package]]
name = "router-bridge"
version = "0.1.0"
source = "git+https://github.com/apollographql/federation-rs.git?branch=geal/defer#4cdcd574a967fc0fe61e0f6d6db92035ed395f0a"
dependencies = [...]
```

**Comment by yanns** [comment]
And I cannot use `patch` because of https://github.com/rust-lang/cargo/issues/10756 😭 
```
[patch."https://github.com/apollographql/federation-rs.git"]
router-bridge = { git = "https://github.com/apollographql/federation-rs.git", branch = "abernix/geals-defer" }
```

**Comment by o0Ignition0o** [comment]
I have been able to reproduce the issue in a docker environment.

@yanns we have just made a change that fixes the build, and I confirm my custom router builds in the docker environment once I've run `cargo update -p router-bridge`.

for debugging purposes, the new commit should be `#72f1fff5`:

```
    Updating router-bridge v0.1.0 (https://github.com/apollographql/federation-rs.git?branch=geal/defer#4cdcd574) -> #72f1fff5
```

**Comment by yanns** [comment]
@o0Ignition0o Thanks for the very quick update.
I can confirm this is working.
💯
