### ISSUE TITLE
Example of how to conciliate several subgraph requests/responses

### ISSUE THREAD

**Issue by yanns** [apollographql/router#1491]
I've checked the different examples of plugins, and I cannot really find what I'm looking for.

One GraphQL request to the router might results in several subgraph requests.
In one plugin, one might have to conciliate several subgraph responses.
In [propagate_status_code](https://github.com/apollographql/router/blob/main/examples/status-code-propagation/src/propagate_status_code.rs), one might have to choose which status code has to be propagated for example.
I'm looking for ways to test this.
I guess that the context is shared between the different subgraph requests/responses, and by looking at existing values in the context, we could have an implementation to conciliate different values.
It would help me having such feature implemented and tested by unit tests, but I could not find any.

**Comment by yanns** [comment]
BTW, a discord server would be awesome to discuss this kind of interrogations.

**Comment by yanns** [comment]
I've tried that approach:
```
        let mock_service = ...
        let mut service_stack = Plugin::new(init)
            .await
            .expect("couldn't create plugin")
            .subgraph_service("accounts", mock_service.boxed());
        let service_stack = service_stack.ready().await.unwrap();

        let service_response = service_stack
            .call(SubgraphRequest::fake_builder().build())
            .await
            .unwrap();
        // manipulate the context to simulate the final state after the first subgraph request
        service_response
            .context
            .insert(header_name, previous_value.to_string())
            .unwrap();

        // execute the second subgraph request
        let service_stack = service_stack.ready().await.unwrap();
        let service_response = service_stack
            .call(SubgraphRequest::fake_builder().build())
            .await
            .unwrap();
```
but the [res.context()](https://github.com/apollographql/router/blob/main/examples/status-code-propagation/src/propagate_status_code.rs#L53) does not contain the first value.

**Comment by bnjjj** [comment]
I'm not sure if I'm right but if you look here https://github.com/apollographql/router/blob/bnjjj/fix_1490/apollo-router/src/plugins/override_url.rs#L81:L81 and use `returning` method maybe you can directly add something into the context of your subgraphResponse ? you can check the documentation of https://docs.rs/mockall/latest/mockall/ which is what we use to create mocks. Maybe you could find something that fits your needs

**Comment by yanns** [comment]
@bnjjj that seems to work. Thanks I'll dig into that direction.

**Comment by yanns** [comment]
I confirm this is working.
I'll check later if it makes sense to use that also in https://github.com/apollographql/router/blob/main/examples/status-code-propagation/src/propagate_status_code.rs

**Comment by o0Ignition0o** [comment]
I believe this is what we use in [our propagate_status_code](https://github.com/apollographql/router/blob/1764cd625e39c1f3672bc24cf90a08f15f000b08/examples/status-code-propagation/src/propagate_status_code.rs#L144) tests

**Comment by yanns** [comment]
> I believe this is what we use in [our propagate_status_code](https://github.com/apollographql/router/blob/1764cd625e39c1f3672bc24cf90a08f15f000b08/examples/status-code-propagation/src/propagate_status_code.rs#L144) tests

Next exactly as this test assumes it's the first and only subgraph request, and I was looking for unit tests to simulate several subgraph requests where we have to conciliate the different responses.

**Comment by o0Ignition0o** [comment]
Oh I see, this would be a nice addition indeed!
