### ISSUE TITLE
Consider renaming map_future_with_context

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1495]
Split from https://github.com/apollographql/router/issues/1152

**Comment by SimonSapin** [comment]
On closer look, “context” in this name refers not necessarily to `apollo_router::Context`, but anything extracted from the request type (with the first closure argument). So how about `map_future_with_request_data`? And naming that first closure parameter something like `extract_request_data`.

**Comment by garypen** [comment]
That seems like a good suggestion. I'll pull together a draft and see what it looks like.
