### ISSUE TITLE
Pre-Supergraph Router service layer (HTTP)

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1496]
Currently we provide:

* A full server that listens for a network requests of various kinds, typically for production use
* A Tower `Service` for handling GraphQL requests with high-level request and response objects, typically for use in tests

It would make sense to provide the intermediate abstraction of Tower service at the HTTP level, where request and response bodies are raw bytes. This could potentially be run in a different HTTP server.

For 1.0 we want to at least have the separation internally, though perhaps not yet provide a public API for it.

**Comment by SimonSapin** [comment]
Removing the `api/1.0` label now that https://github.com/apollographql/router/pull/1582 ensures that the abstraction can exist. Leaving this issue open so we can decide later if we want a public API to construct this transport-level `Service`. (Likely with a builder similar to `TestHarness`.)

**Comment by abernix** [comment]
As some examples of user-land things which we could enable by supporting this, both of the following use-cases come to mind:

- https://github.com/apollographql/router/issues/1298
  This requests a way to accept different content types, like `text/plain`.  I'm not entirely sure what a `text/plain` GraphQL query would be (and it would go against work that the GraphQL HTTP working group is trying to specify about how GraphQL should speak HTTP) but it would be good to enable users to make such exceptions if need be, most likely to preserve existing behaviors where necessary.
- https://github.com/apollographql/router/issues/1314
  This suggests allowing a different serialization format for incoming `variables` and a transport-level service might enable them to coerce that data into a valid GraphQL `variables` structure.

**Comment by lennyburdette** [comment]
The most pressing customer use case I have is supporting a custom persisted query implementation. They have old mobile clients sending a weird PQ format and it will take a long time for those version to die off. They handled this in express middleware when using Apollo Gateway.

**Comment by SimonSapin** [comment]
This is relevant:

https://github.com/apollographql/router/blob/538a06984f797688d9e32ae5e9467d5a7857dc1e/apollo-router/src/router.rs#L53-L58

An open question that remains is how (and whether?) to expose multiple TCP/Unix listeners

**Comment by Geal** [comment]
> An open question that remains is how (and whether?) to expose multiple TCP/Unix listeners 
that would not affect HTTP service plugins, right?

**Comment by o0Ignition0o** [comment]
Do yall have opinions on where the http_service should kick in (as in before or after axum routing?)

My opinion is that it should be right after axum routing (The http service stack should only apply to the graphql path) and before anything else happens (headers parsing || studio redirection or body deserialization shouldn't have happened before)

I've also read mentions of the http_service applying before the axum router, I would be interested to read thoughts on that, especially since we now have custom endpoints that could satisfy that.

**Comment by bnjjj** [comment]
I think having it just after the axum routing makes sense. It should take a raw http request (without json deserialization) and return a raw http response I think
