### ISSUE TITLE
Socket hang up: Router not working when running as docker container  

### ISSUE THREAD

**Issue by asipras** [apollographql/router#1508]
**Describe the bug**
When running router as docker container the requests do not get routed correctly using Apollo studio 
**To Reproduce**
1. Setup services '...'
run router using following command 

> docker run -p 4000:4000 --env APOLLO_GRAPH_REF="<your graph>" --env APOLLO_KEY="<your key>" --mount "type=bind,source=/router.yaml,target=/dist/config/router.yaml" --rm ghcr.io/apollographql/router:v0.15.1

the command runs successfully and router starts up.

Below are contents of my router.yaml. As you can see I have apollo studio in my list of allowed origins.

> server:
>   cors:
>     # Set to true to allow any origin
>     # (Defaults to false)
>     allow_any_origin: false
> 
>     # allow_any_header: true
> 
>     # List of accepted origins
>     # (Ignored if allow_any_origin is true)
>     # (Defaults to the Apollo Studio url: `https://studio.apollographql.com`)
>     origins:
>       - http://localhost:4200
>       - http://localhost:4201
>       - http://localhost:4202
>       - http://localhost:4203
>       - http://localhost:4204
>       - https://studio.apollographql.com # Keep this so Apollo Studio can run queries against your router

2.  Go to apollo studio and try running simple query at http://localhost:4000. 

3. I am getting this error, 

> Unable to reach server
> 
> Try one of these solutions:
> 
> [Embed your graph on your own website ](https://www.apollographql.com/docs/studio/explorer/embed-explorer/)
> To diagnose the problem, please run:
> npx diagnose-endpoint@1.1.0 --endpoint=http://localhost:4000

I ran the npx diagnose-endpoint@1.1.0 --endpoint=http://localhost:4000 and am getting this message

> Diagnosing http://localhost:4000
> ⚠️  Failed to diagnose what went wrong. Here's the error:  RequestError: socket hang up
>     at ClientRequest.<anonymous> (C:\Users\asif.prasla\AppData\Local\npm-cache\_npx\44b567a0d18365cd\node_modules\got\dist\source\core\index.js:956:111)
>     at Object.onceWrapper (node:events:642:26)
>     at ClientRequest.emit (node:events:539:35)
>     at ClientRequest.origin.emit (C:\Users\asif.prasla\AppData\Local\npm-cache\_npx\44b567a0d18365cd\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
>     at Socket.socketOnEnd (node:_http_client:478:9)
>     at Socket.emit (node:events:539:35)
>     at endReadableNT (node:internal/streams/readable:1345:12)
>     at connResetException (node:internal/errors:692:14)
>     at Socket.socketOnEnd (node:_http_client:478:23)
>     at Socket.emit (node:events:539:35)
>     at endReadableNT (node:internal/streams/readable:1345:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   code: 'ECONNRESET',
>   timings: {
>     start: 1660332927217,
>     socket: 1660332927217,
>     lookup: 1660332927218,
>     connect: 1660332927227,
>     secureConnect: undefined,
>     upload: 1660332927228,
>     response: undefined,
>     end: undefined,
>     error: 1660332927229,
>     abort: undefined,
>     phases: {
>       wait: 0,
>       dns: 1,
>       tcp: 9,
>       tls: undefined,
>       request: 1,
>       firstByte: undefined,
>       download: undefined,
>       total: 12
>     }
>   }
> } socket hang up
> Would you care to let us know about this? Please mailto:explorer-feedback@apollographql.com

**Expected behavior**
I should be able to query at http://localhost:4000 using apollo studio.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 10.0.19043 Build 19043

**Comment by garypen** [comment]
Thanks for filing this issue. I'm fairly sure that the issue is a duplicate.

duplicates: #1124 

This is the answer: https://github.com/apollographql/router/issues/1124#issuecomment-1134270536

**Comment by asipras** [comment]
@garypen your suggestion worked. Thanks for your help. It would be great if documentation reflects this.

**Comment by asipras** [comment]
@garypen as per the suggestion i added the listen: 0.0.0.0:4000 entry in my router.yaml. Now my router.yaml looks like this,

> server:
>   listen: 0.0.0.0:4000
>   cors:
>     # Set to true to allow any origin
>     # (Defaults to false)
>     allow_any_origin: false
> 
>     # allow_any_header: true
> 
>     # List of accepted origins
>     # (Ignored if allow_any_origin is true)
>     # (Defaults to the Apollo Studio url: `https://studio.apollographql.com`)
>     origins:
>       - http://localhost:4200
>       - http://localhost:4201
>       - http://localhost:4202
>       - http://localhost:4203
>       - http://localhost:4204
>       - https://studio.apollographql.com # Keep this so Apollo Studio can run queries against your router

I started the router using the docker command and no longer see the socket hangup message.

However when I try to use the router end point to post a query it is not able to route it to subgraph.   When I post the same query to my subgraph endpoint i get the expected response. I can see from the router logs that my query is being posted to the router correctly, however i get the error message as below,

> {
>   "data": null,
>   "errors": [
>     {
>       "message": "HTTP fetch failed from 'newton-asset-register-ms': HTTP fetch failed from 'redacted': redacted",
>       "locations": [],
>       "path": [],
>       "extensions": {
>         "type": "SubrequestHttpError",
>         "service": "newton-asset-register-ms",
>         "reason": "HTTP fetch failed from 'redacted': redacted"
>       }
>     }
>   ]
> }

**Comment by garypen** [comment]
I think your problems are caused by running the router in a docker containrr. If your supergraph specifies that your subgraph is at `localhost`, then this is almost certainly not going to be interpreted successfully within the docker container in which your router is executing. 

I recommend running the router directly on your system, seems like windows, then figuring out and completely understanding docker networking

**Comment by asipras** [comment]
It was indeed docker configuration issue i.e. docker not able to access the localhost. Once we changed tjhr "routing-url" settings so the requests get routed to http://host.docker.internal:5164/graphql instead of  http://localhost:5164/graphql everything worked as expected.

Thank you for your help @garypen
