### ISSUE TITLE
set the rhai scripts loading path relative to the configuration file path

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1515]
Right now the rhai scripts are loaded from a`rhai/` directory relative to the working directory. This is bound to cause issues because the router's configuration will change depending on which directory it is executed from (that reminds me a bit of the DLL preloading attack).

We should instead have the rhai scripts loaded from a path relative to the configuration file, since it will be common to store them nearby (ex: `/etc/router/config.yml` and `/etc/router/rhai/main.rhai`)

**Comment by garypen** [comment]
There are a few things to consider here:
 - The *default* scripts directory could be to not specify a default
 - Prior art in this space (systemd, daemonize, etc...) favours either explicitly setting a working directory or defaulting to location of the binary
 - It's very hard to have an absolute path when you don't control the OS and the binary is on multiple OSs
 - It's possible to run a router without specifying a configuration
 - Risk exposure: a rhai script injection would not have the capability to do anything like a DLL pre-load.

Bearing in mind all of the above, I think that the current behaviour is the best compromise. I don't see any reason why location of configuration should take precedence over location of binary. In particular, if there is no configuration, what would we do then?

Best security practice would be to specify an absolute path, which is what we do in our helm chart, to override the default.

Another option would be to not have a default. In which case, if `rhai.scripts` is not explicitly specified in config, then no rhai scripts could be loaded. I think this would probably be slightly less ergornomic for users.

**Comment by Geal** [comment]
> Prior art in this space (systemd, daemonize, etc...) favours either explicitly setting a working directory 
For server software I have often seen the working directory approach, yes, and generally with a default value.

> or defaulting to location of the binary

the location of the binary or the current working directory? Because for cli apps I've seen the working directory used as origin, yes, but the path to the binary does not ring a bell

What I would like to see here is a behaviour that is not surprising and cannot result in user mistakes. Having the router's behaviour change depending on the location it starts in is surprising. The documentation does not even mention that they are loaded automatically without the configuration file. Rhai scripts are not as dangerous as DLLs but they can still deeply affect the requests and responses.

The non surprising option would be to explicitely activate rhai scripts through the configuration, with a defined path for the scripts that does not depend on the working directory. I do not particularly care if that path is relative to the configuration file, although it makes sense to me to colocate them.

**Comment by garypen** [comment]
> the location of the binary or the current working directory? Because for cli apps I've seen the working directory used as origin, yes, but the path to the binary does not ring a bell

Sorry, not thinking as clearly as usual. I mean the current working directory. Not sure why I wrote location of the binary.

I think we want the same thing (no surprises), but I'm not convinced that location of a (possibly not specified) config is less surprising than current working directory. (which will often be the same as the location of the binary, but clearly doesn't need to be).

The documentation [clearly specifies](https://www.apollographql.com/docs/router/customizations/rhai/#configuration) the rules for locating a "main" (i.e. executable) rhai script and how scripts are located and what the defaults are if not specified. 

As thing stand, you do have to explicitly activate rhai scripts through configuration. If you don't have a `rhai` plugin section, then nothing happens. There is no automatic loading of any scripts without configuration specification.

Nothing will be loaded without a user specifying the name of a main script and then importing further scripts from main.

**Comment by abernix** [comment]
After discussing this, it seems the current behavior is fine.  Closing!
