### ISSUE TITLE
Introspection: Change the caching behavior

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1516]
Since @bnjjj s refactoring of introspection, we don't need to cache every introspection query we know of anymore.

Moreover it causes the router to use [quite a fair bit of memory](https://github.com/apollographql/router/issues/1466#issuecomment-1213091606) when introspection is enabled.

Now would be a great time to remove it from the codebase, and add a simple LRU introspection cache with TTL.

**Comment by abernix** [comment]
Sounds good.  Per our conversation, suggest a low capacity LRU with no TTL since introspection is tied to the life-time of the schema.
