### ISSUE TITLE
linking requests and responses

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1536]
(prompted by the work on #1501)
If we're writing a plugin with rhai, or a native one using the `map_request` and `map_response` methods, we have no way to know which request corresponds to which response, except by explicitely setting some information in the `Context` object.

Could we add an id to a request when it comes in and make it available throughout the entire lifecycle? (possibly in telemetry too?)[
ULIDs](https://github.com/ulid/spec) or the still in draft [UUID v6](https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format#section-5.1) would work well for that

**Comment by abernix** [comment]
Maybe we should just use `span_current_id`? -@bryncooke

**Comment by garypen** [comment]
We should. It's (of course) slightly more complicated than that. I spoke about this with @BrynCooke and we concluded that the best thing to do would be to add a new function:

`apollo_router::get_trace_id()`

which would mask all the complexity of crate/traits required to retrieve this value.

**Comment by garypen** [comment]
This became:

`apollo_router::tracer::TraceId::new()`

I've tried to hide as much complexity as I can.
