### ISSUE TITLE
Feature Request: Listen to unix socket path

### ISSUE THREAD

**Issue by hsblhsn** [apollographql/router#154]
First of all thank you for this great project. While using `@apollo/gateway`, performance is always a concern. Specially when it comes to a [cold start](https://en.wikipedia.org/wiki/Cold_start_(computing)). And I believe this project will resolve the issue.

**The problem**
We have internal tools which uses `@apollo/gateway` just to integrate all of our subgraphs. Which communicates over unix socket. Because unix socket is twice faster and efficient than regular tcp socket when it comes to inter-process communication. While experimenting with `router`, we have realized that router does not support unix socket.  

**Describe alternatives you've considered**
Currently we are using `apollo-server` with `@apollo/gateway` which uses nodejs `http` module under the hood. And it has support for unix socket built in. (ex: `server.listen('/tmp/gateway')`).

**Comment by cecton** [comment]
@hsblhsn should the subgraphs be contactable by unix sockets too?

**Comment by hsblhsn** [comment]
At this moment we are not using unix socket for communicating with subgraphs. But it will be a good feature to support.
