### ISSUE TITLE
update to federation v2.1.0

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1546]
we're currently using an alpha of 2.1.0 right now which is effectively the same as what the final should be, but we believe we will receive a 2.1.0 early next week that is actually published, rather than the tarballs we're relying on right now.

In practice this gets done on `federation-rs` and then updated here to use that version.

**Comment by Geal** [comment]
since https://github.com/apollographql/federation-rs/commit/17bd45e82d5f5ba919bf129933975ddae836b152 we do not need the tarballs anymore. The `@defer` support branch is now merged in router-bridge, and once I merge a fix for https://github.com/apollographql/router/issues/1544 we can update

**Comment by Geal** [comment]
the fix is in https://github.com/apollographql/router/issues/1544

**Comment by abernix** [comment]
sounds great!

let's keep this open so we end up depending on the official release of 2.1.0 as soon as possible (when it's ready)?

**Comment by Geal** [comment]
currently expecting https://github.com/apollographql/federation/pull/2093 and https://github.com/apollographql/federation/pull/2089
