### ISSUE TITLE
Make types #[non_exhaustive] for forward-compatibility

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1550]
So that additions don’t have to be breaking changes.

* Error types in `apollo_router::errors` and elsewhere
* Request/response types in `apollo_router::stages`
* `apollo_router::plugin::PluginInit`
* `apollo_router::graphql::*` structs
* Others?

**Comment by SimonSapin** [comment]
From the spec:

https://spec.graphql.org/October2021/#sel-FAPHLABRBY5oI
> To ensure future changes to the protocol do not break existing services and clients, the top level response map must not contain any entries other than the three described above.

So `apollo_router::graphql::Response` does *not* need to be `non_exhaustive`.

However:

https://spec.graphql.org/October2021/#sel-GAPHRPdBABBqiH
> GraphQL services should not provide any additional entries to the error format since they could conflict with additional entries that may be added in future versions of this specification.

… suggests that `apollo_router::graphql::Error` could gain new fields in future GraphQL versions. Should we make it `non_exhaustive` to enable that without a breaking change? We have a builder that could take care of providing default values.

For `apollo_router::graphql::Request` however, https://spec.graphql.org/October2021/#sec-Execution does not seem to discuss requests as a (JSON) map to transmit.

**Comment by Geal** [comment]
that sounds good, but it might be a good idea to check in the spec wg if it really might change

**Comment by SimonSapin** [comment]
Let’s make these `graphql::*` structs `non_exhaustive` for 1.0-alpha. We can relax this later in 1.x but not the other way around.
