### ISSUE TITLE
Replace http_ext::Request and Response types

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1553]
These types make the API clunky, can we hide them or otherwise simplify? They exist to wrap corresponding types from the `http` crate and implement `Clone`. The `http` type don’t implement `Clone` since they contain `http::Extensions` which contains `Box<dyn Any>`.

Once possibility is not using `http::Request` or `http::Response` at all, but instead store the fields of `http::{request,response}::Parts` except `extensions`. We have `apollo_router::Context` that replaces `extensions` with the same role.

**Comment by Geal** [comment]
that looks like it could work :+1:

**Comment by SimonSapin** [comment]
Rough sketch based on inlining structs from the `http` crate, and removing `http::Extensions` and `http::Version` (which also seems not very useful):

```rust
pub mod supergraph {
    #[non_exhaustive]
    pub struct Request {
        pub http_method: http::Method,
        pub uri: http::Uri,
        pub headers: http::HeaderMap<http::HeaderValue>,
        pub body: graphql::Request,
        pub context: Context,
    }

    #[non_exhaustive]
    pub struct SupergraphResponse {
        pub http_status: http::StatusCode,
        pub headers: http::HeaderMap<HeaderValue>,    
        pub body_stream: BoxStream<'static, graphql::Response>>,
        pub context: Context,
    }

    pub type BoxService = tower::util::BoxService<Request, Response, BoxError>;
}

pub mod execution {
    // Identical, so reusing the struct might be simpler?
    pub type Response = super::supergraph::Response;

    // Almost identical, but a tuple may not be as convenient
    // Maybe ok if all example deconstruct the tuple in method arguments?
    pub type Request = (super::supergraph::Request, QueryPlan);

    pub type BoxService = tower::util::BoxService<Request, Response, BoxError>;
}

pub mod subgraph {
    #[non_exhaustive]
    pub struct Request {
        // Re-use "supergraph" terminology instead of "originating"
        pub supergraph_request: Arc<super::supergraph::Request>,
        pub http_method: http::Method,
        pub uri: http::Uri,
        pub headers: http::HeaderMap<http::HeaderValue>,
        pub body: graphql::Request,
        pub operation_kind: OperationKind,
        pub context: Context,
    }

    #[non_exhaustive]
    pub struct Response {
        pub http_status: http::StatusCode,
        pub headers: http::HeaderMap<HeaderValue>,    
        pub body: graphql::Response,
        pub context: Context,
    }

    pub type BoxService = tower::util::BoxService<Request, Response, BoxError>;
}

**Comment by BrynCooke** [comment]
One reason to not inline was that it means that any library that uses http::* Types cannot be used directly.

**Comment by SimonSapin** [comment]
Keeping `http::Request` leaves two options IMO.

Proposal 1: replace `http_ext::Request` by `http::Request`, no other change. For example:

```rust
pub mod supergraph {
    pub struct Request {
        pub originating_request: http::Request<graphql::Request>,
        pub context: Context,
    }
}
```

Proposal 2: the above, and also invert the nesting:

```rust
pub mod supergraph {
    pub type Request = http::Request<RequestBody>;
    pub struct RequestBody {
        pub graphql: graphql::Request,
        pub context: Context,
    }
}
```

So instead of `request.context.insert(something)` plugin authors would write `request.body().insert(something)`. Which is a bit weird (`Context` was not part of the HTTP request body that was transmitted over the network) but perhaps it’s more conventional to have a Tower service request type *be* `http::Request<Something>` rather than contain it?

**Comment by SimonSapin** [comment]
https://github.com/apollographql/router/pull/1589 does proposal 1 above (which was necessary either way)

**Comment by SimonSapin** [comment]
We’ve agreed to not make further changes than https://github.com/apollographql/router/pull/1589, so closing as done.
