### ISSUE TITLE
QueryPlan::usage_reporting

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1556]
`apollo_router::query_planner::QueryPlan` is a public struct with a public `usage_reporting` field of type `router_bridge::planner::UsageReporting`. Should this field be made private or can it be useful to plugin authors?

Making items from the `router_bridge` crate visible in our public API technically makes the whole crate part of our public API and makes semver-breaking changes cascade. If having this accessible is useful, it should probably be a duplicated struct in our own crate.

**Comment by o0Ignition0o** [comment]
The router bridge is supposed to be part of our private API, +1 to not reexport its types.
