### ISSUE TITLE
potential improvements to error shape when validation error occurs

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1560]
Currently our `errors` responses when there is a query validation error includes the various layers of error-prefixing.  For example, the error returned to the client when an unknown directive is included on a query:
 
```json5
{"errors":[{"message":"value retrieval failed: couldn't plan query: query validation errors: Directive \"@myDirective\" may not be used on FIELD.","locations":[],"path":null}]}
```

While it could be worth having that full `value retrieval failed: couldn't plan query: query validation errors: ` in our debugging logs, I think it makes less sense as a publicly returned error and more like a leaky abstraction of our internal error messages (which could change over time!).

In addition to being more concise, I think removing the prefix would create a more user-friendly message for the client-consumers.  For example, we might just shorten this to:

```json5
{"errors":[{"message":"Directive \"@myDirective\" may not be used on FIELD.","locations":[],"path":null}]}
```

Taking this a step further though, we could also make the error messages more consistent with what Apollo Server currently returns (though I'm curious what validation errors from other servers look like!), including a valuable machine-readable error message property called `code`.  For example, here's what a similar error message looks like on Apollo Server:

```json5
{
  "errors": [
    {
      "message": "Unknown directive \"@myDirective\".",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED",
        "exception": {
          "stacktrace": [
            "GraphQLError: Unknown directive \"@myDirective\".",
            "    at Object.Directive (/home/projects/github-zz8rcx/node_modules/graphql/validation/rules/KnownDirectivesRule.js:56:11)",
            "    at Object.enter (/home/projects/github-zz8rcx/node_modules/graphql/language/visitor.js:301:32)",
            "    at Object.enter (/home/projects/github-zz8rcx/node_modules/graphql/utilities/TypeInfo.js:391:27)",
            "    at visit (/home/projects/github-zz8rcx/node_modules/graphql/language/visitor.js:197:21)",
            "    at validate (/home/projects/github-zz8rcx/node_modules/graphql/validation/validate.js:91:24)",
            "    at validate (/home/projects/github-zz8rcx/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
            "    at processGraphQLRequest (/home/projects/github-zz8rcx/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
            "    at async processHTTPRequest (/home/projects/github-zz8rcx/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
          ]
        }
      }
    }
  ]
}
```

Having the `code` of `GRAPHQL_VALIDATION_FAILED` also makes it easier for clients and tooling to programmatically figure out what is wrong with their request.   The full list of those codes we offer in Apollo Server [can be found here](https://www.apollographql.com/docs/apollo-server/data/errors/).

Of course, we don't need to include a JavaScript stacktrace.  (In fact, those aren't returned in Production anyhow, but I didn't run this in production.). I think it would be sufficient to leave off the whole `exception` object in Rust-land.

Thoughts?

**Comment by o0Ignition0o** [comment]
This sounds great!
I'd love to have a bit more bandwidth to try to tackle that, I think there's a [wip branch in federation-rs](https://github.com/apollographql/federation-rs/commits/bnjjj/fix_plan_error) where @bnjjj and I tried to somewhat improve errors.

Note this is non trivial because some errors are returned and other are thrown, so we need to properly catch them in deno land, and serialize / deserialize them from deno to rust.

**Comment by abernix** [comment]
This should be more possible with the latest `router-bridge` updates in https://github.com/apollographql/federation-rs/pull/161 (coming soon to a `router` repo near you)
