### ISSUE TITLE
Plugins: Change response parts, depending on the body's first payload

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1564]
followup to #1403 

Consider this plugin:

https://github.com/o0Ignition0o/quick-stream-example/blob/igni/change_http_status_code/src/plugins/catch_invalid_type_error.rs

This plugin iterates on response body errors, and tries to return a 401 if it sees a specific error.

I think this usecase is pretty straightforward, and plugin writers should be able to say customize headers or change the status code depending on that.

However due to the BoxStream nature of the Body, it's pretty hard to achieve ATM.

Let's think of a good design so our users can do this.

**Comment by o0Ignition0o** [comment]
so we do have a way to do that, that involves a [peekable](https://github.com/o0Ignition0o/quick-stream-example/blob/3a0b9d410d981bd51a2635c73bd6782426647de7/src/plugins/catch_invalid_type_error.rs#L52) which is a bit tedious but does the job.

@Geal @SimonSapin and I talked about the api a bit, and here's an idea:

```rust
ServiceBuilder::new()
    .service(service)
    .map_first_response(|(parts: http::Parts, response: stages::supergraph::Response| {
         (parts, response)
    })
    .map_each_response(|chunk: graphql::Response| {
        chunk
    })
```

parts contain headers, status code etc, anything but the body. `map_first_response` would thus allow you to decide on http parts according to what is in the first payload. You could also edit the first response as well.

However, you wouldn't be able to have access to the subsequent payloads, and it would be too late to change http headers / status code anyway since they ve already been sent.

map_each_response would then allow you to operate on each response body (including the first one) at the graphql::Response level.

Combination of both would allow you to fulfill most use cases without having to deal with streams yourself.

Thoughts?

**Comment by SimonSapin** [comment]
I'd expected `map_first_response` to get a `graphql::Response` parameter, not the full `supergraph::Response`

**Comment by SimonSapin** [comment]
It’s still not great that the word “response” is so overloaded, but I don’t really have a better idea

**Comment by o0Ignition0o** [comment]
> I'd expected map_first_response to get a graphql::Response parameter, not the full supergraph::Response
true, we have the http parts anyway

**Comment by SimonSapin** [comment]
Your example uses `chunk: graphql::Response`. Should we go with that and have `map_first_chunk` and `map_each_chunk`? Since `map_response` refers to `supergraph::Response` in this case (through `tower::Service::Response`).

I don’t find a sufficiently-specific term in [the `@defer` spec draft](https://github.com/graphql/graphql-spec/pull/742) for the items of the stream, so making one up seems fine.

**Comment by Geal** [comment]
Let's not use "chunk" because it already has a specific meaning for HTTP

**Comment by garypen** [comment]
Would this be a better API ?:
```
ServiceBuilder::new()
    .service(service)
    .map_response(|(parts: Option<http::Parts>, response: Stream<graphql::Response>| {
         (parts, response)
    })
```
It removes the discussion about chunks and it seems a bit simpler to work with to me. I'm not sure we could make it work though.

**Comment by o0Ignition0o** [comment]
@garypen the main struggle is that map_response operates in a sync context, so there's practically nothing with can do with the stream.

As shown here, [dealing with the http parts once we have a handle to the first payload requires advanced wizardry](https://github.com/o0Ignition0o/quick-stream-example/blob/b68f0f99589464370db9e9cc12192378944ff86a/src/plugins/catch_invalid_type_error.rs#L50).

The main requirements of the API I think we need to design are thus:
- ideally sync
- allows users to change the http response using / modifying the first response
- help users reason with the multipart nature of the supergraph::Response

```rust
    .map_response(|response: graphql::Response, parts: Option<http::Parts>| {
         (parts, response)
    })
```

with parts being some for the first response payload could work, i m not quite sure how though. I don't think this api would be less confusing than map_first_response and map_each_response.

**Comment by SimonSapin** [comment]
(Side note: `(http::response::Parts, response: graphql::Response)` is equivalent to `http::Response<graphql::Response>`, which might be nicer for `map_first_response`.)

**Comment by o0Ignition0o** [comment]
Just walked @lennyburdette through this issue and the example, and here's a draft of the things we spoke of:
- having access to the context in map_first_response and map_each_response would be nice, (if anything it would allow users to `ctx.insert("first_chunk_processed", true)` so people would be able to book keep chunks, or we could enumerate them in `map_each_response`.
- `map_each_response` response type could be `ControlFlow<Option<graphql::Response>>` so we could let the router know how to deal with the rest of the stream:

```rust
                    // propagate this new chunk
                    ControlFlow::Continue(Some(response))
                    // swallow this chunk
                    ControlFlow::Continue(None)
                    // Hang up
                    response.has_next = Some(false);
                    ControlFlow::Break(Some(response))
```

Here s a full pseudocode example of what we worked on:


```rust
.map_first_response(
                |ctx: Context,
                 mut parts: http::Parts,
                 response: apollo_router::graphql::Response|
                 -> (http::Parts, Option<apollo_router::graphql::Response>) {
                    let has_invalid_type_error = response.errors.iter().any(|e| {
                        e.extensions.get("type")
                            == Some(&Value::String("ValidationInvalidTypeVariable".into()))
                    });
                    if has_invalid_type_error {
                        tracing::info!("we have an invalid type error!");
                        parts.status = StatusCode::UNAUTHORIZED;
                    } else {
                        tracing::info!("we don't have an invalid type error!");
                    }

                    ctx.insert("processed_first_chunk", true);
                    (parts, response)
                },
            )
            .map_each_response(
                |ctx: Context, response: apollo_router::graphql::Response| -> ControlFlow<Option<graphql::Response>> {
                   
                },
            )
```

**Comment by SimonSapin** [comment]
Adding `Context` sounds good.

Removing some items from the stream or interrupting it in the middle seems like a very advanced use case. I think `map_each_response` doen’t need to cover it as Tower’s `map_response` is still there to work at the `BoxStream` level.

**Comment by o0Ignition0o** [comment]
> Removing some items from the stream or interrupting it in the middle seems like a very advanced use case. I think map_each_response doen’t need to cover it as Tower’s map_response is still there to work at the BoxStream level.

True, let's not overengineer a first draft.

**Comment by SimonSapin** [comment]
It sounds like we can add `ServiceBuilderExt` methods that make it more convenient to work with the stream or its first item, *without* making breaking changes to `{supergraph,execution}::Response`.

Does that sound right to you @o0Ignition0o? If so let’s work on this after 1.0-alpha

**Comment by o0Ignition0o** [comment]
sgtm!

**Comment by SimonSapin** [comment]
> It’s still not great that the word “response” is so overloaded, but I don’t really have a better idea

Let’s split the topic of naming to https://github.com/apollographql/router/issues/1700

**Comment by SimonSapin** [comment]
As discussed this morning, `map_each_response` is probably not necessary because `StreamExt::map` can be used together with Tower’s `map_response`. That said it’s not very discoverable, so worth giving as an example in docs at least.

It would be tricky to get ownership of the stream and construct a new response with a new stream, but we already have a `map` method on `supergraph::Response` to do exactly that, inspired by (and relying on) the same method of `http::Response`:


```rust
impl Plugin for Something {
    // …
    fn supergraph_service(&self, inner: supergraph::BoxService) -> supergraph::BoxService {
        inner.map_response(|supergraph_response: supergraph::Response| {
            supergraph_response.map(
                |stream: Pin<Box<dyn futures::Stream<Item = graphql::Response> + Send>>| {
                    use futures::StreamExt;
                    stream
                        .map(|graphql_response: graphql::Response| {
                            // Something interesting here
                            graphql_response
                        })
                        .boxed()
                },
            )
        })
        .boxed()
    }
}
```

The type annotation on closure parameters are not necessary to compile, I’ve added them to make types visible. Even that aside, it’s still three nested level of mapping before we get to a `graphql::Response`.

We also already have `map_stream` on `supegraph::Response` for this specific case, which removes one nesting level:

```rust
impl Plugin for Something {
    // …
    fn supergraph_service(&self, inner: supergraph::BoxService) -> supergraph::BoxService {
        inner.map_response(|supergraph_response: supergraph::Response| {
            supergraph_response.map_stream(|graphql_response: graphql::Response| {
                // Something interesting here
                graphql_response
            })
        })
        .boxed()
    }
}
```

**Comment by SimonSapin** [comment]
For the use case this issue is initially about, I propose adding this method to our `ServiceExt` trait (and a similar one to `ServiceBuilderExt`):

```rust
    fn map_first_graphql_response<Callback>(
        self,
        callback: Callback,
    ) -> MapFirstGraphqlResponseService<Self, Callback>
    where
        Self: Sized + Service<supergraph::Request, Response = supergraph::Response>,
        <Self as Service<supergraph::Request>>::Future: Send + 'static,
        Callback: FnOnce(
                Context,
                http::response::Parts,
                graphql::Response,
            ) -> (http::response::Parts, graphql::Response)
            + Clone
            + Send
            + 'static,
```

Usage looks like this:

```rust
impl Plugin for Something {
    // …
    fn supergraph_service(&self, inner: supergraph::BoxService) -> supergraph::BoxService {
        use apollo_router::layers::ServiceExt as _;
        inner.map_first_graphql_response(|context, mut http_parts, mut graphql_response| {
            // Something interesting here
            (http_parts, graphql_response)
        })
        .boxed()
    }
}
```

**Comment by SimonSapin** [comment]
The signature above only works with supergraph services, even though execution responses also contain a stream. To make it work there too, we’d need either:

* To make `subgraph::Response` and `execution::Response` the same type. (One would be a `type` alias of the other.) At the moment they’re two structs with identical fields (and methods?)
* Or add some trait to let `map_first_graphql_response` be able to generic over the response type, to extract the stream from it and reconstruct another one with wrapped stream
