### ISSUE TITLE
CI performance improvement

### ISSUE THREAD

**Issue by Geal** [apollographql/router#157]
We've been working on multiple ways to improve CI performance:
- #140 move the composition benchmarks to a separate crate: that did not work too well, the idea was to move criterion out of the common CI runs, which avoids building a lot of dependencies
- #142 WIP: feat: speedup CI build times
- #147 make the OTLP exporters non exclusive: this avoid multiple builds with different features in `xtask test` and improves caching of dependency building
- #153 Remove grpcio: grpcio is redundant with tonic and greatly increases compilation time, we can remove it
- #151 WIP feat: decrease CI build times - low hanging fruits: parallelizing tasks, caching

**Comment by o0Ignition0o** [comment]
A couple of things that we could follow up on eventually:
- We spend quite a bit of time running `npm run clean-install` for tests, while the CI already has a step for that. We could have cargo xtask test not rerun this command before spinning up the dependencies.
- The dependencies are written in node, which requires the CI to setup a full node / npm environment, we could get rid of it alltogether if we published the federation-demo docker container, and depended on it in the circleci environment. (Note I have tested to build and run the images in CircleCI, but [ports and volumes aren't available](https://discuss.circleci.com/t/cannot-communicate-with-docker-container/27253), the proposed workarounds are getting rid of docker compose, or running everything within docker compose, thus defeating the executor platforms alltogether)

**Comment by o0Ignition0o** [comment]
Cache size could also be improved on, cargo target/ aren't cleaned up over time, which means its size grows, and cache restore / save take longer and longer. A naive first approach could use cargo-sweep to clean up previous build artefacts (with the -s and -f flags respectively, -s to save the last sweep timestamp before a cache save, -f to remove anything older than the last sweep timestamp in subsequent restores)

**Comment by Geal** [comment]
@o0Ignition0o can we close this? Or do you see any more improvements to add?

**Comment by o0Ignition0o** [comment]
#218 should be the last open one!
