### ISSUE TITLE
deferred responses should be compressed

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1572]
reported by @BoD

with the latest version of the [supergraph demo with defer](https://github.com/apollographql/supergraph-demo-fed2/pull/212), I’ve added an artificial 4s delay in the Inventory subgraph responses. Then making a query like this:

```graphql
query Product {
  product(id: "apollo-federation") {
    # Comes from Products subgraph (fast)
    dimensions {
      size
    }

    # Comes from Inventory subgraph (slow)
    ... on Product @defer {
      delivery {
        estimatedDelivery
        fastestDelivery
      }
    }
  }
} 
```

I was expecting to receive the initial payload immediately and the 2nd one after 4s, but I’m receiving everything at once after 4s.

**Comment by BoD** [comment]
[Here's](https://github.com/prasek/supergraph-demo-fed2/pull/1/files?w=1) how I added the delay.

And the curl:

```
curl 'http://localhost:4000/'   -H 'content-type: application/json'   --data-raw $'{"query":"query Product($productId: ID!) {product(id: $productId) {dimensions {size} ... on Product @defer {delivery { estimatedDelivery fastestDelivery } } } }","variables":{"productId":"apollo-federation"},"operationName":"Product"}' --compressed

```

**Comment by Geal** [comment]
thanks, I can reproduce it

**Comment by Geal** [comment]
ok, the issue is with response compression. If it is not compressed then the chunks come at the right time

**Comment by SimonSapin** [comment]
We have a work-around for 1.0 but we’d like to switch to a proper solution which is being designed in https://github.com/Nemo157/async-compression/issues/154. Reopening to track that.

**Comment by abernix** [comment]
I've renamed this issue to reflect the state of the work-around, but we should use the original reproduction above to verify any eventual fix.

**Comment by SimonSapin** [comment]
I believe https://github.com/apollographql/router/commit/67aae1314f67adcca70effa4c6a01ab56053de83 provides automated test coverage for this, but if we have another reproduction it’d be good to check as well.

**Comment by Geal** [comment]
follow up work is in https://github.com/Nemo157/async-compression/pull/178

**Comment by Geal** [comment]
I'll do that as a custom layer in the router instead
