### ISSUE TITLE
Update docs/* for recent API changes

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1590]
At least `docs/source/customizations/native.mdx` is outdated

**Comment by garypen** [comment]
There is a PR which addresses a lot of the changes: [#docs](https://github.com/apollographql/router/pull/1571)

Maybe wait for that to land before reviewing and doing any followup.

**Comment by SimonSapin** [comment]
https://github.com/apollographql/router/pull/1623 fixes what I’m aware of. If we find more let’s follow up with further issues/PRs.
