### ISSUE TITLE
query plan condition nodes do not use default values of variables

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1603]
Blocked on https://github.com/apollographql/federation/issues/2100

Example query:

```graphql
query X($if: Boolean! = true) {
    ... @defer(if: $if) {
        x
    }
}
```

relevant code:

https://github.com/apollographql/router/blob/5cb00657ae71d6f502913b3ff912591e64355a4b/apollo-router/src/query_planner/mod.rs#L610-L623

**Comment by Geal** [comment]
to solve this I need to make the `spec::Query` struct available in query plan execution. I'd like to move it inside the `QueryPlan` structure as a `pub(crate)` field. That will not affect the public API:

https://github.com/apollographql/router/blob/bc6c0cd1060d97e01722c0fa25947f9263b16754/apollo-router/src/query_planner/mod.rs#L49-L55

The main modifications will be here:

https://github.com/apollographql/router/blob/bc6c0cd1060d97e01722c0fa25947f9263b16754/apollo-router/src/query_planner/bridge_query_planner.rs#L124-L134

and some indirection in the `SupergraphService`

**Comment by garypen** [comment]
Seems reasonable. I'm presuming there is no real alternative.

**Comment by abernix** [comment]
This should no longer be blocked with the fix for https://github.com/apollographql/federation/issues/2100 arriving in #1698 (now on `main` and shipping in `1.0.0-alpha.3`).  I'm marking it as Todo.
