### ISSUE TITLE
Rename `Server::endpoint` to `Server::graphql_path`

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1606]
Today, we have `endpoint` in our `server` configuration of our YAML.  Its default value is `/`.  You might set it to something like `/my-graphql-endpoint`.

The team is not convinced that `/` or `/graphql` or `/my/graphql/endpoint` are actually "endpoint"s without the rest of the scheme, host, port, prefix.  In other words, a full URL.

Rename this to `graphql_path` since that more accurately defines what it is.

**Comment by garypen** [comment]
also: see: #1500 for higher level concerns.
