### ISSUE TITLE
add a spec compliant parser for Accept HTTP header values

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1618]
we need to look at values from the `Accept` header in various places:
https://github.com/apollographql/router/blob/6131e06660ec95715d78d6e7347d0f8234ac031d/apollo-router/src/axum_http_server_factory.rs#L614-L624

and

https://github.com/apollographql/router/pull/1610/files#diff-3bc7e7515da7351dcdea41fed01f6e494bde5289b83b981b424c6d67358b25d6R157-R160

Splitting directly on `,` or `;` is not enough because there can be quoted strings, so we need a correct parser here

**Comment by glasser** [comment]
see also https://github.com/picoHz/mediatype/issues/4

**Comment by glasser** [comment]
Hey look what we just lazywebbed into existence: https://docs.rs/mediatype/latest/mediatype/struct.MediaTypeList.html
