### ISSUE TITLE
Rust Panic in the Router terminates the TCP connection without an HTTP response

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1619]
**Describe the bug**
When some Rust code panics while handling a request, Tokio drops the corresponding task which causes the TCP connection to be closed without any HTTP response being sent.

TODO: check if this is still the case, I tried it some time ago

**To Reproduce**
TODO

**Expected behavior**
The Router should probably respond to that request with an HTTP 500 status code. This can be achieved with `std::panic::catch_unwind`.

@garypen has argued the Router should also shut down (and let some external tool start a new Router process), as the panicked thread may have left behind poisoned mutexes or other inconsistent state in shared resources. Note though that there’s some debate among rustaceans whether lock poisoning is a good thing, and that neither `tokio` nor `parking_lot` does poisoning.

**Comment by garypen** [comment]
I think @BrynCooke was the originator of the observation about poisoned mutexes, but I certainly agree with him. The main source of panics causing router mis-behaviour has been the `Buffer` in Tower and the channels used to communicate across them. Unfortunately, if a panic occurs it seems like the channel is left in an unusable state (without proper cleanup) and that has the effect of making the router unresponsive. (This requires a lot more investigation before I can write anything more informed about this issue, but it certainly looks like a problem.)

**Comment by Geal** [comment]
that panic can happen at any point, even while the task is actually writing the HTTP response, so I don't think we can handle panics cleanly

**Comment by SimonSapin** [comment]
`async` means that using `cactch_unwind` is not gonna be as straightforward as I'd hoped.

We can guarantee handling *all* panics, but responding with a 500 instead of dropping the connection in "most" cases would be nice.

**Comment by garypen** [comment]
I think the main concern about doing anything like this is that I don't think we can **guarantee** that any attempt to catch_unwind isn't going to hang when we try to process the panic. That's why terminating the process is the best thing we can do.

**Comment by abernix** [comment]
Was https://github.com/apollographql/router/pull/1602 meant to be marked to close this?

**Comment by SimonSapin** [comment]
On further thought, `catch_unwind` is much less straightforward to use in asynchronous Rust since the call stack being unwound is mostly `Future::poll` for various `.await`, whereas the meaningful call stack of `async fn`s lives in nested futures.

I'm fine with closing this as resolved by #1602 (though perhaps a test would be good)

**Comment by SimonSapin** [comment]
If we revisit this and decide not to abort the process on panics, the way to catch panic is async is not `catch_unwind` but rather:

* Run relevant code in a separate task with `tokio::spawn`
* Await the `JoinHandle`
* If this results in a `JoinError`, check its `is_panic` method
