### ISSUE TITLE
Router / Gateway: different data returned on subgraph errors

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1670]
I've set up a gateway and a router that both use the starstuff graphql supergraph.

I've used the federation2 demo subgraph, except the users resolver throws:

```js
const resolvers = {
  User: {
    __resolveReference: (reference) => {
      throw "no";
      // return users.find((u) => u.email == reference.email);
    },
  },
};
```

The response I get from the router is:

```json
{
      "data": null,
}
```

The response I get from the gateway is:

```json
{
    "data": {
        "me": null
    }
}
```

_Originally posted by @o0Ignition0o in https://github.com/apollographql/router/issues/1664#issuecomment-1233845525_

**Comment by abernix** [comment]
This should have been resolved in #1674
