### ISSUE TITLE
should we allow log and span levels to vary independently?

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1671]
Setting the log level for the router also sets the level at which spans are generated. It's debatable if we should allow these to be set independently.

**Comment by deweyjose** [comment]
Hi @garypen some of my confusion related to this topic was under certain conditions (using uplink) I see no spans in DD when log level is higher than INFO. When using a static schema file I saw the higher level (debug and trace) spans in DD.

**Comment by BrynCooke** [comment]
I'm actually not sure this is possible. Spans go through tracing and then to otel, so I don't think this can ever be truly independent.

**Comment by abernix** [comment]
We're not actually sure this is possible, so we'll close for now until this comes up again.
