### ISSUE TITLE
Naming response things

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1700]
The word “response” is quite overloaded in our Rust APIs. At first it seemed hopelessly so, but while typing this out I landed on a separation into three kinds:

* A “(Tower) service response” is (a value of) a type used as a `Service::Response` associated type. It’s what `ServiceExt::map_response` manipulates. We have `apollo_router::services::*::Response` structs for this.

* An “HTTP response”, in Rust APIs, is `Response<GenericBodyType>` from the `http` crate. Our Tower response structs contain an HTTP response field named… `response`. 

* A “GraphQL response” is defined in the spec as a map (struct) with fields `data`, `errors`, etc. In Rust it’s `apollo_router::graphql::Response`. Except for subgraph Tower responses where it’s a single GraphQL response, the body type of our HTTP responses is a `Stream` of one or more GraphQL responses (in order to support `@defer` etc).

----

Drive-by proposal: now that these three kinds (and what to call them) is clearer to me, I think renaming the HTTP response fields of our Tower response structs from `response` to `http_response` would be nicer. But maybe alpha.2 is kinda late for such a cosmetic change?

---

My impulse for this issue was https://github.com/apollographql/router/issues/1564#issuecomment-1222206169. Adding `map_first_response` and `map_each_response` methods next to `map_response` doesn’t seem right when their names refer to different kinds of responses.

With the above categorization in mind, how about `map_first_graphql_response` and `map_each_graphql_response`? “A supergraph HTTP response may contain multiple GraphQL responses” seems reasonable to explain in docs.

**Comment by BrynCooke** [comment]
Currently we have `originating_request` and `response`. If we change `response` to `http_response` then how do we feel about making this symmetrical?

I'm not sure about `map_first_graphql_response` and `map_each_graphql_response`. At least in the other ticket it looked like these methods were doing more than just graphql stuff and included some http stuff. Suggest punting on this.

**Comment by SimonSapin** [comment]
Indeed `map_first_graphql_response` can also manipulate headers or other components of the HTTP response.

By punting do you mean not doing https://github.com/apollographql/router/issues/1564 at all yet? If we do it we still need to come up with names for these two new methods.

**Comment by SimonSapin** [comment]
+1 for `originating_request` → `http_request` if we have `http_response` in response structs.

**Comment by BrynCooke** [comment]
If you do go ahead with `map_each_graphql_response` then consider dropping the `_each_` part as this is not symmetrical with iter or stream.

**Comment by abernix** [comment]
Is it possible that in an effort to model our future shape where we introduce https://github.com/apollographql/router/issues/1496 (roughly, a layer representing the pre-graphql transport surface-area) we might want to consider having both transport-specific and GraphQL response methods here within subgraph, too?

**Comment by BrynCooke** [comment]
Another option for naming is `map_supergraph_response` and `map_first_supergraph_response`. These methods are not just graphql specific, but also specific to the service so having the service name in there will make things explicit.

**Comment by garypen** [comment]
The reason for `originating_request` was to distinguish it from `subgraph_request`. I don't think naming it `http_request` is an improvement. I do like the motivation for symmetry though. If people don't like `originating_request`, I suggest trying to come up with a better name that helps distinguish it from the `subgraph_request` on the `subgraph::Request`. Maybe `incoming_request` and name `subgraph_request` -> `outgoing_request`?

**Comment by garypen** [comment]
Note: The `originating_request` part of this issue was separated into #1713 and fixed in #1715

**Comment by o0Ignition0o** [comment]
Closing this since we're pretty satisfied with the shape of the API we want to expose for 1.0
