### ISSUE TITLE
Allow the AST of the query/mutation to be traversed in the super/subgraph service

### ISSUE THREAD

**Issue by rlch** [apollographql/router#1725]
**Is your feature request related to a problem? Please describe.**
I have a native Rust plugin to handle JWT authorization, but would like to skip the authorization logic if, for instance, a directive is defined on the query/mutation used.

**Describe the solution you'd like**
Provide an instance of the schema AST, perhaps limited to the subset of the AST being requested, so that I can determine what directives are being used.

**Comment by abernix** [comment]
You should be able to find the answer to your "what directives" question by using [`apollo-compiler`](https://crates.io/crates/apollo-compiler) inside of your `supergraph_service`, which receives the `supergraph_sdl`, as seen [in this example](https://github.com/apollographql/router/blob/f81203fa3e8d7efc98e124aca1e8944bc0c05a2d/examples/supergraph_sdl/src/supergraph_sdl.rs#L62-L63).

While it will currently require you do an additional parse on the operation that we've in-theory already done, our intention is to eventually expose the `apollo-compiler`'s crate context on the plugins allowing you to use what we've already parsed.   Work is happening in [the `apollo-rs` repository](https://github.com/apollographql/apollo-rs/) to make that happen!

**Comment by rlch** [comment]
Apologies, I should've closed this when issue when I found this out. I ended up getting this working with `supergraph_sdl` being sufficient for my usecase. 

That would be really useful to use the pre-parsed SDL! @abernix Any idea on what release will contain this?
