### ISSUE TITLE
FTV1 traces should not be sent for free tier users

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1728]
FTV1 is a paid feature, and we are will waste bandwidth by sending them for free tier users.
More info here: https://github.com/apollographql/router/pull/1514#issuecomment-1226415941

**Comment by BrynCooke** [comment]
This is implemented in #1948

**Comment by BrynCooke** [comment]
I think that the code has changed and this is no longer implemented.

**Comment by abernix** [comment]
It's also not just about FTV1 — it's about traces **in the general sense.**  (Whether or not FTV1 is on, certain plans don't have trace retention.)

**Comment by BrynCooke** [comment]
I think this did get implemented then:
https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/telemetry/apollo_exporter.rs#L246-L256

It's not ideal as it can never recover once it gets `tracesIgnored`, but I guess we can say that it it implemented.

**Comment by BrynCooke** [comment]
Gonna open a new issue for the above.
