### ISSUE TITLE
Simple execution plan support for Subscriptions

### ISSUE THREAD

**Issue by blegrosvoalte** [apollographql/router#1743]
**Is your feature request related to a problem? Please describe.**

We'd love to use Apollo Router as our federated gateway, but we are in need of Subscription support.  We use a custom Subscription implementation which is backed by a message bus, rather than something like WS or SSE.  We use HTTP to call Subscription fields, which I know is very custom to our situation.  Our subgraphs are built on a variety of platforms (e.g - NodeJS and .NET).  Atm, when calling a Subscription field, published to Apollo Studio via Rover, the caller is met with a simple error message:

```
{
	"errors": [
		{
			"message": "value retrieval failed: spec error: subscription operation is not supported",
			"locations": [],
			"path": null
		}
	]
}
```

**Describe the solution you'd like**

It'd be very help if there was a mode/flag available to the router to enable the building a simple execution plan to forward a Subscription field onto its subgraph via HTTP.   Nothing fancy requiring federated directives, just simple forwarding.

**Describe alternatives you've considered**

We've looking into https://github.com/apollosolutions/federation-subscription-tools, but due to the diversity of platforms, resources, and hosting used by our teams, it'd be difficult to build a single, Subscription-specific subgraph, to grant access to all of the resources controlled by each team's subgraph.

**Additional context**

**Comment by abernix** [comment]
Thanks for opening this!  Some questions:

1. In this "simple" scenario you are describing, would there be:
	
	* **Multiple** subgraphs that each have _one or more_ subscription _root_ fields (i.e., fields which are directly on the `Subscription` type)
	* **AND** only **one** subgraph involved in subscription from the client at a time.
	
	In other words, would the Router be largely acting as "take subscription from client and pass to subgraph responsible for that subscription"?
	
	... or would the data returned from the subscribe-able type potentially need to trigger fetches of trees of data which spans multiple subgraphs?

2. Just to be clear, you are talking about HTTP (not something like WebSockets), is that correct?
3. And are we talking about long-lived HTTP connections to the client? Would you also be expecting long-lived connections to be held open between the Router and the subgraphs?  Would the ratio be `1 client connection : 1 subgraph connection`?

**Comment by blegrosvoalte** [comment]
Hi @abernix .  Thanks for following up on this one.  I'll try to do my best to answer inline:

> Thanks for opening this! Some questions:
> 
> 1. In this "simple" scenario you are describing, would there be:
>    
>    * **Multiple** subgraphs that each have _one or more_ subscription _root_ fields (i.e., fields which are directly on the `Subscription` type)
>    * **AND** only **one** subgraph involved in subscription from the client at a time.
>    
>    In other words, would the Router be largely acting as "take subscription from client and pass to subgraph responsible for that subscription"?
>    ... or would the data returned from the subscribe-able type potentially need to trigger fetches of trees of data which spans multiple subgraphs?

We are using Apollo Federation and have multiple subgraphs which expose fields under the `Subscription` root type.  If a GQL request has multiple `Subscription` fields provided which ultimately belonged to different subgraphs, we'd like the router to behavior just as it would with a `Mutation` and route to the appropriate subgraph.  It is important to note, we're asking for this behavior because we're reusing an existing messaging infrastructure to push data to our consumers of the API via AMQP.  HTTP is simply the transport to open the subscription with the subgraph.  We use a `Mutation` sent via HTTP, for the time being, to close the subscription.

> 2. Just to be clear, you are talking about HTTP (not something like WebSockets), is that correct?

Yes, GQL requests with subscription field names in the `query` are passed via HTTP in our model atm.  We're currently not using anything stateful to track a subscription via HTTP (eg - SSE via HTTP2).

> 3. And are we talking about long-lived HTTP connections to the client? Would you also be expecting long-lived connections to be held open between the Router and the subgraphs?  Would the ratio be `1 client connection : 1 subgraph connection`?

No, these HTTP connections remain stateless and serve the purpose to update the state of the subgraph to which the field was directed.  Each subgraph hooks into our messaging infrastructure to push data.  When a source event is generated, the host responsible for that event transforms the event into a result event and published that to the message bus (where our existing infrastructure takes over from there).

Hope this helps.

**Comment by blegrosvoalte** [comment]
@abernix Just checking in to see if any time has been spent looking into this?  As we build out more subgraphs, HTTP-based support is going to be essential for our subscription support.

**Comment by abernix** [comment]
@blegrosvoalte This is definitely something we are thinking about and actively about but I don't have any information to share available immediately.  This particular case is one of several approaches we are considering in how we think about the right direction here.  I'll be sure to pass along more information as soon as I have it and am able!

**Comment by bnjjj** [comment]
FYI we released a new version of the Router with the support of federated subscription, take a look at the changelog https://github.com/apollographql/router/releases/tag/v1.22.0
