### ISSUE TITLE
add support for accessing environment variables from rhai scripts

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1744]
It would be helpful to provide access to ENV variables to rhai scripts.

**As an important constraint**, this must respect the environment variable that limits env-access by prefix.

**Comment by BrynCooke** [comment]
When we get round to this we need to ensure that we are using environment variable safe-listing mechanism that we are going to introduce for config expansion.

**Comment by edriwing** [comment]
Hi!

Any news about this subjetc?
This is blocking for us.

Thks !

**Comment by o0Ignition0o** [comment]
Would it be practical to allow users to declare a "global_variables" key in the rhai yml configuration, where people could add their keys / values before they deploy, and we would load them once at router startup / config reload?

This would allow users to use [variable expansion for env variables and more](https://www.apollographql.com/docs/router/configuration/overview#variable-expansion) if they need to, and this would give narrower (and predeclared) access to variables to script writers.

eg:

```yml
rhai:
  scripts: "/rhai/scripts/directory"
  main: "test.rhai"
  global_variables:
    - foo: "bar"
    - baz: "${env.BAZ}"
```

would provide rhai script users with

```javascript

let foo = Router.GLOBAL_VARIABLES.foo;
let baz = Router.GLOBAL_VARIABLES.baz;
```
