### ISSUE TITLE
Support for using externally created secrets

### ISSUE THREAD

**Issue by cabewaldrop** [apollographql/router#1750]
**Describe the bug**

It looks like support for creating secrets external to the helm chart was added [here](https://github.com/apollographql/router/commit/6c9998858043be88fc0f87d1ca3ecbbb75f06d70) and then subsequently reverted [here](https://github.com/apollographql/router/commit/bccf26a44c4fc9706b9dd070dda17210318adba8#diff-13ba3d003721bc6e9344a417e44d79fcea241be1539b22c8fda58b88f45b09b7L62). 

We would still like the option to create a secret externally and then reference it using the value of `.Values.managedFederation.apiSecretName`.  Currently this is not possible because in order for the environment variable for API_KEY to be specified we have to set `.Values.managedFederation.apiKey` in the values file which in turn creates the secret from this [template](https://github.com/apollographql/router/blob/main/helm/chart/router/templates/secret.yaml)

**To Reproduce**

1. Specify values for `.Values.managedFederation.apiKey` and `.Values.managedFederation.apiSecretName` in your values file.
2. Run helm template
3. Verify that a secret is created from the secret.yaml template

**Expected behavior**

We would like to be able to specify a name of an existing secret to be used by our deployment

**Desktop (please complete the following information):**

OS: macOS BigSur
Version: 11.6.7

Thanks in advance for your help on this issue.

**Comment by garypen** [comment]
I think this was always broken. I've been working though the logic and trying to make it behave as agreed in the original issue:

https://github.com/apollographql/router/pull/1196#issuecomment-1150039786

and I can't.

I've got a proposed fix in PR: #1878. I've manually tested the various modes using these properties, but I don't have a cluster that I can actually verify that it works in.

@cabewaldrop  If there's any chance that you could test this fix before I merge, that would be very helpful.

**Comment by hobbsh** [comment]
We are using `.Values.extraEnvVarsSecret` with success. We manage our secrets using `ExternalSecrets`.

**Comment by cabewaldrop** [comment]
Thanks @garypen! I'll test this out today.

**Comment by cabewaldrop** [comment]
I was able to test this out using the following process:

I added the following to a values.sandbox.yaml file

```
managedFederation:
  existingSecret: graph-api-key
  graphRef: my-graph-ref@current
```

Ran the following template command

```
helm template test . --debug -f values.yaml -f values.sandbox.yaml  > template.yaml
```

I was then able to verify that the deployment contained the correct environment variable reference:

```
env:
  - name: APOLLO_KEY
    valueFrom:
      secretKeyRef:
        name: "graph-api-key"
        key: managedFederationApiKey
        optional: true
```

I then deployed this to my cluster and was able to see the router start correctly.  Here is the log segment from start:

```
{"timestamp":"2022-09-27T00:34:46.788681Z","level":"INFO","fields":{"message":"GraphQL endpoint exposed at http://0.0.0.0:80/ 🚀"},"target":"apollo_router::axum_http_server_factory"}
```

This looks like it is working as expected and fixes my issue.  Please let me know if there is anything else you want me to test out.  Thanks for putting this fix together.

**Comment by garypen** [comment]
@cabewaldrop Thanks very much for verifying the fix. I'll get it reviewed/merged for the next release.
