### ISSUE TITLE
Probes for helm chart don't respect configuration of `supergraph.path`

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/router#1787]
**Describe the bug**
Kubernetes probes configured at https://github.com/apollographql/router/blob/c214edf9d41b1ee85d0ac82e49b07b6c31b6e78d/helm/chart/router/templates/deployment.yaml#L90-L103
seem to only work if supergraph path configuration remains the default of `/`

**To Reproduce**
1. Use router config of
```yaml
supergraph:
  listen: 0.0.0.0:4001
  path: /graphql
  introspection: true
```
3. Submit request that is same as that of probes (i.e. on the root path) `curl "http://localhost:4001/?query=\{__typename\}" -H "Content-Type: application/json" -vv`
4. Error of 404
5. `curl "http://localhost:4001/graphql?query=\{__typename\}" -H "Content-Type: application/json" -vv`
6. 200 response

**Expected behavior**
livenessProbe and readinessProbe path should respect the configured supergraph path such that they work in the case the path is different

**Desktop (please complete the following information):**
 - OS: Linux kubernetes
 - Router Version 1.0.0-rc.0

**Comment by o0Ignition0o** [comment]
Good find!

The way to go would be to interpolate `.Values.router.configuration.supergraph.path` with a fallback to `/`

We'll need to double check `{{ .Values.containerPorts.http }}` is correct as well.

**Comment by damienpontifex** [comment]
@o0Ignition0o already got a PR up for consideration with this exact change :)
