### ISSUE TITLE
Error when deferring fragments on the top level Query field

### ISSUE THREAD

**Issue by alessbell** [apollographql/router#1800]
**Describe the bug**
Per the `graphql` [test suite](https://github.com/graphql/graphql-js/blob/a24a9f35b876bdd0d5050eca34d3020bd0db9a29/src/execution/__tests__/defer-test.ts#L196), which we're using to guide E2E testing with Apollo Client, we have a test that attempts to defer a fragment on the top level Query field when running the [supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2):

The following query:

```graphql
  query TestQuery {
    ...QueryFragment @defer
  }
  fragment QueryFragment on Query {
    allProducts {
      dimensions {
        size
      }
      variation {
        id
        name
      }
      sku
      id
    }
  }
```

Produces the error:

```
{
    "errors": [
        {
            "message": "value retrieval failed: router bridge error: the deno runtime raised an error: `request: couldn't receive response couldn't deserialize payload `13645066633052847595`: `deno: couldn't deserialize response : `Error(\"missing field `subselection`\", line: 0, column: 0)``.`",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

**To Reproduce**
1. Clone https://github.com/alessbell/router-defer-e2e-tests
2. Bring up the `supergraph-demo-fed2` router running on port 4000
3. In `router-defer-e2e-tests`: `cd CRA-demo && npm i && npm start`
4. Visit `http://localhost:3000/defer-top-level-query-field`

**Expected behavior**
The query to not return an internal server error.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version: 12.5

**Comment by Geal** [comment]
this looks like https://github.com/apollographql/router/pull/1778, that should fix it

**Comment by BoD** [comment]
Hi! Sorry for the late reaction, I've only tried this test on a recent Router right now.

In our case, the codegen automatically adds the `__typename` field to the selection, so it will look like:

```graphql
  query TestQuery {
    __typename
    ...QueryFragment @defer
  }
  fragment QueryFragment on Query {
    allProducts {
      dimensions {
        size
      }
      variation {
        id
        name
      }
      sku
      id
    }
  }
```

However, the value of the `__typename` field (which should be `Query`) is not returned on the initial payload. Our parser breaks at this point,  as it tries to read it.

Actual:
```
--graphql
content-type: application/json

{"data":null,"hasNext":true}

...
```

Expected:
```
--graphql
content-type: application/json

{"data":{"__typename":"Query"},"hasNext":true}

...
```

**Comment by Geal** [comment]
@BoD this looks like a different issue, I'm opening #1922 to track it

**Comment by BoD** [comment]
Thanks a lot!
