### ISSUE TITLE
Revisit opentelemetry integration

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#1812]
There are several things that need to be looked at:
* ~Upgrade to the latest open telemetry version. - we're expecting changes.~
* Fix premature shutdown of opentelemetry. - Currently we may receive errors on shutdown.
* Revisit hot reload - This got disabled, but there seems to be native support for hot reloading in tracing, so just check again if we actually needed to disable this.

**Comment by abernix** [comment]
> Upgrade to the latest open telemetry version. - we're expecting changes.

This is covered by #1948, so I've removed it from the list.
