### ISSUE TITLE
Improve display of named type for errors

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#1816]
If we query a non existent field, like this:

```graphql
{
  computer(id: "Computer1") {
    nonExistentField
  }
}
```

Here is the error:
```json
{
  "errors": [
    {
      "message": "invalid type error, expected another type than 'Named type Computer'"
    }
  ]
}
``` 

We should get rid of `Named type` and just display `Computer`

**Comment by abernix** [comment]
Thank you! This message was quite difficult to parse! I kept looking for a `Named` type. 🤪
