### ISSUE TITLE
@defer: incorrectly disables defer with null if argument

### ISSUE THREAD

**Issue by alessbell** [apollographql/router#1820]
**Describe the bug**
Per the [test case in graphql-js](https://github.com/graphql/graphql-js/blob/main/src/execution/__tests__/defer-test.ts#L167), the Apollo Client web E2E test suite has a test with the following query:

```graphql
query TestQuery($shouldDefer: Boolean) {
  allProducts {
    ...DimensionsAndVariation @defer(if: $shouldDefer)
    sku
    id
  }
}
fragment DimensionsAndVariation on Product {
  dimensions {
    size
  }
  variation {
    id
    name
  }
}
```

The expected result is that the defer directive _is_ applied since `if` is null, but the response is returned in a single chunk:

```
{"data":{"allProducts":[{"dimensions":{"size":"1","__typename":"ProductDimension"},"variation":{"id":"OSS","name":"platform","__typename":"ProductVariation"},"__typename":"Product","sku":"federation","id":"apollo-federation"},{"dimensions":{"size":"1","__typename":"ProductDimension"},"variation":{"id":"platform","name":"platform-name","__typename":"ProductVariation"},"__typename":"Product","sku":"studio","id":"apollo-studio"}]},"hasNext":false}
```

**To Reproduce**
1. Clone https://github.com/alessbell/router-defer-e2e-tests
2. Run `cd CRA-demo && npm run router:up`
3. Run `npm i && npm start`
4. Visit http://localhost:3000/disable-defer-null-if
5. Run `npm run router:down` to bring router down after testing

**Expected behavior**
The defer directive to be applied and a multipart response returned.

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
- OS: MacOS Monterey
- Version: 12.5

**Comment by jpvajda** [comment]
@prasek  mentioned:

however think I did find a variant of this that is a critical bug

Running the following with no variables:

```js
query TestQuery($shouldDefer: Boolean) {
  allProducts {
    ...DimensionsAndVariation @defer(if: $shouldDefer)
    sku
    id
  }
}
fragment DimensionsAndVariation on Product {
  dimensions {
    size
  }
  variation {
    id
    name
  }
}
```
resulted in router panic

```bash
2022-09-16T15:34:03.171405Z  INFO Apollo Router v1.0.0-rc.1 // (c) Apollo Graph, Inc. // Licensed as ELv2 (https://go.apollo.dev/elv2)
2022-09-16T15:34:03.171549Z  INFO Anonymous usage data is gathered to inform Apollo product development.  See https://go.apollo.dev/o/privacy for more info.
2022-09-16T15:34:03.203568Z  INFO Running with *development* mode settings which facilitate development experience (e.g., introspection enabled)
2022-09-16T15:34:04.792935Z  INFO GraphQL endpoint exposed at http://0.0.0.0:4000/ 🚀
2022-09-16T15:56:10.018398Z ERROR panicked at 'defer expects a `Boolean!` so the variable should be non null too and present or with a default value', /Users/prasek/.cargo/git/checkouts/router-18de2f110854a520/f3f27d7/apollo-router/src/query_planner/mod.rs:657:22
make: *** [up-router-main] Error 1
```

**Comment by Geal** [comment]
I am not sure that test is valid. In recent versions of the RFC, the `if` argument is non nullable (so the router should reject the request, so there's still a bug here)

**Comment by BoD** [comment]
I think, since the `if` argument [has a default value](https://github.com/graphql/graphql-spec/pull/742/files?w=1#diff-30a69c5a5eded8e1aea52e53dad1181e6ec8f549ca2c50570b035153e2de1c43R2128) (`true`) it is legal to not pass a value.
