### ISSUE TITLE
"Cannot return null for non-nullable field" when parent field is null

### ISSUE THREAD

**Issue by chrisvettese** [apollographql/router#1822]
**Describe the bug**
Router sometimes returns "Cannot return null for non-nullable field" when the field is not in the response due to the parent field being null.
![image](https://user-images.githubusercontent.com/43392078/190883841-52529d02-2620-4c1f-a47f-bc3d339ec4e2.png)

**To Reproduce**
It is difficult to explain how to reproduce this problem due to some queries behaving as expected and others not. As shown below in the output section, running more complex nested queries when the query field is null seems to trigger the error.

**Expected behavior**
This screenshot shows a query, made against the same subgraph servers, with Apollo gateway:
![image](https://user-images.githubusercontent.com/43392078/190883689-d2aa8103-2021-40e1-a8e7-f149a1bb7659.png)
The `not found` error is expected. The `nullable field` error is not present, as expected. See the below output section for the exact same query made in Apollo router, where the message occurs.

**Output**
![image](https://user-images.githubusercontent.com/43392078/190883522-6a061e9c-9431-43a0-8fc2-8c5a4a288569.png)
In this case, user is nullable, while id is not returned due to user being null, so the response should be considered valid.
This part is the response is unexpected:
`    {
      "message": "Cannot return null for non-nullable field User.id",
      "path": [
        "user"
      ]
    }`

The requested fields seem to affect the response in unknown ways, for example the error is not present in this simpler query:
![image](https://user-images.githubusercontent.com/43392078/190883549-1fbd7233-d7f6-4311-a441-f2ccb4ad5266.png)

In both of these queries, the `user` and `id` fields are queried, but one of them has the unexpected error while the other doesn't.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Geal** [comment]
thanks for the report. This is likely linked to https://github.com/apollographql/router/pull/1819
Is `driverData` provided by another subgraph than `user()`?

**Comment by chrisvettese** [comment]
Yes it's a different subgraph

**Comment by Geal** [comment]
it is now fixed by #1819, this will go in the next release
