### ISSUE TITLE
Rhai Configuration invalid checks in helm templates

### ISSUE THREAD

**Issue by LockedThread** [apollographql/router#1826]
**Describe the bug**

Using `.Files.Get` like in https://github.com/apollographql/router/blob/f3f27d75c6efc52129057690d0ff06efdea723cb/helm/chart/router/templates/cm-rhai.yaml#L12 is not possible without extending the helm chart so using the helm chart becomes somewhat impossible for any complex configurations. However, that is besides the point, the `{{- if index .Values.router.configuration "rhai" }}` checks are incorrect and should be instead checking for a value in `.Values.rhai.input_file`. The rhai configuration check happens https://github.com/apollographql/router/blob/f3f27d75c6efc52129057690d0ff06efdea723cb/helm/chart/router/templates/deployment.yaml#L113, https://github.com/apollographql/router/blob/f3f27d75c6efc52129057690d0ff06efdea723cb/helm/chart/router/templates/deployment.yaml#L130, and https://github.com/apollographql/router/blob/f3f27d75c6efc52129057690d0ff06efdea723cb/helm/chart/router/templates/cm-rhai.yaml#L2. 

**Expected behavior**
The overall problem with this is that you are unable to use your own rhai configuration in a CI/CD environment where you are unable to inject a file into the helm templating process. 

**Additional context**
Originally, I created a [pr](https://github.com/apollographql/router/pull/1245) so that router's helm chart could support adding a rhai configuration. This was done by using extra configmaps and volumes, this is a far better solution to the overall problem, which is adding support for rhai configurations because the user is given more flexibility in setting up their deployment.

I will be making a PR fixing this issue.

**Comment by garypen** [comment]
I think there's definitely a better answer than what we have, but I'm not sure that #1827 is it.

The reason the existing template checks for an index for `.Values.router.configuration "rhai"` is because in the template, it reads: `.Values.router.configuration.rhai.scripts` under the protection of that check. With your change, we may try to read that value when there is no rhai configuration set, in which case we'll get an error like:

```
Error: template: router/templates/deployment.yaml:115:35: executing "router/templates/deployment.yaml" at <.Values.router.configuration.rhai.scripts>: nil pointer evaluating interface {}.scripts
helm.go:84: [debug] template: router/templates/deployment.yaml:115:35: executing "router/templates/deployment.yaml" at <.Values.router.configuration.rhai.scripts>: nil pointer evaluating interface {}.scripts
```

I agree that the `Files.Get` stuff is not very nice and a better approach could be taken. Perhaps we can work under this issue to figure out a good solution?

Here is my provisional list of desired outcomes:
 - A way to inject a rhai source file into our executing container
 - Ideally, we'd get rid of the `rhai.input_file` altogether and somehow figure it out from our configuration specification
 - CI/CD friendly process
 - <any more?>

**Comment by garypen** [comment]
You can workaround the problem I describe by adding this to your values.yaml:
```
router:
  configuration:
    rhai: {}
```
but that's not a great user experience either.

**Comment by LockedThread** [comment]
> I think there's definitely a better answer than what we have, but I'm not sure that #1827 is it.
> 
> 
> 
> The reason the existing template checks for an index for `.Values.router.configuration "rhai"` is because in the template, it reads: `.Values.router.configuration.rhai.scripts` under the protection of that check. With your change, we may try to read that value when there is no rhai configuration set, in which case we'll get an error like:
> 
> 
> 
> ```
> 
> Error: template: router/templates/deployment.yaml:115:35: executing "router/templates/deployment.yaml" at <.Values.router.configuration.rhai.scripts>: nil pointer evaluating interface {}.scripts
> 
> helm.go:84: [debug] template: router/templates/deployment.yaml:115:35: executing "router/templates/deployment.yaml" at <.Values.router.configuration.rhai.scripts>: nil pointer evaluating interface {}.scripts
> 
> ```
> 
> 
> 
> I agree that the `Files.Get` stuff is not very nice and a better approach could be taken. Perhaps we can work under this issue to figure out a good solution?
> 
> 
> 
> Here is my provisional list of desired outcomes:
> 
>  - A way to inject a rhai source file into our executing container
> 
>  - Ideally, we'd get rid of the `rhai.input_file` altogether and somehow figure it out from our configuration specification
> 
>  - CI/CD friendly process
> 
>  - <any more?>
> 
> 
> 
> 

When I get on my pc later I will send you some gists so you see how my FluxCD setup works with router. The best way to inject the rhai source file would be through a configmap that the user creates, afaik this is how most optional configuration files are added in other charts. Here is an example of what I said previously https://github.com/bitnami/charts/blob/3e63f24cca3c296f1f05546f78cf65c732489df9/bitnami/redis/values.yaml#L144. Another option we could have is something like this https://github.com/bitnami/charts/blob/3e63f24cca3c296f1f05546f78cf65c732489df9/bitnami/redis/values.yaml#L137. Lmk what you think.

**Comment by LockedThread** [comment]
@garypen If you give me a go ahead I will write the implementation that was laid out by the previous message. Checkout this for my current CI/CD setup for router.
https://github.com/KnightHacks/manifest/tree/main/apps/base/router

**Comment by LockedThread** [comment]
> @LockedThread I just want to make sure I understand the proposal.
> 
> 
> 
> You want to solve this by introducing: `extraConfigMaps` We'd then use this capability to specify a `configMap` which contained our `rhai` script and which we mounted into our container via the usual volume mounting process. We could use the existing configuration section for `rhai` to point at this location for our scripts.
> 
> 
> 
> I think that sounds better than what we currently have. We could definitely get rid of the `rhai.input_file` related processing, which would be a very nice outcome, and I think it would meet all of my requirements. 

I would like to implement the same thing the bitnami redis char does for their configuration. Having it so you can yaml in line the whole rhai file or reference an existing configmap which our chart will then mount and reference as the rhai file.

**Comment by garypen** [comment]
Sounds good. I think we've discussed it far enough. You should go ahead with an implementation and we'll fine tune it (if required) from there.

**Comment by LockedThread** [comment]
> Sounds good. I think we've discussed it far enough. You should go ahead with an implementation and we'll fine tune it (if required) from there.

Sounds good. On another note, do you know if Apollo will be doing internships for 2023?

**Comment by abernix** [comment]
@LockedThread We don't have any information to share yet.  Keep your eyes on [Interns](https://www.apollographql.com/careers/interns), [Careers](https://www.apollographql.com/careers) and our [Twitter](https://twitter.com/apollographql)!

**Comment by LockedThread** [comment]
> @LockedThread We don't have any new information to share on our university program right now.  Keep your eyes on [Interns](https://www.apollographql.com/careers/interns), [Careers](https://www.apollographql.com/careers) and our [Twitter](https://twitter.com/apollographql)!

Thank you. I would love to make an impact by interning at some point. Love what y'all do, keep doing it.

**Comment by garypen** [comment]
@LockedThread I had a couple of spare hours and took a swing at doing this work in #1917. I'd appreciate a review from you if you have time. I don't think it's exactly what you proposed, but it is an improvement on what we have and I hope/think it would meet most user's needs.

**Comment by LockedThread** [comment]
> @LockedThread I had a couple of spare hours and took a swing at doing this work in #1917. I'd appreciate a review from you if you have time. I don't think it's exactly what you proposed, but it is an improvement on what we have and I hope/think it would meet most user's needs.

Yeah for sure, I will take a look.

**Comment by garypen** [comment]
> > @LockedThread I had a couple of spare hours and took a swing at doing this work in #1917. I'd appreciate a review from you if you have time. I don't think it's exactly what you proposed, but it is an improvement on what we have and I hope/think it would meet most user's needs.
> 
> Yeah for sure, I will take a look. Sorry for the lack of activity, It's been a bit hectic with Hurricane Ian down here in Florida.

Don't worry about timing/activity. I'm sure a Hurricane would take priority over something like this. I hope things aren't too dreadful for you.
