### ISSUE TITLE
docs and readme review for 1.0.0

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1849]
When we go to 1.0.0, we should remove the various indicators that we are "pre-1.0" from the documentation, README, etc.

**Comment by hobbsh** [comment]
It would be great to document upgrade paths to get to 1.0 so you don't have to wade through release notes and hope for the best.

**Comment by abernix** [comment]
I can certainly sympathize with the struggle of wading through release notes and I agree that it would be ideal to have 1:1 mappings between every pre-release version and 1.0.

Pre-release versions are particularly challenging because there are variable instructions — and even some back and forth — for each one and early adopters could be on any number of them.  The core team also wishes we had less breaking changes between pre-releases (particularly in our configuration!), but the goal was always to get to a stable 1.0 API.   Some of this is inherent to adopting software pre-1.0.  

Going forward, I feel comfortable defining a clear set of migration steps from major version to next major version.  The good news is that our configuration validation should point out the key points and both our documentation and a Ctrl-F/Cmd-F (Find) on the `CHANGELOG.md` should jump to the relevant changers.

In the meantime, I'll try to do the best job possible capturing the key points effectively in the (up and coming) release notes and I think we'd be happy to yield feedback about particular cases in our [discussions](https://github.com/apollographql/router/discussions).

I'm certainly looking forward to our 1.0.0 release!
