### ISSUE TITLE
If accept header is provided, don't return responses not covered by it

### ISSUE THREAD

**Issue by glasser** [apollographql/router#1882]
**Describe the bug**
If you send an operation with `accept: multipart/mixed; deferSpec=20220824`, then you should never get an `application/json` response back, even if the operation does not contain `@defer`. (Probably this should be an error.)

Moreover, if you send some random `accept: monkey/pants` header you shouldn't get `application/json` either.  Though starting by fixing the specific case of "I only asked for multipart" would be good.

**To Reproduce**
1. Ask on Slack if sending `accept: multipart/mixed; deferSpec=20220824` without `@defer` gets `content-type: application/json` back
2. Wait until @Geal tells you that the current behavior is to get `content-type: application/json` back

**Expected behavior**
If a client says they only are expecting `multipart/mixed`, they should not receive `application/json`. No strong opinion about whether this receives a 4xx error or a `multipart/mixed` message with a single submessage, though I think the former is better (so that we're never sending `multipart/mixed` without `hasNext` fields).

**Comment by glasser** [comment]
semi-related: https://github.com/apollographql/router/pull/1201#issuecomment-1256817149

**Comment by bnjjj** [comment]
What do you expect if you're sending the multipart header for a defer but the query contains `@defer(if: false)` ? As the `if` parameter is set to `false` it's not deferred at all and we're answering with a `content-type: application/json`. In #1891 I throw an error because it will answer a `content-type` unrelated to the `accept` header.

**Comment by glasser** [comment]
I think that's correct (but in practice clients will send `accept` headers that include both multipart and a different content-type)
