### ISSUE TITLE
Router adds confusing error message when subgraph returns no valid GraphQL response with content type text/plain

### ISSUE THREAD

**Issue by oliverjumpertz** [apollographql/router#1947]
**Is your feature request related to a problem? Please describe.**

We recently forgot to forward a specific header to one of our subgraphs. The subgraph, in return, responded with an HTTP 403, a content type of "text/plain" and no content.

As Router explicitly checks for the response content type, the Router's response included an error with the following message:

"subgraph didn't return JSON (expected content-type: application/json or content-type: application/graphql+json; found content-type: text/plain".

This was pretty difficult to debug because it was not the actual root cause.

**Describe the solution you'd like**

The spec does not say anything about HTTP status codes, so it would be difficult to check for that, but according to https://github.com/graphql/graphql-spec/blob/main/spec/Section%207%20--%20Response.md , a valid GraphQL response MUST be at least a "map". As far as I understand, it can (but does not necessarily need to) include a key "data" and may contain a key "errors".
(I interpret the spec from the side of a user here. I don't know whether subgraph X really raised an error so I cannot expect a key "errors". Thus, the presence of errors explicitly marks an error, its absence is ambiguous to me).

If Router checked for the presence of said map and, if absent, added an error message that at least states that the GraphQL response was invalid (because it was no map at all, which in this case should be an empty JSON object at least), it would be very helpful for debugging such cases.

**Describe alternatives you've considered**
./.

**Additional context**
We already spoke on Slack, so some of you are already aware of the context. :)

**Comment by o0Ignition0o** [comment]
Just read through the [Graphql/HTTP spec](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#status-codes) and the status code and content-type are very intertwined.

However the spec defines behavior for `application/graphql-response+json` and `application/json`. I ll have a look at how the gateway behaves

**Comment by bnjjj** [comment]
Is it something similar to https://github.com/apollographql/router/pull/2118 ?

**Comment by oliverjumpertz** [comment]
Yes, this could indeed be similar. :)
