### ISSUE TITLE
validation doesn't honor default enum values

### ISSUE THREAD

**Issue by andrew-kolesnikov** [apollographql/router#1979]
Our particular spec has a mutation input containing `channel: SimpleStringEnum! = WEB` but to pass validation, router expects input to still have that field explicitly set. 

{"input":{"channel":"MOBILE",...}}} passes validation
{"input":{...}}} doesn't with a cryptic error `response: {“errors”:[{“message”:“invalid type for variable: ‘input’“,”locations”:[],“path”:null,“extensions”:{“type”:“ValidationInvalidTypeVariable”,“name”:“input”}}]}
`

**Comment by andrew-kolesnikov** [comment]
@Geal the problematic mutation uses fragments, and likely to be related to the work done for https://github.com/apollographql/router/issues/1367

**Comment by Geal** [comment]
@andrew-kolesnikov could you show a reproducible test case?

With this schema:

```graphql
enum Terminal {
    WEB,
    MOBILE
}
type Query{
    test: String
}
type Mutation {
    page(channel: Terminal! = WEB): String
}
```

and this query:
```graphql
mutation GetPage($terminal: Terminal) {
    page(channel: $terminal)
}
```

right npow it works, but if you could show me something with the same shape as your query that would help

**Comment by Geal** [comment]
ok I see the error with
```graphql
mutation GetPage($terminal: Terminal!) {
    page(channel: $terminal)
}
```

**Comment by Geal** [comment]
hmm no, that fails because the operation itself actually needs a value. Can you show an example query?

**Comment by Geal** [comment]
alright, thanks!
