### ISSUE TITLE
Additional Prometheus Metrics

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1985]
We would need to agree on what these would be, but it seems like we could emit some other standard Prometheus metrics that could be nice from a debugging and observability standpoint.

* Istio returns [these](https://istio.io/latest/docs/reference/config/metrics/)
* Linkerd sets [these](https://linkerd.io/2.12/reference/proxy-metrics/)
* Nginx Ingress Controller sets [these](https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/prometheus/)

We should do a principled review of these and other options and make a proposal.

**Comment by bnjjj** [comment]
Request Size and Response Size might be interesting, but it's also good to know it's already available with our current implementation for exemple by using `Content-Length` header we should be able to know response size and request size. Maybe we should document that usage...

**Comment by abernix** [comment]
Blocked on #1948

**Comment by o0Ignition0o** [comment]
@abernix is it still something we want to work on ? we have a fair bunch of [metrics](https://www.apollographql.com/docs/router/configuration/metrics#available-metrics) now which, in conjunction with tracing, gives us a lot of observability.

**Comment by abernix** [comment]
Agree.  More than happy to close this and make the additional asks for metrics much more concrete (with their own issue).
