### ISSUE TITLE
docs: Development Mode

### ISSUE THREAD

**Issue by abernix** [apollographql/router#1988]
In #1474 ([landing in `1.0.0-rc.0`](https://github.com/apollographql/router/releases/tag/v1.0.0-rc.0)), we introduced a `--dev` flag which is currently best described in [the `CHANGELOG` for that release](https://github.com/apollographql/router/blob/main/CHANGELOG.md#adds-a-development-mode-that-can-be-enabled-with-the---dev-flag-1474):

> By default, the Apollo Router is configured with production best-practices.  When developing, it is often desired to have some of those features relaxed to make it easier to iterate.  A `--dev` flag has been introduced to make the user experience easier while maintaining a default configuration which targets a productionized environment.
> 
> The `--dev` mode will enable a few options _for development_ which are not normally on by default:
> 
> - The Apollo Sandbox Explorer will be served instead of the Apollo Router landing page, allowing you to run queries against your development Router.
> - Introspection will be enabled, allowing client tooling (and Sandbox!) to obtain the latest version of the schema.
> - Hot-reloading of configuration will be enabled. (Also available with `--hot-reload` when running without `--dev`)
> - It will be possible for Apollo Sandbox Explorer to request a query plan to be returned with any operations it executes. These query plans will allow you to observe how the operation will be executed against the underlying subgraphs.
> - Errors received from subgraphs will not have their contents redacted to facilitate debugging.

We need to get some actual documentation in for this, so users understand it exists!

**Comment by abernix** [comment]
@StephenBarlow Not asking for you to jump on this, but more just for awareness: in case you want to start threading this through any documentation that you currently have in-flight or have upcoming.

**Comment by chandrikas** [comment]
Closing for now. We have some documentation here: https://www.apollographql.com/docs/router/configuration/overview/#dev-mode-defaults
