### ISSUE TITLE
Tokio runtime metrics in prometheus plugin

### ISSUE THREAD

**Issue by andriihrachov** [apollographql/router#1992]
**Is your feature request related to a problem? Please describe.**

I need deep instrumentation for the router, not only latency.

**Describe the solution you'd like**
Include tokio runtime metrics to telemetry.prometheus plugin

**Comment by Geal** [comment]
is it still something you need? Would tokio-console support help? https://github.com/apollographql/router/blob/dev/CHANGELOG.md#add-support-for-tokio-console-pr-1632

**Comment by abernix** [comment]
I'll close this since we haven't heard back.
