### ISSUE TITLE
Router doesn't allow a payload larger than 2MB

### ISSUE THREAD

**Issue by gtavares** [apollographql/router#2000]
**Describe the bug**
Router doesn't allow a payload larger than 2MB. I believe it is because on version 1.0.0 the axum version was updated to [0.5.16](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md#0516-10-september-2022). In that specific version a security issue was fixed and for that reason a default body limit was added. I think we need to disable this behaviour as stated in the changelog or provide a way to configure this value.

`The default limit is at 2 MB and can be disabled by adding the new DefaultBodyLimit::disable() middleware. See its documentation for more details.`

**To Reproduce**
1. Submit a request with a payload size larger than 2MB.
2. See the error: `Failed to buffer the request body: length limit exceeded`

**Expected behavior**
Allow a request with a payload larger than 2MB

**Output**
`Failed to buffer the request body: length limit exceeded`

**Comment by abernix** [comment]
Just for the sake of better understanding, can you describe your use case for sending a payload that large?  e.g. Are you sending binary data or large payloads of any particular type?

**Comment by gtavares** [comment]
I'm sending a file by encoding it to a base64 string. I know that is not an ideal solution but it is what we have right now.

**Comment by abernix** [comment]
I completely figured pretty much _exactly_ that, but just wanted to ask and confirm. 😁   Thanks!

**Comment by jjroush** [comment]
Also experiencing this payload issue with large a input which exceeds 2mb; is Apollo looking for a PR to remove this limit?

**Comment by krish** [comment]
There are two parts of this issue.

`Max body length exceed`
`Request Entity Too Large`
 

From those two max body length should fix from http client like axios or http. But Request Entity too large is the max size set by the server. That is limit defined by server. Not the client. So when configure client to support `Max body length exceed` its required to server support for same amount or higher. (default usully is 2MB)

When we use direct GraphQL server (apollo backed by express) we set this from express.

Also when we use Federation with Gateway we set this from Gateway. Again, as express Configuration. we need a fix to do the same on router. Because as far as client concern they send payload to router. 

Here is how fixed request Entity too Large error on Federation **Gateway** need similar fix to router

 

```
app.use(json({ limit: '100mb' }));

  app.use(

    urlencoded({ limit: '100mb', extended: true, parameterLimit: 100000 }),

  );

  await app.listen(3080);
```

 

and

 

```
server: {

        cors: true,

        playground: true,

        introspection: true,

        bodyParserConfig: {

          limit: '100mb',

        },

      },
```

**Comment by andrew-kolesnikov** [comment]
Any updates on this issue?

**Comment by andrew-kolesnikov** [comment]
My organization is a heavy rust router user, we also ran into this issue. Is there any reason this isn't exposed as a configurable setting?

**Comment by bnjjj** [comment]
There is no reason right now except we have a big todo list right now. If you want to try to implement it and open a PR here is some guidances. You will have to use [this ](https://docs.rs/axum/latest/axum/extract/struct.DefaultBodyLimit.html) and add it [there](https://github.com/apollographql/router/blob/dev/apollo-router/src/axum_factory/axum_http_server_factory.rs#L408) by using the configuration coming from `configuration.server.body_size_limit`. Add this `body_size_limit` field [right here](https://github.com/apollographql/router/blob/dev/apollo-router/src/configuration/mod.rs#L928) which will be an `Option<usize>`

**Comment by jjroush** [comment]
@bnjjj I went down the path of implementing your recommendation but while testing think this is no longer an issue. I was able to reproduce the issue when on router `v1.2.0`

## Example Request 

```
mutation CreateReview($createReviewId: ID!, $upc: ID!, $body: String!) {
  createReview(id: $createReviewId, upc: $upc, body: $body) {
    id
  }
}
```

```
{
    "upc": "1234",
    "createReviewId": "1234",
    "body": "asd ...(2MB)..asd",
}
```

## 1.2.0 Response
Code: `413`
Msg: `Failed to buffer the request body: length limit exceeded`

## 1.11.0 Response
Code: `200`

## Dev branch Response
Code: `200`


With the 200+ issues y'all are inundated with, I think this is one you can close!
