### ISSUE TITLE
`protoc` as a build requirement

### ISSUE THREAD

**Issue by abernix** [apollographql/router#2011]
Upcoming dependency changes to `prost` necessitate that `protoc` be installed:

From [its changelog for 0.11.0](https://github.com/tokio-rs/prost/releases/tag/v0.11.0):

> Relase 0.11 brings a few breaking changes and changes to how prost
> sources protoc.
> 
> - `prost-build` now requires `protoc` to be available in the path or set
>   via the `PROTOC` env var.
> - `prost-types` now contains new `Timestamp`/`Duration` `FromStr` implementations.
> - MSRV bump to `1.56` and all crates have been moved to edition 2021

We should evaluate what the impact of this change is and if it will require changes to our build instructions and CI, or if it's avoidable through other means.

Places to evaluate/consider:

- Documentation
- [`DEVELOPMENT.md`](https://github.com/apollographql/router/blob/dev/DEVELOPMENT.md)
- Friendly error message improvements if we need them.

**Comment by garypen** [comment]
This is now documented in our DEVELOPMENT.md file and was fixed by #1970. The full set of changes was:
 - diy dockerfile
 - DEVELOPMENT.md
 - circleci config.yaml (to install protoc)
