### ISSUE TITLE
Lay foundation of crypto module in Rhai

### ISSUE THREAD

**Issue by abernix** [apollographql/router#2025]
When communicating with some subgraphs, it is necessary to sign the requests — for example various Google Cloud and AWS functions have their own HMAC requirements:

- [Google](https://cloud.google.com/run/docs/authenticating/service-to-service#acquire-token)

- [AWS](https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html)

When building your own native Rust plugin, this isn't particularly challenging (in fact, there are off the shelf AWS and GCP specific Crates that can make it even easier), but should we consider exposing such functionality in Rhai directly?

Perhaps something off-the-shelf that is relatively full-featured along the lines of the [Node.js `crypto`](https://nodejs.org/api/crypto.html) stdlib? (No strong feelings on what — e.g., sodium, orion, etc.; figuring that out would be part of the task.)

### Alternatives

The alternative here is that we just bake-in utility functions that do these for you for providers who are big enough to warrant it (I'm largely thinking about AWS, Google, Azure).  It will take a non-zero amount of time, effort and code for someone to implement those with just basic crypto functions, but maybe we still enable folks to do something more ad-hoc by having the functions there anyhow.

### Basic Requirements

Lay the foundation for a set of crypto helpers.  Let's just start with some simple things for now but be open to more: 

- [ ] SHA-256
- [ ] Google signing (above)
- [x] AWS signing (above) (configurable in yml via https://github.com/apollographql/router/pull/3365)
- [x] Base64 decode/encode

**Comment by brh55** [comment]
+1 Currently need this for a customer, and has been brought up in the past.

But given Rhai is positioned to reduce the path of resistance for folks moving from gateway with limited Rust expertise. It should be able handle common customizations seamlessly (i.e. header manipulation), so we should at least provide base64 decode/encode and sha-256.

**Comment by garypen** [comment]
It's not complete. Just the base64 part, so re-opening.

**Comment by prasek** [comment]
@abernix @chandrikas see related AWS Signaturev4 subgraph fetch signing in:
- https://github.com/apollographql/federation/issues/1784

**Comment by o0Ignition0o** [comment]
[Sigv4 support](https://github.com/apollographql/router/pull/3365) just landed, but it looks orthogonal to this issue, so we'll keep it open.

**Comment by abernix** [comment]
Given that SigV4 and Base64 Encode/Decode are done, I'm going to go ahead and close this as it's less visionary at this point and more just an omnibus ticket that doesn't add quite as much value.  **Concrete asks for more functions can be opened as new issues**.  Thanks!
