### ISSUE TITLE
Question: should we customize the Cargo.toml's include to add the license?

### ISSUE THREAD

**Issue by cecton** [apollographql/router#204]
I think we need to customize the `include` so the license gets shipped with the package. I can't test to be sure because we don't use the published version of apollo-parser yet (which prevents packaging apollo-router-core). But this is something we need to make sure before publishing.

**Comment by o0Ignition0o** [comment]
Are we talking about apollo-parser's license file? or the routers?

I'm not sure the router will be published to crates.io and [the xtask package command does include the license.html file](https://github.com/apollographql/router/blob/main/xtask/src/commands/package/mod.rs#L10) to the build artefacts.

**Comment by cecton** [comment]
> I'm not sure the router will be published to crates.io

That will make the use of apollo as a lib difficult :grin:

**Comment by abernix** [comment]
If a `license-file` is specified, it is always included.

**Comment by cecton** [comment]
Someone has read the doc :grin:
