### ISSUE TITLE
"healthcheck exposed" logged even though healthcheck is not enabled

### ISSUE THREAD

**Issue by nils-jansen** [apollographql/router#2041]
**Describe the bug**
Even though the healthcheck isn't enabled in the `router.yaml` file, the following log output is generated:
`healthcheck endpoint exposed at http://127.0.0.1:8088/health`

**To Reproduce**
1. Start up Apollo Router using docker (default commands from documentation, no extra configuration)
2. Observe logging output
3. Check to see if 127.0.0.1:8088 is reachable

**Expected behavior**
Logging output should be consistent with reality - either no log indicating the healthcheck is enabled when it isn't or enabling it to be active by default.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**
Seems to be a bug somewhere around [this line](https://github.com/apollographql/router/blob/48780c40c79ccf0056971f5b679e258fd07ee785/apollo-router/src/axum_factory/axum_http_server_factory.rs#L102).

**Comment by garypen** [comment]
The health check is [enabled by default](https://www.apollographql.com/docs/router/configuration/health-checks).

If you run this on your laptop (not in docker), then you can curl the health endpoint:

```
curl http://127.0.0.1:8088/health
{"status":"UP"}%
```

If you are running it in docker, by default it will only accept connections from local clients (i.e.: a process running inside the docker container), so you wouldn't be able to reach http://127.0.0.1:8088, from outside your docker container.

Summary: I don't think there is a bug. @nils-jansen If I'm wrong, please re-open this. I think it should be easy for you to confirm what I've done.

If you want to curl the health check in docker from your host system (or another remote machine), then you need to specify something like this in your configuration file:
```
health-check:
  listen: 0.0.0.0:8088
  enabled: true
```
Then run something like this:
```
docker run -p 8088:8088 -p 4000:4000 \
  --mount "type=bind,source=/configuration.yaml,target=/dist/config/router.yaml" \
  --rm \
  ghcr.io/apollographql/router:v1.4.0 -s /supergraph.graphql
```
You'll need to updated the `/configuration.yaml` to point at the absolute path to where your configuration file lives and you'll need to set `-s /supergraph.graphql` to the location of your SDL schema (or use APOLLO_GRAPH_REF, etc... to pull it down automatically).

**Comment by nils-jansen** [comment]
Gotcha, I think I get what's happening here. Thanks for explaining it.
Do you know what the reasoning is behind using `127.0.0.1:8088` instead of `0.0.0.0:8088` by default?

Would it be a reasonable suggestion to change this in the future?
