### ISSUE TITLE
Cannot pass cargo-deny v0.13.4 checks

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#2055]
```bash
$ cargo deny -L error check  
error[rejected]: failed to satisfy license requirements
  ┌─ xtask 1.2.1 (path+file:///Users/ignition/projects/apollo/router/xtask):4:12
  │
4 │ license = "Elastic-2.0"
  │            ^^^^^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: not explicitly allowed
  │
  = xtask v1.2.1

advisories ok, bans ok, licenses FAILED, sources ok
```

Steps to fix this:

- [x] Make sure crates.io accept crates released under the `Elastic-2.0` license
- [x] Update license ref in router-bridge from `LicenseRef-ELv2` to `Elastic-2.0` cargo.toml(s)
- [x] Update license ref in the router from `LicenseRef-ELv2` to `Elastic-2.0` cargo.toml(s)
- [x] Remove mentions of `LicenseRev-Elv2` in deny.toml and about.toml

⚠️ once this land, we will all need to update cargo-deny and cargo-about on our local machines

**Comment by o0Ignition0o** [comment]
#2054 fixes step 3

**Comment by o0Ignition0o** [comment]
https://github.com/apollographql/federation-rs/pull/206 will fix step 2

**Comment by o0Ignition0o** [comment]
crates.io uses [spdx version = 0.9.0](https://github.com/rust-lang/crates.io/blob/e09d5d2a403f9aafccf9d7f76968aeb387baa7d3/Cargo.toml#L77) which contains my PR that adds [Elastic-2.0 to the accepted spdx licenses](https://github.com/EmbarkStudios/spdx/releases/tag/0.9.0)

This fixes step 1

**Comment by o0Ignition0o** [comment]
https://github.com/EmbarkStudios/cargo-about/pull/205 Should allow us to update `cargo-about` and generate `Elastic-2.0` compatible licenses.

**Comment by o0Ignition0o** [comment]
A locally built cargo-about that targets my fork allows me to generate [the right html file.](https://github.com/apollographql/router/pull/2054/commits/52411206952099597916d94a9183d371c2764af1)

**Comment by o0Ignition0o** [comment]
The current workaround is to make sure we re using `cargo-deny 0.12` to run checks.

**Comment by Geal** [comment]
fixed by @o0Ignition0o
