### ISSUE TITLE
Include Dockerfile or Build Container Image script in Scaffold

### ISSUE THREAD

**Issue by flyboarder** [apollographql/router#2056]
**Describe the solution you'd like**
I'd like the router plugin scaffold to include a basic working Dockerfile or script to compile the custom router plugin.

**Describe alternatives you've considered**
Requiring the user to manually write a Dockerfile.

**Additional context**

From slack....
> There is also no direct way to go from our router plugin scaffold to a containerized router:
Router Scaffold -> no Dockerfile to build a container with
[build_docker_image.sh](https://github.com/apollographql/router/blob/dev/dockerfiles/diy/build_docker_image.sh) -> only works from diy folder in router project

**Comment by abernix** [comment]
Should be fixed by https://github.com/apollographql/router/pull/2307 which was shipped in v1.8.0!  Thanks for opening this originally!
