### ISSUE TITLE
Propagating response headers from a subgraph

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2060]
**Describe the solution you'd like**
It should be possible to propagate response headers from a supgraph to client. The same way we can propagete request headers to subgraphs, it should be possible to propagate response headers from a subgraph.

Tried to use the `subgraph_service` hook in `rhai` scripting, but it doesn't seem to be possible to set client response headers from within that hook.

**Describe alternatives you've considered**
Trying something along these lines for now which feels a bit weird, but let me know if thats totally fine.

```rhai
let propagated_headers = ["x-trace-id", "x-ratelimit-remaining", "cache-control", "x-cache-status", "x-ratelimit-retry-after", "retry-after"];

fn supergraph_service(service) {
    let map_callback = |response| {
        for header in propagated_headers {
            try {
                response.headers[header] = response.context[header]
            } catch {
                // cache key missing
            }
        }
    };
    service.map_response(map_callback);
}

fn subgraph_service(service, subgraph) {
    let map_callback = |response| {
        for header in propagated_headers {
            try {
                response.context[header] = response.headers[header]
            } catch {
                // cache key missing
            }
        }
    };
    service.map_response(map_callback);
}
```

**Additional context**
We are trying to move to a federated GraphQL. First step is to put the router in front of our API. Currently, we are sending a bunch of headers to the clients that we would gradually move to the `router`, but for the time being we want to propagate them from the subgraph.

**Comment by bnjjj** [comment]
I think this one is related to https://github.com/apollographql/router/issues/1284

**Comment by garypen** [comment]
@Meemaw Until #1284 is resolved, your approach (using the context) is the simplest way to propagate headers from your subgraph to the client.

**Comment by abernix** [comment]
I'm going to close this in favor of #1284.  In whatever design we choose here, we should be cautious about building dependencies on expected query plan shapes since those could evolve over time.  Thanks for opening this originally and follow the other issue for updates!
