### ISSUE TITLE
not all requests counted in prometheus metrics

### ISSUE THREAD

**Issue by deweyjose** [apollographql/router#2064]
**Describe the bug**
Invalid GQL requests are not included in Prometheus metrics. This can lead to gaps in metrics and impacts monitoring/alerting etc.

In the example below which is representative of what we see in our ecosystem at times. Clients will send malformed GQL requests, which typically generate 400s, which are not included in premetheus metrics. 

**To Reproduce**
```
curl --request POST \
  --header 'content-type: application/json' \
  --url 'http://0.0.0.0:8080/graphql' -vv
*   Trying 0.0.0.0:8080...
* Connected to 0.0.0.0 (127.0.0.1) port 8080 (#0)
> POST /graphql HTTP/1.1
> Host: 0.0.0.0:8080
> User-Agent: curl/7.79.1
> Accept: */*
> content-type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-type: text/plain; charset=utf-8
< content-length: 86
< access-control-allow-origin: *
< date: Tue, 08 Nov 2022 20:00:15 GMT
< 
* Connection #0 to host 0.0.0.0 left intact
Failed to parse the request body as JSON: EOF while parsing a value at line 1 column 0%    



curl http://0.0.0.0:8080/metrics -vv
*   Trying 0.0.0.0:8080...
* Connected to 0.0.0.0 (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> Host: 0.0.0.0:8080
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 0
< date: Tue, 08 Nov 2022 19:58:04 GMT
< 
* Connection #0 to host 0.0.0.0 left intact
```

**Expected behavior**
We expect to see supergraph prometheus request count metrics tagged with 400 in this case. More broadly though, we expect to see every request accounted in it's corresponding http status tag for supergraph request counts.

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by bnjjj** [comment]
The long term solution is to use opentelemetry `0.18`  thanks to this PR https://github.com/apollographql/router/issues/1948 because they added [this feature ](https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/struct.MetricsLayer.html#usage)

**Comment by BrynCooke** [comment]
Although implementer this is blocked on an opentelemetry release.

**Comment by bnjjj** [comment]
This PR https://github.com/apollographql/router/issues/1948 has been merged
