### ISSUE TITLE
Healthcheck documentation

### ISSUE THREAD

**Issue by kmcrawford** [apollographql/router#2079]
I was following the healthcheck [documentation](https://github.com/apollographql/router/blob/main/docs/source/configuration/health-checks.mdx) and needed to use `0.0.0.0` vs `127.0.0.1` to get the heathcheck to work.

Not working:
```
health-check:
  listen: 127.0.0.1:8088
  enabled: true
```

Working:
```
health-check:
  listen: 0.0.0.0:8088
  enabled: true
```

**Comment by o0Ignition0o** [comment]
Hi! Thanks for raising this issue!

Am I right assuming you're running the router in a Docker environment? If so you would indeed need to set `listen` to `0.0.0.0:8088`.

This has surprised a couple of users before, so it's imo worth documenting a bit better, adding a caveat section on how to set it up in a docker environment.

**Comment by kmcrawford** [comment]
Yes. Running locally on docker and in a Kubernetes environment.
