### ISSUE TITLE
Ability to respond from rhai script supergraph_service request mapper

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2083]
**Is your feature request related to a problem? Please describe.**
We want to add some custom validation logic to our router -- validate that requests are signed. If they are not, we bail out of the request with 400 without going to the subgraphs.

**Describe the solution you'd like**
Rhai script has a `map_request` mapper that we can use on the `supergraph_service` where we can access request query/headers, but there seems to be no way to respond to a request in a nice way (except for throwing, which will result in a 500 response).

**Describe alternatives you've considered**
Could do that in rust native plugin if needed.

**Additional context**
N/A

**Comment by Meemaw** [comment]
Seems similar to https://github.com/apollographql/router/issues/2023

**Comment by garypen** [comment]
It certainly is. I'll close this, if you don't mind, so that we focus our attention on #2023.

Please follow #2023, or re-open this if you think they are sufficiently different.
