### ISSUE TITLE
M1: `--hot-reload` flag will not work with a process executing via rosetta 2

### ISSUE THREAD

**Issue by garypen** [apollographql/router#2098]
Typically, such processes are containers running on your M1 machine using `docker` or some form of local `kubernetes`.

The main workaround is not to supply the `--hot-reload` flag. If you do need the flag on your M1 machine, then you must build a docker container yourself (perhaps using our diy `build_docker_image.sh` script, once #2085 merges).

We will address this soon by introducing either a multi-arch docker image or by providing separate images for "arm64" and "amd64" platforms.

If you wish to confirm that your docker image matches the M1 platform, you can do the following:

```
docker inspect <image name> | grep Architecture
        "Architecture": "arm64",
```
If your Architecture is "arm64" then `--hot-reload` should work. If it is "amd64", then that image will execute under Rosetta 2 and thus `--hot-reload` will not work.

**Comment by garypen** [comment]
I've figured out part of the solution. I can now build a multi-arch docker image on my laptop:

I'm documenting the process here in case it's helpful to anyone-else.

Firstly, you need to create a buildx builder:

```
docker buildx create --use --name mybuilder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host'
```
Note: You only need to do this if you are pushing to a docker registry that can't be resolved from the normal build container. I'm pushing to a registry running in a k3d cluster on my laptop, so that's a bit unusual and that's why I need to do this.

Now, build your multi-arch docker image:

```
docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg ROUTER_RELEASE=v1.4.0 -f dockerfiles/Dockerfile.router -t localhost:49276/router:v1.4.0-multi-arch .
```
Note: You have to push your multi-arch image somewhere or it will just live in your build cache. In this case, I'm pushing it to localhost:49276, (which is why I needed the unusual networking config for my builder). This takes about a minute or so to build the container on my laptop and then update the registry. Once this has finished, you can check the results:
```
docker buildx imagetools inspect localhost:49276/router:v1.4.0-multi-arch
Name:      localhost:49276/router:v1.4.0-multi-arch
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:1bd675847cd4bc07f00dc2229c68cd59a053c458660fde75c9978d0a55f99b2e
           
Manifests: 
  Name:      localhost:49276/router:v1.4.0-multi-arch@sha256:31bc61b24602281136d3143ca81c4f2a3cf9792fea9f482635a3200449bcf4b6
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64
             
  Name:      localhost:49276/router:v1.4.0-multi-arch@sha256:3611a10b1f207180a69a548190a759e09e451468f5cac266c6aff49bb1d211e0
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```
You can see I now have a multi-arch image in my registry: arm64 and amd64

Now: I just need to figure out how to get this working on our CI platform...

**Comment by garypen** [comment]
I *think* this is only an issue when running `amd64` code under rosetta 2 on M1 machines. I'm marking this as fixed by #2138, since that introduces multi-arch docker images. Previously our docker image where `amd64` only and I think that was the most common cause of this issue for users. 

If anyone encounters this problem in future, please re-open this ticket so that we can investigate it further.

**Comment by jon-frankel** [comment]
@garypen I've come across this issue while running the router natively on an M1 Mac, not inside of Docker. When I run this script to auto-update the supergraph document locally:

```sh
while :
do
  curl -s $SCHEMA_ENDPOINT > supergraph.graphql
  sleep 10
done
```

and then run the router with this:

```zsh
./router --dev --supergraph supergraph.graphql --hot-reload
```

Then I get this error:

```zsh
2022-12-14T14:30:04.095417Z  INFO reloading schema
2022-12-14T14:30:04.120186Z ERROR could not parse schema: Api("Syntax Error: Unexpected <EOF>.")
2022-12-14T14:30:04.463826Z apollo-router/src/files.rs:34  WARN apollo_router::files: could not process file watch notification. send failed because channel is full
2022-12-14T14:30:04.464656Z  INFO reloading schema
apollo-parser parsing error.

  × expected R_PAREN, got __Schema
2022-12-14T14:30:04.472293Z ERROR panicked at 'failed printing to stdout: formatter error', library/std/src/io/stdio.rs:1015:9
```

I suspect this is a problem of how overwriting the file causes file change events to be emitted, and how the file watcher listens for those events and triggers the Rust function. The file might be an interim state when Rust receives the change event, and it doesn't have the full contents written yet? I'm a bit out of my depth both on the OS side and the Rust side. I imagine there's some try-catch logic that could be added to make sure the file is done being overwritten.

I did a test by manually editing a few things in the supergraph document and that works fine. I also updated my script to this, which seems like a reasonable workaround:

```sh
while :
do
  curl -s $SCHEMA_ENDPOINT > supergraph.graphql.temp
  cp supergraph.graphql.temp supergraph.graphql
  sleep 10
done
```

That allows the router to continue running, although there are a ton of these warnings:

```zsh
2022-12-14T14:13:55.326717Z apollo-router/src/files.rs:34  WARN apollo_router::files: could not process file watch notification. send failed because channel is full
2022-12-14T14:13:55.382088Z apollo-router/src/files.rs:34  WARN apollo_router::files: could not process file watch notification. send failed because channel is full
2022-12-14T14:13:55.435277Z apollo-router/src/files.rs:34  WARN apollo_router::files: could not process file watch notification. send failed because channel is full
```

If this is a problem with Rosetta, are there plans to ship a native Apple Silicon version of the router?

**Comment by garypen** [comment]
@jon-frankel This isn't a rosetta issue.

It is however, as you speculate, a data integrity issue.

Your first script is directing content into a file which the router is watching and which the router expects to be always valid when processed. As you load data into "supergraph.graphql", then at some point a file modified event will fire and the router will attempt to process it. At that point, the file may not be a valid schema and you will see errors such as you describe.

Your second script avoids this issue (correctly) by atomically replacing the existing schema with a new schema in a single step. Both schemas are always valid, so no issues with schema parsing. As to the WARN, I wouldn't expect to see a huge number of those, but you will see more for a large schema or a heavily loaded system. It's not anything to be concerned about though.

I think your last question is really asking if we intend shipping an Apple Silicon version of the router for MacOS, since we do already ship an aarch64 (close to Apple Silicon) version of the router for Linux. The answer to that is: not at this time.  Our CI platform doesn't provide a build machine that we could use to do that.

I will observer that our docker images are multi-arch now and so they will work seamlessly on both aarch64/amd64.
