### ISSUE TITLE
Consider migrating otel tests to tracetest.io

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2114]
We currently have a couple of ways of testing telemetry.
1. A Jaeger integration test - uses the Jaeger API to query for spans after they have been collected by jaeger and reassembles them into a trace
2. test-span - A tracing layer that intercepts spans and tries to construct a trace.

With the upgrade of otel test-span has issues because it creates spans before the otel subscriber has been set up and thus they never get the otel context attached. This is problematic as we rely on the otel context currently to decide if we are being sampled or not, but also in future to store apollo specific data that is only to be used for the apollo exporter.

Both existing solutions are difficult for developers to understand and can easily be broken by the wrong call to accept a change in an insta snapshot.

tracetest.io looks promising as an alternative:

- [ ] get a test running.
- [ ] expand test suite.
- [ ] update ci appropriately.

tracetest includes support for jager and otel collector out of the box, if we do this then we can look to add datadog and zipkin support later.

**Comment by o0Ignition0o** [comment]
While this is certainly appealing, we will use the new stdout exporter at the moment. I'm going to close this issue since we haven't engaged for over a year.
