### ISSUE TITLE
Debugging Router via VSCode debug configuration

### ISSUE THREAD

**Issue by vamsi360** [apollographql/router#2144]
**Describe the bug**
I am trying to setup router debugging via WSL on Windows using VSCode. When I install the CodeLLDB extension and run, I get the below message: "Cargo has produced no matching compilation artifacts"

**To Reproduce**
1. Followed development.md file to setup Rust on WSL local and running it -> it works.
2. Imported to VSCode and able to browse the code
3. Installed codeLLDB extension and attempted to launch the debugger using below launch.json

```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Cargo launch",
            "cargo": {
                "args": [
                    "build",
                    "--lib"
                ]
            },
            "args": []
        }
    ]
}
```

**Expected behavior**
Debug the router from main.rs

**Output**
"Cargo has produced no matching compilation artifacts"

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (via WSL)

**Additional context**

**Comment by vamsi360** [comment]
Able to run it with below launch configuration, is there a way to run this directly without pointing to executable?

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Launch",
            "program": "${workspaceFolder}/target/debug/router",
            "args": [
                "-s",
                "examples/graphql/local.graphql",
                "-c",
                "dockerfiles/router.yaml"
            ],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

**Comment by chandrikas** [comment]
Hi @vamsi360, is this still an issue or have you managed to find a way around?

**Comment by chandrikas** [comment]
Closing for now. Please reopen if this is still an issue.
