### ISSUE TITLE
subgraph errors should bubble up to the next nullable parent field

### ISSUE THREAD

**Issue by Geal** [apollographql/router#215]
as described in https://www.apollographql.com/blog/graphql/basics/using-nullability-in-graphql/

With this schema:

```graphql
type Restaurant {
  name: String!
  rating: Int!
  location: Location!
}

type Location {
  address: String!
}

type LatLng {
  lat: Int!
  lng: Int!
}

type Query {
  restaurants(query: String): [Restaurant]
}
```

if a subgraph returns a response with this content:

```json
{
        name: "All Star Cafe",
        rating: 5,
        location: null
}
 ```

`location` must not be null, so we register an error, and mark the `restaurant` itself as null:

```json
{
  "data": {
    "restaurants": [ null ]
  },
  "errors": [{
    "message": "Cannot return null for non-nullable field Restaurant.location."
  }]
}
```

spec: https://spec.graphql.org/June2018/#sec-Errors
> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.

**Comment by Geal** [comment]
@cecton ^

**Comment by cecton** [comment]
Looks interesting!

**Comment by cecton** [comment]
I'll take this one

**Comment by cecton** [comment]
Cannot be done before #62 (can be done with #62 though...). Unassigning myself for now....

**Comment by Geal** [comment]
more context on this: currently subgraph errors are not integrated in the response. If we have something obvious like a connection error to the subgraph, it will be present, but if there was an error for a specific entity, we would get from the subgraph a response with an errors array containing some errors and related path, and those are not gathered right now.

We need to gather the subgraph errors, append their path to the current query plan node's path, and erase the error message (we don't want to expose subgraph info there).
We need to wait until the entire response was received to check the errors and find the next nullable parent field because:
- a field provided by a subgraph might be marked as non null, so it could cross the subgraph entity boundaries
- if another field of the same object is provided by a different subgraph, we could end up with a removed entity due to the first error, but see it added again by the second subgraph query (with missing fields)

**Comment by Geal** [comment]
aggregating the errors is easy enough. Recognizing nullable fields will be a bit more challenging: when traversing the response with errors, for each field we will need to look up in the schema if it is nullable
