### ISSUE TITLE
Project created using `cargo-scaffold` from documentation generates a xtask cargo project with a bunch of errors

### ISSUE THREAD

**Issue by vamshiaruru-virgodesigns** [apollographql/router#2165]
**Describe the bug**
I was following the documentation here: https://www.apollographql.com/docs/router/customizations/custom-binary, to start developing some plugins. Cargo build and run work just fine, but there's a binary called `xtask`.  That particular binary has a bunch of issues. The `clap` dependency doesn't have the `derive` feature without which none of the derive macros from clap work. Even after adding that, I get following errors:
```
error[E0277]: the trait bound `RouterAction: FromArgMatches` is not satisfied
  --> xtask/src/main.rs:22:16
   |
22 |         #[clap(subcommand)]
   |                ^^^^^^^^^^ the trait `FromArgMatches` is not implemented for `RouterAction`
   |
   = help: the following other types implement trait `FromArgMatches`:
             Action
             Args
             Box<T>

error[E0277]: the trait bound `RouterAction: FromArgMatches` is not satisfied
  --> xtask/src/main.rs:23:9
   |
23 |         action: RouterAction,
   |         ^^^^^^  ------------ required by a bound introduced by this call
   |         |
   |         the trait `FromArgMatches` is not implemented for `RouterAction`
   |
   = help: the following other types implement trait `FromArgMatches`:
             Action
             Args
             Box<T>

error[E0277]: the trait bound `RouterAction: Subcommand` is not satisfied
  --> xtask/src/main.rs:18:17
   |
18 | #[derive(Debug, Subcommand)]
   |                 ^^^^^^^^^^ the trait `Subcommand` is not implemented for `RouterAction`
   |
   = help: the following other types implement trait `Subcommand`:
             Action
             Box<T>
   = note: this error originates in the derive macro `Subcommand` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `xtask` due to 3 previous errors
```

**To Reproduce**
1. `cargo-scaffold scaffold https://github.com/apollographql/router.git -r apollo-router-scaffold/templates/base`
2. cd to xtask and run cargo build

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: ios
 - Version 12.2.1

**Additional context**
Can some one also help me understand what is the use of xtask? I am new to rust so I am not quite sure what's happening here.

**Comment by bnjjj** [comment]
Ok this is due to a recent changes we made in our dependencies on dev branch. To fix this please run this command instead ` cargo-scaffold scaffold https://github.com/apollographql/router.git -r apollo-router-scaffold/templates/base -t v1.4.0` 

About `cargo xtask`  it's just a tool which let's us write our scripts in rust instead of writing a Makefile + some bash. Under the hood it's looking at the local `xtask` directory and run it as a binary.

**Comment by vamshiaruru-virgodesigns** [comment]
Thank you, your command works :D

**Comment by bnjjj** [comment]
When this PR https://github.com/apollographql/router/pull/2263 has been merged the best option is to use `cargo-scaffold scaffold https://github.com/apollographql/router.git -r apollo-router-scaffold/templates/base -t main` and use `cargo-scaffold` >= `0.8.7`.

**Comment by marekrydlewski** [comment]
Hi @bnjjj, the PR #2263 is merged but the problem still does exist: building router with `cargo build` succeeds, but adding a plugin via e.g. `cargo router plugin create hello_world` fails with the same error mentioned above. Do you have any idea how that can be fixed? Thanks in advance.

**Comment by bnjjj** [comment]
@marekrydlewski This PR https://github.com/apollographql/router/pull/2343 will fix it, as a workaround you can do it manually in your own project updating `clap` dependency in `xtask/Cargo.toml` and set it to `4.0.32`. Let me know if it works :)

**Comment by marekrydlewski** [comment]
That works, thanks!
