### ISSUE TITLE
forbid `@defer` on subscriptions

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2167]
[`@defer` spec updates](https://github.com/graphql/graphql-spec/compare/01d7b98f04810c9a9db4c0e53d3c4d54dbf10b82...f58632f496577642221c69809c32dd46b5398bd7#diff-607ee7e6b71821eecadde7d92451b978e8a75e23d596150950799dc5f8afa43eR1589-R1605) mandate that `@defer` cannot be used in a subscription operation

**Comment by bnjjj** [comment]
Already covered by the query planner which rejects with an error `{"errors":[{"message":"subscription operation is not supported"}]}`

**Comment by bnjjj** [comment]
We should reconsider this issue when #1743 will be solved
