### ISSUE TITLE
Create a single caching implementation

### ISSUE THREAD

**Issue by garypen** [apollographql/router#217]
**Describe the solution you'd like**

Recent caching changes have resulted in two copies of caching code in the router both doing the same thing. We'd like to have 
one solution, with tests, which make it easy to use.

**Describe alternatives you've considered**

We have discussed adopting existing open source caching solutions that more fully represent our requirements. We aren't aware of one that matches our, admittedly fairly woolly, requirements. Improving the quality of our implementation will make it easier to work with and/or replace in the future.

**Additional context**
N/A

**Comment by cecton** [comment]
One way to find a crate that would do exactly what we need is to look at the dependents crate on crates.io: https://crates.io/crates/lru/reverse_dependencies

Of course it's always better if we can find something thoroughly tested and that fits perfectly. But I understand this might not be possible. Rust's ecosystem is still young, not everything is in there... if we do happen to create our own stuff I'd suggest to make a new crate specialized for that and license it under MIT OR Apache-2.0 for the community.

**Comment by garypen** [comment]
fixed: #235 
(some outstanding issues are extracted into #244 )
