### ISSUE TITLE
Router performance problem

### ISSUE THREAD

**Issue by voslartomas** [apollographql/router#2189]
**Describe the bug**
We recently deployed Router with single subgraph to our staging environment and watched for few days and it was stable and fast, now we promoted deployment to pre production, where is little bit bigger load and responses of queries might be also bigger (as there are real data) and we can see spikes as shown on picture below.

<img width="1195" alt="Screenshot 2022-12-01 at 12 38 57" src="https://user-images.githubusercontent.com/1945040/205043553-764d2bda-f899-40c1-b742-a99dd3eee404.png">

Not sure if I can enable something to have more granular tracing? Or what does exactly happen in this slow step?

Also it seems like most these slow queries are collections.

Edit: Found occurrence also for single entity query (not collection), attaching screenshot from Honeycomb.

<img width="1209" alt="Screenshot 2022-12-01 at 14 38 10" src="https://user-images.githubusercontent.com/1945040/205067047-0fb7db2f-c019-46c6-a7ca-cc96b46f2732.png">

We have graph in Apollo studio so can give more info if needed on which queries, variant of graph etc.

Another example, this one had empty response, just few bytes.

<img width="1189" alt="Screenshot 2022-12-01 at 16 40 30" src="https://user-images.githubusercontent.com/1945040/205095575-bf85b59d-b3e1-4b59-9ba3-925ccc26b567.png">

**Expected behavior**
I would expect to have much less time spent in this stage.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 1.4.0

**Comment by Geal** [comment]
waiting 20s before entiring the supergraph part does not sound right, we should get this fixed quickly. What kind of query is this? Is it large (either in query or in variables)? Is it compressed?
What do you see in the router's behaviour, does it have high CPU or RAM usage? How many requests per second for a router running on how many cores?

**Comment by Geal** [comment]
closing this for now: we looked at it out of band and it was due to another network component
