### ISSUE TITLE
The CORS plugin should allow users to specify access-control-max-age in configuration

### ISSUE THREAD

**Issue by osamra-rbi** [apollographql/router#2212]
Is it possible to add the method to the Request interface for Rhia? Is there a reason it isn't there in the first place? 

We're in the process of migrating from Apollo Gateway to Apollo Router, but one thing we cannot do is cache CORS requests, which is doing something along the lines of setting:
`Access-Control-Max-Age: 86400`

This can't be done with the current Rhia API as method isn't exposed on the Request interface, therefore we can't check for OPTION requests to add the headers needed

**Comment by garypen** [comment]
I think this actually requires a change to our CORS plugin, to support a`max-age` property, so I'm going to update the title and change the labelling.

**Comment by osamra-rbi** [comment]
Definitely think it makes more sense to be in the CORS configuration, this is where I first looked to see if it was possible

Although another header that's needed is Cache-Control and that's not necessarily something that's under CORS, maybe it makes more sense for that to be set via Rhia if the method could be exposed? Not sure.

[Here's this article that explains what we've been doing to provide more context](https://httptoolkit.com/blog/cache-your-cors/

**Comment by garypen** [comment]
I think it may make sense to do that automatically if the CORS plugin is modified to support a max-age property. Alternatively, our [HTTP processing stage will be delivered soon](https://github.com/apollographql/router/pull/2170) and I expect that may also help out here.

**Comment by osamra-rbi** [comment]
> I think it may make sense to do that automatically if the CORS plugin is modified to support a max-age property. Alternatively, our [HTTP processing stage will be delivered soon](https://github.com/apollographql/router/pull/2170) and I expect that may also help out here.

That makes sense. 

Meanwhile, I guess a temporary solution to achieve what we want is to make a native Rust plugin, until there's something in Apollo Router that allows us to do what we need

**Comment by osamra-rbi** [comment]
Hi @garypen @bnjjj 

I'll be opening up a PR that adds the max-age to the CORS configuration. I'm not sure of a solution for adding Cache-Control since it is somewhat independent of CORS

**Comment by abernix** [comment]
> cache CORS requests

I'm curious why this is feature is inherently important to you because it's my understanding from my basic Google search that this behavior literally cannot be relied on in browsers: Firefox is the only browser that allows 24 hours and most other browsers put cache limit in place on of anywhere from 5 minutes to 2 hours.  It also seems they offer no guarantees of that.

**Comment by osamra-rbi** [comment]
> > cache CORS requests
> 
> I'm curious why this is feature is inherently important to you because it's my understanding from my basic Google search that this behavior literally cannot be relied on in browsers: Firefox is the only browser that allows 24 hours and most other browsers put cache limit in place on of anywhere from 5 minutes to 2 hours.  It also seems they offer no guarantees of that.
> 
> 

Hey! You're right, each browser has different limits

Despite Firefox being the only browser that supports 24 hours, Chrome will see that and set it to its own limit (2 hours) 

The reason we did this was for response improvements. Before we had this, each request that went to our gateway would have to do a CORS request

After adding the header, we saw improved latency and a 20% request reduction to our gateway 

Honesty, we could probably lower the value since 24 hours is a bit high from my understanding

FWIW, we're going to be moving our gateway (router) to the same domain as our sites so we don't have to deal with CORS 

Nevertheless, I do think it's worth having this option anyways since it fits under CORS
