### ISSUE TITLE
how could I do it if I don't want to enable usage reporting even when I specify `APOLLO_KEY` and `APOLLO_GRAPH_REF`?

### ISSUE THREAD

**Issue by sianwunlai-houzz** [apollographql/router#2224]
Hi @prasek, how could I do it if I don't want to enable usage reporting even when I specify `APOLLO_KEY` and `APOLLO_GRAPH_REF`?

_Originally posted by @sianwunlai-houzz in https://github.com/apollographql/router/issues/1379#issuecomment-1338884308_

**Comment by abernix** [comment]
What are you trying to accomplish by disabling usage reporting?  Can you get more specific about what problem you're trying to avoid?  Traces transmitted via OpenTelemetry (arguably, the computationally more costly aspect of usage report) themselves can be adjusted by changing the sampling rate ([docs](https://www.apollographql.com/docs/router/configuration/tracing#trace-config)), and additionally the FTV1 rate can be sampled even further using [this configuration](https://www.apollographql.com/docs/router/configuration/apollo-telemetry/#enabling-field-level-instrumentation).

Overall, usage _metrics_ about field usage (note: I'm not talking about traces here) are a key component of providing valuable schema checks in Studio so disabling them is not something we intend to do.

Happy to answer any follow-up questions!

**Comment by TLadd** [comment]
@abernix I imagine the thought here would be to utilize apollo studio for managed federation (which also requires setting these env vars) but not send usage data, so you aren't charged per-request. You would obviously lose the functionality you mention around schema checks,, but it would allow managed federation for composing and hosting the supergraph schema  to be run for free.
