### ISSUE TITLE
router panics when parsing invalid schema

### ISSUE THREAD

**Issue by garypen** [apollographql/router#2269]
```
2022-12-14T14:30:04.095417Z  INFO reloading schema
2022-12-14T14:30:04.120186Z ERROR could not parse schema: Api("Syntax Error: Unexpected <EOF>.")
2022-12-14T14:30:04.463826Z apollo-router/src/files.rs:34  WARN apollo_router::files: could not process file watch notification. send failed because channel is full
2022-12-14T14:30:04.464656Z  INFO reloading schema
apollo-parser parsing error.

  × expected R_PAREN, got __Schema
2022-12-14T14:30:04.472293Z ERROR panicked at 'failed printing to stdout: formatter error', library/std/src/io/stdio.rs:1015:9
```

From a customer comment on #2098. I'm not sure which version of the router caused this problem.

**Comment by jon-frankel** [comment]
@garypen I see I was using version 1.5.0 — I think 1.6.0 just became available. I updated just now and I saw the error message on the first attempt at running it. Trying three more times, it does start and stay up, though the warnings continue to happen. I also see the warning when running from inside docker.

**Comment by Geal** [comment]
@SimonSapin does this still happen with recent apollo-parser fixes?

**Comment by SimonSapin** [comment]
No, nothing changed around this recently that I know of. I can reproduce the error on `dev`.

Schema parsing calls `apollo_router::error::ParseErrors::print` to format errors with miette to stdout. I don’t know what it does that instead of normal logging. Then it’s `impl Debug for miette::Report` that returns an error, but it’s not obvious from reading miette code why it does that either.

**Comment by SimonSapin** [comment]
It looks like miette errors because apollo-parser reports an `index` for some errors that is out of bounds of the input string.

**Comment by SimonSapin** [comment]
Found the root cause: the input string we give to apollo-parser has `introspection_types.graphql` concatenated to it, but not the one we give to miette

**Comment by Geal** [comment]
oh, nice one!

**Comment by smyrick** [comment]
This is not a Router issue but commenting here that it would be nice if Studio/checks could validate not just schema types but config and schema metadata too
