### ISSUE TITLE
provide a rhai interface to the router service

### ISSUE THREAD

**Issue by garypen** [apollographql/router#2278]
#2170 provided the new router_service. We should provide access to this from our rhai environment.

## Use Cases

- [ ] https://github.com/apollographql/router/issues/2699
- [ ] More?

**Comment by klippx** [comment]
What is `router_service` even? Do you have a link to docs?

**Comment by lennyburdette** [comment]
New customer use case: they have clients that [double-encode variables and extensions in requests](https://www.apollographql.com/docs/apollo-server/migration#doubly-escaped-variables-and-extensions-in-requests) (something that apollo 3 supported). A Rhai `router_service` hook would allow them to fix this as they deprecate those clients (which may take years). This is a blocker (they could use coprocessors but that's a heavy-weight solution for what would be a five-line script.)

```rhai
fn router_service(service) {
  service.map_request(|req| {
    if type_of(req.body.variables) == "string" {
      try {
        req.body.variables = json_decode(req.body.variables);
      } catch (err) {
        throw "Invalid variables";
      }
    }
  });
}
```

**Comment by abernix** [comment]
> `router_service` is an experimental service. You can have a look at the [router docs overview](https://www.apollographql.com/docs/router/customizations/overview#how-customizations-work) and the [request / response definitions](https://github.com/apollographql/router/blob/2c97f283000c0e1c176974d7d7ea3442f4a3a1c9/apollo-router/src/services/router.rs#L39) to get an early feel for it.

For anyone following along, `router_service` is no longer experimental.  Additionally, #3234 is a PR that is meant to close this issue.
