### ISSUE TITLE
Weekly automated release

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#229]
It would be advantageous to create a weekly automated release, especially pre-1.0 where users don't want to be kept waiting to get the latest bug fixes and improvements.

Propose that a we automate releasing every Monday until such time that we hit 1.0.

**Comment by abernix** [comment]
Agree with the idea, but how do we want to automate the version bumpage?

(e.g., are we thinking conventional commit-y?)

**Comment by abernix** [comment]
Oh, additionally, I'd also like to understand how we might keep a nice set of published release notes for each release with an automated publishing mechanism in place.

**Comment by BrynCooke** [comment]
Ideally we always add something to the changelog for each PR. Otherwise when a release comes round we are scratching our heads trying to remember what we did.

Regarding version bumpage, maybe we don't. I've seen some projects produce binaries with the current version plus the git hash as a suffix. The goal here is to prevent people having to wait a long time for updated binaries, so we could save the full release process to be something we do manually, but automatically produce snapshots on a regular basis.

**Comment by abernix** [comment]
Related to changelog stuff though, a tempting thing to instrument is https://twitter.com/github/status/1468671811235762187?s=21, but that seems like a different issue I should open.

**Comment by abernix** [comment]
Closing in favor of https://github.com/apollographql/router/issues/2261
