### ISSUE TITLE
Improve response on invalid query variables

### ISSUE THREAD

**Issue by andraaandrus** [apollographql/router#2301]
**Describe the solution you'd like**
For a query such as this one
```
curl \
  -X POST \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  --data '{ "query": "query Test($country: Country!) { shippingMethodsByLocation(country: $country) { name } }", "variables" : "null" }'\
  http://0.0.0.0:4000/test/graphql 
```
The response from the router (v1.6.0 and up), is:
```
status : 400
body   : Invalid GraphQL request
```
Is it possible to have more context on the error that occurred, potentially in `router_response.context` so we know that the error is regarding the format of the variables?

**Describe alternatives you've considered**
We are using the `router_service`  (as mentioned [here](https://github.com/apollographql/router/issues/1298#issuecomment-1354373558)) to modify the response body to include more information in the response we send to our clients, but we have to check the entire response body from Apollo Router in order to do so, and "Invalid GraphQL request" does not provide sufficient context for us at the moment.

**Additional context**
Prior to upgrading to v1.6.0, the response from the router was:
```
status: 422
body: Failed to deserialize the JSON body into the target type: invalid type: string "null", expected a map at line 1 column 
```

**Comment by o0Ignition0o** [comment]
Hi, thanks for opening an issue!

I've just tried sending the same query to a router that targets our dev branch, and enabling prometheus:
```yml
telemetry:
  metrics:
    prometheus:
      enabled: true
```

and visiting `http://localhost:9090/metrics` showed me this:

```
apollo_router_http_requests_total{error="failed to parse the request body as JSON",service_name="apollo-router",status="400"} 1
```

I agree it's not very helpful.

We could add the error message and reason to the metrics endpoint (as shown [in this draft PR](https://github.com/apollographql/router/pull/2305)) which would yield a bit more, and / or log the errors as well.

Here's what the metrics endpoint shows in the draft PR:

```
apollo_router_http_requests_total{error="failed to deserialize the request body into JSON: invalid type: string \"null\", expected a map at line 1 column 123",service_name="apollo-router",status="400"} 1
```

I'm tempted to /not/ show the error in the response body for potential security reasons, and rather use logs / prometheus metrics, especially in a production environment. But maybe the team thinks otherwise.

**Comment by o0Ignition0o** [comment]
I discussed it a bit further with @bnjjj and we might be able to iterate on the work he has done in https://github.com/apollographql/router/pull/2178 to provide an error with context

**Comment by andraaandrus** [comment]
Thank you @o0Ignition0o

**Comment by andraaandrus** [comment]
Hi @o0Ignition0o @bnjjj and happy new year 🎉

We started using the fix to this issue on our side and we have some feedback:

We are trying to provide our users a more meaningful error message when the format of `variables` is incorrect. The current response from the router is not specific enough for our use case.
```
{
  "errors": [
    {
      "message": "Invalid GraphQL request",
      "extensions": {
        "details": "failed to deserialize the request body into JSON: invalid type: string \"null\", expected a map at line 1 column 100",
        "code": "INVALID_GRAPHQL_REQUEST"
      }
    }
  ]
}
```
Is it possible to provide a more specific code for invalid variables object or potentially add a typed information (like an enum) into the response context so that we don't have to parse the whole response body?

Thank you!
