### ISSUE TITLE
Support supergraph composition via service introspection (a.k.a IntrospectAndCompose)

### ISSUE THREAD

**Issue by col** [apollographql/router#2311]
In certain circumstances it can be really useful to compose the supergraph at runtime by introspecting all of the subgraphs. In my case we've been using this in our performance testing environment (using the Apollo Gateway) so that it builds the correct supergraph based on the service versions being tested. We're migrating to the Apollo Router now but this feature is missing.

**Proposed Solution**
Essentially just duplicate the existing `IntrospectAndCompose` feature from Apollo Gateway.
See: [composing subgraphs with IntrospectAndCompose](https://www.apollographql.com/docs/apollo-server/using-federation/apollo-gateway-setup#composing-subgraphs-with-introspectandcompose)

The main difference would be that we should be able to enable this feature and provide a list of all the subgraph services as part of the configuration file. 

Maybe something like this:
```yaml
introspect_subgraph_urls:
  accounts: http://accounts:8080
  products: http://products:8080
```

**Alternative**
The alternative to this is to write a script that will introspect each service and manually compile the supergraph using Rover CLI. This is less than ideal as we'd really like to automate the deployment of the entire performance test environment and it would be difficult to integrate this script before starting the Router.

**Comment by Geal** [comment]
the supported way to do it is to use rover, can we help you automate your benchmarks using rover? What is the issue with running a script before starting the router?

**Comment by Meemaw** [comment]
@Geal I think this would be very useful for dev/testing environments. For example, one could define its stack (consisting of 3 subgraphs and router for example) in docker compose and get it up and running with 1 command.

Without it, this is roughly 4 steps:
- Start 3 subgraphs
- Wait for them to be ready to respond to http requests
- Use rover cli to generate a supergraph schema
- Start the router with the generated schema

**Comment by Geal** [comment]
Did you try starting the router with `rover dev`? https://www.apollographql.com/docs/rover/commands/dev/
It can compose a schema then start the router with that schema.

Adding composition in the router would make it 3 steps instead of 4, there would not be a big gain, and our focus in automating it right now is by going through managed federation

**Comment by col** [comment]
I wasn't aware of the `rover dev` command. I'll give it a try this week. Thanks!

**Comment by chandrikas** [comment]
Closing issue. Please let us know if this is still an issue and reopen.
