### ISSUE TITLE
Invalid content type on invalid graphql request errors

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2320]
**Describe the bug**
If an invalid GraphQL request is sent to the router, router does not set `content-type: application/json` even though the response is JSON, and looks like this:

```json
{
	"message": "Invalid GraphQL request",
	"extensions": {
		"details": "failed to deserialize the request body into JSON: EOF while parsing a string at line 1 column 11",
		"code": "INVALID_GRAPHQL_REQUEST"
	}
}
```

P.S. The new error handling done in 1.7.0 is great, just noticed this slight regression.

**To Reproduce**
1. Start router with any schema
2. Do a curl request with invalid payload, e.g `-H 'content-type: application/json' -d '{"query":"}'`

**Expected behavior**
Response should have `content-type: application/json` header

**Comment by bnjjj** [comment]
Good catch ! I will fix it :)
