### ISSUE TITLE
Ability to set timeouts to individual subgraphs based on the query.

### ISSUE THREAD

**Issue by vamshiaruru-virgodesigns** [apollographql/router#2328]
**Is your feature request related to a problem? Please describe.**
Right now, timeout is at subgraph level. Is there a way to perform timeouts at resolver level based on the query? For example, for query A, we want timeout of a resolver to be 100 MS, but for a in query B, we want the timeout to be 500 MS. At the moment, there's no way to do this. 

**Describe the solution you'd like**
Maybe some way to pass additional information (either via headers, or annotations) when making the query, and we can extend the execution layer / subgraph layer to timeout based on this information? For example
```
query A {
     query {
         field1
         @timeout(40) field2 {
             field3
             field4
         }
     }
}

**Describe alternatives you've considered**
I am not sure what I can do here. Is this sort of support possible to implement? I have a feeling we can do it using plugins by extending the execution service, but  i am not sure. Any guidance is appreciated.

**Comment by vamshiaruru-virgodesigns** [comment]
Okay, timeout at resolver level is the wrong way to put it. More like, timeout when router calls individual subgraphs. I want this timeout to be dynamic based on the request, instead of knowing at compile time. I am not sure how this is possible :/ For example, if the operation name is `Query1`, I want the timeout for `subgraphA` to be 100 ms, if the operation name is `Query2`, I want the timeout for `subgraphA` to be 500 ms. But I am pretty sure the timeout can't be dynamic this way, right? The `subgraph_service` is built once, and the `timeout` layer has to be provided at that point. 

Is there any way to do this? I think I could do this in node-js federation by extending `RemtoeDataSource` and overriding the `fetcher` in the datasource.

**Comment by vamshiaruru-virgodesigns** [comment]
Based on further research, I came to this solution:
```rust
        let subgraph_name = subgraph_name.to_string();
        ServiceBuilder::new()
            .map_future_with_request_data(
                move |req: &subgraph::Request| {
                    info!("subgraph_name: {subgraph_name}");
                    let body = req.subgraph_request.body();
                    let super_body = req.supergraph_request.body();
                    info!("Processing request in subgraph service in map future: {body:?}");
                    info!("Processing request in subgraph service in map future super: {super_body:?}");
                   // There is hopefully enough information here to get timeout (based on operation name, subgraph, the query being processed etc
                    req.context.clone()
                },
                move |ctx: Context, fut| async move {
                    info!("In map future with request data: {ctx:?}");
                    let resp = tokio::time::timeout(
                        std::time::Duration::from_nanos(5),
                        fut,
                    ).await.expect("Timeout unexpected");
                    resp
                },
            )
            .service(service)
           .boxed()
```
Is using tokio::timeout like this fine? How do I populate errors when timeout happens here (as in are there any best practices I can use?). 

Thanks in advance!

**Comment by Geal** [comment]
doing this as a directive is not possible right now, there are still a few steps before we support custom directives, so in the meantime, your main bet would be extending the router, as you're doing right now, with a header indicating the timeout.

`tokio::timeout` is fine for this. For errors, I think the best approach here would be to construct a graphql response with a null data field, and an errors field indicating the timeout (you can take inspiration from here: https://github.com/apollographql/router/blob/dev/apollo-router/src/services/subgraph_service.rs#L397-L410 ). That way, you would still get data from the rest of the query if it's available

**Comment by vamshiaruru-virgodesigns** [comment]
Thanks! That works, I am closing this issue :)

**Comment by vamshiaruru-virgodesigns** [comment]
Hi @Geal , can you help me figure out how to get the rest of the response incase of timeout from one subgraph? I'm getting the following error:
```
Subgraph response from 'subgraph' was missing key `_entities`
```
Here's how I am trying to build the response in case of error:
```rust
subgraph::Response::builder()
                                .data(serde_json::Value::Null)
                                .error(
                                    apollo_router::graphql::Error::builder()
                                        .message("Timeout error!")
                                        .extension_code("FETCH_ERROR")
                                        .build(),
                                )
                                .context(Context::new())
                                .extensions(
                                    serde_json_bytes::json!({
                                        "code": "FETCH_ERROR",
                                        "exception": {
                                            "stacktrace": vec!["Timeout error!"]
                                        }
                                    })
                                    .as_object()
                                    .cloned()
                                    .unwrap(),
                                )
                                .build();
```
