### ISSUE TITLE
Feature: Subgraph HTTP service

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#2349]
#1496 Has added the ability to work with raw http payloads at the router level.

It would be great if we could have an equivalent at the subgraph level.

This would allow users to customize http behavior when making subgraph calls, while still being able to benefit from our yml provided plugins (retries, timeouts and deduplication for example).

This would enable usecases such as advanced tls handshakes, dynamic url resolution and more.

It would also allow custom implementations, so #2230 could be fixed via a plugin

**Comment by hrkfdn** [comment]
Are there plans to make this service public applications using the router crate? It seems like it could also help with https://github.com/apollographql/router/issues/364, i.e. by having a Lambda handler transform requests to `subgraph_http::Request`

**Comment by o0Ignition0o** [comment]
Hi!

I'm not quite sure how this would help, since the subgraph_http_service would be used to transform raw http requests being made to subgraphs, but I'm not quite sure that would actually help for #364

**Comment by hrkfdn** [comment]
Ah you're right, sorry, I think I somehow forgot this was for communication to subgraphs.
