### ISSUE TITLE
Return a HTTP 504 Gateway Timeout when the router timeout triggers

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2400]
The timeout in traffic shaping returns an `Err`, which is translated to a HTTP 500 in the axum code: https://github.com/apollographql/router/blob/dev/apollo-router/src/axum_factory/axum_http_server_factory.rs#L342-L347

We should convert it to a more meaningful error (probably directly ion the timeout layer)

**Comment by rafagsiqueira** [comment]
Question, when apollo router timeout is achieved it returns 200 code message with:
```
{
    "data": null,
    "errors": [
        {
            "message": "Your request has been timed out",
            "path": [],
            "extensions": {
                "code": "GATEWAY_TIMEOUT",
                "service": "treaties"
            }
        }
    ]
}
```
Is there any way to return a 504? My apollo client (angular apollo) has an off-the-shelf retry implementation for network errors, which I am unable to use, since apollo router returns a 200.

**Comment by smyrick** [comment]
@rafagsiqueira I believe this is because the timeout you are hitting is a subgraph timeout, not a router level timeout: https://github.com/apollographql/router/pull/8309
