### ISSUE TITLE
Update to Federation v2.3.0

### ISSUE THREAD

**Issue by abernix** [apollographql/router#2465]
This tracks the need to update the Router to support Federation v2.3.0.  As of the writing of this issue, that release is in `2.3.0-beta.3` state and tracked in the [`federation` repo's milestone](https://github.com/apollographql/federation/milestone/21).  This issue may remain open until the final `2.3.0` lands and any additional follow-up work or verification (such as consideration for whether or not https://github.com/apollographql/federation/pull/2335 is necessary to port to the Router!) has been completed.

**Comment by AndriiTsok** [comment]
I just wanted to confirm this one being a blocker as 2.3.0 has been released. Unfortunately, the interfaceObject and the 2.3 namespace do not work for the latest version of the router.

**Comment by o0Ignition0o** [comment]
Closing this issue since router 1.10 runs federation 2.3
