### ISSUE TITLE
Open Telemetry: subgraph spans not contained by parent router span

### ISSUE THREAD

**Issue by prasek** [apollographql/router#247]
**Describe the bug**
Split out from #180: Open Telemetry: subgraph spans not contained by parent router span

**To Reproduce**
1. `git clone git@github.com:apollographql/supergraph-demo-fed2.git`
2. `make docker-up-router-otel` - uses [docker-compose.router-otel.yml](https://github.com/apollographql/supergraph-demo-fed2/blob/main/docker-compose.router-otel.yml)
3. `make smoke-router`
4. http://localhost:9411/ -> `Run Query`
5. see subgraph spans not contained by parent router span
6. click `Show` and see the offset subgraph spans

**Expected behavior**
2. subgraph trace spans should be contained within the parent router span, like it does for the Gateway in https://github.com/apollographql/supergraph-demo-fed2#tracing-with-open-telemetry

![image](https://user-images.githubusercontent.com/284840/144910235-038090d2-be4d-481a-8e4e-ed19ce79fd4f.png)

**Output**
![image](https://user-images.githubusercontent.com/284840/144910608-8f408a05-bd6d-43a1-8aba-ceeff68f9355.png)

**Desktop (please complete the following information):**
```
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

**Comment by o0Ignition0o** [comment]
Reproduced, I'll get back to you once I've zeroed in on what's going on.

**Comment by garypen** [comment]
I just tried reproducing this on my mac laptop and couldn't. All the spans appear to be correctly contained within their parent (see my screenshot). I am wondering what the first 600ms are doing, but that's perhaps a different problem...

![Screenshot 2022-01-07 at 16 26 54](https://user-images.githubusercontent.com/107218/148574658-ef7f7b2a-2905-48b8-a8c1-954425a50900.png)

I know we've done quite a bit of work on the Otel stuff since this was filed, so maybe one of the changes has fixed this? @prasek Could you try this on your machine and see if you can re-produce it?

**Comment by prasek** [comment]
@garypen @o0Ignition0o -- with router 0.1.0-alpha.3

![image](https://user-images.githubusercontent.com/284840/149204766-84358ddd-2db8-4d91-bef5-0a8f78f99e5c.png)

**Comment by o0Ignition0o** [comment]
worth mentioning we're working with https://github.com/apollographql/supergraph-demo here, i couldn't reproduce before, and it was because I was running checks against supergraph-demo-fed2

**Comment by o0Ignition0o** [comment]
Got pretty good results locally with https://github.com/apollographql/supergraph-demo-fed2/pull/89

I'll try to do the same in supergraph-demo as well

**Comment by prasek** [comment]
the above PRs have helped some, but the span skew issue remains after multiple `make smoke` operations are executed.

**Comment by prasek** [comment]
- With https://github.com/apollographql/supergraph-demo-fed2/pull/89

<img width="1884" alt="image" src="https://user-images.githubusercontent.com/284840/160460510-6c6fa150-b8e1-4f02-a9f8-46e00e82a522.png">

<img width="1890" alt="image" src="https://user-images.githubusercontent.com/284840/160460844-76fb2482-c7ef-4cf5-b561-0fc6e60d01c7.png">

**Comment by o0Ignition0o** [comment]
thanks, i ll keep investigating, I haven't reproduced this so far (running docker for mac 4.6.1 with the new fs feature) 
![image](https://user-images.githubusercontent.com/9465678/160462388-f72d614b-7413-4ea7-9210-bdebd49cf71d.png)

**Comment by prasek** [comment]
> I haven't reproduced this so far (running docker for mac 4.6.1 with the new fs feature)

Thanks @o0Ignition0o, with just the new Virtualization framework enabled this issue is no longer reproducing for me, so closing this out!

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/284840/160468820-994fa648-f203-46ce-b156-9b4e14b8589d.png">

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/284840/160469085-ffdb0c67-d81f-48b6-9f57-71d232dce624.png">
