### ISSUE TITLE
Router config: Wildcards in supergraph endpoint path do not longer work

### ISSUE THREAD

**Issue by pieterwillaert** [apollographql/router#2471]
since version 1.8
https://www.apollographql.com/docs/router/configuration/overview#endpoint-path

for example: When starting the application with this router config
```
supergraph:
  # The path for GraphQL execution
  # (Defaults to /)
  path: /*
```

this appears in the logs:
```
2023-01-25T11:55:24.877417Z  INFO healthcheck endpoint exposed at http://0.0.0.0:8088/health
2023-01-25T11:55:24.877519Z  INFO GraphQL endpoint exposed at http://127.0.0.1:4000/* 🚀
```

requests to http://127.0.0.1:4000 results in a http 404, the healthcheck works fine 

Also without the asterisk it work.

**Comment by bnjjj** [comment]
It has been introduced by the axum upgrade https://github.com/tokio-rs/axum/releases/tag/axum-v0.6.0 they introduced a breaking change which means it only matches on `test.com/` and not `test.com` if you provided `/*`. But in that specific case (`/*`)  it would make sense to also add the support to `test.com`. But if you're providing `/whatever/*` it doesn't make sense to apply that specific rule

I will open a PR for this

**Comment by pieterwillaert** [comment]
Thanks for the fast solution!
