### ISSUE TITLE
Running router with APOLLO_TELEMETRY_DISABLED=1 fails

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2478]
**Describe the bug**
Running router v1.9.0 with `APOLLO_TELEMETRY_DISABLED=1` (as per the [documentation](https://github.com/apollographql/router/blob/925d6b950587180605a62ddc805f6516ac1ce78d/docs/source/privacy.mdx)), fails with the following error:

```
error: one of the values isn't valid for an argument
```

**Comment by bnjjj** [comment]
It needs to be used with `true` or `false` instead of  `1` or `0`. I will update the documentation

**Comment by abernix** [comment]
@bnjjj Let's land the documentation fix for now, but can we change the implementation to support `1` and `0`?  It's critical that we do so because it's the pattern that `rover` uses.

**Comment by bnjjj** [comment]
Let's keep this issue open then

**Comment by abernix** [comment]
This should have been fixed by @nicholascioli's https://github.com/apollographql/router/pull/4549 in https://github.com/apollographql/router/releases/tag/v1.39.0.
