### ISSUE TITLE
"Error: no valid configuration was supplied" when APOLLO_TELEMETRY_DISABLED=1

### ISSUE THREAD

**Issue by andriihrachov** [apollographql/router#2492]
**Describe the bug**

When starting custom router binary with env "APOLLO_TELEMETRY_DISABLED=1"  (which is used for disabling telemetry for rover), router gives error

```
Error: no valid configuration was supplied
```

**To Reproduce**
1) Start apollo router with APOLLO_TELEMETRY_DISABLED=1
**Expected behavior**
No error

**Comment by bnjjj** [comment]
Linked to https://github.com/apollographql/router/issues/2478 and the solution is [here](https://github.com/apollographql/router/issues/2478#issuecomment-1404827108)
