### ISSUE TITLE
Response compression (gzip, deflate, br, whatever)

### ISSUE THREAD

**Issue by Mithras** [apollographql/router#251]
**Is your feature request related to a problem? Please describe.**
Large responses introduce noticeable lag when sent uncompressed.

**Describe the solution you'd like**
Compression natively supported for both client-router and router-subgraph communications.

**Describe alternatives you've considered**
For client-router I guess I can use a nginx side car container as a workaround but it's not ideal and will introduce unnecessary lag.
For router-subgraph I can probably make a hack to always compress responses from subgraphs but I'm not sure the router is capable of handling decompression.

**Comment by Mithras** [comment]
I think router is at the point when this is the only blocking issue for us.

- Router can't compress responses
  For example, if I send `Accept-Encoding: gzip, deflate, br`, I still get no `content-encoding` in response.
- Router can't decompress subgraph responses
  For example, if I add
  ```
  headers:
    all:
      - insert:
          name: Accept-Encoding
          value: gzip
  ```
  to get gzipped response from subgraphs, I get `apollo_router_core::query_planner: Fetch error: HTTP fetch failed from 'api': service 'api' response was malformed: service 'api' response was malformed: expected value at line 1 column 1`.

I understand that the Router is only `v0.1.0` and it's expected that certain features are not yet implemented but can you at least reply if it's something that will be added in future? For us lack of compression makes Router orders of magnitude slower than Gateway.

**Comment by bnjjj** [comment]
Hello @Mithras sorry for the delay, as we will reach `General Availability` in the next few days. After that we will consider implementing compression. It's coming, we're adding it in our backlog, thanks for creating the issue

**Comment by golfingal72** [comment]
Absolutely NECESSARY to have this feature before even attempting to use...  when will support for this be enabled?
