### ISSUE TITLE
Add a read-only mode for Automatic Persisted Queries

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2528]
APQ is generally used by the clients to pre register their queries at runtime, but it can be useful to pre register as a separate step, lock down the APQ cache and make it read only. That can effectively transform the router in a static API

**Comment by smyrick** [comment]
This is partially being worked on with the known operations and operation registry. This would still be a separate flow from APQ but one addition that has come up from customers is the ability to provide some manifest file that is APQ compliant to pre-populate all the Router caches.

Should this issue be split up to better document these individual and independent changes?
