### ISSUE TITLE
Router doesn't seem to gracefully handle in flight requests on shutdown

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2539]
**Describe the bug**
Router doesn't seem to gracefully handle in flight requests on shutdown.

**To Reproduce**
1. Start router (in dev or release mode)
2. Hit a resolver that has a 15s sleep in it
3. Stop the router
4. See the in flight request fail

**Expected behavior**
Request should go through, and the router should wait for a given period (would be nice if that matched the supergraph timeout configuration) for all requests to drain.

**Comment by Geal** [comment]
that sounds like a bug, yes. There should be a limit to the graceful shutdown of requests though, otherwise the router could block for a long time

**Comment by Meemaw** [comment]
I think normal behaviour is for the application server to stop accepting new tcp connections, and wait for the inflight requests to finish.

Its up to load balancer in front of the app server to stop sending traffic to the application that is about to be killed.

**Comment by marc-barry** [comment]
In an ideal case this is what happens:
* Apollo Router receives a signal to shutdown gracefully (i.e. `SIGQUIT` like in the Nginx case: http://nginx.org/en/docs/control.html).
* The router begins the shutdown process by failing a readiness check In general a service needs both readiness and health check to do things properly. Readiness is used for determining if traffic should be routed to the service and the health check is used to determine if the service is healthy.
* The router also stops accepting new connections but completes in-flight requests.
* A time duration of `X` seconds occurs before the router terminates.

I can't seem to determine how Apoolo Router behaves today but reading https://github.com/apollographql/router/blob/c6374ba3018a26014d68685de0d1124cbcf35b41/apollo-router/tests/common.rs#L266-L272 seems to indicate to me that the shutdown isn't graceful.

I think that Apollo Router could support a graceful shutdown by simply supporting a new signal (i.e. `SIGQUIT`) and then performing the actions above.

**Comment by Meemaw** [comment]
@Geal any update on this? Seems like a fairly important issue also for the Apollo GraphOS.

**Comment by Geal** [comment]
Yes, #2610 fixes it, it will go in the next release
