### ISSUE TITLE
The Kubernetes Helm Chart doesn't support pod priority setting (priorityClassName)

### ISSUE THREAD

**Issue by marc-barry** [apollographql/router#2543]
**Is your feature request related to a problem? Please describe.**
We run fairly large Kubernetes clusters on Google Cloud Platform GKE and make use of node autoscaling. Since all our other deployments have pod priorities set our Apollo Router pods get preempted (evicted) quite often and this leads to instability within our GraphQL routing setup.

**Describe the solution you'd like**
Kubernetes supports pod priority and preemption via https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/. This is done by creating `PriorityClass` objects and then assigning them to deployment object specifications with the `priorityClassName` parameter.

**Describe alternatives you've considered**
If a `priorityClassName` isn't set it defaults to a default value if set for the cluster or a value of zero. One can set a default value but then all non-set pods compete and this issue cannot be overcome.

**Additional context**
We considered writing our own deployment setup by copying all your Helm configuration and then maintaining it ourselves but it is better to contribute back to the community as anyone who runs Kubernetes clusters with multiple pods from different deployments will need this functionality.

**Comment by marc-barry** [comment]
I submitted https://github.com/apollographql/router/pull/2544 as a solution to the issue.

**Comment by garypen** [comment]
Seems like a nice suggestion. I'll look through your PR on Monday.
