### ISSUE TITLE
Tracing integration test is flaky

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2548]
Tracing integration tests are sometimes showing FTV1 attributes in span snapshots, this is causing the tests to fails sometimes.
Disable FTV1 in these tests.

**Comment by o0Ignition0o** [comment]
Do we have at least one snapshot || regression test that makes sure ftv1 support doesn't vanish? Or is this something to be added in https://github.com/apollographql/router/pull/2541 ?
