### ISSUE TITLE
 error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by dulguun0225** [apollographql/router#2555]
**Describe the bug**
When I run `./router --version` it gives me `./router: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory` error.

**To Reproduce**
Run this command:
```
/router --version
```

**Expected behavior**
Print the version

**Output**
```
./router: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Desktop (please complete the following information):**
 OS Info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

**Comment by garypen** [comment]
This seems relevant: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

Reading the details implies that it maybe/is an issue with ubuntu 22.04 packaging.
