### ISSUE TITLE
Context::Get does not return Err when key is not present

### ISSUE THREAD

**Issue by brenoos** [apollographql/router#2580]
**Describe the bug**
Not sure if this is a bug.
I build my own binary to create a plugin, the plugin works fine but when I try to get a value from the context, it does not return an Err when the key is not present like the code docs are saying 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/16320379/217651221-48af0749-07f6-43d9-a7d5-1856b1160e12.png">

So I am hitting Ok every time and then hitting None when the key is not present.

**To Reproduce**
1. Use the get method in a custom plugin or other place where you can use the context.
2. Use a dumb key that will not exist.
3. Match the result.
4. it will be Ok even if the key does not exist.

**Expected behavior**

At least to me makes more sense to receive an Err when the key is not present and None in the option if the key exists but the value is empty

**Output**
```
match request.context.get("not valid key") {
                Ok(option) => match option {
                    Some(_) => println!("ok"),
                    None => println!("value is empty"),
                },
                Err(_) => println!("key does not exist"),
            };
```

In this quick example here, my code is always printing `value is empty` and never reaches the Err to print "key does not exist"

<img width="755" alt="image" src="https://user-images.githubusercontent.com/16320379/217652580-b7b13e28-395e-4967-9714-911310b303ca.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 13.1

**Comment by bnjjj** [comment]
The documentation is wrong. It returns an error if we can't deserialize the context entry in the type you're asking for. And the `Option::None` means it doesn't exist in the context. We need to update the doc

**Comment by brenoos** [comment]
Thank you very much @bnjjj
