### ISSUE TITLE
Use of `__typename` affects presence of fragment spread data on interfaces

### ISSUE THREAD

**Issue by carldunham** [apollographql/router#2587]
**Describe the bug**

We are seeing a difference in behavior between Apollo Gateway and Router that looks like a bug in Router.
Not sure what the spec really should be, but we have these in the wild.

Given schema:

```
schema {
  query: Query
}

type Query {
  animal: Animal!
  dog: Dog!
}

interface Animal {
  id: String!
}

type Dog implements Animal {
  id: String!
  name: String!
}
```

Issuing the query

```
query dog {
  dog {
    ...on Animal {
      id
      # __typename
      ...on Dog {
        name
      }
    }
  }
}
```

Gives the result

```
{
  "data": {
    "dog": {
      "id": "123"
    }
  }
}
```

Uncomment `__typename` (or use Gateway as the server), and you get

```
{
  "data": {
    "dog": {
      "id": "123",
      "name": "Rover"
    }
  }
}
```

Also, changing the query to not nest will work:

```
query test {
  dog {
    ... on Animal {
      id
    }
    ... on Dog {
      name
    }
  }
}
```

**To Reproduce**
Implement the above schema in a Router service and run the given query(ies).

**Expected behavior**
We expect that the results from Router would be the same as from Gateway.

**Output**
See above.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: v1.10.3

**Additional context**

**Comment by Geal** [comment]
could you show the request and response coming in and out of the subgraph?

**Comment by carldunham** [comment]
Happy to. I've tried doing the experimental logger thing, but that didn't work for me. May have to wire shark it.

**Comment by carldunham** [comment]
So I need to edit this issue, after taking the time to actually isolate it, rather than deriving from production code.

This reproduces the issue: https://github.com/carldunham/apollo-router-2587

**Comment by carldunham** [comment]
OK, so I was able to get the logging to work. Router is definitely asking for (and getting) the right data from the subgraph, but seems to be dropping it for its response.

**Comment by carldunham** [comment]
Any updates here?

**Comment by BrynCooke** [comment]
Marking as high priority as it is a correctness issue.

**Comment by abernix** [comment]
Let's look at the reproduction provided above and see if this still exists or if it's been resolved with some of our query planner updates in recent versions

@carldunham: if you already know that it's resolved or **not** resolved, please let us know! 😄
