### ISSUE TITLE
Add tests for per-type metrics

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#2592]
As pointed out in https://github.com/apollographql/router/pull/2541#discussion_r1102077064, that PR add behavior not covered by existing tests:

* Computation of field execution weights
* Reporting of per-path error statistics

**Comment by SimonSapin** [comment]
@glasser, https://github.com/apollographql/router/pull/2541 fills `PathErrorStats` based on errors in the FTV1 protobuf from subgrahps. Should it instead be based on errors in the GraphQL supergraph response? (In order to include errors generated by the Router itself.) What about if subgraph errors are redacted in the supergraph response? https://www.apollographql.com/docs/router/configuration/subgraph-error-inclusion

**Comment by glasser** [comment]
https://apollograph.slack.com/archives/C02UX05LF4K/p1676312383438469?thread_ts=1676312199.238259&cid=C02UX05LF4K
