### ISSUE TITLE
Support for different deployments of one subgraph for apollo router

### ISSUE THREAD

**Issue by vishvajeet-patil** [apollographql/router#2620]
**Is your feature request related to a problem? Please describe.**
We want to support two different but identical in behaviour deployments of same subgraph (so they will have two different URLs). 
Is there a current way right now other than variants to support two different URLs for two deployments of subgraph?

**Describe the solution you'd like**
Possible way to route traffic to different endpoints of same subgraph on the basis of some marker like header or something

**Describe alternatives you've considered**
We thought of using variants to upload different URLs of subgraph (with identical schema) but that has multiple problems

- We need two separate deployment of router to achieve this
- We need to have entire super graph present in other variant as well. So even the subgraph that are not related about separate deployment use-case we need their schema pushed in new variant with same urls as in other variant.

**Additional context**

**Comment by Geal** [comment]
you could try a [rhai script](https://www.apollographql.com/docs/router/customizations/rhai#service-callbacks) that works at the subgraph level and updates the request URL depending on the header presence. Here's an example of access to the subgraph request: https://github.com/apollographql/router/blob/main/examples/subgraph-request-log/rhai/src/rhai_subgraph_request_log.rhai

**Comment by BrynCooke** [comment]
Closing as a rhai solution has been suggested
