### ISSUE TITLE
Ubuntu: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#2623]
This pinned issue shows you how to work around a temporary openssl related issue.
Ubuntu 22.XX doesn't provide libssl@1.1 anymore. The router will fail to start and show this error:

```bash
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

This happens because ubuntu only ships libssl 3.X:

```bash
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

A known workaround is to manually install libssl 1.1 as explained in this [stackoverflow issue](https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory) by following the steps outlined in the answer.

We will keep this issue open for discoverability purposes, until we completely move to rustls.

**Comment by mabuyo** [comment]
I came across this issue trying to host the router on Heroku! Heroku 22 uses Ubuntu 22.04 (which has the same issues as described above). I had to downgrade the [Heroku stack](https://devcenter.heroku.com/articles/stack#stack-support-details) from 22 to 20 using this command:

```
heroku stack:set heroku-20 -a <APP_NAME>
```

Hope it helps someone else!
