### ISSUE TITLE
Support external query planning preferences

### ISSUE THREAD

**Issue by paulpdaniels** [apollographql/router#2633]
**Is your feature request related to a problem? Please describe.**
When migrating fields between graphs, it is difficult to manage a partial rollout of changes at the subgraph level. The federation v2 specification introduced the `@override` directive to explicitly halt traffic to subgraphs other than the declaring one, but that can only be employed at the end of a transition. Prior to that the router determines opaquely which of the possible subgraphs to use when resolving a field if there are multiple possibilities. This makes it difficult to canary test a field migration by gradually increasing traffic to it.

**Describe the solution you'd like**
With the inclusion of [external service fetching](https://github.com/apollographql/router/pull/2229) it would be good if there was also a hook available that included at minimum the field path + list of possible resolutions for a field that has multiple possible sub-graph resolutions. Using this mechanism it should be possible to define a request+response path where an external service can return a preference hint or an outright override during the query planning stage in order to influence how the router constructs queries.

i.e. something like

```
// Request
{ "path": "user", "query": "mutation", "subgraphs": ["users", "auth"], "context": {...}}

// Response
// Re-ordered subgraph preferences
{ "path": "user", "subgraphs": ["auth", "users"]}
```

**Describe alternatives you've considered**

The alternative I considered was creating two separate graph deployments where one doesn't have the new field and the other with the field overridden (effectively forcing the desired query plan), then control traffic to each deployment via a traditional load balancer. This has the downside of being much more complex since it would involve substantial changes to our CI infrastructure to support multiple deployments with different graph variants.

**Comment by o0Ignition0o** [comment]
Hey,

We had a discussion around this, and it looks close to this issue https://github.com/apollographql/federation/issues/2190, which is being discussed. Do you mind me closing this so you can comment on the federation issue instead?

**Comment by paulpdaniels** [comment]
Yes we can move the discussion over there
