### ISSUE TITLE
Support for either router_service or client identification modification in Rhai

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#2635]
**Is your feature request related to a problem? Please describe.**

Many users may have current custom mappings in Apollo Gateway for [client awareness/identification](https://www.apollographql.com/docs/router/managed-federation/client-awareness/) which isn't possible to map directly within the router without either A) a sidecar application or proxy, or B) a custom Rust plugin for the router. 

This mapping can often be simplified to client X = client name Y, which is feasible to implement within Rhai as an [object map](https://rhai.rs/book/language/object-maps.html). 

**Describe the solution you'd like**

Given the above, there are two paths forward here: 

* Implement the `router_service` stage within Rhai, as this is would allow the setting of the related header values (as defined in the configuration) before being parsed
* Add a way to get/set the client name and version within Rhai, such that they could be set within the script (or gotten to help with other logic, e.g. avoiding certain logging scenarios for specific clients)

Implementing both would be potentially great, however the second may lead to oddities with regards to tracing and general usage reporting. The first would be a way to avoid some of those pitfalls. 

**Describe alternatives you've considered**

As mentioned earlier, sidecars could potentially address this, as would a custom plugin, but both are high-effort solutions to what should be a low-effort solve.

**Comment by garypen** [comment]
It is our wish to "Implement the router_service stage within Rhai," at some point. Just trying to find time to fit it on the schedule. Thanks for raising the issue.

**Comment by abernix** [comment]
https://github.com/apollographql/router/issues/2027 is pretty related, particularly now that JWT claim stuff is now accessible in Rhai as I understand it.  I wonder if we need still separate issues for these two things or not? (And if one should take precedence over the other, I don't have feelings yet).
