### ISSUE TITLE
Extension configuration and loading

### ISSUE THREAD

**Issue by Geal** [apollographql/router#266]
While working on #265, I came upon a design that could work for extensions.
First, we consider this organisation for configuration:
- an extension can be static (in tree), wasm (loaded by path) or DLL/Native/CABI (loaded by path)
- an extension is configured to be called on hook points (requestDidStart, etc), has capabilities (network, file access by path), and its own map String -> String of configuration options
- hook points can have a weight to indicate in which order they are run (not particularly attached to that idea though)

Then, to load extensions:
- we have one main `Extensions` structure created from the configuration
- on each hook point, we call it directly with some context. Example: `self.extensions.requestDidStart(request).await;`
- it is then tasked with looking up which `ExtensionFactory` to use there, and call it to get an `ExtensionInstance`
- the factory knows if it must create a new instance or get one from memory. It can have different instances per query (by looking up the trace id which is the same for an entire query)
- the call to the hook is instrumented by default, with the extension's name

**Comment by o0Ignition0o** [comment]
Closing this for now, because we have a rough idea of the first steps towards this. the rest will be discussed and will need design.
