### ISSUE TITLE
Rhai: expose json encode / decode functions

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#2663]
The rhai engine provides a lot of cool tools we could reexpose, one of them being the [json support utilities](https://rhai.rs/book/language/json.html)

Would it be a good idea for us to expose those?

**Comment by Geal** [comment]
>Internally, Engine::parse_json cheats by treating the JSON text as a Rhai script.

not sure about exposing that, maybe a proper call to serde_json would be better

**Comment by waqasraz** [comment]
We need that as well. because we are passing objects to the header as mentioned in this link
https://community.apollographql.com/t/stringify-in-rhai/5912

**Comment by kschrade** [comment]
We have a client that would need this feature to get parity to what they have today in their gateway. They currently pass a stringified JSON object in their header and cannot parse it.
