### ISSUE TITLE
CPU consumption increased between 1.8 and 1.10.2

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2694]
we got a report that when updating the router from 1.8 to 1.10.2, CPU usage got 4x higher. I'll see if I can have a reproduction I can paste here

**Comment by abernix** [comment]
1.10.2 definitely had some drops, but #2882 had a notable improvement in that regard.  We'll continue to improve our monitoring on these sorts of things, as we now have on our CI Status checks for each PR.
