### ISSUE TITLE
Personal data logged out in the json format

### ISSUE THREAD

**Issue by yanns** [apollographql/router#2695]
**Is your feature request related to a problem? Please describe.**
When using the jons format, the spans are also logged.
In some spans, the graphql variables and document are logged:
```
"span": {
    "apollo_private.field_level_instrumentation_ratio":0.01,
    "apollo_private.graphql.variables":"{\"sku\":\"\"}",
    "graphql.document":"fragment ..."
```

Those values could log some personal data.
As far as I've checked, `"apollo_private.graphql.variables"` does not seem to disclose any value.
But `"graphql.document"` can disclose some personal data:
Ex:
```
{
        users(
          where:"email=\"<removed by me>\"",
        ) {
```

**Describe the solution you'd like**
- either we can remove all values
- or we can configure what can be logged. I guess this is related to https://github.com/apollographql/router/issues/1840

**Describe alternatives you've considered**
No real alternative. The application should not log any personal data.
.

**Comment by Geal** [comment]
which spans are affected? How is telemetry configured, especially the `[send_variable_values](https://www.apollographql.com/docs/router/configuration/apollo-telemetry#send_variable_values)` option?

**Comment by yanns** [comment]
The name of the span is `"name":"supergraph"`.

**Comment by yanns** [comment]
We have not changed the `send_variable_values`, and variables seem fine.
I think that the issue is about `"graphql.document"` for now.

**Comment by Geal** [comment]
Ah, right. For data sent to Apollo, all the hardcoded variable values are removed, but probably not for other telemetry options.
Is it something you can fix on the client side? If queries contain hardcoded user data, then a separate query plan will have to be generated and stored for each of them, so you'll run in a lot of issues

**Comment by yanns** [comment]
Our API is used directly by all our customers.
We cannot change that.

In our current implementation, we remove all values on variables before logging the query.

**Comment by yanns** [comment]
I don't know the exact proportion, but it's quite important.
And the proportion is not very useful for us: we are not allowed to log any personal data.

Maybe a plugin could remove those values if they need with a [middleware](https://github.com/apollographql/router/issues/2661)?

**Comment by yanns** [comment]
For me, implementing https://github.com/apollographql/router/issues/1651 would be sufficient. Then I'd create my own json logger that would not log the query.

**Comment by abernix** [comment]
This also relates to work that is getting discussed in https://github.com/apollographql/router/issues/3226 in terms of toggling these options on and off.

**Comment by abernix** [comment]
@yanns Do you think we could close this in favor of #3226?

**Comment by yanns** [comment]
ok for me
