### ISSUE TITLE
Traits or Generics for the CachingMap struct

### ISSUE THREAD

**Issue by garypen** [apollographql/router#270]
**Describe the solution you'd like**
The current approach uses traits, but generics may be a superior solution.
@cecton observed in #244 that KISS is a good principle which favours generics over traits here.

**Describe alternatives you've considered**
Traits or Generics

**Additional context**
See #244 for more details.

**Comment by abernix** [comment]
It's plausible that the caching will be moved to a caching _layer_, which would lead us to revisit this.

**Comment by abernix** [comment]
We'll consider using Generics when we spend time on the caching (and cache abstraction) plan.
