### ISSUE TITLE
Reducing Cache Contention on the Cache Lock

### ISSUE THREAD

**Issue by garypen** [apollographql/router#272]
**Describe the solution you'd like**
The CachinMap implementation is tuned for high performance and scalability. However, possibilities for more performance exist.

**Describe alternatives you've considered**
It's possible to drop locks sooner on the slow path to maximise concurrency over the share cache. More detailed analysis is required to be sure that this is safe.

**Additional context**
See #244 for more details.

**Comment by Geal** [comment]
fixed by #275
