### ISSUE TITLE
Access to the pre-calculated GraphOS query signature hash

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#2728]
**Is your feature request related to a problem? Please describe.**
The query hash is used by Router for operation reporting and was previously available in the Gateway `context`. In the Router, the context no longer has this value and in Rhai scripts it is not on the request to add into the context manually. This requires manually hashing the `req.body.query` param which might actually be a different hash from the one used in operation reporting due to the deduping of operation signatures

**Describe the solution you'd like**
The GraphQL context in all locations has the query hash for the current operation which can then be consumed from either Rhai or coprocessors

**Describe alternatives you've considered**
We could just add it into the request processing in Rhai and have others add it to the context if they need it, but it is not available there either

**Additional context**
This info is available in the Gateway so this is a backwards compatibility issue

**Comment by abernix** [comment]
Are you referring to the straight SHA-256 of the exact operation, **or** the operation signature that we internally calculate via a normalization and hashing algorithm that's used for bucketing the operation into similar groups in Studio reporting?

Whichever it is, I'm curious **what** is trying to be accomplished with it?

**Comment by smyrick** [comment]
The customer is asking for access to the same hash that they can see in Studio logging, so yes, the internal operation signature via normalization. They want to log this in the Router so they can trace errors in their system to the operations and logs they can view in studio

**Comment by smyrick** [comment]
This is the query hash that is available today

https://www.apollographql.com/docs/graphos/metrics/operation-signatures/#logging-signatures-at-runtime

**Comment by grxy** [comment]
We (Gusto) also would like access to the hash used in the URL for the operations details page. We are hoping to be able to link directly from our internal metrics and log indexing tools to the Studio page so that engineers can easily see usage data, client data and versions, and more. If y'all decide to release this either directly in the router or simply share an overview of how the algorithm works like the above, either would be appreciated!
