### ISSUE TITLE
Release the caching functionality as a separate crate.

### ISSUE THREAD

**Issue by garypen** [apollographql/router#273]
**Describe the solution you'd like**
It would be good to externalise the caching functionality and release the crate independently from the router. This should only be done after other issues around caching are resolved to minimise interface churn.

**Describe alternatives you've considered**
Not releasing the crate means less opportunity for community contribution or shared benefits.

**Additional context**
See #244 for more details.

**Comment by cecton** [comment]
Did we consider replacing our entire implementation with [cache_loader_async](https://crates.io/crates/cache_loader_async)?

It seems to fit our entire use case:

> The LoadingCache will first try to look up the result in an internal HashMap and if it's not found and there's no load ongoing, it will fire the load request and queue any other get requests until the load request finishes.

> You can use a simple pre-built LRU cache from the lru-rs crate by enabling the lru-cache feature.

> To implement an own cache backing, simply implement the public CacheBacking trait from the backing mod.

I can't see this mentioned in #244 so I assumed this has been discussed verbally? Can we explain the reasons why this option has been rejected here in this ticket? (#244 is closed and this issue (#273) is close enough to the subject.)

**Comment by Geal** [comment]
I was not aware that this crate existed.
Looking at the design, it sets up an async API using a channel sending to a [spawned task](https://github.com/ZeroTwo-Bot/cache-loader-async-rs/blob/master/src/internal_cache.rs#L55-L77) that handles cache queries one by one. There's a way to [subscribe to an update of a value](https://github.com/ZeroTwo-Bot/cache-loader-async-rs/blob/master/src/internal_cache.rs#L134-L151).

I see a few issues, most of them could be fixed:
- [channel size is hardcoded](https://github.com/ZeroTwo-Bot/cache-loader-async-rs/blob/master/src/cache_api.rs#L180), 128 looks low enough that we could get some contention, especially considering that [some actions spawn more tasks sending more channel messages](https://github.com/ZeroTwo-Bot/cache-loader-async-rs/blob/master/src/internal_cache.rs#L140-L143)
- there is no way in the API to ask for a value, run an async function to generate that value, and if the value is already generating, subscribe on the result (subscription in the update function is just there to wait for the previous update to apply the new one). This is the main reason for the router's cache implementation

I think we should wait a bit before committing to using an external crate like that, and first think about the features we want from a cache, considering we might do request or entity caching in the future

**Comment by cecton** [comment]
> I think we should wait a bit before committing to using an external crate like that, and first think about the features we want from a cache, considering we might do request or entity caching in the future

I would have thought it makes more sense the other way around: first try to use what exists and wait before creating a new wheel? Especially if the concerns are addressable:

> channel size is hardcoded, 128 looks low enough that we could get some contention, especially considering that some actions spawn more tasks sending more channel messages

We can make a PR.

> the update functions assume that the loading function is synchronous

We only have synchronous loading function afaik or use use spawn_blocking.

> there is no way in the API to ask for a value, run an async function to generate that value, and if the value is already generating, subscribe on the result (subscription in the update function is just there to wait for the previous update to apply the new one). This is the main reason for the router's cache implementation

That is incorrect. According to their doc it does that:

> The LoadingCache will first try to look up the result in an internal HashMap and if it's not found and there's no load ongoing, it will fire the load request and queue any other get requests until the load request finishes.

**Comment by Geal** [comment]
> I would have thought it makes more sense the other way around: first try to use what exists and wait before creating a new wheel?
we could apply the same reasoning and keep what we have now, it works for what we currently need. That's why I'd like for us to think about what we will need from a cache implementation for our future needs.
Personally, I think caching will be such a core feature of the router, and could have such specific requirements for graphql, that we should fully understand and control the caching implementation. So I am wary of taking one of the few off the shelf solutions we can find on crates.io. I might be wrong though, so that's why we need to align on the requirements first.

> We only have synchronous loading function afaik or use use spawn_blocking.
the [CacheResolver](https://github.com/apollographql/router/blob/04f14eb8ecc96061bcf02577b14b0a489c8a0518/apollo-router-core/src/traits.rs#L12) is async. For now the only use we have for this is the query planner, which is in a `spawn_blocking` task, but when we implement whole request caching, we will need an async resolver.

Also, the [cache backing API is sync](https://docs.rs/cache_loader_async/0.1.2/cache_loader_async/backing/trait.CacheBacking.html), which will not work if we would like to store cache entries in an external database (useful if we want coherent caching when running multiple routers). That's fixable too.

> That is incorrect. According to their doc it does that:
>
> > The LoadingCache will first try to look up the result in an internal HashMap and if it's not found and there's no load ongoing, > > it will fire the load request and queue any other get requests until the load request finishes.

right, I was only looking at the update function, and missed the loader parameter, which actually returns a future, while the `update_fn` parameter is synchronous.
There's probably an operation ordering mistake in there, but fixable too.

I'm worried that we would end up rewriting a large part of the crate for our needs though :weary:

**Comment by cecton** [comment]
> when we implement whole request caching, we will need an async resolver

A whole request caching? For now we have caching for query planner but also for the query parser. What is the whole request caching? Like caching the `PreparedQuery`?

> I'm worried that we would end up rewriting a large part of the crate for our needs though weary

I'm not against writing our own stuff if our implementation is *that* different. It's totally a valid concern :+1:

**Comment by garypen** [comment]
> Did we consider replacing our entire implementation with [cache_loader_async](https://crates.io/crates/cache_loader_async)?
> 
> It seems to fit our entire use case:
> 
> > The LoadingCache will first try to look up the result in an internal HashMap and if it's not found and there's no load ongoing, it will fire the load request and queue any other get requests until the load request finishes.
> 
> > You can use a simple pre-built LRU cache from the lru-rs crate by enabling the lru-cache feature.
> 
> > To implement an own cache backing, simply implement the public CacheBacking trait from the backing mod.
> 
> I can't see this mentioned in #244 so I assumed this has been discussed verbally? Can we explain the reasons why this option has been rejected here in this ticket? (#244 is closed and this issue (#273) is close enough to the subject.)

This crate wasn't evaluated. The discussion about crate alternatives was on the original issue: #42 .

**Comment by cecton** [comment]
> This crate wasn't evaluated. The discussion about crate alternatives was on the original issue: #42 .

I guess we missed it last time. I propose we evaluate this crate now before we make a separate crate for our caching implementation.

**Comment by o0Ignition0o** [comment]
++ this has come up in #433, we need to have a discussion about cache_loader_async that would ease our trait / cache structures layout

**Comment by abernix** [comment]
We've talked about this a fair bit at this point and feel that, ultimately, our caching needs are going to be quite specific and highly intertwined with a lot of our machinery in a way that will make it challenging to abstract this out.  Closing, but we can reconsider if the opportunity presents itself again.
