### ISSUE TITLE
Remove misleading embedded example

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2737]
The embedded example is a throwback to early days of the Router where distribution as middleware was considered viable.
As development has progressed this approach has become obsolete as we have baked some of our functionality into the webserver layer.
In addition, the entire example uses the `TestHarness` which is designed for testing rather than production traffic.

**Comment by Tehnix** [comment]
>As development has progressed this approach has become obsolete as we have baked some of our functionality into the webserver layer.

@BrynCooke is there any alternative from the embedded example, or is obsolete referring to the thought having been completely abandoned?

(for context: looking to use the Rust router in AWS Lambda to avoid the JS based one)
