### ISSUE TITLE
Should we use a faster hasher in CachingMap

### ISSUE THREAD

**Issue by garypen** [apollographql/router#274]
**Describe the solution you'd like**
We are using the Lru crate for LRU caching. We use the default hasher. Should we consider a faster hasher?

**Describe alternatives you've considered**
None yet.

**Additional context**
See #244 for more details.

**Comment by Geal** [comment]
Copying here the strong requirement that any hasher we use must be safe against hash flooding attacks:

> note that hashing functions where the key is controlled by client requests can lead to [hash flooding attacks](https://v8.dev/blog/hash-flooding) where keys are generated specifically to create a lot of collisions and ultilmately DoS the server. It's rediscovered every 2 years in every web platform (php, ruby, js...) and it's the reason algorithms like SipHash were developed.
If we end up using a hashmap like structure, I strongly advise that we use a safe hashing function, since that will be internet facing code

**Comment by abernix** [comment]
If this comes up as a flag in performance conversations (e.g., concretely, with data) then let's go ahead and consider a faster hashing impl.
