### ISSUE TITLE
Expose Router Response Errors in supergraph_response field for plugin

### ISSUE THREAD

**Issue by krutikavk** [apollographql/router#2772]
An additional field in `supergraph_response` to log errors not generated by subgraph could be useful.

**Context**
We are working on a plugin that logs a field `hasErrors` in case there are errors in `supergraph_response`. Router response from subgraph that is not reachable returns the following:

Response status: 200
Response:  
```
{
	"data": null,
	"errors": [
		{
			"message": "HTTP fetch failed from 'redacted': redacted",
			"path": [],
			"extensions": {
				"type": "SubrequestHttpError",
				"service": "test-subgraph",
				"reason": "HTTP fetch failed from 'redacted': redacted"
			}
		}
	]
}
```

`errors` field in `supergraph_response` is available as a stream inside response object. 

**Suggested Solution** 
Errors that are not generated from a subgraph could be available as a separate field:  
```
{
	"data": null,
        "routerErrors": {
		{
			"message": "HTTP fetch failed from 'test-subgraph': HTTP fetch failed from 'redacted': redacted",
			"path": [],
			"extensions": {
				"type": "SubrequestHttpError",
				"service": "test-subgraph",
				"reason": "HTTP fetch failed from 'redacted': redacted"
			}
         }
         "errors": []
}
```

This can be a useful case to identify errors in `supergraph_response` without the need to access a response stream for responses with status code 200. For example, subgraph service is not reachable, subgraph service timed out, etc.

**Comment by o0Ignition0o** [comment]
Hi,

I think what you would like to achieve could be done at the `subgraph_service` level. You would be in a situation where you don't need to have access to the body stream, and you could put what you need in the `context`.

You would then be able to retrieve it at the supergraph or router service level to do bespoke logic (like add it to the `extensions` as @bnjjj mentionned.

I'm going to close this issue, but feel free to reopen it if you'd like to add more color or if you're still stuck!
