### ISSUE TITLE
Rhai: Allow log_* functions to state log type in addition to message

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#2777]
**Is your feature request related to a problem? Please describe.**

Users often need to implement custom logging for instrumentation, and Rhai serves as a good place for much of this logic. The router currently supports different log functions, accepting a single "out" argument; e.g. `log_info("this is the out attribute");` which will output as (using the JSON option): 

```json
{"timestamp":"2023-03-15T12:37:34.266317Z","level":"INFO","message":"rhai_info","out":"this is the out attribute","span":{"apollo_private.http.request_headers":"{}","client.name":"test","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"2f8dc07325619af95b1f61effcd7a9f2","name":"router"},"spans":[{"http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"SERVER","name":"request"},{"apollo_private.http.request_headers":"{}","client.name":"test","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"2f8dc07325619af95b1f61effcd7a9f2","name":"router"}]}
```

Note that the `message` within the log states `rhai_info`- the other log commands follow a similar naming convention. 

While this is largely okay, and would be indicative for actual Rhai errors, there's often a need to group logs by a specific log attribute. 

**Describe the solution you'd like**

An ideal solution would be the ability to _also_ pass the `message` attribute as an argument vs. the standard `rhai_*` string. 

This would appear as: 

`log_info("this is the out attribute", "subgraph-a");` 

And would output as:

```json
{"timestamp":"2023-03-15T12:37:34.266317Z","level":"INFO","message":"subgraph-a","out":"this is the out attribute","span":{"apollo_private.http.request_headers":"{}","client.name":"test","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"2f8dc07325619af95b1f61effcd7a9f2","name":"router"},"spans":[{"http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"SERVER","name":"request"},{"apollo_private.http.request_headers":"{}","client.name":"test","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"2f8dc07325619af95b1f61effcd7a9f2","name":"router"}]}
```

The only difference being the `message` attribute as noted. 

**Describe alternatives you've considered**

You can provide that additional context with JSON parsing the `out` attribute and using a object map (e.g. `log_info(#{message:"message", type: "subgraph-a"});`

which outputs: 

```json
{"timestamp":"2023-03-15T12:43:32.747654Z","level":"INFO","message":"rhai_info","out":"#{\"message\": \"message\", \"type\": \"subgraph-a\"}","span":{"apollo_private.http.request_headers":"{}","client.name":"test","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"87dd349dfc5e4eac980232ca74867551","name":"router"},"spans":[{"http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"SERVER","name":"request"},{"apollo_private.http.request_headers":"{}","client.name":"test","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"87dd349dfc5e4eac980232ca74867551","name":"router"}]}
```

Which would require some custom transformation to remove the `#` from the string, but otherwise is a normal JSON string.

**Comment by abernix** [comment]
I'll open this issue back up because we reverted this in https://github.com/apollographql/router/pull/2840, just prior to the 1.13.0 release, due to some API considerations we wanted to make.

**Comment by garypen** [comment]
Previous discussion suggested that what we'd like is:

JSON FORMAT

{"timestamp":"2023-03-23T11:52:13.838160Z","level":"INFO","message":"<my message>","target":"my_script.rhai"}

What we get:

{"timestamp":"2023-04-19T07:46:15.483358Z","level":"INFO","message":"rhai_info","out":"this is info level log message","span":{"apollo_private.http.request_headers":"{}","client.name":"manual","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"55eb21f1e0c02c658c3c4c69f0e4894d","name":"router"},"spans":[{"http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"SERVER","name":"request"},{"apollo_private.http.request_headers":"{}","client.name":"manual","client.version":"","http.flavor":"HTTP/1.1","http.method":"POST","http.route":"/","otel.kind":"INTERNAL","trace_id":"55eb21f1e0c02c658c3c4c69f0e4894d","name":"router"}]}

If I strip out the span details, then we are left with:

{"timestamp":"2023-04-19T07:46:15.483358Z","level":"INFO","message":"rhai_info","out":"this is info level log message"}

So, required transformation:

Make the content of `out` be the content of `message`.
Remove the `out` field.
Add a `target` field which documents the name of the executing `rhai` script.

**Comment by garypen** [comment]
With the same input, this is what #2975  produces :

{"timestamp":"2023-04-19T08:39:22.114846Z","level":"INFO","message":"this is info level log message","target":"src/rhai_logging.rhai"}
