### ISSUE TITLE
Unable to deploy helm chart

### ISSUE THREAD

**Issue by flyboarder** [apollographql/router#2787]
**Describe the bug**
Unable to deploy router 1.12.1 using helm. Confirmed broken in `1.11.0` confirmed working in `1.10.3`.

**To Reproduce**
Run helm install command from documentation
```
helm install --set router.configuration.telemetry.metrics.prometheus.enabled=true --set managedFederation.apiKey="REDACTED" --set managedFederation.graphRef="REDACTED" --create-namespace --namespace router-deploy router-test oci://ghcr.io/apollographql/helm-charts/router --version 1.12.1 --values router/values.yaml
```

**Expected behavior**
Chart installs successfully.

**Output**
```
Pulled: ghcr.io/apollographql/helm-charts/router:1.12.1
Digest: sha256:cbd817f08e9dab86c4eb94477ba26848cb4801a74302cbeaf5039c4d3d0ec56b
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe.httpGet): unknown field "initialDelaySeconds" in io.k8s.api.core.v1.HTTPGetAction, ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "initialDelaySeconds" in io.k8s.api.core.v1.HTTPGetAction]
```

**Desktop (please complete the following information):**
 - OS: unknown
 - Version: unknown

**Additional context**

**Comment by flyboarder** [comment]
This seems to be caused by a spacing issue in the configuration file, patched with:
https://github.com/apollographql/router/pull/2788

**Comment by vtoolme** [comment]
I've also encountered the same problem. It seems to be an indentation issue, as mentioned in the Kubernetes documentation. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request
