### ISSUE TITLE
Uplink consistency logic needs improving

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2794]
Currently the interaction with uplink has two modes of operation.

Fallback: The default, uses `https://uplink.api.apollographql.com/graphql` and then `https://aws.uplink.api.apollographql.com/graphql`

Round robin: If `APOLLO_UPLINK_ENDPOINTS` is set then it round robins between URLs

Uplink endpoints are not strongly consistent, so when using round robin there is a high chance that the router will flip flop, especially if uplink is having problems. This could also affect fallback strategy to a lesser degree.

Instead the router always poll all endpoints and should discard any message that is older than the latest that it has received. As long as each message has a monotonic increasing identifier then it should improve reliability.

**Comment by abernix** [comment]
Let's consider https://github.com/apollographql/router/issues/1282 in this.

**Comment by BrynCooke** [comment]
We probably need to have a higher level discussion around HA for uplink. It seems like several users are trying to use `APOLLO_UPLINK_ENDPOINTS` to have a local cache of uplink responses, but this approach probably won't work the way they expect due to the way that the last known ID is passed in with each request.

**Comment by BrynCooke** [comment]
Reopening, as we need to tweak the logic further.
