### ISSUE TITLE
Tracing: write down what we have learned when investigating

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#28]
We have found out a couple of guidelines, that I've jotted down in a notes file.

I would like to tidy them and share the knowledge to avoid more tracing related bugs

`still waiting for the final doc on how to properly apply tracing, otherwise LGTM`

**Comment by Geal** [comment]
@o0Ignition0o friendly ping on this :wink:

**Comment by o0Ignition0o** [comment]
Oh nice one, Marking it in my todo ^^
