### ISSUE TITLE
Coprocessors cannot extract method and path from RouterRequest, status code from RouterResponse

### ISSUE THREAD

**Issue by pcarrier** [apollographql/router#2861]
**Describe the solution you'd like**
When my coprocessor receives:
- a `RouterRequest` event, it can determine that the request has the method `GET/POST/…` and the path `/graphql?hello`
- a `RouterResponse` event, it can determine the HTTP status code.

**Describe alternatives you've considered**
None.

**Additional context**
This is a requirement of apilog at Apollo.

**Comment by o0Ignition0o** [comment]
fixed by #2863
