### ISSUE TITLE
improve docs.rs/crates.io documentation for rust plugins

### ISSUE THREAD

**Issue by abernix** [apollographql/router#2868]
A great deal of our Rust plugin API documentation currently lives on [docs.rs/apollo-router](https://docs.rs/apollo-router), as is common convention with Rust libraries: unsurprisingly, as it's automatically driven by the code and comments within the code.

Since it's the common convention, it also means there's an excellent developer experience which includes quickly accessing that documentation from the developer's IDE, excellent syntax highlighting and navigation tooling — including quick-jumping to relevant documentation for structs/impls/fns/etc., which in many results in documentation appearing directly in the IDE.

However, we **also have _some_ documentation** within our Apollo [Native plugin documentation](https://www.apollographql.com/docs/router/customizations/native), including definitions of how the plugin life-cycles are organized.  While our Apollo documentation is overall incredible, the experience as it stands right now tends to leave developers "crossing the chasm" when it comes to implementing native Rust plugins and it leaves us updating documentation in two places rather than letting the documentation be generated from the code itself, as is the case from Rust docs.

We should make the Rust docs on docs.rs inclusive of the information we currently have on our in our own documentation, move it to a centralized place so developers can have the best of both worlds in a single place, and probably setup some stepping stones in our own documentation that allows us to send folks to those docs with the right context (and similarly, link back to our docs from docs.rs, as appropriate)

**Comment by BrynCooke** [comment]
While we do think it would be a great docs improvement, we don't have the bandwidth to take this on right now, and we need to pull this into a larger API improvement effort.
