### ISSUE TITLE
502 Errors from Load balancer while reloading schema

### ISSUE THREAD

**Issue by voslartomas** [apollographql/router#2901]
**Describe the bug**
We can still see some 502 errors coming from Router and while testing locally I found out that it happens also when reloading graph.

This is log from router
`{"timestamp":"2023-03-28T11:41:20.549488Z","level":"INFO","message":"reload complete"}`

And below is screenshot from browser, which shows that some requests failed at this time. I can also see 502 errors in our production, it happens around restarts of pods most of the time. Using latest router (v1.13.0)

(Also this was catched while running in --dev mode, but can see occasionally 502 errors from production and it seems while reloading schema or restarting pods).

<img width="701" alt="Screenshot 2023-03-28 at 13 45 51" src="https://user-images.githubusercontent.com/1945040/229755743-a4d42221-708a-441e-9aaf-3b6aeba33b5d.png">

Example from production, on the left there is graph with deploys, red means new change and reload of router and on the right there are alb errors.
<img width="1335" alt="Screenshot 2023-04-04 at 17 25 07" src="https://user-images.githubusercontent.com/1945040/229841453-10d3b368-01d7-4542-b338-bddca4c73702.png">

**Comment by Geal** [comment]
I don't think the 502 error can come from the router, there's nothing in the code to generate them. Is there another component in the middle?

**Comment by voslartomas** [comment]
Well it does not directly comes from the router, but it means that router is not accessible for brief of the moment. This comes from load balancer, which is trying to call router.

**Comment by abernix** [comment]
And also, if you're still seeing it, do you think https://github.com/apollographql/router/pull/3557 could help? Would you mind trying our the prerelease version?

**Comment by abernix** [comment]
We think that https://github.com/apollographql/router/releases/tag/v1.27.0 would be a good option for you to explore.  We'll close this since we haven't heard back from you, but happy to re-open if the problem persists.  Thanks!
