### ISSUE TITLE
Serving our own Custom Playground or Customizing Apollo Sandbox 

### ISSUE THREAD

**Issue by jplee0324** [apollographql/router#2915]
**Is your feature request related to a problem? Please describe.**
Our GraphQL implementation that we are placing behind the Apollo Router is currently using SSE for subscriptions. Because of this we're unable to use Apollo Sandbox since it only supports WS and would like to host our own custom Playground instead

**Describe the solution you'd like**
Is there an existing path for hosting our own custom landing page/sandbox? Or even making custom modifications to the Apollo Sandbox?

**Additional context**
I looked into using [web_endpoints()](https://github.com/apollographql/router/blob/e425022359f52cb6d783b6d0626ebc16fa63d30d/apollo-router/src/plugin/mod.rs#L276) for rhai scripts, but it seems like this would have to be done using coprocessors or creating our own native plugin.

**Comment by abernix** [comment]
We don't intend on supporting this in the Router right now, though you could submit a request for Subscriptions over SSE to be supported in Explorer [on this repo](https://github.com/apollographql/apollo-studio-community), if you're so inclined.

You could still setup your own custom `web_endpoints` as you noted, but you could not do that with Rhai or Co-processors.  You would have to use your own native plugin for now.  As another alternative, if you didn't want to write the Rust plugin, you could put a proxy in front of the Router that looks for the appropriate `accept` HTTP header and routes to a different webserver that serves your own custom homepage.  We don't have plans to change this right now.

Hope this helps!
