### ISSUE TITLE
chore: write a test to validate all YAML configuration in `./examples`

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/router#2932]
currently, it is possible to make changes to a YAML file in `./examples/**/*.yaml` that do not conform to the config schema.

I propose adding a test `all_examples_are_valid_router_configuration` that iterates over `./examples`, looks for `.yaml` or `.yml` files, parse them to a `serde_json::Value`, and pass them to `setup_router_and_registry`.

**Comment by abernix** [comment]
I love this suggestion.  We even validate our documentation examples today, but we apparently don't validate those YAML files!
