### ISSUE TITLE
APQ system should reject a query if its sha256Hash doesn't match

### ISSUE THREAD

**Issue by vreon** [apollographql/router#2948]
**Describe the bug**

The APQ docs for Apollo Server [state](https://www.apollographql.com/docs/apollo-server/performance/apq/#command-line-testing):

> The hash you provide _must_ be the exact SHA-256 hash of the query string. If it isn't, Apollo Server returns an error.

Bearing in mind that Apollo Server is not Apollo Router, I'd expect the same behavior from Router. However, Router only logs a warning in this situation, and allows the query to execute.

https://github.com/apollographql/router/blob/8d6f69d8266584f03474d817ac485faa2a5b8b97/apollo-router/src/services/layers/apq.rs#L83

**To Reproduce**
1. Issue a query to any Router that has APQ enabled, but specify an invalid sha256Hash. Example:

    ```sh
    curl --get https://www.example.com \
        --header "Content-Type: application/json" \
        --data-urlencode 'query={ viewer { username } }' \
        --data-urlencode 'extensions={"persistedQuery":{"version":1,"sha256Hash":"banana"}}'
    ```
2. Router will log a warning, but executes the query anyway and responds with the result.

**Expected behavior**

Router should reject the query with an error message/code, perhaps `PERSISTED_QUERY_NOT_FOUND`.

**Output**
n/a

**Desktop**
n/a

**Additional context**

In lieu of a good solution for query cost analysis, I wanted to use a Rhai script to create an allowlist of query hashes, similar to the request in #2528, but since Router permits queries that don't match the sha256Hash, this approach won't work.

<details>
  <summary>Expand to show the Rhai script</summary>

```rhai
let allowedQuerySha256Hashes = #{
    b0455b0dbfe6f76a7603e17cb9f0079fc6fc0286af0254a95462a06fa743757f: (),
    // ...
};

fn supergraph_service(service) {
    const request_callback = Fn("process_request");
    map_request(service, request_callback);
}

fn process_request(request) {
    if
        request.body.extensions == () ||
        request.body.extensions.persistedQuery == () ||
        request.body.extensions.persistedQuery.version != 1 ||
        !allowedQuerySha256Hashes.contains(request.body.extensions.persistedQuery.sha256Hash)
    {
        throw #{
            status: 403,
            body: #{
                errors: [#{
                    message: "Forbidden",
                    extensions: #{
                        code: "FORBIDDEN"
                    }
                }]
            }
        };
    }
}
```

</details>

**Comment by o0Ignition0o** [comment]
Hey, thanks for raising this issue! I'm currently updating the code, but I'm not sure `PERSISTED_QUERY_NOT_FOUND` is appropriate here. `PERSISTED_QUERY_SHA_MISSMATCH` could be more accurate imo.

**Comment by vreon** [comment]
Thanks @o0Ignition0o! That sounds great to me, I just wasn't sure if there was a need to stick to the existing error codes.
