### ISSUE TITLE
Float values are being modified by router in the response

### ISSUE THREAD

**Issue by nathanmarcos** [apollographql/router#2951]
**Describe the bug**
This problem was noticed during the migration from Gateway to Router, the response body was supposed to be exact the same when in fact there were differences. Float values seem to be facing a rounding issues when flowing through router.

**To Reproduce**
Given the following subgraph:
```js
import { ApolloServer } from '@apollo/server';
import { startStandaloneServer } from '@apollo/server/standalone';
import gql from 'graphql-tag';
import { buildSubgraphSchema } from '@apollo/subgraph';

const typeDefs = gql`
  extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

  type Query {
    floats: [Float]
  }
`;

const resolvers = {
  Query: {
    floats() {
      return [
        -1.8134499788284302,
        107.60917663574219,
        39.926090240478516
      ];
    },
  },
};

const server = new ApolloServer({
  schema: buildSubgraphSchema({ typeDefs, resolvers }),
});

const { url } = await startStandaloneServer(server);
console.log(`🚀  Server ready at ${url}`);
```

Start a federated session with rover:
```sh
rover dev --name floats --url http://localhost:4000
```

Head to router sandbox at `http://localhost:3000` and shoot the following query:
```gql
query ExampleFloatsIssue {
  floats
}
```

The response will look like this:
```json
{
  "data": {
    "floats": [
      -1.8134499788284304,
      107.6091766357422,
      39.92609024047851
    ]
  }
}
```

**Expected behavior**
When shooting the exact same query directly to the subgraph sandbox at `http://localhost:4000`, you get the correct response values:
```json
{
  "data": {
    "floats": [
      -1.8134499788284302,
      107.60917663574219,
      39.926090240478516
    ]
  }
}
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Ventura 13.3.1

**Comment by liangchunn** [comment]
My suspicion for this issue is that `serde_json` is deserializing the JSON value into the type `serde_json::Number` which modifies the precision.

Enabling the feature `arbitrary_precision` for `serde_json` solves this problem (at least in my test case):
```toml
serde_json = { version = "1", features = ["arbitrary_precision"] }
```

### Example

```rs
// main.rs
use serde_json::Number;

fn main() {
    let data = r#"[-1.8134499788284302, 107.60917663574219, 39.926090240478516]"#;
    println!("raw: {data}");
    let deserialized = serde_json::from_str::<Vec<Number>>(&data).expect("failed to deserialize");
    println!("deserialized(raw): {deserialized:?}");
    let serialized = serde_json::to_string(&deserialized).unwrap();
    println!("serialize(deserialized(raw)): {serialized}");
}
```

#### Output without `arbitrary_precision`
```
raw: [-1.8134499788284302, 107.60917663574219, 39.926090240478516]
deserialized(raw): [Number(-1.8134499788284304), Number(107.6091766357422), Number(39.92609024047851)]
serialize(deserialized(raw)): [-1.8134499788284304,107.6091766357422,39.92609024047851]
```

#### Output with `arbitrary_precision`
```
raw: [-1.8134499788284302, 107.60917663574219, 39.926090240478516]
deserialized(raw): [Number(-1.8134499788284302), Number(107.60917663574219), Number(39.926090240478516)]
serialize(deserialized(raw)): [-1.8134499788284302,107.60917663574219,39.926090240478516]
````

**Comment by o0Ignition0o** [comment]
Hi, thanks for opening this issue!

I just had an other look at the [spec section around floats](https://spec.graphql.org/October2021/#sec-Float) which mentions:

```
The Float scalar type represents signed double-precision finite values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point).

Response formats that support an appropriate double-precision number type should use that type to represent this scalar.
```

I think your investigation is correct, because the numbers you mentioned cannot be represented with a double precision finite value, which leads me to believe this is why you're noticing rounding errors.

Do you happen to know what precision was used to create the values in the first place?

**Comment by nathanmarcos** [comment]
Hi @o0Ignition0o , thanks for the quick reply!

These values were created by a Kotlin code using the method `.toDouble()` on a `String`.

According to the docs it uses [double-precision 64-bit IEEE 754](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-double/#double).

Here is an example of the Kotlin code:

```kotlin
fun main() {
    println("-1.8134499788284302".toDouble())
    println("107.60917663574219".toDouble())
    println("39.926090240478516".toDouble())
}
```

You can execute it in the playground: https://pl.kotl.in/3YvDh9Xkf

**Comment by Geal** [comment]
serde_json's `Number` should already support double precision: https://docs.rs/serde_json/latest/src/serde_json/number.rs.html#33
And considering the binary representation:

-1.8134499788284302 -> 0xBFFD03E420000000
-1.8134499788284304 -> 0xBFFD03E420000001
107.60917663574219 -> 0x405AE6FCC0000000
107.6091766357422 -> 0x405AE6FCC0000001

I might be more inclined to look for a bug in serde-json than introducing arbitrary_precision here

**Comment by garypen** [comment]
I did some investigating and concur that the issue arises within serde_json when deserializing `Number` to `f64`.

I wrote up a test program and found that the `float_roundtrip` [feature](https://docs.rs/crate/serde_json/latest/features) may be sufficient for our needs. Float parsing is slower, perhaps 2x slower, but should provide the required levels of accuracy and with less impact than enabling `arbitrary_precision`.

#### Output with `float_roundtrip`
```
raw: [-1.8134499788284302, 107.60917663574219, 39.926090240478516]
deserialized(raw): [Number(-1.8134499788284302), Number(107.60917663574219), Number(39.926090240478516)]
serialize(deserialized(raw)): [-1.8134499788284302,107.60917663574219,39.926090240478516]
```

**Comment by garypen** [comment]
I verified that `float_roundtrip` is working as required with a router as follows:

1.  Take the provided `floats` subgraph example and run the subgraph
2.  Run: `rover dev --url http://localhost:4000/ --name floats` and verify that the incorrect values are returned.
3. Build a new router with the serde_json feature `float_roundtrip` enabled.
4. Replace the router in ~/.rover/bin/router-1.22.0 with my debug build router
5. re-run the rover command and verify that the correct values are returned.
