### ISSUE TITLE
OTLP HTTP silently swallows errors

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2959]
This has already been fixed upstream: https://github.com/open-telemetry/opentelemetry-rust/pull/945
And will be closed when we are able to upgrade to 0.19

**Comment by BrynCooke** [comment]
This if fixed in otel 0.19

**Comment by o0Ignition0o** [comment]
Reopening the issue since we have to revert the upgrade until they release a patch. See #3242
