### ISSUE TITLE
Router v1.15.0 Docker image includes a broken wrapper script that exits immediately

### ISSUE THREAD

**Issue by vreon** [apollographql/router#2966]
**Describe the bug**

The Docker image for v1.15.0 always exits immediately with `error: unrecognized subcommand`.

```sh
$ docker run -it --rm ghcr.io/apollographql/router:v1.15.0
error: unrecognized subcommand

$ docker run -it --rm ghcr.io/apollographql/router:v1.15.0 -h
error: unrecognized subcommand
```

**To Reproduce**
See above

**Expected behavior**
Apollo Router should start normally.

**Output**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**

The `/dist/router_wrapper.sh` entrypoint script is hard-coded to pass a single empty string argument to Router, which is invalid:

```sh
$ docker run -it --rm --entrypoint /bin/bash ghcr.io/apollographql/router:v1.15.0 -c 'cat /dist/router_wrapper.sh'
#!/usr/bin/env bash
set -e
if [ -f "/usr/bin/heaptrack" ]; then
  exec heaptrack -o /dist/data/router_heaptrack /dist/router ""
else
  exec /dist/router ""
fi
```

It looks like something is evaluating the `$@` in the Dockerfile instead of including them literally.

https://github.com/apollographql/router/blob/8837b8825948e66ae1d4559199ea8156af43185c/dockerfiles/Dockerfile.router#L38-L47

**Comment by garypen** [comment]
This was caused by: https://github.com/apollographql/router/pull/2925. I've looked at trying to improve this, but I think the simplest thing for now is to revert the PR.
