### ISSUE TITLE
Router empty response

### ISSUE THREAD

**Issue by sbolanosQB** [apollographql/router#2983]
**Describe the bug**
I get an empty response with no errors when using the router locally with a supergraph that contains one subgraph

**To Reproduce**
1. Download my subgraph .sdl  using the download button in the playground (my subgraph is using apollo server 3)
2. Using that subgraph schema I generated a rover config using passing the file and the URL of the subgraph in prod (the subgraph requires auth headers for introspection) I did not include any other settings
3. Run the router using the supergraph file generated by rover ( it seems to be fine)
4. When running a query the response is an empty object, the same query in the subgraph will return data. (I am setting the same headers in the router sandbox as I will set in the subgraph playground)

I get no errors or logs from the router

**Comment by Geal** [comment]
hello, could you provide the following information:
- the query
- a reduced schema (with only the parts required for the query). The full schema is fine too
- the subgraph request and response

**Comment by abernix** [comment]
I'll close this as we haven't heard back from you, but happy to re-open if this is still a problem for you and you can provide a reproduction as requested above.  Thanks!
