### ISSUE TITLE
replace the reloadable tracing fmt layer with a hot reconfigurable one

### ISSUE THREAD

**Issue by Geal** [apollographql/router#3000]
currently there's a performance cost with the fmt layer, used to write logs to stdout, because it is stored behind a reloadable layer. We don't use most of the features of that layer, we only configure text VS JSON, and toggles to display or not the filename, line number and target. Instead of a reloadable layer with the RwLock it implies, this could be a bitfield stored in an AtomicU8, which would be much more scalable. This would also avoid the calls to on_enter, on_exit etc for every span, since our ogs do not care about it.
There's on possible problem here: we might want to have configurable access logs in the future, which would bring us back to a reloadable layer

**Comment by abernix** [comment]
Any thoughts on where we should sequence this work in, @Geal? Do you think that this ties into #3226?

**Comment by Geal** [comment]
this is implemented in #2999, which we should merge after #3656 and #3669. They will go in the next release (after 1.29). This is independent from #3226

**Comment by abernix** [comment]
@Geal #2999 is merged.  Does this get closed, now?

**Comment by Geal** [comment]
my previous comment was wrong, the relevant work was split out of #2999, in https://github.com/apollographql/router/pull/3086. That one should be revisited when the otel update 0.20 is done

**Comment by abernix** [comment]
The logging layer is — in its entirety — going to be replaced in #3226.  With that in mind, should we just make this a _requirement_ of #3226 — and close this ticket — rather than an individual ticket?   If you agree, can you make that ask on #3226 and close this?  (If you disagree, let's keep this open but just reply so we know either way. 😸 )

**Comment by Geal** [comment]
added more context in https://github.com/apollographql/router/issues/3226#issuecomment-1742758870
