### ISSUE TITLE
Opaque error message when an APOLLO_ env var set that the router doesn't accept

### ISSUE THREAD

**Issue by chadxzs** [apollographql/router#3023]
**Describe the bug**
I was getting the opaque error message: "error: one of the values isn't valid for an argument" when trying to run router, even when it appeared I was passing no values. After much debugging and some luck that I had seen this error message before in another scenario, I was able to track it down to having the rover CLI option `APOLLO_TELEMETRY_DISABLED=1` in my ~/.zshrc file.

**To Reproduce**
```sh
APOLLO_TELEMETRY_DISABLED=1 ./router
error: one of the values isn't valid for an argument
```

**Expected behavior**
Ignore the option if router doesn't accept or care about it. Improve the error message to point at the exact argument that is causing the problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.3.1 (22E261)

**Comment by bricker** [comment]
For Googlers: set `APOLLO_TELEMETRY_DISABLED=true` instead, but only with the `router` program.

The confusion is because `rover` accepts "1" as a valid value (it even recommends it in the post-install message), but `router` does not.
