### ISSUE TITLE
Responses getting cut off in v1.16.0

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#3035]
**Describe the bug**
There seems to be a major bug in v1.16.0. It looks like responses are getting cutt-off mid json string. Not using `@defer` or anything of such kind.

It seems to happen when the `Accept-Encoding` header is present (which is sent by all browsers by default).

**To Reproduce**
1. Do a query that returns a long response
2. Send `Accept-Encoding: gzip` header

**Expected behavior**
Returns valid JSON

**Output**
JSON that is cutt-off at some length, resulting in an invalid data/JSON being returned.

**Comment by Geal** [comment]
there's a fix in #3037
