### ISSUE TITLE
Mockup extensibility API.

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#304]
Create a public facing extensibility API that can fulfill the following use cases:
* Overriding downstream service URL
* Selectively redirect to external URL.
* CORS configuration.
* Header/Cookie manipulation/propagation.
* Access query body
* Call an external service.
* Custom tracing.
* Custom logging.
* Authentication.
* Timeouts/Rate limiting/Retry/Optimistic retry.

Code can be found at: https://github.com/apollographql/router/tree/tower-layer

**Comment by abernix** [comment]
Code can be found at: tower-layer
