### ISSUE TITLE
Mockup architecture based on Tower services.

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#305]
Closely related to the [Extensibility API](https://github.com/apollographql/router/issues/304)

Goal is to enumerate:
* The services that need to be present in our desired state.
* The data that needs to flow between services.
* Come up with a plan to convert our existing components into service and in what order.

Assert that the architecture:
* Is likely to perform well.
* Is able to support websockets.
* Is able to support defer/stream.

This task may involve trying to convert the existing codebase in a throwaway fashion.

**Comment by BrynCooke** [comment]
These are the proposed datastructures that flow throw the new service based architecture:
```
pub struct RouterRequest {
    // The original request
    pub frontend_request: Request<graphql::Request>,

    pub context: Context,
    //Parsed_request
}

pub struct RouterResponse {
    // The original request
    pub frontend_request: Arc<Request<graphql::Request>>,

    pub backend_response: Response<graphql::Response>,

    pub context: Context,
    //Parsed_request
}

pub struct PlannedRequest {
    // Planned request includes the original request
    pub frontend_request: Request<graphql::Request>,

    // And also the query plan
    pub query_plan: QueryPlan,

    // Cloned from RouterRequest
    pub context: Context,
    //Parsed_request
}

pub struct SubgraphRequest {
    pub service_name: String,

    // The request to make downstream
    pub backend_request: Request<graphql::Request>,

    // Downstream requests includes the original request
    pub frontend_request: Arc<Request<graphql::Request>>,

    // Cloned from PlannedRequest
    pub context: Context,
    //Parsed_request
}
```

**Comment by cecton** [comment]
Thanks I think that's the pieces I missed to understand the thing

**Comment by cecton** [comment]
@BrynCooke do we need a Planner service and a Subgraph service too?

**Comment by Geal** [comment]
Subgraphs have already been converted to services, but not yet for the planner. It makes sense for the planner (if we add caching, etc) but maybe not exposing it in the public API

**Comment by BrynCooke** [comment]
Yeah, it means we can have caching and possibly tracing instrumentation implemented as layers.
Agree not to expose to the user right now.

**Comment by cecton** [comment]
I'll do it for the planner but I also need to change the one for the subgraph because you implemented it in the struct of apollo-router. It works but it won't allow the user to implement their down subgraph fetcher without having to re-implement the service.

**Comment by BrynCooke** [comment]
As we have decided to commit to the tower approach the following tickets have been created:
* #342 
  * #343
  * #344
  * #346
  * #345
Closing this ticket even though we will continue to work with the related feature branch.

**Comment by Geal** [comment]
>  it won't allow the user to implement their down subgraph fetcher without having to re-implement the service.

That was the point, replacing the Fetcher trait with Service. But I did not have the time to make other parts more generic

**Comment by cecton** [comment]
```rust
impl Service<(String, graphql::SubgraphRequest)> for HttpServiceRegistry {
```

@Geal @BrynCooke was it also intended to implement Service on the ServiceRegistry?? There is benefit for that?

**Comment by cecton** [comment]
(Also it looks like the SubgraphRequest was more meant for ServiceRegistry than the Fetcher. Or is it for both?)
