### ISSUE TITLE
Resolving nullable field raising error which doesn't set the field to null

### ISSUE THREAD

**Issue by hyche** [apollographql/router#3071]
**Describe the bug**
According to https://spec.graphql.org/October2021/#sec-Handling-Field-Errors

`
If a field error is raised while resolving a field, it is handled as though the field returned null, and the error must be added to the "errors" list in the response.
`

This behaviour works fine with gateway but not with router.

**To Reproduce**
1. Send a following request 
`
query {
  profile {
    email
  }
}
`
while `profile` is nullable

2. Router return 
`
{
  "data": {},
  "errors": [
    {
      "message": "Unauthorized",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ],
      "path": [
        "profile"
      ]
    },
}
`

**Expected behavior**
it should be (based on gateway ouput):
`
{
  "data": {
     "profile": null
  },
  "errors": [
    {
      "message": "Unauthorized",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ],
      "path": [
        "profile"
      ]
    },
}
`

I also expect `data` is null, if `profile` is not nullable.

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Router version v1.18.0

**Comment by hyche** [comment]
> could you give more information? Especially a reduced schema, the request to the subgraph and the response it sent to the router

Sorry for late reply, I just figure out that router is actually works as expected, because our services have a middleware that return error on a check that didn't resolve that nullable field to null. So the response from subgraph to router is 
```
 { "data": null, "errors": [ { "message": "Unauthorized", "locations": [ { "line": 1, "column": 2 } ], "path": [ "profile" ] }, }
```
which is correct, and router also returns that response to our client. Btw I don't know why Sandbox shows the `null` on `data` field as an empty object value, it's weird and the error is duplicated on Sandbox as well, I use curl alternatively and it shows corretly.

Now the questionable thing is why gateway does change the response from subgraph "correctly" like that.. but i guess it is gateway's fault :). I also accidentally found the checking bug when switch from gateway to router due to that behaviour, and it makes senses now.

Thanks

**Comment by Geal** [comment]
oh, that's good to know, thanks. I'm closing this now, then
