### ISSUE TITLE
How to pass subgraph as a parameter to response callback

### ISSUE THREAD

**Issue by kay8910** [apollographql/router#3088]
I have tried using this closure, but it is giving module not found exception.
```
fn process_subgraph_response(subgraph) 
{ return |response|{
manipulate_headers::set_txn_id_in_response_header(response);
apollo_error_code_plugin::set_extension_in_response_context(response);
}
}
```

**Comment by Geal** [comment]
could you give more information? What is in the `manipulate_headers::set_txn_id_in_response_header` and `apollo_error_code_plugin::set_extension_in_response_context` functions? Is it that you want to pass the subgraph name around?

**Comment by kay8910** [comment]
import "./manipulate_headers" as manipulate_headers;
import "./apollo_error_code_plugin" as apollo_error_code_plugin;
Above are the modules which we are trying to use to add some additional headers and add data to response context.
I want to pass the subgraph to process_subgraph_response method so that i can return a closure and get the subgraph value in closure function. But when closure function is called its says module not found (above two modules)

**Comment by Geal** [comment]
are the other modules in files in the same directory as the main rhai script?

**Comment by kay8910** [comment]
I also have one more question, we are getting error object, but we are getting duplication of error object as shown in attached file, how to fix this?
[router-response.json.zip](https://github.com/apollographql/router/files/11509645/router-response.json.zip)

**Comment by o0Ignition0o** [comment]
Hi,

`subgraph_service` in rhai takes the service name as 2nd parameter.

You could edit your script so that it takes two parameters.

In the [router docs example](https://www.apollographql.com/docs/router/customizations/rhai#converting-cookies-to-headers), this would mean editing `process_request` so it takes two parameters, ie:

```diff
- fn process_request(request) {
+ fn process_request(request, subgraph_name) {
```

I'm going to close this issue, but feel free to reopen it if you need more information!
