### ISSUE TITLE
Parent based sampling has regressed

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3103]
The recent perf optimisations around trace sampling has broken Otel parent based sampling. 

- [x] Verify if this has regressed.
- [ ] Make it work again if it has. 
- [x] Add a test.

For a nice description of parent based sampling see: https://www.aspecto.io/blog/opentelemetry-sampling-everything-you-need-to-know/#parent-based-sampler

**Comment by BrynCooke** [comment]
After spending the day trying to unpick this the feeling is that we should revert #2894 and look at it again once the release is out the door.
For us to get this over the line we'll need to show that in any filter implementation we can demonstrate that all spans are correctly parented within Otel and that for a sampled trace all ancestors are passed correctly to the otel filter.

**Comment by chandrikas** [comment]
Closing this for now - we've reverted #2894
