### ISSUE TITLE
Router should mark fetch spans as error if the downstream response had errors

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3123]
Relevant reading:
Semantic conventions for GraphQL: https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/instrumentation/graphql/
Semantic conventions for HTTP https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts#L244-L275

It looks like the node implementation of otel allowed customization of error handling at the execution level.

Full customization will be difficult without some sort of scripting support, but we should make sure we are following the HTTP semantic conventions at the very least.

Let's also add a config option to telemetry to mark fetch spans as errors if they have errors.

**Comment by chandrikas** [comment]
Will be done as part of https://github.com/apollographql/router/issues/3226
