### ISSUE TITLE
Subgraphs returning 401 error codes not being treated as errors by router

### ISSUE THREAD

**Issue by dandersonhall** [apollographql/router#3141]
**Describe the bug**
When a subgraph service returns a 401 (or similar error codes) to the router it does not create a `SUBREQUEST_HTTP_ERROR` if the subgraph also returns `Content-Type: application/json`

**To Reproduce**
1. Setup [api-gateway-test.zip](https://github.com/apollographql/router/files/11564797/api-gateway-test.zip) by running `npm install` followed by `npm start`. This will run a server on `http://localhost:3000`
2. Run a router such that any of the subgraphs now points to `http://localhost:3000` and run a query against router that will cause that subgraph to be called.
3. Router should return
```
{
  "data": {}
}
```
4. Now, in the `api-gateway-test` directory open `/routes/index.js` and comment out the `res.setHeader('Content-Type', 'application/json');` line. The server will now return `Content-Type: text/html`. Restart the server.
5. Run the same query as before against the router, it should now return (assuming the router is not configured to forward subgraph errors):
```
{
  "data": {},
  "errors": [
    {
      "message": "HTTP fetch failed from 'redacted': redacted",
      "path": [],
      "extensions": {
        "code": "SUBREQUEST_HTTP_ERROR",
        "service": "redacted",
        "reason": "redacted"
      }
    }
  ]
}
```

**Expected behavior**
Router will return the `SUBREQUEST_HTTP_ERROR` as above in all situations where a 401 or similar error is thrown by the subgraph service.

**Additional context**
This was discovered when an API Gateway in front of a subgraph service threw 401 errors which were not getting back to the client.

**Comment by BrynCooke** [comment]
When tackling this we need to take into account: https://graphql.github.io/graphql-over-http/draft/#sec-Status-Codes.
If this is non-compliant behaviour then we can consider making sure that users can use rhai to work around this.

**Comment by BrynCooke** [comment]
This code seems suspicious: https://github.com/apollographql/router/blob/dev/apollo-router/src/services/subgraph_service.rs#L630-L631
