### ISSUE TITLE
circleci: investigate the need of global .gitconfig ssh:// instead_of https://

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#317]
followup to #316, we might want to investigate whether we actually need the ssh instead of https statement in .gitconfig.

This issue is opened as a followup since it has much lower priority than the blocking issue we raised about check-compliance

this seems like it would cause other problems.  like when we want to fetch things that are on a private repo using a circleci / git deploy key or something?

i'm surprised as to why that git remote for the advisories couldn't be fetched over gitssh?  it's a public repo and i'd expect it to work?

_Originally posted by @abernix in https://github.com/apollographql/router/pull/316#discussion_r782053894_

**Comment by o0Ignition0o** [comment]
not sure if related: https://app.circleci.com/pipelines/github/apollographql/router/988/workflows/65ee47ed-adad-4f22-886f-e74d92c195ef/jobs/6313 might hint at a cause

**Comment by abernix** [comment]
Let's close this for now, and re-open if it becomes a problem again.
