### ISSUE TITLE
map_response is not called when subgraph errors

### ISSUE THREAD

**Issue by utay** [apollographql/router#3182]
**To Reproduce**

I got inspired by the [status-code-propagation](https://github.com/apollographql/router/blob/07c9bfc9f5d7b87e3e165690c40ce5f83e21324d/examples/status-code-propagation/rust/router.yaml#L14) example but I doubt it's working for statuses 5XX.

I use this code in a plugin to detect if a subgraph errors with status code 500:
```
    fn subgraph_service(&self, _name: &str, service: subgraph::BoxService) -> subgraph::BoxService {
        ServiceBuilder::new()
            .map_response(move |res: subgraph::Response| {
                if res.response.status() == StatusCode::INTERNAL_SERVER_ERROR {
                    res.context
                        .insert(context::SUBGRAPH_INTERNAL_SERVER_ERROR_KEY, true)
                        .unwrap();
                }
                res
            })
            .service(service)
            .boxed()
    }
```

However when the subgraph errors with 500, `map_response` is not called and `map_err` seems to be called instead. The issue is that in `map_err` I have no way to type the error as `FetchError` is `pub(crate)`; the only thing I can use is `BoxError` which doesn't let me handle the error properly with pattern maching, etc. 

**Expected behavior**

Unless I'm missing something, I'd love to be able to intercept the subgraph 500 in this case. Maybe `map_response` could be called anyway, or `FetchError` could be public so it can be used in plugins.

**Comment by utay** [comment]
https://github.com/apollographql/router/issues/3268 should give access to the context in map_error so this issue will be fixed with that

**Comment by abernix** [comment]
@utay What about using [`map_future_with_request_data`](https://github.com/apollographql/router/blob/41cb44e3c861b50ea3925e9d992c263b2a1109cf/apollo-router/src/layers/mod.rs#L301C8-L301C36)?

**Comment by utay** [comment]
@abernix In case of an error that would allow us to access the context but I'm not sure we would be able to mutate it (existing occurrences in the router code clone the context)

**Comment by BrynCooke** [comment]
@utay Please can you check to see if this is still an issue for you? The subgraph error handling has been modified to always return a valid graphql response.

**Comment by utay** [comment]
@BrynCooke I confirm this is no longer an issue, thanks!
