### ISSUE TITLE
Slow router shutdown time

### ISSUE THREAD

**Issue by prasek** [apollographql/router#320]
**Describe the bug**

Router shutdown time is 10.2 seconds vs. Gateway 0.4 seconds in [supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2)

**To Reproduce**
1. `git clone git@github.com:apollographql/supergraph-demo-fed2.git`
2. `make demo-local-router`
3. see router shutdown time is 10.2 seconds, unlike the subgraphs which shutdown in < 0.4 seconds

![image](https://user-images.githubusercontent.com/284840/149216038-eb523872-707d-400a-a88d-b8cf0257216e.png)

Compare to Gateway
1. `make demo-local`
2. see gateway shutdown time is 0.3 seconds, like the subgraphs

![image](https://user-images.githubusercontent.com/284840/149216116-e34f4c56-911a-434f-9222-98971b74dd2d.png)

**Expected behavior**
Router shuts down as fast as Gateway, in <= 0.3 seconds.

**Desktop (please complete the following information):**
OS: Mac OS 12.1.0 [64-bit]

**Comment by o0Ignition0o** [comment]
It seems like 10s is the [default timeout](https://docs.docker.com/compose/reference/stop/) for docker-compose stop. 

Moreover the router is currently waiting for a [Ctrl+C](https://github.com/apollographql/router/blob/9c0281eb82c74313ede6534538e29c247c96c6b2/apollo-router/src/main.rs#L172) shutdown signal, which is probably not what docker sends. I'll have a look at what SIG docker sends and I'll get back to you!

**Comment by o0Ignition0o** [comment]
Quoting docker documentation:

The main process inside the container will receive `SIGTERM`, and after a grace period, `SIGKILL`

**Comment by prasek** [comment]
@o0Ignition0o this is still taking 10s with the PR ☝️ so re-opening this for now.

Note the version is not present in the log output, so it's using the new image.

![image](https://user-images.githubusercontent.com/284840/151613500-27d5c54b-282b-4b13-97ec-3cfa7f56881a.png)

**Comment by o0Ignition0o** [comment]
Thanks for reopening it, I’ll check next week

**Comment by prasek** [comment]
@o0Ignition0o looks like this did the trick
- https://github.com/apollographql/supergraph-demo-fed2/pull/33

Same as what [postgres](https://github.com/docker-library/postgres/blob/master/14/bullseye/Dockerfile#L204) is doing in their official Docker image.

**Comment by o0Ignition0o** [comment]
Postgres readme seems to indicate this is set this way in order to abort in flight requests. I however wonder what kind of request are still in flight at the time we’re trying to shut down the router. I’ll try to have a look regardless

**Comment by abernix** [comment]
Since the default for [`STOPSIGNAL` is `SIGTERM`](https://docs.docker.com/engine/reference/builder/#stopsignal), does this mean that the router is _not_ terminating on merely `SIGTERM`?

**Comment by prasek** [comment]
@abernix yes exactly. I've been [adding `STOPSIGNAL SIGINT` to my custom router images](https://github.com/apollographql/supergraph-demo-fed2/blob/main/router/custom-image/Dockerfile#L14), but for the pre-packaged router image it takes 10 seconds to shutdown.

Adding `STOPSIGNAL SIGINT` to the https://github.com/apollographql/router/blob/main/dockerfiles/Dockerfile.router would solve the issue for using the stock router docker image in [supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2/blob/main/docker-compose.router.yml#L5)

Re-opening this for now as `make demo-local-router` is using the stock router image.

**Comment by abernix** [comment]
Ok, that sounds like a bug then and something we should fix.  Thanks for re-opening.

**Comment by Geal** [comment]
so the default docker stop signal is SIGTERM (15), and when tested locally, the router stop immediately, so there must be an issue specific to running in a container

**Comment by Geal** [comment]
the router's container closes with exit code 137 which indicates an OOMkill but I don't really see it with docker inspect
