### ISSUE TITLE
Reaffirm and document plugin ordering

### ISSUE THREAD

**Issue by abernix** [apollographql/router#3207]
We don't currently have a test that asserts the determinism that we _believe_ (basis: manual analysis of code) exists in our plugin APIs.  We also don't have documentation that expresses the determinism, but we would like to _offer_ and stand behind that determinism.

The code needs a test added that verifies/demonstrates this determinism and ensures it is maintained and the documentation for plugins should outline that determinism once it's verified

**Comment by SimonSapin** [comment]
This is determinism in the order in which multiple plugins are called for a given request.


The relevant code is:

* Using `serde_json::Map` to store plugin configuration:

  https://github.com/apollographql/router/blob/760b3b5ff37eaaa508d03398569ffb9ae31b8e81/apollo-router/src/configuration/mod.rs#L435-L437

* Iterating that map when creating plugin instances:
  
  https://github.com/apollographql/router/blob/760b3b5ff37eaaa508d03398569ffb9ae31b8e81/apollo-router/src/router_factory.rs#L436

* This `Map` type is backed by `IndexMap` because the `preserve_ordering` feature is enabled:
  https://github.com/apollographql/router/blob/760b3b5ff37eaaa508d03398569ffb9ae31b8e81/apollo-router/Cargo.toml#L182

---

The test should likely be an "integration test" (in the Cargo sense of `tests/*.rs`) that uses `register_plugin!` (not just `TestHarness` hooks) with multiple plugins that have observable side effects.

**Comment by BrynCooke** [comment]
Suggest add a test for plugin ordering but not set expectations for users.
It is currently unclear that we will stick with current plugin ordering, and to document it will make it a breaking change to modify things in future.
Indeed we have on several occasions changes the ordering of our internal plugins.

**Comment by SimonSapin** [comment]
Based on reading code, the current ordering is:

1. Apollo-provided mandatory plugins, in a hard-coded order
2. Apollo-provided non-mandatory plugins, in YAML config order
3. User plugins, in YAML config order

What we might want to change in the future is within 1. and 2. together, right? So I propose we document the ordering as:

1. Apollo-provided plugins, in unspecified order that may change in future Router versions
2. User plugins, in YAML config order. (Registered but un-configured user plugins are disabled.)

Or maybe not even mention Apollo-provided plugins at all in that part of docs. Only document the ordering of user plugins relative to each other.

**Comment by SimonSapin** [comment]
Thank you for this feedback! We’ll double-check all of this.

> My brief and naive testing seemed to show them executing in reverse YAML config order,

Is that for executing `map_request` or `map_response`? Rust plugins typically make a new, outer `BoxService` that wraps an inner `BoxService` they receive as a parameter. `map_request` calls its callback before the inner service is called, whereas `map_response` calls its callback after the inner service has returned. So a request would "traverse" multiple plugins outermost first, a response innermost first.

**Comment by SimonSapin** [comment]
New documentation that will show up soon at https://www.apollographql.com/docs/router/customizations/native/ :

> Within a given service (router, subgraph, etc.), a _request_ is handled in the following order:
> 
> * [Rhai script](https://www.apollographql.com/docs/router/customizations/rhai)
> * [External coprocessor](https://www.apollographql.com/docs/router/customizations/coprocessor)
> * Rust plugins, in the same order they're declared in your [YAML configuration file](https://www.apollographql.com/docs/router/configuration/overview/#yaml-config-file).
> 
> The corresponding _response_ is handled in the opposite order.
> This ordering is relevant for communicating through [the `context` object](https://www.apollographql.com/docs/router/customizations/native/#5-define-necessary-context).
> 
> When a single supergraph request involves multiple subgraph requests, the handling of each subgraph request and response is ordered as above but different subgraph requests may be handled in parallel, making their relative ordering non-deterministic.

**Comment by theJC** [comment]
Any thoughts / consideration on (or examples and/or doc if it can work) for how to wire in plugins that do not require configuration?

How does one list a plugin in the yaml list of plugins without any configuration?    When I register but not list the plugin in the yaml, I do see that the registered plugin is seen via DEBUG creating plugin factory plugin_factory_name=  but then not listed in DEBUG plugins list: log message.

I have not yet successfully figured a way to list it in the plugins section in a way without any config without router complaining, ie: 
```
    indeed_plugin.fake_context_state: ~
                                      ^----- null is not of type "object"
```

**Comment by abernix** [comment]
@theJC Do you mind opening that question up as [a Discussion](https://github.com/apollographql/router/discussions) so someone can follow-up on that?
