### ISSUE TITLE
Name open telemetry root span to match graph operation name

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/router#3229]
**Is your feature request related to a problem? Please describe.**
No problem, a refinement on current setup.

**Describe the solution you'd like**
Each span sent via opentelemetry seems to always be named "request". It'd be nice if the root activity/span could be the operation name of the graph query in some way. 
As an example the HotChocolate C# federation library we're using does this and helps a lot to track down appropriate requests
https://github.com/ChilliCream/graphql-platform/blob/9f21941ae90272b96adb6a7d556000939decaa9a/src/HotChocolate/Diagnostics/src/Diagnostics/InstrumentationOptions.cs#LL31C1-L34C49

**Describe alternatives you've considered**
Setup custom filtering within monitoring solution to parse out attributes on the span: possible, but one more hoop to jump through for inexperienced people looking to find their request

**Additional context**
See image of current view we see within Dynatrace with router configured using otlp to send traces there. Every trace is named "request" which makes it a little abstract for users to find the trace they're after
<img width="1050" alt="image" src="https://github.com/apollographql/router/assets/1321276/b3aa89fd-d462-4f37-9bc5-6123de647d68">

**Comment by BrynCooke** [comment]
Indeed https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/instrumentation/graphql/ states that span name must use the format `<graphql.operation.type> <graphql.operation.name>`. 

This could be an additional span that is added as a child of the request span, as at the request we have not parsed anything yet. This would also allow us to move existing attributes off of the `supergraph` span.
