### ISSUE TITLE
metrics reporting isn't working correctly for OTLP and datadog on dev

### ISSUE THREAD

**Issue by garypen** [apollographql/router#3242]
metrics reporting for the router exporting via OTLP and observing in datadog is not working correctly following the `0.19.0` otel update.

**Comment by garypen** [comment]
If there is no hotfix for this before we want to make our next release, we will need to revert [the otel 0.19.0 PR](https://github.com/apollographql/router/pull/3196).

**Comment by o0Ignition0o** [comment]
No hotfix yet unfortunately, as discussed I will revert the pr and reopen the related issues

**Comment by o0Ignition0o** [comment]
For more context, metrics don't properly flush when the router reloads (on schema updates or configuration change if hot reload is enabled)

![image](https://github.com/apollographql/router/assets/9465678/8b18ffff-bff9-4f69-907f-9a83a196ad6a)

**Comment by o0Ignition0o** [comment]
Unpinning this since the tip of dev and the latest release uses otel 0.18

**Comment by o0Ignition0o** [comment]
Closing because we fixed it \o/
