### ISSUE TITLE
Allow some configuration of the sandbox.

### ISSUE THREAD

**Issue by tmc** [apollographql/router#3244]
Being able to specify initialSubscriptionEndpoint in particular would be nice (since the router doesn't currently handle subscriptions).

Sidebar: IMO simply setting a specific service to handle all subscription traffic would be way more helpful than just not supporting subscriptions at all.

**Comment by bnjjj** [comment]
We released a new version of the router to add the support for subscription, take a look at the changelog https://github.com/apollographql/router/releases/tag/v1.22.0
