### ISSUE TITLE
restore heaptrack functionality to our debug docker image

### ISSUE THREAD

**Issue by garypen** [apollographql/router#3249]
Somewhere along the way we stopped installing `heaptrack` into our debug docker images. This is a regression and should be fixed.

**Comment by abernix** [comment]
Reference to the docs [for `ARG`](https://docs.docker.com/engine/reference/builder/#arg), which seems to support this theory.

**Comment by garypen** [comment]
The docs note that the ARG comes into scope at the line where it is declared and remain in scope for the rest of the containing build stage. That means that I think our use of ARG is correct. I think the fix is simply that we aren't setting DEBUG_IMAGE true when invoking the debug build. See my PR for what I think is the fix.

Also: everything under `diy` is related to DoItYourself docker image builds and isn't part of the automated release build process. The published docker image is built using `dockerfiles/Dockerfile.router`.

**Comment by abernix** [comment]
> think the fix is simply that we aren't setting DEBUG_IMAGE true when invoking the debug build. See my PR for what I think is the fix.

Ah, okay.  That makes sense.  I'd kinda jumped to concluding that it was broken more recently (by me).
