### ISSUE TITLE
Is query deduplication activated by default ? 

### ISSUE THREAD

**Issue by SofieneOuerdiane** [apollographql/router#3257]
Is query deduplication activated by default ?  
It is not clear in the documentation, and after reading the code, I have some doubts
[Query deduplication](https://www.apollographql.com/docs/router/configuration/traffic-shaping/#query-deduplication)

**Comment by abernix** [comment]
Query-deduplication is disabled by default.  I've opened #3258 to hopefully clarify, but let me know if that parenthetical addition wouldn't have helped in your case.

Thanks for opening this!
