### ISSUE TITLE
API 1.0 - Use polling futures instead of boxed futures

### ISSUE THREAD

**Issue by cecton** [apollographql/router#327]
We (@Geal and I) noticed tokio is avoiding boxed future (`Pin<Box<dyn Future = ... + Send, 'a>>`). This is probably for performance reason and we might want to do the same because performance is important for us and because tower uses polling everywhere too.

Nevertheless we need to take into consideration the impact of switching to polling futures on the API because a lot of convenience will become unavailable (most notably: `async_trait`). This will impact our users.

**Comment by SimonSapin** [comment]
@BrynCooke @Geal @bnjjj @abernix @o0Ignition0o The 1.0 release is approaching, do we want to make a change here? Replacing `async fn` (through `async_trait`) with explicit `impl Future` sounds like a big usability hit for plugin authors.

**Comment by Geal** [comment]
I think that ship has sailed long ago. I still believe we could benefit from explicit futures in internal parts of the router, but for the plugin API boxed futures will be the only way

**Comment by BrynCooke** [comment]
Closing, we can open again if people disagree.
