### ISSUE TITLE
Key / Value cache abstraction

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#329]
The router needs to be able to rely on and provide various layers of caches.

Depending on user's requirements and existing infrastructure, we should design a Trait that allow for various backend implementations that could leverage say, inmemory / memcached / redis and more.

Sccache could serve as an idea of what it would look like (the trait would be different though, because we're not looking for a file interface) https://github.com/mozilla/sccache/tree/master/src/cache.

We should investigate existing work around that in the rust ecosystem and see what it would look like.

This issue is the foundation of:

- [ ] #326
- [x] #130 
- [ ] #1401

**Comment by abernix** [comment]
Let's close this now that https://github.com/apollographql/router/pull/1281 has landed and let the other issues (referenced above) persist for covering next steps. Thanks!
