### ISSUE TITLE
BytesStream chunks: make sure we don't lose any

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#33]
e409895 got fixed assuming no BytesStream chunk will contain the end one response, and the beginning of an other one at the same time.

we want to add test coverage to this, and track this, maybe using https://github.com/facebookincubator/rust-partial-io ?

This issue is open so we can either make sure that's the case, or keep the remaining bytes while we stream::unfold.

This is opened as a followup as this isn't high priority

**Comment by Geal** [comment]
I think we can close this one. For requests with multiple responses like stream we'll have other ways to implement (with multipart IIRC)
