### ISSUE TITLE
docs failing to build for `apollo-router` on crates/docs.rs

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#3305]
The latest `apollo-router` crates are failing to build on docs.rs, as seen here: https://docs.rs/crate/apollo-router/1.26.0/builds

The latest successful docs build is for [apollo-router 1.21.0-alpha.0](https://docs.rs/apollo-router/1.21.0-alpha.0/apollo_router/index.html)

We will unpin and close this issue once the [upstream fix](https://github.com/denoland/rusty_v8/issues/1248) is published.

**Comment by o0Ignition0o** [comment]
Deno has released a version with the fix, putting it back in todo

**Comment by abernix** [comment]
Our documentation is again building and being published to [docs.rs](https://docs.rs/apollo-router/latest/apollo_router/) successfully!
