### ISSUE TITLE
CI: Iterate on our release pipeline

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#332]
Our CI Pipeline got quite a bit of rework lately, but unfortunately our Release pipeline has not.

Moreover I've had a very hard time last week as I tried to release `v0.1.0-alpha.3` because I've hit several roadblocks.

Each of these hiccups should have happened, but because we don't release often, we discovered all of them at the same time.

We could automate a weekly generation of a draft release artifact, which we would manually update the change log for, before we actually make it public.

That would allow CI to go red whenever there's an issue, so we would be able to perform quick fixes.

How does the team feel about this? Are there other ways / low hanging fruits we could reach for ?

**Comment by abernix** [comment]
I hope that #242 and #229 will solve the pains you had here.  I'm going to keep those open to track things.
