### ISSUE TITLE
Add support for GCP Operations/Stackdriver Trace exporter

### ISSUE THREAD

**Issue by bokjo** [apollographql/router#3357]
**Is your feature request related to a problem? Please describe.**
Noticed that OpenTelemetry is supported out of the box but with just few exporters  https://www.apollographql.com/docs/router/configuration/tracing/

GCP Operations(Stackdriver) is not supported as a trace exporter, I can see that OTel already has Rust SDK for it https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-stackdriver 

What can I do for this to be supported by the router? Don't really want to deploy a dedicated OTel exporter just for this (we are already using the batch GCP Stackdriver exporter for the Apollo Gateway)

Even tho I'm not Rust dev. might give it a try to implement it if needed with some guidance

**Describe the solution you'd like**
Be able to use directly GCP Operations/Stackdriver as a backend for OTel traces using the router.

**Describe alternatives you've considered**
An alternative is to deploy a dedicated OTel exporter service just for the router, the other services/graphs are using the batch Stackdriver exporter 

**Additional context**
N/A

**Comment by Geal** [comment]
hi, there has not been much movement here for a while, and from our experience at Apollo, opentelemetry-collector would work well. If you have more specific needs, feel free to reopen this issue so we can discuss it
