### ISSUE TITLE
Investigate jemalloc page faults

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3396]
Users have reported that during testing they are seeing a very high number of page faults. This happened when we switched to jemalloc.
This could be related to: https://github.com/jemalloc/jemalloc/issues/2294

Note that the same users saw a boost in performance, which also mirrors our experience. So it's not critical that this is solved right away, but maybe there is some tuning of jemalloc still to be done which could affect performance of the router.

**Comment by garypen** [comment]
An increase in page faults probably indicates that jemalloc is being more aggressive about freeing (and then re-allocating) memory. I doubt it's a problem. Just a sign that jemalloc is doing what we want, i.e. managing memory more conservatively.

**Comment by garypen** [comment]
I'll leave this assigned to me, but I won't do anything unless a customer reports worse router performance with this behavioural change.

**Comment by abernix** [comment]
We can re-open this if additional reports about page faults come in from users, but we haven't seen anything more at this time.  Thanks!
