### ISSUE TITLE
Mockup YAML configuration.

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#340]
So that we can figure out if the programmatic API is correct we need to have an idea of where we are going with the YAML config.
It would be bad for the structure to be substantially different as it will increase the cognitive load of making the transition from one to the other.

**Comment by BrynCooke** [comment]
Here is a starter to discuss: https://github.com/apollographql/router/blob/tower-layer/configuration.yaml

**Comment by BrynCooke** [comment]
Moved to discussion: https://github.com/apollographql/router/discussions/405

**Comment by o0Ignition0o** [comment]
closed in favor of #407
