### ISSUE TITLE
Log operation metrics/limits in info mode

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#3416]
**Is your feature request related to a problem? Please describe.**
Today we can configure operation limits and prevent large operations from executing. You can turn on [warn_only mode](https://www.apollographql.com/docs/router/configuration/operation-limits#warn_only-mode) to log out if any operations fail your current configured limits but what if I don't have any limits at all set, how can I see what the current operation depth or height is?

**Describe the solution you'd like**
I want to know for all operations what their number of

* height
* depth
* alias count
* root field count

sent as logs or traces at the info level so I can track that outside of the limits themselves

Some config like this could work so I don't need to set any limits or warning mode, just start logging

```
limits:
  log_info: true
```

**Describe alternatives you've considered**
I could turn on `warn_only` mode and configure some limits, but those show up as warning and ideally I want this info to be logged for all operations without warning and still being able to use operation limits turned on later with info logging still on

**Additional context**
This info could then also be sent to Studio so we could see that in the Operations view and know what is going on from there

**Comment by bnjjj** [comment]
I suggest to expose these data with metrics instead of logs or traces

**Comment by smyrick** [comment]
This was resolved by https://github.com/apollographql/router/pull/5433
