### ISSUE TITLE
Clarification on config option `traffic_shaping: { all: { timeout: 10s } }`

### ISSUE THREAD

**Issue by chadxzs** [apollographql/router#3441]
In the json schema output of `router config schema` in v1.15.1 it lists the option:

```yaml
traffic_shaping:
  all:
    timeout: 10s
```

and describes this timeout as "Enable timeout for incoming requests". It's not clear what this means. It's also not listed in the example config on https://www.apollographql.com/docs/router/configuration/traffic-shaping/#configuration. How is this different from `traffic_shaping: { router: { timeout: 10s } }`?

I'm looking for a way to configure a global subgraph request timeout.

**Comment by bnjjj** [comment]
Thanks for raising this @chadxzs I will forward this request to our doc team. I recently opened a [PR ](https://github.com/apollographql/router/pull/3456) related to timeout in traffic_shaping. We will try to add more details.

But TLDR: `all` means all subgraphs so all requests going from the router to subgraphs. And `router` means all requests going from the client to the router.
