### ISSUE TITLE
Coprocessor headers: true disables content-length

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3465]
When using coprocessors headers:false and body:true the content-length header is automatically populated.
If headers is set to true then content-length is not sent, presumably because the header is being zapped.
We should always send content length.

**Comment by o0Ignition0o** [comment]
Ok there are two bugs here:

  - content-length is not sent
  - when a coprocessor sends an invalid content length back in router-service, we use it (and we should not)

**Comment by o0Ignition0o** [comment]
This is fixed by #3802 (assuming I correctly understood the issue)
