### ISSUE TITLE
Automate RC release

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3467]
We currently have a set of manual instructions for releasing the router. They are slightly out of date considering that we generally create alphas/rcs these days and will convert to a real release once we are happy.

The automation should happen in circleci using a parameterized job. This will allow us to specify the desired target version.

The jobs should:
* Create RC automatically. This should require no intervention.
* Have a decision task to create a real release from an RC creating appropriate branches to allow for changelog editorial.
* Automatically detect when PRs are merged to allow the release flow to proceed.

**Comment by abernix** [comment]
Can we use https://github.com/apollographql/router/issues/2261 instead?
