### ISSUE TITLE
Consider adding binaries per-PR

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#3480]
**Describe the solution you'd like**

Given that a good chunk of the PRs are related to fixes/new features that require testing by external groups, or individuals with minimal ability to build Rust applications locally, it'd be nice to have access to prebuilt binaries for testing. 

In effect, have the PR have an artifact associated with it, either via Github actions or CircleCI. 

**Describe alternatives you've considered**

Using Rust locally. It becomes more complex if you need to support cross-compilation, however.

**Comment by garypen** [comment]
@lleadbet We now publish [nightlies](https://github.com/orgs/apollographql/packages) for our helm chart and container image.

Not the same as binaries for every PR, but possibly good enough. Also: team members can generate a build from a specific PR, which should be flexible enough for other use cases.

If that's good enough, could we close this issue down?
