### ISSUE TITLE
apollo_router_session_count metric is suspect

### ISSUE THREAD

**Issue by garypen** [apollographql/router#3485]
As described in: https://github.com/apollographql/router/issues/3392#issuecomment-1645524436 the metric seems to provide odd values at times. A negative session count is often reported and clearly that's not right.

**Comment by Geal** [comment]
reopening as this does not appear fixed, the metric is increasing indefinitely

**Comment by Geal** [comment]
(on second thought, closing again and opening a new issue, that might be better for our internal tracking)
