### ISSUE TITLE
start a configuration reload from a HUP signal

### ISSUE THREAD

**Issue by Geal** [apollographql/router#35]
Right now we support configuration reload through filesystem watch. This can be unreliable sometimes (missing udpdates), and it will try to reload files on each save even if we're not done modifying (the router should check the configuration file and schema before replacing, but that's another topic).

Should we support a signal to tell the router to reload its configuration? Specifically, SIGHUP is commonly accepted for that. That would fit well with tools like systemd and its `ExecReload` command

**Comment by SimonSapin** [comment]
Kind related: we (optionally) do a graceful shutdown on SIGINT (CTRL+C), do we also do that on SIGTERM?
