### ISSUE TITLE
Provide Router config yaml support to explicitly disable apollo studio usage reporting plugin

### ISSUE THREAD

**Issue by theJC** [apollographql/router#3514]
**Describe the solution you'd like**

Provide an explicit yaml configuration element to provide the ability to disable Apollo Studio usage reporting plugin.  

Presently the logic enables based on whether router is configured to use apollo studio schema registry, which we often do in our dev environments and pipelines for our subgraph producing teams.  

Quite often we want do not wish to have the requests we perform in dev or in load tests being reported into apollo studio for usage but use our QA environments schema as currently registered in apollo studio.

The use of the apollo studio schema registry should not be hard-coupled into the usage reporting plugin.

Additionally, the router documentation for plugins specifically indicates plugin configurations should have a enablement flag:
https://www.apollographql.com/docs/router/customizations/native/#2-define-your-configuration
> At a minimum, this configuration contains a boolean that indicates whether the plugin is enabled

**Describe alternatives you've considered**
Not use schema registry which puts removes the significant leverage we get from using the schema registry and adds significant burden and failure possibilities to toolchains and development pipelines used within our organization.

**Additional context**
Current code that controls whether its enabled or not:
https://github.com/apollographql/router/blob/eb5d889a15604fd6cd2f766bd2213a8d4ec43ded/apollo-router/src/plugins/telemetry/metrics/apollo.rs#L24-L31

**Comment by BrynCooke** [comment]
You can already use the `APOLLO_TELEMETRY_DISABLED` environment variable for doing this.
Create a new graph variant for load testing if you want to separate the total ops from your main prod traffic.

Note that we do consider total ops even for load testing as required reporting for the Router, and there is no way to disable this.
