### ISSUE TITLE
Apply plugin only for specific paths

### ISSUE THREAD

**Issue by consra** [apollographql/router#3523]
We have implemented a custom plugin for doing JWT verification and the supergraph is listening on the path /graphql. Every request received on the /graphql path will go through the plugin implemented by us. Is there a way to expose another path for the supergraph which will bypass the plugin ?

**Comment by abernix** [comment]
Hi! Good question.

The  `supergraph` > `path` option [supports wildcard characters](https://www.apollographql.com/docs/router/configuration/overview/#endpoint-path).

You can enable multiple paths via that configuration option and then just choose to **not** execute your plugin's logic within your plugin if the path does not match (or **does** match, depending on what you're looking for).

Hope this helps!
