### ISSUE TITLE
Allow disabling built-in `Telemetry` plugin

### ISSUE THREAD

**Issue by xuorig** [apollographql/router#3559]
It would be great to make the `Telemetry` plugin optional.

It currently doesn't play very well with implementations that don't use the built in `Executable` and/or folks setting up their own global subscribers / tracers. We'd also like to be able to customize the tags on the spans / have our own telemetry plugin instead.

Workaround today is to setup our own subscribers, not calling `init_telemetry` which sets up the globals/reload system. Which means `activate()` never truly sets up the plugin with its configuration. However, the traces are still emitted so we have to filter them out if we have our own telemetry plugin and services.

**Comment by BrynCooke** [comment]
This was implemented in #4244
