### ISSUE TITLE
Add support for container lifecycle events to helm chart

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#3563]
**Is your feature request related to a problem? Please describe.**
We are seeing a small number of 500/502 errors on every deployment of the router.

**Describe the solution you'd like**
Would like to experiment with the `preStop` lifecycle hook to delay the SIGTERM command being sent to the pod. This gives K8S some time to reconcile the state and take the pod service out of all relevant components.

https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Describe alternatives you've considered**
N/A

**Additional context**
Seems this has helped others, e.g https://github.com/apollographql/router/issues/3233#issuecomment-1601231852

**Comment by Meemaw** [comment]
@garypen any thoughts on adding this? I can prepare a PR as well.

**Comment by garypen** [comment]
@Meemaw It's a reasonable suggestion. I have just fixed #3521 which should help with this kind of issue, but I'm in favour of adding the functionality anyway if you have time to raise the PR.

Maybe wait for the next release of the router and see if #3521 improves things for you before doing the work if you are short of time.

**Comment by Meemaw** [comment]
@garypen If I understand that PR correctly, it will only affect health checks, which are done by kubelet. We see some degree of 500/502 responses from the ingress perspective which surely aren't health checks.

**Comment by garypen** [comment]
> @garypen If I understand that PR correctly, it will only affect health checks, which are done by kubelet. We see some degree of 500/502 responses from the ingress perspective which surely aren't health checks.

You are correct. It could make things better since we now indicate that the router is not ready in the JSON blob we return from the readiness check, but in fact, because the readiness probe just assumes "connecting == ready" this makes no difference. 

We should probably further enhance our liveness/readiness probes to use a command and parse the JSON output, but that's one for another day.
