### ISSUE TITLE
Generate license file from dependencies

### ISSUE THREAD

**Issue by abernix** [apollographql/router#36]
We should generate this file based on our dependencies — perhaps using [`cargo-about`](https://crates.io/crates/cargo-about)?) — and include this file in the packaged distributions.  Our `LICENSE` should also be included.

**Comment by o0Ignition0o** [comment]
I'm halfway through generating a license, and adding a CI step to make sure the license file is up to date.

Are we fine with an HTML output, with inline CSS?
