### ISSUE TITLE
Include specified correlation request header value(s) in all router log statements

### ISSUE THREAD

**Issue by danpayne17** [apollographql/router#3612]
**Is your feature request related to a problem? Please describe.**
In the gateway it was simple to establish a log context that included per request data to both provide context around the log statement but also to allow correlation of multiple log statements across the gateway, subgraphs and upstream services that all participated in the request. Things in the log context are typically correlation IDs, request properties and user properties.
**Describe the solution you'd like**
We would like to be able to specify a set of request header names and when present, they header name and value would automatically be added to every router log message.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abernix** [comment]
For reference, we believe that will land in `v1.35.0` which is _currently_ in release candidate stage (https://github.com/apollographql/router/releases/tag/v1.35.0-rc.0, atm!), but that RC does have one though currently have one known telemetry bug that we discovered during our larger deployment test runs.  We believe that will be fixed later today (and surface in `rc.1` 😄 )
