### ISSUE TITLE
RustSec advisories on rustls-webpki and webpki

### ISSUE THREAD

**Issue by Geal** [apollographql/router#3645]
The RustSec project flagged two of the router's dependencies:
- webpki: https://rustsec.org/advisories/RUSTSEC-2023-0052
- rustls-webpki: https://rustsec.org/advisories/RUSTSEC-2023-0053

So far we believe that the router is not affected, as it does not support client certificates.

A fix is in the works in https://github.com/apollographql/router/pull/3643, it will require updating a chain of other related dependencies

**Comment by o0Ignition0o** [comment]
We are waiting on a tonic update which will make it into the otel 0.20 update.

**Comment by Geal** [comment]
unblocked now that webpki was updated. The fix is in https://github.com/apollographql/router/pull/3728
