### ISSUE TITLE
[Helm]: Add ability to read router configuration from a file

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#3654]
**Is your feature request related to a problem? Please describe.**
When using k8s/helm, one has to define configuration object for the router. Similar/same thing is needed for local development. This makes for a lot of duplication.

**Describe the solution you'd like**
It would be great if helm chart supported reading the configuration from a `router.yaml` file. This would avoid a lot of duplication and ensure configs are in sync.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Geal** [comment]
Do you mean something like https://helm.sh/docs/chart_template_guide/accessing_files/ ?

**Comment by Geal** [comment]
since `Files.get` appears to work, we'll close this issue. Feel free to reopen if there are further ideas to discuss
