### ISSUE TITLE
APOLLO_ROUTER_NUM_CORES not documented

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#3679]
**Describe the solution you'd like**
Would like `APOLLO_ROUTER_NUM_CORES` to be properly documented and clearly answering these questions:
- What are the Apollo's recommendation on deployment sizes ~ a lot of smaller instances, vs fewer larger instances (to best utilise caching etc....)
- How does it behave by default? Does it take all cpus of the host?
  - If so, it should be documented that this should be set in relation to the cpu request/limits in k8s/helm

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Geal** [comment]
`APOLLO_ROUTER_NUM_CORES` is meant for debugging purposes: when benchmarking the router locally, limiting the router's available CPU allows us to easily overwhelm it with traffic, and profiling it without recording too much data.

For production deployments, CPU limits should be set in k8s or helm as you said. So far we are recommending a few large instances, that will reuse the cache properly and handle schema updates quicker

**Comment by Meemaw** [comment]
> `APOLLO_ROUTER_NUM_CORES` is meant for debugging purposes: when benchmarking the router locally, limiting the router's available CPU allows us to easily overwhelm it with traffic, and profiling it without recording too much data.
> 
> For production deployments, CPU limits should be set in k8s or helm as you said. So far we are recommending a few large instances, that will reuse the cache properly and handle schema updates quicker

How many threads/cores will the router use if there are no limits set in the k8s deployment. K8S limits have a lot of quirks, and we run our workloads without them. We use requests, but I'm not sure if the underlying crate (probably [num_cpus](https://docs.rs/num_cpus/latest/num_cpus/)) uses that.

**Comment by abernix** [comment]
It defaults to the number of cores, but indirectly.  I suspect you could also set [`TOKIO_WORKER_THREADS`](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#:~:text=This%20will%20override%20the%20value%20read%20from%20environment%20variable%20TOKIO_WORKER_THREADS.) in the environment, but we aren't planning to document this further or support it officially right now.
