### ISSUE TITLE
ADR: about naming rules, graphql module, prelude

### ISSUE THREAD

**Issue by cecton** [apollographql/router#368]
We already agreed on that in the past but it wasn't written down and I think we tend to forget. We should make an ADR.

1. We follow [Rust's naming guide](https://rust-lang.github.io/api-guidelines/naming.html). Therefore GraphQL words should be written `Graphql` just like HTTP word is usually written `Http` in other crates.
2. We don't prefix all our objects by `Graphql`, we want to use a module so things can be accessed by scope: `graphql::Request` vs `http::Request`
3. The prelude imports the `graphql` module automatically but no object directly (except traits).

**Comment by abernix** [comment]
@SimonSapin Do you think there's anything here worth considering in the API 1.0 stuff?  Have we stuck to this?

**Comment by abernix** [comment]
Closing this then.  Thanks!
