### ISSUE TITLE
v1.28.0 — version has been yanked to avoid escape character bug

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3680]
Using the following comment will within a graphql schema will prevent the Router starting.
  ```
  """
  '/\W/'
  """
  ```

This worked on 1.27.0.

**Comment by o0Ignition0o** [comment]
Here is a snippet that reproduces the issue:

```rust
use apollo_compiler::ApolloCompiler;
use apollo_compiler::AstDatabase;

fn main() {
    let stuff = r#"
    """
    '/\W/'
    """
    "#;

    let mut compiler = ApolloCompiler::new();
    let id = compiler.add_type_system(stuff, "schema.graphql");

    let ast = compiler.db.ast(id);

    let mut parse_errors = ast.errors();
    assert_eq!(
        "ERROR@5:27 \"expected definition\" \"\"\"\n    '/\\W/'\n    \"\"\"",
        parse_errors.next().unwrap().to_string()
    );
}
```

This test passes using apollo_compiler "=0.10.0" and fails using apollo_compiler "=0.11.0" and above.

The test fails with this output:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"ERROR@5:27 \"expected definition\" \"\"\"\n    '/\\W/'\n    \"\"\""`,
 right: `"ERROR@5:27 \"unexpected escaped character\" \"\"\"\n    '/\\W/'\n    \"\"\""`', src/main.rs:17:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SimonSapin** [comment]
I think the underlying cause is the same as https://github.com/apollographql/router/issues/3541

**Comment by abernix** [comment]
We yanked 1.28.0.  We will re-publish a new 1.28.x series as soon as this issue is resolved.  [v1.27.0](https://github.com/apollographql/router/releases/tag/v1.27.0) is again the latest version as of this time.  iThanks for your patience!

**Comment by goto-bus-stop** [comment]
Fix in https://github.com/apollographql/router/pull/3675

**Comment by abernix** [comment]
Thank you @goto-bus-stop! We have released https://github.com/apollographql/router/releases/tag/v1.28.1 with the fix.  It takes the place of our 1.28.0 recommendation and we've updated the release notes for v1.28.1 to include all of v1.28.0's notes.
