### ISSUE TITLE
Memory leak on router reload

### ISSUE THREAD

**Issue by xuorig** [apollographql/router#3686]
We've recently bumped the router from `1.23.0` to `1.27.0`. After the deployment, our instances started to get killed due to OOM errors within a day. 

<img width="731" alt="Screenshot 2023-08-27 at 6 15 11 PM" src="https://github.com/apollographql/router/assets/1919498/c2b100cf-5f24-4c8a-8ce6-d3e19eb0e4b0">

*(Ignore the temporary drops as these were due to profiling)*

**Here is a heap profile done by enabling jemalloc profile and comparing to base period, about an hour apart: https://github.com/apollographql/router/assets/1919498/26753a47-fa8e-4379-8612-13e370417da6**

Meanwhile my colleague Stephen @fotoetienne bisected to what seems this PR:  https://github.com/apollographql/router/pull/3341

There seems to be something retaining memory between restarts, most likely schema objects / the salsa DB behind apollo-compiler.

I did notice other things:

 - [`Notify` tasks](https://github.com/apollographql/router/blob/dev/apollo-router/src/notification.rs#L559) are being added and never dropped. Running `tokio-console` revealed more than 20 of those tasks on a router running locally for an hour.
 - The only way I see these tasks not [exiting their loop](https://github.com/apollographql/router/blob/dev/apollo-router/src/notification.rs#L638) is if the sender is never dropped.
 - If the sender is never dropped, that probably means `Notify` is not getting dropped either, which means `Configuration` are probably laying around as well.
 - Then I noticed this piece of code: https://github.com/apollographql/router/pull/3341/files#diff-67b9590c5fe973fea43d5bc5a29f37da7b961823665694909f45a00ec50e873dR174-R176
   - The PR added a circular reference. Configuration has a notify object, and notify possibly has a reference to the `Configuration` in its `router_broadcasts`.

Early testing seems to indicate that removing this circular reference at least stops leaking Notify tasks. But I haven't confirmed 100% this is the source of the leak / increased memory usage just yet. Putting my notes out here for now, but will continue investigating tomorrow morning.

**Comment by BrynCooke** [comment]
Thank you for the detailed investigation. We'll get a fix in ASAP.

**Comment by xuorig** [comment]
Thanks @BrynCooke!

Here's what happens when a [`Weak` reference is used instead](https://github.com/apollographql/router/commit/2842b935c8f2205c73dfb093ff41be9c8ae3f918)

<img width="717" alt="Screenshot 2023-08-28 at 8 23 21 AM" src="https://github.com/apollographql/router/assets/1919498/36a6f97f-0729-4d34-b389-02be347a62d8">

**Comment by o0Ignition0o** [comment]
This may be a case of YAGNI, but I have hopes we will not need to cut all subscriptions on schema updates eventually, which is why we kept the spawned task around.

Would you mind opening a PR with the Weak reference patch?

**Comment by fotoetienne** [comment]
> I have hopes we will not need to cut all subscriptions on schema updates eventually, which is why we kept the spawned task around.

@o0Ignition0o Agreed. Cutting all subscriptions on schema update could cause a thundering herd when all subscribers reconnect at once

**Comment by abernix** [comment]
Could this be closed with the (recent!) release of https://github.com/apollographql/router/releases/tag/v1.28.1 which includes the #3692 from @xuorig?

**Comment by abernix** [comment]
Actually, I'll close this, but happy to re-open if the answer is "nah". 😺   Thank you for the PR!

**Comment by xuorig** [comment]
Thanks @abernix , yep this is indeed fixed using `1.28.1`
<img width="731" alt="Screenshot 2023-08-28 at 5 24 16 PM" src="https://github.com/apollographql/router/assets/1919498/8cb6cc97-3638-465d-9147-7602768d79a8">
