### ISSUE TITLE
Router-Datadog spans tagging

### ISSUE THREAD

**Issue by JulianRojasBet** [apollographql/router#3702]
**Is your feature request related to a problem? Please describe.**
There is not currently possible to tag Router spans when [using Datadog for tracing](https://www.apollographql.com/docs/router/configuration/tracing/#using-datadog).

**Describe the solution you'd like**
It would be great to have the ability to add tags to Apollo Router spans (either one or all of them) from values on the request headers or generally for any source. So that way, it is possible to enhance our Datadog observability and metrics by filtering/grouping spans using those tags. e.g knowing which user-agents hits our API the most.

**Describe alternatives you've considered**
Haven't found any customization or way to do it by using rhai scripts

**Comment by Geal** [comment]
hi, thanks for the report. We are aware of this need, and looking into it. You can follow the development inhttps://github.com/apollographql/router/issues/3226

**Comment by BrynCooke** [comment]
This is available in the version 1.35

https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/spans#attributes

Spans can now be completely customized via yaml.

**Comment by BrynCooke** [comment]
This has been implemented as part of advanced telemetry selectors.
https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/selectors/
