### ISSUE TITLE
Query planning cache warm up improvements

### ISSUE THREAD

**Issue by Geal** [apollographql/router#3704]
the [warm_up_queries option](https://www.apollographql.com/docs/router/configuration/in-memory-caching#caching-query-plans) takes the most used queries from the in memory cache, and creates query plans for them when a new schema comes in, before switching the router to this new schema. This makes schema updates much smoother, because it won't delay most of the queries coming, since they already have a query plan available.

It could benefit from a few improvements though:

* [x] #3767 
* [x] #3766 
* [x] #3621
* [x] #3769
* [x] #3770
* [x] #3815

Follow up:
* [ ] #3768
* [ ] #3771

**Comment by Geal** [comment]
action: break this down in smaller tickets

**Comment by abernix** [comment]
I'm going to close this umbrella issue now since there are so _few_ sub-tickets left that aren't completed.  We can track the remaining two on their own.
