### ISSUE TITLE
Improve benches in the project

### ISSUE THREAD

**Issue by cecton** [apollographql/router#372]
Right now we have only one benchmark and it's not even compiling anymore.

Those localized benchmarks are useful and complementary to bigger scoped benchmarks like Bryn did with the perf tests. It allows to test the impact on specific changes of specific parts of the project. I believe this should be enriched.

In any way we shouldn't keep this in a state of half-done. Either we go for it and make it good or we drop them entirely.

**Comment by abernix** [comment]
Only having one benchmark is indeed a bit problematic and something we should improve.  It's worth noting that I'm under the impression that the benchmark does compile if you go _into_ the benchmark directory, but doesn't work from the root of the project (which is indeed, still not ideal. 😸 )

**Comment by abernix** [comment]
Benchmarks are now compiling!
