### ISSUE TITLE
Optional prefix for Redis cache keys

### ISSUE THREAD

**Issue by nmoutschen** [apollographql/router#3765]
**Is your feature request related to a problem? Please describe.**

I'd like to use [Redis ACLs](https://redis.io/docs/management/security/acl/) for a shared cluster, which would restrict which keys a Router can/cannot modify.

**Describe the solution you'd like**

As a user, I could add a configuration parameter in the router configuration YAML that will add a prefix to all keys. If this is not present, it will default to the current behaviour.

**Describe alternatives you've considered**

Using a dedicated cluster for the Router, but this is not economical.

**Additional context**

N/A

**Comment by abernix** [comment]
If you could propose a set of YAML configuration changes here that we could align on, we'd be happy to consider a PR here. 😄
