### ISSUE TITLE
Redirect to Studio doesn't preserve HTTP scheme

### ISSUE THREAD

**Issue by abernix** [apollographql/router#380]
Currently, when browsing to the endpoint with a browser (technically speaking, on account of the presence of `Accept: text/html`), we redirect to Studio Explorer Sandbox.  This seems to work well when the scheme is `http://`, but if the Router is running on an `https://` endpoint, then the endpoint URL that is passed to Studio Explorer as the `endpoint` doesn't keep using `https://`, instead switching to using `http://{domain}` (should be `https://domain`).

Since the `https://` domains cannot talk to `http://` (by browser spec; for security), Studio Explorer cannot communicate with the Router without manually changing the endpoint in the Studio Explorer interface to `https://`.

**Comment by abernix** [comment]
It's _plausible_ that we'll need to use `x-forwarded-proto` to make the right choice here.  In other words, if the router is aware of it being `https`, that's potentially good enough reach to assume it's `https`.  **However**,`x-forwarded-proto` is present, then perhaps that should take the cake.

**Comment by abernix** [comment]
It's also plausible that we should use a browser-based redirect and have a nice landing page like Apollo Server does.  We merely need to serve a small bit of [boilerplate HTML](https://github.com/apollographql/apollo-server/blob/c801a81466c0ab2d6a3bd38e72e59740150ea49f/packages/apollo-server-core/src/plugin/landingPage/default/index.ts#L155-L210) that loads an interface from a CDN.  (The rest of that linked file probably makes sense to look at too.)

**Comment by medelman17** [comment]
Another solution would be to have the explorer team/implementation look at the `referer` header on the redirect and make the decision re: what the correct endpoint is at that time rather than having to supply the endpoint as a query variable. This, imho, would be cleanest and get rid of the above coupling.

**Comment by abernix** [comment]
If you were my browser, the `referer` header would always be blank unless I setup an exception for you. 😉 

This will be resolved if we go with #68, which I've updated #388 to mention.

**Comment by abernix** [comment]
Fixed indirectly by https://github.com/apollographql/router/pull/526
