### ISSUE TITLE
Failing to build router on 1.30.0

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#3834]
**Describe the bug**
There seems to be some build changes in `1.30.0`.

```sh
error: failed to run custom build command for `libz-ng-sys v1.1.12`

Caused by:
  process didn't exit successfully: `/Users/meemaw/workspace/graphql-federation/target/debug/build/libz-ng-sys-e7168e344411dcc8/build-script-build_zng` (exit status: 101)
```

Any ideas as to what might have changed that caused this?

**Comment by abernix** [comment]
What is the last version that worked for you?

**Comment by bnjjj** [comment]
Hey we recently upgraded the Deno version [ which introduces a prerequisites](https://github.com/denoland/deno/blob/06ece5645c07471a740af8ee622da970845daae7/Cargo.toml#L93) to [build the router](https://www.apollographql.com/docs/router/customizations/custom-binary#prerequisites), you know need to install [CMake 3.5.1 or later](https://cmake.org/download/) to build the router. Feel free to close this issue if it’s fixed

**Comment by Meemaw** [comment]
Was there any commit with corresponding build changes you had to do? I assume `Dockerfile` also had to change.

**Comment by Meemaw** [comment]
Can build the router now, but getting the following error while trying to run it (via Docker).

```sh
/dist/router: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or director
```

**Comment by Meemaw** [comment]
Installing `cmake` fixed things, now getting the following error when trying to run it (via docker)

```sh
/dist/router: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

Are you aware on any recent changes related to openss/rust build targetsl?

Trying to upgrade router from 1.27.0 -> 1.30.0, and Rust from 1.71.1 -> 1.72.0

**Comment by garypen** [comment]
We updated our final layer to use `bookworm`, so closing this again. At some point in the future, it would be more ideal to tie our example file rust build image to the same image of the final layer, but this is only an example and it's easy to fix manually as required.
