### ISSUE TITLE
Allow throttling of query plan warmup

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3836]
When the router reloads, the router may warm up by planning last known queries. This can be a CPU intensive operation, so we should consider adding some sort of throttling mechanism to prevent the router being overwhelmed.

This will need configuration yaml design to implement.

**Comment by Geal** [comment]
duplicate of https://github.com/apollographql/router/issues/3768, no?

**Comment by BrynCooke** [comment]
Yep, closing
