### ISSUE TITLE
Query planning caching as a layer.

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#384]
Be nice if this caching layer was not tied to query planning at all so it could be used for caching other aspects of the pipeline.
Suggest modifying https://github.com/apollographql/router/blob/geal-all-along-the-tower-service/apollo-router-core/src/layers/cache.rs to support caching of errors,

**Comment by o0Ignition0o** [comment]
dropping this for now because it IMO requires us to have a nice #457 story

**Comment by abernix** [comment]
This could be done, but we didn't come to an agreement about how we were going to do caching.  Distributed caching might come into the picture here, but we'll evaluate this when we have the caching conversation as a possible thing to cache.
