### ISSUE TITLE
Router exits when using monotonic_counter on ARM

### ISSUE THREAD

**Issue by yanns** [apollographql/router#3860]
**Describe the bug**

Inside a plugin written in rust, when I use [`monotonic_counter`](https://www.apollographql.com/docs/router/customizations/native#using-macros), the router stops at this point.
No stack trace. It exits with code 1.
It seems to be reproducible only on new mac.

**To Reproduce**
Inside the plugin, using `monotonic_counter`, like:
```rust
            tracing::info!(
                monotonic_counter.caffeine_cache_miss_total = 1,
                cache = self.cache_name.as_str()
            );
```

Starting the router with the info RUST_LOG:
```bash
RUST_LOG="info,apollo_router::info" APOLLO_ROUTER_SUPERGRAPH_PATH=schemas/ctp-supergraph.graphql APOLLO_ROUTER_CONFIG_PATH=config/router.yaml cargo run
```

When reaching the `tracing::info!(monotonic_counter `, the router exits.
No error, no stacktrace.

Naive assumption:
`tracing::info!(monotonic_counter ` must have some condition, like if not exists, then do that, else do that.
It might be a concurrency issue only on ARM because it is using different memory barriers. 

**Expected behavior**
The router should not exit.

**Desktop (please complete the following information):**
 - OS: Macbook Pro Apple M1 Max, macOS 13.5.2
 - Version 1.30.0

**Alternatives**
I've tried to use the [metrics crates](https://lib.rs/crates/metrics) instead, but it does not seem that the router handles this.
There was no issue with this crate, but also no metrics.

**Comment by garypen** [comment]
I hit this problem a couple of hours ago. You get some useful information if you run at log level DEBUG.

I think the answer is to change your log line to:
```
tracing::info!(
                monotonic_counter.caffeine_cache_miss_total = 1u64,
                cache = self.cache_name.as_str()
            );
```
If you verify my suggestion works, I'll see if we can figure out a good way to address this.

**Comment by garypen** [comment]
We need to understand if this will be fixed when the new metrics recording framework lands. If so, we shouldn't address this problem now.

**Comment by garypen** [comment]
#3865 better captures the nature of this problem, so closing this one as a duplicate.
