### ISSUE TITLE
Aliased entity fields incorrectly overwritten on field/alias naming collisions

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/router#3874]
Original issue reported in `@apollo/gateway`: https://github.com/apollographql/federation/issues/2770
Related fix: https://github.com/apollographql/federation/pull/2776

The related code in router _appears_ to have the same issue, but I haven't created a test to reproduce.

**Comment by Geal** [comment]
we validated that the router works correctly for this in https://github.com/apollographql/router/pull/3975/
