### ISSUE TITLE
Testing Studio reporting without modifying the configuration

### ISSUE THREAD

**Issue by Geal** [apollographql/router#3883]
In #3871, we had an issue when APOLLO_KEY and APOLLO_GRAPH_REF where set but `telemetry.apollo` was not defined in the configuration. In that case, Studio reporting should still work.
As it stands now, we have no way of testing this. The Studio reporting integration tests rely on creating a HTTP server and directing the router to send the reports there:

https://github.com/apollographql/router/blob/dfed65001f274a0720c73a2324320bd33f0fbba5/apollo-router/tests/apollo_reports.rs#L69-L74

Unfortunately, this creates `telemetry.apollo` in the config, so it cannot test the issue we saw.
We have the same problem with the environment variable: the environment expansion creates the configuration entry:
https://github.com/apollographql/router/blob/dfed65001f274a0720c73a2324320bd33f0fbba5/apollo-router/src/configuration/expansion.rs#L97-L101

We need a way to test Studio reporting without modifying the configuration object

**Comment by BrynCooke** [comment]
Suggest we add an otel metric for sending telemetry to studio. Then we add a test for that otel metric. This can be done using the existing integration test harness so would be quick to implement.
