### ISSUE TITLE
make sure that the schema is not replaced by an invalid new schema

### ISSUE THREAD

**Issue by Geal** [apollographql/router#39]
currently we will generate a new graph from a schema, even if it is invalid: https://github.com/apollographql/router/blob/2cc92b110acf2f5858aad2854b11ccc9ceba84a8/crates/apollo-router/src/graph_factory.rs#L13-L20

The schema update feature should refuse invalid schema instead of replacing the existing one, with an error log (not a panic)

**Comment by garypen** [comment]
I think this is now handled by the state_machine transitions:

https://github.com/apollographql/router/blob/82561ea9252f989ed5602b73c44267591bb503eb/apollo-router/src/state_machine.rs#L175

If the attempt to load_subgraphs() fails, then an error is logged and the server continues to use the existing router.

**Comment by Geal** [comment]
the schema was already parsed and validated when we reach this code, and #136 provides good error logs for those, so we can close this issue
