### ISSUE TITLE
Add topologySpreadConstraints to Helm chart

### ISSUE THREAD

**Issue by sylr** [apollographql/router#3903]
**Describe the solution you'd like**

Add possibility to define `topologySpreadConstraints` in the helm chart.

**Describe alternatives you've considered**

None.

**Additional context**

https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by smyrick** [comment]
Duplicate of https://github.com/apollographql/router/issues/3891
