### ISSUE TITLE
Coprocessor with streaming responses doesn't work

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#4013]
The logic for supporting deferred responses can't work.

The issues is here: https://github.com/apollographql/router/blob/cf4a79a126132eb30e368bdf2277a89278ae2a9b/apollo-router/src/plugins/coprocessor/supergraph.rs#L431-L432.

This will always panic as the wrong builder is used for the stage

**Comment by garypen** [comment]
I think your description is wrong in the issue. It's supergraph logic that is mistakenly using a router builder, so the impact is on the new supergraph coprocessor.

It should be:

Reproduction
Configure coprocessor.supergraph_response
Send a query to the router that uses @defer
Router will panic.

Mitigation
Anyone who is using a coprocessor with supergraph_response configured should explicitly disable defer and not use subscriptions.
OR
Disable coprocessor supergraph_response

**Comment by BrynCooke** [comment]
You are right, I've updated it.

**Comment by o0Ignition0o** [comment]
https://github.com/apollographql/router/pull/3647 is where the bug was introduced, so router [1.31.0..=1.32.0] are affected
