### ISSUE TITLE
Custom metrics not working with Datadog after 1.32.0

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#4015]
**Describe the bug**
After upgrading to 1.32.0 we noticed custom metrics are no longer emitted.

Code might look like this:
```rust
let meter = global::meter("graphql-federation");
let hit_counter = meter.u64_counter("hit").init();
hit_counter.add(1, &[]);
```

**Expected behavior**
Custom metrics are reported.

**Comment by o0Ignition0o** [comment]
Hi,
The recommended way to add custom metrics is documented [here](https://www.apollographql.com/docs/router/customizations/native#add-custom-metrics).

Can you give it a try and let us know if it works?

Thanks!

**Comment by Meemaw** [comment]
That works indeed.

Thanks!
