### ISSUE TITLE
bug: multi-value headers don't propagate to subgraphs correctly

### ISSUE THREAD

**Issue by nmoutschen** [apollographql/router#4153]
**Describe the bug**

When sending multiple headers with the same name but different values to the Router, there's only one header entry that remains in the request to the subgraph

**To Reproduce**
1. Setup a test router using the experimental_logging functionality and header propagation set to forward all headers, with a subgraph that logs all requests
2. Send a request with 2 headers using the same name
3. See that the supergraph request headers have 2 headers of the same name
4. See that the subgraph request headers only have 1
5. See that the subgraph only sees one too

**Expected behavior**

Header propagation should propagate all values for multi-value headers.

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by garypen** [comment]
Probably need to replace `insert()` with `append()` here:
