### ISSUE TITLE
Prometheus: the default service name and namespace changed 

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#4169]
The docs in https://www.apollographql.com/docs/router/configuration/metrics/#using-prometheus are unfortunately out of date, possibly since #4034.

Moreover it looks like the prometheus metrics don't add the service_name in the tags anymore.

We need to investigate and either update the documentation or fix this.

```
target_info{process_executable_name="router",service_name="unknown_service:router",service_version="1.33.2"} 1
```

It seems to be in line [with the otel specification](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#resource-attributes-1), we probably need to update the documentation.

**Comment by o0Ignition0o** [comment]
It looks to me like the docs was updated, @BrynCooke can you confirm and close the issue if it's the case? 🙏

**Comment by BrynCooke** [comment]
Let's close this. All the telemetry docs are about to change anyway.
