### ISSUE TITLE
Add examples for new API

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#419]
Create an examples directory, include some basic stuff like a plugin and header manipulation.
Show code and YAML examples.

- [ ] #645
- [ ] #646
- [ ] #647
- [ ] #648
     subgraph `a` returns `cache-key: one-way` and subgraph `b` returns `cache-key: or-another`, and the response key returned to the client is `surrogate-cache-key: one-way,or-another`
- [ ] #649
     e.g., `Cookie: yummy_cookie=choco; tasty_cookie=strawberry` 👉  make it a header `tasty_cookie: strawberry` to a subgraph.
- [ ] #650
~- [ ] logging (coming soon)~
- [x] JWT (Rust plugin, in `examples/` directory with YAML configuration)
- [ ] #644

**Comment by o0Ignition0o** [comment]
we probably want to have one example for each approach laid out https://github.com/apollographql/router/discussions/488#discussion-3880824:

```
1 - Propagate headers => use the HeadersPropagationLayer and configure it with yml
2 - Hook at one(1) specific spot of the lifecycle => Write a layer
3 - Hook at several spots of the lifecycle and use global (whole program) state => Write a plugin and store it in self
4 - Hook at several spots of the lifecycle and use a local (query) state => Write a plugin and communicate through context
```

1 - Headers propagation, (maybe cost modelling eventually?)

2 - logging / metrics counter (how many times a subgraph is being invoked / query executed / Cost modelling (cc Lenny's work) + Application layer rate limiting 

3 - OTEL / custom telemetry (How to persist it across restarts btw?)

4 - JWT / Auth example / RHAIScript / Something else ?

**Comment by o0Ignition0o** [comment]
- Refactor current plugin examples so they call router::main() instead of building one
- Create an example that does the current examples "main.rs" job.
- add comments explaining that the "build your own router" / "compose your tower::Service" are not required if you only want to write a plugin

**Comment by o0Ignition0o** [comment]
```Extension: if a subgraph returns something specific, change the http status code

Surrogate cache key from fastly ? -> combine em all and join em with commas

Inbound cookie changed from a cookie key / value pair to a header

Cookie : name "Jeremy" => value "foobarbaz" => make it a header "x-jeremy": "foobarbaz"

Go through our homebuilt plugins and document them better

Redacting email address / api keys from response errors```

**Comment by abernix** [comment]
Closing as these have been broken down into individual issues.
