### ISSUE TITLE
studio usage ingress reporting improvements

### ISSUE THREAD

**Issue by garypen** [apollographql/router#422]
NB: There is some overlap here, so be aware of options to streamline fixes. For instance, using retry crate might eliminate need for backoff crate or explicitly processing errors (assuming retry crate does "the right thing").

- [x] Distinguish between client and server errors and handle appropriately.

  apollo-spaceport/src/server.rs

  When submitting data to the ingress.
  The existing TS server distinguishes between client errors (4xx) and server errors (5xx). If the error is a 4xx error, then fail *without* retrying. 

- [ ] Use backoff crate instead of own implementation in spaceport.

  apollo-spaceport/src/server.rs

  Existing backoff logic is weak. Consider using [backoff crate](https://docs.rs/backoff/latest/backoff/index.html)

- [ ] Use retry crate instead of own implementation in spaceport.

  apollo-spaceport/src/server.rs

  Consider using [retry crate](https://docs.rs/retry/latest/retry/)

**Comment by abernix** [comment]
Let's agree to re-factor this if we find out that our existing logic isn't working out.  I could imagine that we'll have our own logic based on Studio that we'll need to comply with anyhow, based on some headers or other things.
