### ISSUE TITLE
add namespacing to redis keys

### ISSUE THREAD

**Issue by Geal** [apollographql/router#4247]
it would allow authorization based on a prefix, for multitenant clusters

**Comment by BrynCooke** [comment]
Just been reading and the term in the the redis docs is `keyspace`, so let's align around that.

**Comment by Geal** [comment]
keyspace refers to the entire set of keys. Namespace is commonly used in Redis, and well understood elsewhere https://redis.com/blog/5-key-takeaways-for-developing-with-redis/
