### ISSUE TITLE
client identity: allow configuring default header names

### ISSUE THREAD

**Issue by garypen** [apollographql/router#426]
[Client Segmentation](https://www.apollographql.com/docs/studio/metrics/client-awareness/#using-apollo-server-and-apollo-client) is supported by the router. However, this mechanism also support [configuration of the headers](https://www.apollographql.com/docs/studio/metrics/client-awareness/#advanced-apollo-server-configuration) used to identify clients. The router does not support this configurability and only recognises the default header names.

Should we replicate this behaviour into the router or is it reasonable to require clients to use the specified default names?

**Comment by abernix** [comment]
The headers which need configuration are located here:

https://github.com/apollographql/router/blob/9e9786191e4638e4d35dc068293efe8850403ba7/apollo-router/src/warp_http_server_factory.rs#L436-L447

**Comment by abernix** [comment]
Of course, part of this involves designing and agreeing on a place for it in the configuration.
