### ISSUE TITLE
clarify `ReportHeader` source system in usage reporting

### ISSUE THREAD

**Issue by garypen** [apollographql/router#427]
NB: This isn't an issue with existing products, since there is no external collection capability.

In the case where there is an external spaceport which is processing data from multiple routers (each on, potentially, different hosts) should we be reporting details about the system where the spaceport is executing or about the system where the routers are executing? (I'm fairly sure we want the latter, although currently we get the former).

At some point in the future, assuming that we do want the latter, I intend to pass in a ReportHeader with each batch of data (or have a register that associates a router with a ReportHeader in a collector or ...). Anyway, when that thinking is clarified this problem will disappear.

**Comment by abernix** [comment]
We definitely want the latter!

**Comment by abernix** [comment]
The reworking of metrics into `spaceport` has rendered this obsolete..  Closing!
