### ISSUE TITLE
vendor decompression code from async-compression

### ISSUE THREAD

**Issue by Geal** [apollographql/router#4283]
we have fixes to apply in a timely manner that we'll contribute to the project, they can release it at their own pace

**Comment by garypen** [comment]
I'll try a source fix first: https://github.com/Nullus157/async-compression/pull/255 and intern it if timing doesn't work out.

**Comment by Geal** [comment]
marking this one as blocked since async-compression has not made a release yet

**Comment by bnjjj** [comment]
We have the fix in the new async-compression release https://github.com/apollographql/router/commit/9ef02a13b0def880608ebbf4b5c6800473c3a469
