### ISSUE TITLE
spurious metrics data seems to be generated since otel 0.21.0

### ISSUE THREAD

**Issue by garypen** [apollographql/router#4301]
In router v1.35.0-rc.0 we have observed that there are a few new problems with metrics:

 - Some metrics are completely missing attributes: e.g. coprocessor
 - Some metrics have additional attributes (services)

This must be investigated.

**Comment by garypen** [comment]
We tested a rollback to `0.20.0` in our test environment and found that the missing attributes problem disappeared. We should rollback to `0.20.0` for the next router release.

**Comment by jtescher** [comment]
Interesting. There were some issues [fixed in 0.21.1](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/CHANGELOG.md#v0211), you could try re-running your tests with the latest version to see if the issues are still present.
