### ISSUE TITLE
Router filters errors on input params and long paths

### ISSUE THREAD

**Issue by michaelboke** [apollographql/router#4340]
The router filters too aggresively on errors when they have a path that contains the input params or the path is not exactly in what was requested. 

In one of my usecases i try to run a mutation with invalid data. this will trigger a validation  error in my subgraphs code. The error path contains the exact path to the param that is wrong. (and this could be the problem)

An example of the mutation I run with an invalid uuid value:
```
mutation CreateLocation($input: NewLocation!) {
  createLocation(input: $input) {
    id
    accountID
    name
  }
}
```

The provided variables for the $input
```
{
  "input": {
    "accountID": "invalid"
    "name": "test"
  }
}
```

The input type for NewLocation
```
input NewLocation {
  accountID: UUID!
  name: String!
}
```

Expected response from router (is the response i got from my subgraph)
```
{
  "data": null,
  "errors": [
    {
      "message": "invalid UUID",
      "path": [
        "createLocation",
        "input",
        "accountID"
      ]
    }
  ]
}
```

Actual response from router
```
{
  "data": null,
}
```

I noticed when the error path only returns 1 element with the operationName the error is included in the router response.
```
{
  "data": null,
  "errors": [
    {
      "message": "invalid UUID",
      "path": [
        **"createLocation"**
      ]
    }
  ]
}
```

For a quick test I changed the method `contains_error_path` in [query.rs](https://github.com/apollographql/router/blob/ce72cd21cc02f8232eddd486c2fbb145278c860b/apollo-router/src/spec/query.rs#L1044) to always return a match, and now it always returns my errors in the router. This is not the solution but it indicates that this filtering here needs some work.
```
pub(crate) fn contains_error_path(
        &self,
        operation_name: Option<&str>,
        label: &Option<String>,
        path: &Path,
        defer_conditions: BooleanValues,
    ) -> bool {
  true
}
```

I tried to come up with a solution, but i'm still not rusted enough to fully understand what is happening here :sweat_smile: hope someone could help me.

I also have the following option in my router config enabled to always return the errors
```
include_subgraph_errors:
  all: true
```

**Comment by Geal** [comment]
unfortunately, error paths are only defined by the GraphQL spec to point at paths in the response, not in the query. Path to input arguments were still accepted in the past, before we implemented `@defer` and subscriptions. But once we had these features, we had to be strict about error path matching, so the errors could be dispatched to the right response.
If you put those input errors in extensions though, they will be transmitted unmodified

**Comment by michaelboke** [comment]
Ah id do get it, i refreshed my brain and read the specs about the error return path. And you are totally right that it should only contain the path for errors in the response.

Unfortunate i'm using gqlgen in go that is reporting serialization errors on and so on with a fully defined path. I should raise the question there to simplify the path. 

Thanks  @Geal  for clearing this up.
