### ISSUE TITLE
Router not GraphQL spec compliant with Abstract spreads in object scopes 

### ISSUE THREAD

**Issue by ebylund** [apollographql/router#4348]
The functionality described in [section 5.5.2.3.2 of the GraphQL Spec](https://spec.graphql.org/October2021/#sec-Abstract-Spreads-in-Object-Scope), Abstract spreads within an object scope do not appear to work in Apollo Router. All examples shown below are with the published Apollo Router executable **v1.35.0**

## Unions with no nested types
Using a schema as follows, a union is made on two objects, Cat and Dog. Both objects are similar to one another, and a field under query is created to return a Dog object

```graphql
type Query {
  dog: Dog
}

type Dog {
  name: String!
  nickname: String!
  barkVolume: Int
}

type Cat {
  name: String!
  nickname: String!
  meowVolume: Int
}

union CatOrDog = Cat | Dog
```

The following is the response from a query to a [gqlgen](https://gqlgen.com/getting-started/) server, that specifies the root level dog field and spreads the union CatOrDog under it.

![image](https://github.com/apollographql/router/assets/7840285/aa1f75e9-9485-4c1f-8f23-6898e0f4db25)

The Apollo Router returns a similar response for the same schema, but adds on the field unique to the Cat type, meowVolume to the response payload even though it does not exist on type Dog

![image](https://github.com/apollographql/router/assets/7840285/0e003e71-6dc9-48a1-b9fd-70021c3d9f25)

**Expected behavior**
The router should not be sending back `meowVolume` in this case.

## Union with one nested type
The schema is modified to instead nest Dog under an arbitrary wrapper object called NestedDog. The union is now on Cat and NestedDog

```graphql
type Query {
  nestedDog: NestedDog
}

type NestedDog {
  dog: Dog!
}

type Dog {
  name: String!
  nickname: String!
  barkVolume: Int
}

type Cat {
  name: String!
  nickname: String!
  meowVolume: Int
}

union CatOrDog = Cat | NestedDog
```

The query was modified accordingly, and making the query below to a gqlgen server results in the following response:

![image](https://github.com/apollographql/router/assets/7840285/93e8b017-7d8d-4602-9987-ebcdabdaeffd)

However, the Apollo Router seems to completely null out the Dog type for the same query:

![image](https://github.com/apollographql/router/assets/7840285/affd4f2b-08da-401c-af01-86ce72dcfffa)

Removing the spread on the Cat object fixes this issue and allows the response to pass through successfully

![image](https://github.com/apollographql/router/assets/7840285/1c8a647d-0db8-4233-92a7-b8e696ebfe05)

## Additional Context
The request sent to the subgraph (gqlgen server) and response received from the subgraph were logged using a rhai script (this holds for both queries tested under the union with nested type):

**Subgraph Request:**
```graphql
query test__example__0 {
  nestedDog {
    __isCatOrDog: __typename
    dog {
      name
      nickname
      barkVolume
    }
  }
}

```
**Subgraph Response:**
```json
{
 "data": {
   "nestedDog": {
     "__isCatOrDog": "NestedDog",
     "dog": {
       "barkVolume": 7,
       "name": "Fido",
       "nickname": "Fi"
     }
   }
 }
}

```

**Comment by abernix** [comment]
👋  Just noting that #4401 and #4402 are fixes in progress for this, currently pending review.  Thanks for opening this!

**Comment by abernix** [comment]
@ebylund This is available to try in https://github.com/apollographql/router/releases/tag/v1.37.0-rc.0!
