### ISSUE TITLE
JWT Validation with Dynamic Signing Keys and Apollo Router

### ISSUE THREAD

**Issue by cyberhck** [apollographql/router#4357]
**Describe the bug**
Apollo Router currently encounters issues when validating JWTs signed with keys generated within the `poll_interval` timeframe. This behavior hinders systems that dynamically generate signing keys from leveraging Apollo Router's JWT authorization capabilities.

**Problem:**
- When a request containing a JWT signed with a newly generated key (within the `poll_interval`) arrives, Apollo Router deems the JWT invalid, even though the signing key is valid and publicly available.
- This limitation prevents systems with dynamic key rotation from utilizing Apollo Router's JWT authorization functionality.

**To Reproduce**
1. Start router with `poll_interval` set to 5 mins for now
2. Trigger a key rotation on your authentication service and generate a new JWT.
3. Use this JWT with JWT authentication feature on apollo router

**Expected behavior**
Upon receiving a request with a JWT signed by a key not yet cached locally, Apollo Router should:
- Attempt to fetch the latest JSON Web Key Set (JWKS) from the configured URL.
- Validate the JWT using the retrieved public key instead of immediately rejecting the request due to an unknown key.
This approach ensures that even with dynamically generated keys, valid JWTs are accepted after the JWKS is fetched.

**Desktop (please complete the following information):**
 - Kubernetes: GKE
 - Version: unsure
 - Apollo router version: 1.35.0

**Alternatives Considered**
- **Triggering JWKS Fetch via HTTP Endpoint**: This approach is unreliable in distributed environments like Kubernetes due to potential for inconsistent key availability across replicas.
- **Delaying JWT signing**: This introduces unnecessary delays and doesn't guarantee consistent key availability across replicas
- **Kubernetes API Restart**: Restarting the router for key rotation is inefficient and disruptive

**Additional context**
Our authentication service rotates the keys every N hours, and it publishes it's key and makes it available to the router.

**Impact:**

The current behavior creates significant limitations for systems utilizing dynamic key rotation and Apollo Router's JWT authorization. Implementing the proposed solution would significantly improve compatibility and enable efficient JWT validation even with frequent key rotations.

**Comment by Geal** [comment]
Most identity providers have a strict rate limit on JWKS download, so the poll interval parameter is very much needed. Having a mechanism to download keys when a JWT comes signed with an unknown key means that it would be very easy to trigger that rate limit by spamming the router with invalid tokens.
This issue is confusing me, because when doing dynamic key rotation, aren't we supposed to wait enough time for the key to propagate before creating tokens using it?

**Comment by cyberhck** [comment]
> Most identity providers have a strict rate limit on JWKS download, so the poll interval parameter is very much needed. Having a mechanism to download keys when a JWT comes signed with an unknown key means that it would be very easy to trigger that rate limit by spamming the router with invalid tokens. This issue is confusing me, because when doing dynamic key rotation, aren't we supposed to wait enough time for the key to propagate before creating tokens using it?

We can do 2 things:
- add a flag to enable download in that case (so that this is enabled only for people with this flag turned on and can default to off)
- if a key was recently fetched, don't fetch

How do we know if a key has been propagated? If the poll interval is 1 minute, do we wait 1 minute before signing tokens? How do we make sure the auth service's wait time and router's poll interval are always in sync?

**Comment by Geal** [comment]
> We can do 2 things:
> * add a flag to enable download in that case (so that this is enabled only for people with this flag turned on and can default to off)
> * if a key was recently fetched, don't fetch

Unknown keys would still be fetched over and over. The current system is designed to verify tokens quickly and synchronously, without calling into an external service in the middle of verification. Adding that external call could generate a lot of traffic for invalid tokens, while the main goal is to reject invalid queries quickly and cheaply.

>How do we know if a key has been propagated? If the poll interval is 1 minute, do we wait 1 minute before signing tokens? How do we make sure the auth service's wait time and router's poll interval are always in sync?

I do not know about your architecture, but aren't you controlling the router's configuration? If you know the poll interval is one minute, then yes, from the moment the new key is available in the JWKS, you can wait 1mn until you can create new tokens, because at that point all routers will have downloaded the new key. Then wait for old tokens to expire to remove the old key.
Another way to make sure routers get the new key immediately is to trigger a configuration reload, either by starting the router with `--hot-reload` and changing the configuration file, or sending a `SIGHUP` signal. This is more efficient than restarting pods, because it keeps the existing process handling current traffic, but uses the new configuration for new traffic

**Comment by cyberhck** [comment]
while I am controlling both configuration, nothing is stopping from the poll interval in router to go out of sync with auth-service's value, those are 2 separate values defined in 2 different places that can change.

The `--hot-reload` would not work, because auth-service wouldn't know how many replicas of router exists.

Adding a flag that defaults to false, and when enabled would requests to fetch sounds like it's safe, no?

Without this feature, we'd have to keep doing what we're doing and not use router's authentication

**Comment by Geal** [comment]
> while I am controlling both configuration, nothing is stopping from the poll interval in router to go out of sync with auth-service's value, those are 2 separate values defined in 2 different places that can change.

I can empathize with that, but this is not something that could be solved at the router level. Isn't there some central configuration management that can fill in the right value in both places?

> The --hot-reload would not work, because auth-service wouldn't know how many replicas of router exists.

Again, I don't know about your architecture, but there should be a way to update the configuration for all replicas without having to know about all of them, no?

> Adding a flag that defaults to false, and when enabled would requests to fetch sounds like it's safe, no?

it is not a simple flag to add. The mandate of the authentication layer is to reject invalid or expired tokens quickly. Adding a network call easily triggered by any invalid tokens goes against that goal.

> Without this feature, we'd have to keep doing what we're doing and not use router's authentication

What are you doing currently?

**Comment by cyberhck** [comment]
> I can empathize with that, but this is not something that could be solved at the router level. Isn't there some central configuration management that can fill in the right value in both places?

These are two different deployments each getting their own ConfigMap from their own respective location.

> Again, I don't know about your architecture, but there should be a way to update the configuration for all replicas without having to know about all of them, no?

In a k8s environment, if I have 3 instances issuing new signing keys, I'd somehow have to coordinate them.

> it is not a simple flag to add. The mandate of the authentication layer is to reject invalid or expired tokens quickly. Adding a network call easily triggered by any invalid tokens goes against that goal.

Understandable.

> What are you doing currently?
Currently, we have a auth and split proxy that sits in front of apollo router. This takes care of authenticating and splitting traffic against 2 running router with 2 configuration (we A/B test configuration changes)

Anyways, we do have 2 ways to achieve this, one being auth-service waiting for a duration before actually using that token, or keep using the auth-proxy.

closing the issue as resolved.
