### ISSUE TITLE
plugin_utils: Derive `Default/Builder` on structs plugin users will rely on

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#437]
There's a couple of structures we're using a lot, which might be more convenient to have builders or defaults on. Let's have a look at the ones we would like to add helpers to, and see if there's improvements we can make.

Maybe we could derive `Default` on `Request`

_Originally posted by @bnjjj in https://github.com/apollographql/router/pull/428#discussion_r802872560_

**Comment by bnjjj** [comment]
Regarding `RouterRequest` type for example:

```rust
pub struct RouterRequest {
    // Context for extension
    pub context: Context<http_compat::Request<Request>>,
}
```

How would you want to create it ? 

Today our builder looks like:

```rust
#[derive(Default, Clone, TypedBuilder)]
#[builder(field_defaults(default, setter(strip_option)))]
pub struct RouterRequest {
    query: Option<String>,
    operation_name: Option<String>,
    variables: Option<Arc<Object>>,
    #[builder(default, setter(!strip_option, transform = |extensions: Vec<(&str, Value)>| Some(from_names_and_values(extensions))))]
    extensions: Option<Object>,
    context: Option<Context<()>>,
    headers: Option<Vec<(String, String)>>,
}

RouterRequest::builder().query(my_query).headers(my_headers).context(Some(my_context)).extensions(my_extensions);
```

IMHO in the current implementation we can set a context directly and also set extensions which are supposed to be in the context, so which one do we choose ? It's not easy to understand for the user.
I think it could be interesting to have good builders on each types that compose a `RouterRequest` or `RouterResponse` or ... which means we could have better builder implementations to easily create a `Context`/`Context<http_compat::Request<Request>>`. With the recent PR (https://github.com/apollographql/router/pull/553) we now have a good builder to to create an `http_compat::Request<T>`. We also already have builder for `Request`.
Then if we assemble each of these builders together we could simply/maybe get rid of `plugin_utils` and only use provided builders.

Here is some examples of what we could have:


```rust
// Use the already provided builders for each types and get rid of plugin_utils types

let request = Request::builder().query("my_query").operation_name("MyOperation");
let http_request = http_compat::RequestBuilder::new(Method::GET, Url::parse("http://test").unwrap())
    .header("my-header", "my-value")
    .body(request)
    .unwrap();
let mut context = Context::new(http_request);
context.insert("MyKeyExtension", "MyValue").unwrap();
context.insert("MyOtherKey", "MyOtherValue").unwrap();
let router_request = RouterRequest::new(context);
```

```rust
// Here I give only what we could change but all is flatten


let request = Request::builder().query("my_query").operation_name("MyOperation");

let router_request = RouterRequest::builder()
    .url(Url::parse("http://test").unwrap()) // URL is mandatory ?! or we put http://test by default ?
    .query("my_query")
    .operation_name("myOperation")
    .header("my-header", "my-value")
    .insert_extension("myKey", "myValue").build();
```

With the first example it's more verbose but also way more flexible, it's up to the user to create whatever they want. It's maybe less easy to use but if we provide good documentations, doc tests and so one for each structures I think it could easily do the job. It makes me think about the way we're building entities and document in [`apollo-encoder`](https://docs.rs/apollo-encoder/latest/apollo_encoder/), it's well documented so very easy to use.

**Comment by abernix** [comment]
From #681:

> Now that we have a better feel for what structures we need to build extensions, we should discuss and normalize what is in the plugin utils. Especially what should be used only for testing purposes and what can be used in running code.

**Comment by BrynCooke** [comment]
I just released a crate that may be useful for this task: https://crates.io/crates/buildstructor

It supports fallible construction so we can give the users a nice API and delay validation of headers and URLs until the call to build.
