### ISSUE TITLE
headers set by the subgraph service should not be propagated from the client query by the headers plugin

### ISSUE THREAD

**Issue by heathprovost** [apollographql/router#4398]
**Describe the bug**
Requests that already have the accept header set to the value `application/json, application/graphql-response+json` on the inbound request to the router are getting multiple accept headers appended to the request incorrectly. 

In other words if the original request contains this:

```
accept: application/json, application/graphql-response+json
```

The router ends up sending this to the subgraph:

```
accept: application/json, application/graphql-response+json
accept: application/json
accept: application/graphql-response+json
```

Unfortunately, the default behavior of the C# GraphQL.Client is to set the accept headers exactly this way : https://github.com/graphql-dotnet/graphql-client/blob/fbf37dfff2830e36a45296079bac27ec60fad550/src/GraphQL.Client/GraphQLHttpRequest.cs#L40

This behavior started in v1.35.0 of the router, and seems to me to be attributable to this changeset: https://github.com/apollographql/router/commit/9a44bedd070dcf66dc0c1e63b4645033bc5262e8#diff-6ef5a208ca8622f30eef88f75c18566e0304d59856b66293dcd6811555e6382e which changed the method used to set the Accept header from an .insert() to an .append(). The older behavior of just using .insert() avoided the issue because it simply overwrote the entire accept header, which is probably not the desired behavior either.

**To Reproduce**
1. Setup services normally (using router or cloud router v1.35.0)
2. Submit a request including the header `Accept: application/json, application/graphql-response+json`
3. View the request coming out of the router, it is incorrectly appending additional headers when it should not be.

**Expected behavior**
The router should see that the headers it is trying to set are already there and should do nothing in that scenario.

**Additional context**
This issue causes breakage with subgraphs running inside of lambdas behind ALBs in AWS because of how request headers are marshaled when they are converted from an http request to a lambda request. AWS lambda does not properly marshal the requests when they contain both multivalue headers AND multiple of the same header key (it works with either or, but not both) . 

We are currently working around this issue by overriding the default behavior of the C# GraphQL.Client and stripping the Accept header off before the request goes out. Not a great solution obviously.

**Comment by Geal** [comment]
do you have any header propagation rules in the router's configuration? https://www.apollographql.com/docs/router/configuration/header-propagation

**Comment by heathprovost** [comment]
We are currently just doing this:
```
headers:
  all:
    request:
      - propagate:
          matching: .*
```

**Comment by Geal** [comment]
ok so the issue here is that headers that are set by the router as part of the subgraph request, like `Accept` or `Accept-Encoding`, should not be part of propagated headers

**Comment by heathprovost** [comment]
> ok so the issue here is that headers that are set by the router as part of the subgraph request, like `Accept` or `Accept-Encoding`, should not be part of propagated headers

I dont think so no. They should be part of the propogated headers, they just should not be blindly added as well. In other words these headers should be forwarded if and when they exist, and when they do NOT exist they should be added to the outbound request.

What is happening now is that the router is doing both. It is propagating them from the inbound request AND adding them again. 

What should happen (imo) is that the router should only add them if they do not already exist on the inbound request.

**Comment by abernix** [comment]
This probably deserves some investigation, and perhaps should be considered together with behaviors in #4420.
