### ISSUE TITLE
Default plugins provided by the router

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#440]
If we want to allow config of this then a plugin would be the way to go. I'm still not sure what we want to do with default plugins. It could be worth introducing a concept of a default plugin. APQ and Otel probably fall in to this category.
Let's create a separate ticket to follow up though.

_Originally posted by @BrynCooke in https://github.com/apollographql/router/pull/433#discussion_r803581431_

**Comment by BrynCooke** [comment]
Closing for now. #623 Made adding default plugins fairly easy in that they can be added at a central location in the config code.
https://github.com/apollographql/router/pull/623/files#diff-4a11c81ac00715f2740e504e8041ac1fe77d97b65f6d367a4fff4fe269e2114eR85
