### ISSUE TITLE
Expose fetch.rs OperationKind Enum publicly

### ISSUE THREAD

**Issue by ShaunPhillips** [apollographql/router#4410]
**Describe the solution you'd like**
Give OperationKind public scope such that it can be used in code that imports `apollo-router` as a dependency. This would allow for direct checks against the enum value vs. checking the C-style enum equivalent, i.e. 0, 1, 2.

The enum is already public where it is defined:

https://github.com/apollographql/router/blob/a2c8badf95a0a8cdbb30b9afe68795f76297fed8/apollo-router/src/query_planner/fetch.rs#L37

However, it is not externally visible as `query_planner` is not exposed publicly:

https://github.com/apollographql/router/blob/a2c8badf95a0a8cdbb30b9afe68795f76297fed8/apollo-router/src/lib.rs#L70

If making `query_planner` public is not desirable, then would it be possible to pull shared Enums and Type definitions to a shared module that is fully public?

**Describe alternatives you've considered**
Hard coded checks based on the C-style enum equivalent, i.e. `req.operation_kind as i32 != 0` to check for not a `Query` as well as string parsing checks.

**Additional context**

**Comment by abernix** [comment]
We are, in-fact, not yet ready to commit to making `query_planner` public, particularly as we re-platform the query planner into Rust.  This might change eventually, but even in that world, we would still prefer to provide more specific APIs for most use-cases, to reduce the blast-radius of breaking changes when things evolve.

In that spirit, could you shed a little bit more light on highlighting the use-case you're trying to solve for by using the enums and type definitions?

**Comment by ShaunPhillips** [comment]
Thanks everyone! Yes, the main concern was that `OperationKind` is used in public APIs but comparing its value directly to the enum was not possible.
