### ISSUE TITLE
router telemetry tracing datadog DEFAULT_ENDPOINT should not contain a path, opentelemetry_datadog will append the path

### ISSUE THREAD

**Issue by theJC** [apollographql/router#4416]
**Describe the bug**

Router's datadog TracingConfigurator will leverage endpoint.rs function to_uri to use a default or fill in parts that are missing from the default, pulling from DEFAULT_ENDPOINT which is currently: `http://localhost:8126/v0.4/traces`   (note it contains a path)

The resulting value is then passed into opentelemetry_datadog version 0.8.0::new_pipeline().with(assembled url)

In [opentelemetry_datadog's src/exporter/mod.rs the build_endpoint function ](https://github.com/open-telemetry/opentelemetry-rust/blob/v0.20.0/opentelemetry-datadog/src/exporter/mod.rs#L256C22-L256C22)will take that string, and then append `/v0.5/traces` additionally, resulting in a incorrect url being used:   `http://host:port/v0.4/traces//v0.5/traces`

The DEFAULT_ENDPOINT should not have a path.

**To Reproduce**
```
curl -sSL https://router.apollo.dev/download/nix/v1.35.0 | sh
curl -L https://supergraph.demo.starstuff.dev/ > starstuff.graphql
```

```
cat <<EOT > failure_config.yaml 
telemetry:
  exporters:
    tracing:
        datadog:
            enabled: true
            endpoint: localhost:8126
EOT
```

```
./router --supergraph starstuff.graphql --log=trace --config=failure_config.yaml &
```

```
curl -v  --request POST \
  --header 'content-type: application/json' \
  --url 'http://127.0.0.1:4000/' \
  --data '{"query":"query { __typename }"}'
```

**Expected behavior**
Datadog exporter will send to a valid url that does not have a path of /v0.4/traces//v0.5/traces

**Output**
Errors resulting from Router are:

```
OpenTelemetry trace error occurred: request failed with status 404 Not Found
OpenTelemetry trace error occurred: error sending request for url (http://hostname:8126/v0.4/traces//v0.5/traces): 
connection closed before message completed
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - macos
 - Version [e.g. 22] - 14.2.1 

**Additional context**
 Apollo Router v1.35.0

**Comment by BrynCooke** [comment]
I've made a fix although have not added the ability to specify the API version which looks like it may be needed later.
