### ISSUE TITLE
Introduce API schema

### ISSUE THREAD

**Issue by abernix** [apollographql/router#443]
In order to match the behavior now in the Gateway and to support _Contracts_, we need to introduce a concept of an "API schema".

The "API schema" is a deterministic, but runtime-generated derivative of the "Supergraph schema" using the `toAPISchema` function in JS-land (taking a look [at its tests](https://github.com/apollographql/federation/blob/1ffecef9ef52f6dc127939cdc375f0465774f093/internals-js/src/__tests__/toAPISchema.test.ts) would be beneficial, but the implementation [is here](https://github.com/apollographql/federation/blob/8c4f0b3ec498cc4b92611390043e84451576424d/internals-js/src/definitions.ts#L1160-L1178)).  We'll probably/may want to expose this in the `router-bridge`, which now lives in https://github.com/apollographql/federation-rs/.

While the supergraph represents the full schema the router knows how to route across (and uses for query planning), the "API schema" acts as the externally introspect-able and the schema that users can actually execute operations against. (In practice, the API schema excludes `@core_` directives and fields that are marked as `@inaccessible`).

Tasks:
- [x] Implement `to_api_schema` This will strip out anything marked as inaccessible and some other stuff. 
- [x] Modify the router bride to validate against the API schema and plan against the real schema.
- [x] Output shaping is performed against the API schema if present.

**Comment by o0Ignition0o** [comment]
- `NaiveIntrospection` should return `toAPISchema` variant
- We need to check whether we could validate queries against `toAPISchema` and plan against `toSchema`

- Be careful about message hints / lints.
- Thoroughly check whether output shaping should be performed against `toAPISchema` or `toSchema`

**Comment by BrynCooke** [comment]
Tasks:
[ ] Implement `to_api_schema` This will strip out anything marked as inaccessible and some other stuff. 
[ ] Plan query against both API and regular schema. This will validate that the query is valid wrt. the API schema.
[ ] Output shaping is performed against the API schema if present.

**Comment by o0Ignition0o** [comment]
validation: https://github.com/apollographql/federation-rs/blob/main/router-bridge/js-src/plan.ts#L17 is the line where we want to append .toAPISchema();

**Comment by abernix** [comment]
Do we want to apply it to the `plan` or in `introspect`?

**Comment by o0Ignition0o** [comment]
I'd wager we want to apply it to both, because plan validates a query against a schema, and a query shouldn't be valid if it tries to make use of `@inaccessible` or `@core` fields
