### ISSUE TITLE
Selectors that extract body elements use JSONQuery rather than JSONPath

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#4443]
We've documented selectors that extract from json as using JSONPath but it looks like we use JSONQuery.
We should use one or the other. My initial inclination is to switch to JSONPath as we have documented because it is more powerful, and the library is maintained.

Related, the error message for non parseable paths is really bad as it implies that custom attributes are not allowed.

**Comment by Geal** [comment]
which library are you mentioning? AFAIK we use 2 different libraries for json paths internally

**Comment by BrynCooke** [comment]
Currently we have:
```
access-json = "0.1.0" # Used in headers plugin and selectors
jsonpath_lib = "0.3.0" # Abandoned and buggy
jsonpath-rust = "0.3.5" # Under active development, we should use this.
```

**Comment by BrynCooke** [comment]
OK, so I had a look and the advantage of access json is that it provides query over any serializable, at the cost of not being jsonpath, and cloning of any values it actually returns.
The nice thing about jsonpath, is it works on references so no cloning, but can't be used on the graphql::Response struct.

**Comment by BrynCooke** [comment]
Checking to see if there is a JSONPath library that supports Valuable.

**Comment by BrynCooke** [comment]
For now this is a documentation change. It we are allowing query of real datastructures rather than just `serde_json::Value`, so we'll have to document JSONQuery.
This does not preclude us from adding JSONPath support in future as these start with `$` rather than `.`.

**Comment by BrynCooke** [comment]
To complicate matters, `access-json` doesn't support wildcards. We need to find a better solution.

**Comment by BrynCooke** [comment]
I think this is how we should proceed:

Replace `SubgraphResponseBody` with:
`SubgraphResponseData` and `SubgraphResponseErrors`

These will use `jsonpath_rust` (already used in the Router).
If serde fails a good error message must be emitted to the user.

Query of errors will require serialization, but this is probably OK as errors should be small.
Query of data will not require serialization as `jsonpath_rust` can work against a reference of `&Value`.
