### ISSUE TITLE
Add NonSerializable Context entries

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#4445]
Currently all context parameters are serialized to JSON when stored. This means that they can be sent to coprocessors and Rhai.

However this is a not possible for certain structures, and is at the very least could affect performance for certain scenarios.

Apollo should continue to use the existing json based context where appropriate, but also provide functionality similar to `private_entries` for users.

As negative trait bounds don't exist yet we will need to add a new API for this. Suggest that we model using by using the existing API with a suffix.

**Comment by Geal** [comment]
we could just expose the private entries(not directly, through methods on context). There is no risk of conflict between internal router usage, and what users would touch, because the data is indexed by type id, and internal router data is in private types
