### ISSUE TITLE
Helm VirtualService should support multiple Gateway names

### ISSUE THREAD

**Issue by marcantoine-bibeau** [apollographql/router#4464]
**Describe the solution you'd like**
Helm VirtualService SHOURL support multiple Gateway names

**Describe alternatives you've considered**
in values file:
virtualservice:
  gatewayName: ""

should be: 

virtualservice:
  gatewayNames: []

**Additional context**

**Comment by Geal** [comment]
would you have an idea of how to do that with our current chart? Is that something you would consider sending a PR for?

**Comment by marcantoine-bibeau** [comment]
Sure! I can do that :)

**Comment by marcantoine-bibeau** [comment]
@Geal I do not find how I can become a contributor. :(  I have the template changes but I cannot create a PR

**Comment by Geal** [comment]
you can fork the project, make the change in your fork then create a PR
