### ISSUE TITLE
Startup output says "Listening on http://http://"

### ISSUE THREAD

**Issue by abernix** [apollographql/router#447]
Router from version built from bef4fc6542205a24e80b2886ba8ef36e16fc6515 reveals an invalid URL on startup — `http://http://127.0.0.1:4000`:

```
2022-02-11T10:11:23.706072Z  INFO apollo_router::trace: spaceport: None, graph: None
2022-02-11T10:11:24.130394Z  INFO router: Listening on http://http://127.0.0.1:4000 🚀
```

**Comment by garypen** [comment]
I think this crept in with: https://github.com/apollographql/router/pull/158

Removing the hard-coded "http://" from the startup message and also adding "file:" for Display for UDS seems a good approach for now.
