### ISSUE TITLE
Provide correlation between router and subgraphs

### ISSUE THREAD

**Issue by kwiatopl** [apollographql/router#4485]
I want to have automatically generated correlation id for each request that would be passed from router to subsequent subgraphs to allow better observability and debugging experience.
I was looking into Spans but that would probably require Enterprise plan and on top of that I'm not exactly sure how would correlationId be automatically generated. Maybe I could use `trace_id` to achieve my goal?
I'm hosting my router on AWS ECS, Subgraphs are hosted as Lambdas behind API Gateway.

Could you guide me how to do it?

**Comment by BrynCooke** [comment]
You can use tracing without an enterprise license in the Router. Otel trace id propagation will work giving you fully correlated traces in your APM.

Just make sure that your subgraphs are Otel enabled and that you have configured your trace exporter correctly in the router.

Open telemetry headers will be transmitted on subgraph requests which include a trace ID.

**Comment by BrynCooke** [comment]
Closing as a solution was suggested but no feedback was given.
