### ISSUE TITLE
File uploads - Metrics

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#4504]
Implement operation and configuration metrics.

**Comment by IvanGoncharov** [comment]
Metrics description from RFC:

> Our users need insight into file upload statistics. Statistics would be collected using OpenTelemetry. There are several stories this design covers:
> measuring and recording file sizes of uploaded files
> measuring and recording the number of files inside requests
> insights on rejected requests due to individual files exceeding the maximum size
> insights on rejected requests due to requests exceeding the maximum number of files in it
> For the limit-related errors (max file size and maximum number of files) Router will use standard error reporting and error code semantics, where the Router emits OpenTelemetry tracing spans as part of its request pipeline. All errors will also be emitted, allowing error data to be propagated to OpenTelemetry APM tooling like Datadog, Honeycomb, etc.
