### ISSUE TITLE
Incorrect link for NewRelic exporter in Tracing/OTLP page

### ISSUE THREAD

**Issue by lehnenb** [apollographql/router#4507]
**Describe the bug**

While browsing the Trace Exporter page for Open Telemetry, I noticed that the link for the NewRelic page is broken

**To Reproduce**
1. Access the OTLP tracing exporter page: https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/otlp
2. Scroll down to the section listing the different backends for exporting traces
3. Click on the New Relic link: 
<img width="756" alt="Screenshot 2024-01-17 at 09 35 42" src="https://github.com/apollographql/router/assets/3442298/0a1d10ff-c1d0-489c-9442-41c5341c17d3">

**Expected behavior**
Upon clicking the NewRelic link, I expected to be redirected to the following URL: https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/new-relic

**Output**
When I clicked the NewRelic link, I was redirected to the following URL: https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/newrelic.

Since the above URL didn't exist, I was ultimately shown the: "404 - Houston, something went wrong on our end" error page.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5 (22G74)

**Additional context**
Here's the PR fixing this issue: #4508

**Comment by Geal** [comment]
fixed by https://github.com/apollographql/router/pull/4508
