### ISSUE TITLE
configurable histogram buckets per metric

### ISSUE THREAD

**Issue by Geal** [apollographql/router#4543]
there is an ask for configurable histogram buckets per metric (currently we only have a global configuration). This would let users get more precision for some metrics while keeping the amount of data low for other metrics

**Comment by BrynCooke** [comment]
I think the buckets should go under the specific instruments:

https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/instruments/

As this is not implemented yet, I would mark this ticket as blocked for now..

**Comment by bnjjj** [comment]
I think this is valuable for custom instruments created through the configuration file in `instruments` but we also have metrics created in custom rust plugin and so it would make sense to keep these in `metrics.common` or another sub section in instruments called `common` ?

**Comment by abernix** [comment]
Note while this feature first appeared in Router https://github.com/apollographql/router/releases/tag/v1.40.0, we don't recommend using it until https://github.com/apollographql/router/releases/tag/v1.46.0.  We've updated the CHANGELOG to reflect this note.

The version recommendation is based on the first stable version (note, this excludes versions which are not recommended in the [changelog](https://github.com/apollographql/router/blob/dev/CHANGELOG.md)) after https://github.com/apollographql/router/pull/4771 landed.
