### ISSUE TITLE
No http otlp exporter suported

### ISSUE THREAD

**Issue by andre-c-alves** [apollographql/router#4559]
I'm trying de following configuration (export metrics to Dynatrace)

`
telemetry:
  exporters:
    metrics:
      otlp:
        # Enable the OpenTelemetry exporter
        enabled: true
        endpoint:  defaut
        protocol: http
`

but I got the message:
"ERROR  plugin apollo.telemetry could not be configured: otlp metric export does not support http yet"

It's working for tracing, but not for metrics. Does anyone have idea?

**Comment by BrynCooke** [comment]
The issue is still open in https://github.com/open-telemetry/opentelemetry-rust/issues/772, but it looks like from the code this is now supported. We should take another look, or maybe you could raise a PR?
