### ISSUE TITLE
Add router log events for client terminating connections (broken pipe) and timeouts 

### ISSUE THREAD

**Issue by ebylund** [apollographql/router#4569]
**Is your feature request related to a problem? Please describe.**
When a client closes it's connection to the router before subgraphs have been able to respond, the router gives no details about what has happened. The same things happens during timeouts

**Describe the solution you'd like**
Have the router log two types of events where it is currently silent:
- On timeouts.
- When clients close the connection to the router before subgraphs have responded.

**Comment by BrynCooke** [comment]
This would be solved by #4320
