### ISSUE TITLE
dead links in docs

### ISSUE THREAD

**Issue by Geal** [apollographql/router#4690]
in https://www.apollographql.com/docs/router/configuration/telemetry/exporters/metrics/overview/:

* the resource attributes link is dead
* the custom histogram buckets link is dead
* histogram is misspelled
in general we should review the telemetry docs and fix those kinds of small issues, as there's been a lot of changes recently

**Comment by BrynCooke** [comment]
@shorgi Could you take a look?

**Comment by Geal** [comment]
"historgram" typo fixed in https://github.com/apollographql/router/pull/4572/files#diff-1e3a339e6303fb9bee093329138842168bb7d51ab0071fe294910b639e3af7da
