### ISSUE TITLE
Bulk Update Graph-Specific Roles (from Observer to Contributor) 

### ISSUE THREAD

**Issue by anir95** [apollographql/router#4695]
Developer team has a graph dedicated for the apollo odyssey courses, but the default role that people get is too low. The teams wants to set it to contributor, but only for this graph so the team members have appropriate permissions to do the course. In addition, they can expect dozens of users coming onto this graph.

Is there any way to bulk update the permissions for a variant to reflect this?

**Comment by garypen** [comment]
I think you may have logged this issue against the wrong project by mistake. The router developers don't have access to fix issues like this.
