### ISSUE TITLE
Investigate lifting output shaping tests from gateway-js/

### ISSUE THREAD

**Issue by abernix** [apollographql/router#47]

**Comment by Geal** [comment]
the plan for now is:
- hook the gateway creation in all tests to use the router if the environment variable specifying its path is present
- most of the tests check the query planner output, which is not available from the router. Possible solutions:
  - deactivate query plan testing if we are using the router (likely requires modifications to the tests)
  - still start the JS query planning code along with the router, run it and return the result (less modifications to the tests)
- the tests will generate a supergraph from the fixtures and store it to a file to load it into the router. We could use the router's `--watch` command to reload it whenever there's a new supergraph file
- this might be very slow to run, and if it requires too many modifications to the tests, it might live in a branch for a while. It will still be very useful to the router even in that state. Running it from time to time in the beginning will uncover a lot of bugs

**Comment by Geal** [comment]
now that extensions have landed, we can revisit this topic. Here's the plan: most of the gateway tests uses [this execute function](https://github.com/apollographql/federation/blob/21ea8d5e028050a546bfca3c8dd092be44b1aa07/gateway-js/src/__tests__/execution-utils.ts#L37-L79), that we could hook to set up a router, perform the query there then return the results.
My previous test was generating the supergraph on the typescript side, serializing that to a file, starting a router process, sending the request, receiving the response, then waiting for the router to stop. It is way too slow and cannot be parallelized easily. With the tower infra we can make a bespoke router to run those tests.

the steps to get there:
- we need a way to choose between gateway and router when running the tests: [In my previous attempt](https://github.com/apollographql/federation/pull/1105/files#diff-e9146cf54ed522ff583879db89119138a03f8c32948bf2a85b99c2e754fe6ebeR52), I used an environment variable
- we need a way to call the rust router from JS. I am not sure if neon can wrap async APIs. It could be easier to make a rust server to which we can send the query and the subgraph data, and internally it performs the query and serializes the response
- we need a way to [create a subgraph dynamically](https://github.com/apollographql/federation/blob/21ea8d5e028050a546bfca3c8dd092be44b1aa07/gateway-js/src/__tests__/execution-utils.ts#L42-L51), and generate a schema from it. That can be done as a subgraph plugin. I expect that plugin would be useful independently from the test
- we must [build a supergraph schema from the subgraphs](https://github.com/apollographql/federation/blob/21ea8d5e028050a546bfca3c8dd092be44b1aa07/gateway-js/src/__tests__/execution-utils.ts#L53). Maybe we can embed rover parts to do that?
- We have a query planner service now, so we should be able to return the query plan (it's supposed to be the same as the gateway, so here we'll spot any inconsistencies)

**Comment by Geal** [comment]
closing this as we have found a nice way to compare the router and gateway using the fuzzer
