### ISSUE TITLE
Caching: raise the default Redis timeout

### ISSUE THREAD

**Issue by Geal** [apollographql/router#4743]
It is set to 2ms right now, which is far too low for some users.
https://github.com/apollographql/router/blob/dev/apollo-router/src/cache/redis.rs#L165

They can modify it themselves, but it tends to trip them up. We should set a larger timeout, and let users who want tighter deadlines configure it instead

**Comment by theJC** [comment]
I believe https://github.com/apollographql/router/pull/5795 addressed this issue

**Comment by Geal** [comment]
You're right, closing this now then
