### ISSUE TITLE
Allow fully disabling response compression

### ISSUE THREAD

**Issue by xuorig** [apollographql/router#4800]
Currently, apollo-router will compress responses by respecting the `accept-encoding` header. Compression has a cost, and certain contexts may not require compression to happen on the `router` itself, for example if it is fronted by another process with compression enabled.

A new configuration option could be added so that response compression can be turned completely off. Happy to contribute a PR.

**Comment by garypen** [comment]
Could you provide a little more detail about the "certain contexts" that you mention?

In the example you provide, wouldn't it be the responsibility of the fronting process to remove/modify the "accept-encoding" header?

**Comment by xuorig** [comment]
Closing, @garypen you're totally right 👍 it's a problem in itself if the fronting process sends `accept-encoding` while taking ownership of compression.
