### ISSUE TITLE
Metric combining `apollo_router_processing_time` and `apollo_router_query_planning_time` for requests that require query planning

### ISSUE THREAD

**Issue by samjcombs** [apollographql/router#4851]
**Is your feature request related to a problem? Please describe.**
Currently, if query planning exceeds the timeout, it will return an error, and on the next request for that operation, it will pick up where it left off and continue planning.  It will only publish the metric when the query plan is completed.  This means long running query planning events that span multiple requests report as a single `apollo_router_query_planning_time` metric.  

This is a helpful metric to understand how long query plans take, but it complicates things when looking for "exactly how much time requests spend in Router." 

**Describe the solution you'd like**
Is it possible to expose a metric that adds `apollo_router_query_planning_time` to `apollo_router_processing_time` on a conditional basis, i.e., requests that don't require any query planning would just report the `processing_time`, but any requests that require query planning would have the `query_planning_time` added to `processing_time`?

This would aid in setting up percentile-based alerting using the total time a request spends in Router.

**Describe alternatives you've considered**
For most requests `apollo_router_processing_time` is fine.  But that metric doesn't give the full picture when requests require query planning.  Because `query_planning_time` spans multiple requests, there isn't an easy way to combine the two.  

**Additional context**
From a naming perspective, it isn't obvious that `apollo_router_processing_time` doesn't include the time spent in query planning because it seems that would be a part of the Router processing.  I understand, because it's offloaded to Deno that it makes sense to instrument them separately, but a combined metric here would give us a much cleaner look at "exactly how much time requests are spent in Router," which has been an elusive one at times.

**Comment by xuorig** [comment]
@samjcombs what would that metric actually represent? My understanding is that `apollo_router_processing_time` does include time spent planning, but it only includes the time actually spent **waiting for the plan to be ready** for that specific request, which does seem to align with "exactly how much time requests are spent in Router". That seems like the important metric to track when it comes to overhead per request.

**Comment by samjcombs** [comment]
Ahh, thanks for confirming that
> time actually spent **waiting for the plan to be ready**

_is_ included in `processing_time`

I got misled by looking at _p99s_ instead of _max_ for processing_time. Requests that wait for query plans are likely well below 1% of all requests, so I was "missing" it. 

Thanks for the clarification here!

**Comment by samjcombs** [comment]
Closing this feature request as obsolete because time spent waiting for query planning  _is_ included in `processing_time.` (Verified just now comparing max processing_time to max query planning time and they line up perfectly) 
This would also catch any super-long query plans that require multiple requests to plan.  Thanks, @xuorig, for the help here.
