### ISSUE TITLE
Add Rhai sha256 hashing function

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#4939]
## Is your feature request related to a problem? Please describe.**
We want to hash error codes and custom values in the request/response for logging purposes. SHA256 is also used with Persisted Queries and caching so being able to generate the same values in Rhai could help with custom scripting

Base64 encoding doesn't help because anyone who has access to the encoded messages can easily decode them vs sha256 hashing which is one way

## Describe the solution you'd like**
Expose new global functions in rhai, similar to `base64::*`, but for [sha256](https://docs.rs/sha256/latest/sha256/)

```rhai
let text = "alice and bob";
let hash = sha256::digest(text);

print(hash) # 629f44ee052437b149370d37b9810e19a1df618712ccae63593d37c9b96e3237
```

## Describe alternatives you've considered**
We could use a coprocessor to solve this today

## Additional context**
This was brought up in a larger issue as one step to support encryption in Rhai in https://github.com/apollographql/router/issues/2025 but that issue was closed because we added native Sigv4 support. This issue was also opened just for the sha256 function, but it was closed as a duplicate of the larger crypto issue: https://github.com/apollographql/router/issues/2112

Outside of crypto support it would be helpful to have a sha256 hashing function available so we don't have to use a coprocessor for small request/response manipulation

**Comment by elloboblanco** [comment]
throwing in my support for this, would love this feature 🙌🏻
