### ISSUE TITLE
Opentelemetry-jaeger scalability

### ISSUE THREAD

**Issue by Geal** [apollographql/router#50]
**Describe the solution you'd like**
when running benchmarks with Jaeger as trace collector, opentelemetry generates a lot of errors, of two kinds:
* `thrift agent failed with message too long`
* ` OpenTelemetry trace error occurred. cannot send span to the batch span processor because the channel is full`

To understand the errors, here's how the current tracing system works:
- tracing spans are generated by the tracing crate
- there's an opentelemetry subscriber that receives the span
- a batch span processor accumulates spans and sends them to the exporter once enough spans have accumulated, or a [ticker triggered](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/sdk/trace/span_processor.rs#L300-L369)
- [opentelemetry-jaeger converts the opentelemetry spans to the jaeger format then calls the uploader](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/mod.rs#L92-L116)
- the uploader serializes the spans to thrift then sends an UDP message https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/uploader.rs#L48-L56https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/agent.rs#L72-L92

So the first error message happens because when the batch is sent, we have no way of knowing if it will be too large for a single UDP packet (the default limit in the crate is 65000 bytes). This can be solved in two ways:
- reducing batch size. The appropriate value for the batch size will depend on the traffic: the batch size is the number of top level spans, so if we have a few spans with a lot of subspans (like a query with a lot of subqueries) we could be under the batch limit but above the UDP packet limit. The batch size and other options can be managed with environment variables defined here: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/sdk/trace/span_processor.rs#L48-L63
- using the auto_split parameter that was added recently: https://github.com/open-telemetry/opentelemetry-rust/commit/a0899d9ed595343e9d4eb2dbd994235dedb501ed#diff-05c33517a7162e2e901acc0d121d9c1cfa701baf2aee85148c7b7097289b4dc2 it tries to split the batch to make smaller packets https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/agent.rs#L177-L211 (this is not really vectored IO, oh well)

In my tests auto_split works most of the time. Except for very large spans, that would be larger than a UDP packet when serialized. **Is there a way to send a span in multiple pieces and let jaeger aggregate them?**

The second error happens because the jaeger exporter is spending too much time serializing the batch, especially in the build_span_tags function: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-jaeger/src/exporter/mod.rs#L693-L716 (see https://gist.github.com/Geal/0b9588bdeaa05e1494636e63ef431f96 for example code reproducing our tracing pipeline and a flamegraph, the highest column is the serialization task). This function could be optimized a bit, but I don't know how much.

We're bound to run into more issues with a large number of traces, so we should investigate sampling:
https://docs.rs/opentelemetry/0.16.0/opentelemetry/sdk/trace/enum.Sampler.html

it can be set up when creating the pipeline:
```rust
let tracer = opentelemetry_jaeger::new_pipeline()
 .with_trace_config(
            trace::config()
                .with_sampler(Sampler::AlwaysOn)
) .install_batch(opentelemetry::runtime::Tokio)?;
```

Sampling can be controlled by a custom implementation of [ShouldSample](https://docs.rs/opentelemetry/0.16.0/opentelemetry/sdk/trace/trait.ShouldSample.html). unfortunately, the sampling decision is done before we go through the span, probably to avoid collecting too much data. I'd like to have heavy sampling for successful queries (since they would be the most frequent ones), but no sampling at all for failing queries (we want to know about those). That might require patching opentelemetry.

**Comment by o0Ignition0o** [comment]
Putting this back to the "needs design section", and unassigning until we have a better idea of what we're trying to accomplish here.

**Comment by abernix** [comment]
Let's let this act as a proof of the problem in case someone encounters this again in the future, but we haven't seen this rear its head in a while.  Closing for now, but happy to re-open!
