### ISSUE TITLE
Reducing the configuration schema file

### ISSUE THREAD

**Issue by Geal** [apollographql/router#5003]
the [generated configuration schema](https://github.com/apollographql/router/blob/dev/apollo-router/src/configuration/snapshots/apollo_router__configuration__tests__schema_generation.snap) is now around 35000 lines. It might be time to reduce it a bit. schemars is supposed to extract object types into references that can be reused when necessary, but it looks like this is not happening, especially in the telemetry conditions. Can we find a way to reduce it further?
This will also have an effect on generated code size (schemars derived code is huge) which will impact linking times

**Comment by abernix** [comment]
Just cross-referencing issues for my own / posterity's / the community's context — this was introduced by https://github.com/apollographql/router/pull/5015 and fixed in the attached PR.
