### ISSUE TITLE
docs: broken link for "tech notes"

### ISSUE THREAD

**Issue by juancarlosjr97** [apollographql/router#5072]
**Describe the bug**

The documentation link to https://github.com/apollographql/router/blob/dev/docs/source/configuration/telemetry/exporters/tracing/overview.mdx#related-topics of [Sending Apollo Router traces and metrics to APM tools using OpenTelemetry](https://github.com/apollographql/router/blob/dev/technotes/TN0015-router-to-apm-via-opentelemetry) is broken.

**To Reproduce**

Open https://github.com/apollographql/router/blob/dev/technotes/TN0015-router-to-apm-via-opentelemetry

**Expected behavior**

Techn notes are available :)

**Comment by abernix** [comment]
@shorgi Do you mind taking a look at this?

**Comment by smyrick** [comment]
The link to our technotes is not meant to be linked in GitHub, it links on our docs site


See the page in docs: https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/overview#related-topics

-----

> [Related topics](https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/overview#related-topics)

> [Connecting OpenTelemetry traces to Prometheus](https://www.apollographql.com/docs/technotes/TN0003-opentelemetry-traces-to-prometheus)
> [Sending Apollo Router traces and metrics to APM tools using OpenTelemetry](https://www.apollographql.com/docs/technotes/TN0015-router-to-apm-via-opentelemetry/)

**Comment by juancarlosjr97** [comment]
Great, Thank you guys. We might close this one :)
