### ISSUE TITLE
trace_id check to accepts dashes as UUID format

### ISSUE THREAD

**Issue by juancarlosjr97** [apollographql/router#5086]
**Is your feature request related to a problem? Please describe.**
Long story short: trace_id to accept UUID format.

When adding the propagation and the custom header for the trace_id, aka correlation id from Kong, it fails with an error `cannot generate custom trace_id: invalid digit found in the string` as the Kong plugin for correlation id creates it in a format `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`, see Kong Correlation ID Plugin documentation: https://docs.konghq.com/hub/kong-inc/correlation-id/

**Describe the solution you'd like**
The router checks for the trace_id to be a hexadecimal string https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/telemetry/mod.rs#L1850-L1856 which means do not accept dashes and it fails.

**Describe alternatives you've considered**

Raise an MR to accept any kind of string from trace_id.

**Additional context**

Closely related to https://github.com/apollographql/router/pull/5071

**Comment by Samjin** [comment]
related to this too. https://github.com/apollographql/router/issues/5056

**Comment by juancarlosjr97** [comment]
Hey @abernix. Thanks for sharing. I had a quick look but from my understanding, if it is stripping the dashes, how does that provide continuity using the same trace_id on the request, or am I missing something?

**Comment by abernix** [comment]
@BrynCooke You're pretty connected to the work here - Can you advise? (Look carefully they're both different nuances of dashes in trace IDs)

**Comment by BrynCooke** [comment]
@juancarlosjr97 Trace ID in opentelemetry is represented as a 128 bit number. This is usually represented as a hex string without dashes and is based on [w3c trace id](https://www.w3.org/TR/trace-context/#trace-id) format.

The UUID that is supplied by kong is a 128 but UUID. This has dashes in but is still 128 bits and so can be coerced into the Otel 128 bit number by removing the dashes and parsing as hex.

When sending to your APM, depending on protocol it will send the trace ID in different formats, but the APM should understand this and decode them to the same value. At least that's the theory. 

I haven't used kong, but the docs seem to indicate that the otel plugin allows propagation of various formats: 
https://docs.konghq.com/hub/kong-inc/opentelemetry/#propagation. Is this something you have configured?

**Comment by juancarlosjr97** [comment]
Hey guys,

I have pending testing this after https://github.com/apollographql/router/pull/5071. The previous error `cannot generate custom trace_id: invalid digit found in the string disappear but now I have the following error `cannot generate custom trace_id: cannot parse integer from empty string`

The version I am running is v1.52.0 and the only change I have done was adding the 


```yaml

      propagation:
        datadog: true
        request:
          header_name: x-correlation-id
```

I tested different formats of the header, and all are sending that error to the logs.

**Comment by juancarlosjr97** [comment]
I can confirm it is working after #5071 got merged  :) 

Thank you!
