### ISSUE TITLE
distributed Query Plan cache may be poisoned by experimental query plan features

### ISSUE THREAD

**Issue by fotoetienne** [apollographql/router#5093]
**Describe the bug**
If a router instance is sharing a distributed cache with other router instances, and one router instance used experimental query plan features, the resulting query plans will be cached with the same id as query plans that are not using the experimental features. 

**To Reproduce**
1. Deploy a cluster of router instances sharing a distributed cache
2. Deploy a single instance of the router (sharing the same distributed cache) that is configured to use experimental query plan features such as `generate_query_fragments`
3. Issue a request against the new router instance and then the same query against the other instances
4. All instances will issue a query using the experimental query plan feature

**Expected behavior**
Query plans created with different federation versions and federation options will be cached with a unique key

**Comment by fotoetienne** [comment]
A proposed solution is to add `QueryPlannerConfig` to `CachingQueryKey` ([PR](https://github.com/apollographql/router/pull/5094)). Thoughts?

**Comment by Geal** [comment]
yes, adding it to the cache key is the right approach here
