### ISSUE TITLE
Allow defining shared layers for all sub-graphs 

### ISSUE THREAD

**Issue by tomrj** [apollographql/router#512]
**Is your feature request related to a problem? Please describe.**

When configuring header propagation for sub-graphs, if one needs to pass same header to all sub-graphs, configuration file would have a lot of duplication. 

**Describe the solution you'd like**
Set shared layers for all sub-graphs, e.g.

```
shared_layers:
  - ...
```

or similar.

**Describe alternatives you've considered**
Duplicating all same header configuration block for all subgraphs explicitly.

**Additional context**
User authentication details are by default forwarded to all sub-graphs.

**Comment by damienpontifex** [comment]
Might be solved by #599

**Comment by abernix** [comment]
This is indeed fixed by https://github.com/apollographql/router/pull/599.  Please see the release notes for [`0.1.0-alpha.9`](https://github.com/apollographql/router/releases/tag/v0.1.0-alpha.9) for more information on the new `all:` key!
