### ISSUE TITLE
Rhai Scripting - how to get subgraph response code

### ISSUE THREAD

**Issue by flovilmart** [apollographql/router#5158]
Hey team!
We wish to catch 401 errors using a `fn subgraph_service(service, subgraph)` `map_response` handle however the `response` object does not expose `status` or `status_code`, and we're left unpacking the generated errors code and checking for `SUBREQUEST_HTTP_ERROR`.

**Describe alternatives you've considered**

We're checking for the presence of in response.body.errors[].message `401` and in response.body.errors[].extensions.code `SUBREQUEST_HTTP_ERROR`.

**Comment by bnjjj** [comment]
It will be fixed by #5045

**Comment by flovilmart** [comment]
Thanks @bnjjj amazingly fast turnaround!
