### ISSUE TITLE
Go through the Odyssey tutorials with the Router

### ISSUE THREAD

**Issue by abernix** [apollographql/router#523]

**Comment by Geal** [comment]
related: #837

**Comment by garypen** [comment]
Did 1.5 of the 3 stages but then had to stop because the tutorial went into a section requiring auth (https://www.apollographql.com/tutorials/voyage-part2/auth-in-a-federated-graph) which I couldn't achieve in the router without enhancements (JWT). Marking as blocked for now.

**Comment by garypen** [comment]
It should be possible to proceed with this now that we have [experimental JWT authn support](https://www.apollographql.com/docs/router/configuration/authn-jwt).
