### ISSUE TITLE
Error message for invalid 'content-type' in subgraph response doesn't provide enough information

### ISSUE THREAD

**Issue by IvanGoncharov** [apollographql/router#5359]
**Describe the bug**
At the moment error message for invalid 'content-type' in subgraph response looks like this:
```
HTTP fetch failed from 'test': subgraph didn't return JSON (expected content-type: application/json or content-type: application/graphql-response+json; found content-type: text/html)
```

It doesn't contain invalid values, and it doesn't have any explanation of what is wrong with a content type.

**Comment by xzowuniaercm1-cmyk** [comment]
HTTP fetch failed from 'ads-gateway': 503: Service Unavailable HTTP fetch failed from 'ads-gateway': subgraph response contains unsupported content-type: text/plain; expected content-type: application/json or content-type: application/graphql-response+json
