### ISSUE TITLE
Propagate errors from subgraph without hiding

### ISSUE THREAD

**Issue by ghost** [apollographql/router#5397]
Apologies if this is not a bug. Our team has invested the better part of a week trying to get this working, and we have been unsuccessful.

**Describe the bug**
We are unable to get the Router to propagate error message from our subgraphs.

In all the following scenarios, we have router config
```
include_subgraph_errors:
  all: true
```

We have a service (Service P) which is a subgraph in our supergraph. If we send a query with a bad input directly to the Service P, it returns a helpful response error:

```
{
    "errors": [
        {
            "message": "UUID cannot parse the given literal of type `StringValueNode`.",
            "path": [
                "input",
                "acceptorId"
            ],
            "extensions": {
                "field": "Foo.acceptorId",
                "fieldType": "UUID"
            }
        }
    ]
}
```
However if we send the same query to the subgraph via the Router, we get less helpful responses, depending on what `Content-Type` and `Status` we return from Service P.

- If Service P returns status `200` and content type `application/graphql-response+json; charset=utf-8` or a content-type of `application/json`, then the response we get from the router is:
```
{
    "data": null
}
```
^ The secondary concern here, is that it doesn't indicate that an error happened at all. 

- If Service P returns status `400` and content type `application/graphql-response+json; charset=utf-8`, then the response we get from the router is:

```
{
    "data": null,
    "errors": [
        {
            "message": "HTTP fetch failed from 'paymentprocessing': 400: Bad Request",
            "extensions": {
                "code": "SUBREQUEST_HTTP_ERROR",
                "service": "paymentprocessing",
                "reason": "400: Bad Request",
                "http": {
                    "status": 400
                }
            }
        }
    ]
}

```

In this case, it at least indicates that an error happened, but doesn't have any information as to why, which is a bad experience for our customers who are beginning their integration.

**To Reproduce**
1. Any schema on a subgraph behind the router.
2. Return one or more errors from subgraph on request.

**Expected behavior**
I was expecting the errors returned by the subgraph to be included in the response from the router.

**Desktop (please complete the following information):**
- We run Router in a docker container on a Arm64 Linux container.

**Additional context**
- tested on multiple version of Router, including the latest 1.48.1
- include_subgraph_errors is set for all subgraphs
- We tried different combinations of status codes and content types for the subgraph response.

**Workarounds?**
We are also interested in work arounds if anyone can provide direction for that. We already have a couple small Rhai scripts running in production, and are able to add another if required.

Thank you in advanced.

**Comment by abernix** [comment]
This sounds like it could be potentially a bug.  Do you know if there were any previous versions of the Router that didn't cause this? And is it possible for you to provide a runnable reproduction?

**Comment by matt-tesouro** [comment]
I can check out get history, but I believe its at least been since version ~1.36. I will also try to create a minimally reproducible example thats executable. Might need a couple days to find the time though. Thank you for the reply.

**Comment by matt-tesouro** [comment]
Okay I set up a repository here: https://github.com/matt-tesouro/graphql-incorrect-error-propagation

Startup and commands are in the readme, along with the responses I get. Basically:

1. docker-compose up -d
2. Curl commands for getting responses from subgraph directly.
3. Curl commands for getting responses through Router.

If for some reason you want to update the schemas, both subgraphs are in the root directly, and you can recompose them using the command in the readme.

**Comment by alhabibhasan** [comment]
I've seen this as well, adding the following config doesn't seem to let errors pass through:

```yaml
include_subgraph_errors:
  subgraphs:
    api-xxxx: true
```

**Comment by alhabibhasan** [comment]
I'm coming across a similar issue where setting the config to:

```yaml
include_subgraph_errors:
  subgraphs:
    api-xxxx: true
```

Doesn't seem to have any impact on the response and error messages are always redacted.

Has there been any investigation in to a fix?

**Comment by fl-chris-altamimi** [comment]
This is a serious issue for us - Would love to get more eyes on this if possible.

**Comment by ptsteadman** [comment]
We're investigating a similar issue of errors not being propagated from subgraphs with `include_subgraph_errors` being set to `all: true`, but with enum / custom scalar type validation instead. `400` vs `200` status codes from subgraph seems to be relevant.

Some things we learned along the way:
- the issue doesn't happen with validation errors for built-in scalars like using an number when a String is expected; the router returns a 400 directly without sending it to the subgraph, queries with custom scalars (ex DateTime) result in a request to the subgraph
- if an invalid enum value is provided **inline** in a query or mutation, the router returns 400 directly, if it's specified as an input variable, a request is made to the subgraph
- we have both an apollo server 3 subgraph and gqlgen subgraphs. when requests with invalid enums values are made to the apollo subgraph directly, a 400 + errors is returned, for the gqlgen subgraphs, a 200 + errors is returned. apollo router only seems to propagate the errors from the apollo server subgraph (bc status code 400)?

I'll try out the nightly build of with the fix that just got merged to see if it also fixes our issue.

**Comment by grzn** [comment]
+1.

Can't you leave the path as-is? in our case, when the graphql variables contain the wrong thing, we return in the path something like `["variable", "varName", "subKey", "fieldName"]` but the router completely drops the path from the error response.
