### ISSUE TITLE
build spaceport as a binary for release

### ISSUE THREAD

**Issue by garypen** [apollographql/router#546]
**Is your feature request related to a problem? Please describe.**

We build a `spaceport` binary as an executable but don't include it in the release.

**Describe the solution you'd like**

Maybe we should?

**Describe alternatives you've considered**

You can just use a separate router as an external collector. It's a bit odd, but ...

**Additional context**

N/A

**Comment by abernix** [comment]
This has been deferred for a while, so let's close this for now and re-open this if we decide that we need to tackle it again.
