### ISSUE TITLE
Add the ability to insert header from the context in the header layer

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#547]
Following a discussion and suggestion from @Geal it could be great to add the ability for a user to insert a header from the context in the header layer

**Comment by abernix** [comment]
@bnjjj Do you mind taking another look at this when you have a chance? Is this still relevant or something that we should talk about?

**Comment by bnjjj** [comment]
I think yes it could be still relevant ! The idea is to be able to add a header with a value fetched from our extensions given a key. It's not a big priority and could be deferred

**Comment by abernix** [comment]
To quote a bit from a non-GitHub convo:

> In general, would be interested in finding a way for plugins to communicate with each other.  E.g., a notification plugin might need to get the identity and put that into the context for another plugin to see, "okay, do I need to assign something else to a subgraph? do I need to integrate that inside the query exection?".  a way to put something into the context and get something _from_ the context, too. -@Geal
