### ISSUE TITLE
Unnecessary cache warmup message displayed on router startup

### ISSUE THREAD

**Issue by bonnici** [apollographql/router#5489]
## Describe the bug
When starting up the router with no queries to cache, the following message is displayed
> warming up the query plan cache with 0 queries, this might take a while

## To Reproduce
1. Start up the router with no queries or persisted queries to cache.
2. See info-level message noted above.

## Expected behavior
The message should not be displayed unless there is at least one query or persisted query to cache.

## Desktop (please complete the following information):
 - OS: macOS 14.5 (23F79)
 - Version v1.48.1

**Comment by ahsan-naveed** [comment]
https://github.com/apollographql/router/pull/5617
