### ISSUE TITLE
Improve the welcome message of the router 

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#549]
following this discussion https://github.com/apollographql/router/pull/535#discussion_r813095973, the ask here is that we spend some time doing some editorial polish on the output that the `router` displays when you run it without the right configuration.

The place where this lives in the code (as of this commit) is here:

https://github.com/apollographql/router/blob/28cf2b7303c87410ba1f9b997dca5990a134b484/apollo-router/src/executable.rs#L196-L221

Checkout `main` to see where things have drifted to by the time issue is actioned. 😉

**Comment by abernix** [comment]
@StephenBarlow Do you think this is something you could lend some time to between now and ... end of April?

**Comment by StephenBarlow** [comment]
Haha yes I think I can squeeze it in sometime in the next month! I'll add to my list

**Comment by BrynCooke** [comment]
As #780 was merged can we close this?
