### ISSUE TITLE
GRAPHQL_VALIDATION_FAILED returned when a field with variables is filtered out due to authN/Z directives

### ISSUE THREAD

**Issue by kschelonka** [apollographql/router#5648]
## Describe the bug

When 

* an unauthorized portion of a query is removed during filtering (e.g. due to the `@requiresScope` directive)
* and the removed portion references a variable
* and some of the query still remains after the filter step (i.e. the query is not fully unauthorized)

then an error with GRAPHQL_VALIDATION_FAILED is returned and the entire query is rejected instead.

## To Reproduce

1. Set up a router + graph with an authorization directive such as @requiresScopes, which accepts an input

Example: 
```
Query {
   returnMe(var: String!): String @requiresScopes(scopes: [["role:admin"]])
   sayHi: String
}
```

2. Submit a request which requests an unauthorized field with a term, but some of the query should still succeed

Example:

variables = `{"var": "Send this back"}`

```
query returnAndSayHi($var: String!) {
  returnMe(var: $var)
  sayHi
}
```

3. GRAPHQL_VALIDATION_FAILED is returned instead of partial data with an array of UNAUTHORIZED_FIELD_OR_TYPE error(s)

```
{
  "errors": [
    {
      "message": "Variable \"$var\" is never used.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ]
}
```

## Expected behavior
For the authorized components of the query to execute and return data, and the rejected components to be returned as an array of UNAUTHORIZED_FIELD errors.

Example: 

```
{
  "data": {
    returnMe: null,
    sayHi: "Hi!"
  },
  "errors": [
    {
      "message": "Unauthorized field or type",
      "path": [
        "returnMe",
        "@"
      ],
      "extensions": {
        "code": "UNAUTHORIZED_FIELD_OR_TYPE"
      }
    }
  ]
}
```

## Output
Studio examples of this bug on a dev deployment of Pocket's (Mozilla) graph:

* [Fails if query is partially filtered, and the filtered fields contain variables](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAMoICGeUAFgMIR4AOMAzgBQAkLANjAObpSKPAEskfAIQAaIhxT44gksLGSAlEWAAdJESKt8mnXr0sKVaiXIA3BGACS8uO3l5Fs13A3bdJvSggUcm56GFRjEwBfCOjfKAhubgQoFBEIJAAhAhJePjYefkEuXO8IvTFhCBidSJApEGtKEXIAIySWDBAfPS0QAr5ewV6Aa3IUAFp5Fgn4xOTU9N6pCN7PQaJevAQAM1E%2BfDGGJZqQSKA)
* [Succeeds if all fields are filtered out ](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAMoICGeUAFgMIR4AOMAzgBQAkK%2Bc6pKeAJZIA5gEIANEQ4sKVOg2YsylGgGY%2B9JqxXyAirkIkBw8VJlyaWpQDFBAG254ATJsU7L1O4-wsxASiJgAB0kIiJZVQVtdkj5Pgso6w8otSkAMwcnBLirdxZvJ2dAkLDwohQIFHJ7ehhUUPCAX0aiVnwg1vC8BChkFF0aBBZOsvKKni6iFrGIzxJyADcEMABJbjgWACECAHl09NkUNideaVOSqfDK6tqIepQpmebQppAJEEXKQXIAI3thhgQKVwsEQKcwXwwT10kIRPhyJU8GCJK0wblokpBtQ1JDOthDAQ8dCELDBPC8IiGGCmqiyujPMkCll8M48SDymD7ORRDByPDiSAAKIAOTBrVprxATSAA)
* [Succeeds if filtered fields do not contain variables](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAMoICGeUAFgMIR4AOMAzgBQAkLANjAObpSKPAEskfAIQBKIsAA6SIkVb5ZCpUrwIoyFGUo0ELNYo1KU%2BOOo0Bfa3dNQI3btpQiISAEIESvPmw8-IJc-jLypkpiwhD2CjYgADQgAG6UIuQARq4sGCARSnIgQXxFgkUA1uQoALQWLLVOLm4eSEWJ8SA2QA)

## Additional context
* [PR](https://github.com/Pocket/pocket-monorepo/pull/639) containing the changes which are used to reproduce this bug
* Relevant [schema file](https://github.com/Pocket/pocket-monorepo/blob/960af46c5993ee3ae7fe3441cbadc8a4f040d875/servers/user-list-search/schema.graphql#L168)
* Relevant [router code](https://github.com/Pocket/pocket-monorepo/tree/dev/servers/client-api)

Unsure if yall are able to access the studio links -- I can provide cURL examples to a public endpoint on request.

**Comment by carldunham** [comment]
We may be seeing something similar, where variables used only in query directives result in `Variable \"$zzz\" is never used`. If not, can open another ticket.

**Comment by carldunham** [comment]
> We may be seeing something similar, where variables used only in query directives result in `Variable \"$zzz\" is never used`. If not, can open another ticket.

Followed up with https://github.com/apollographql/router/issues/5747. May or may not be related.
