### ISSUE TITLE
SubgraphService : APQ support

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#567]
We now support APQ for incoming requests, but we could use it as clients when interacting with subgraphs:

- Try to perform an APQ request, bail out totally if `PersistedQueryNotSupported` in errors
- Otherwise perform APQ requests as much as possible.

**Comment by radekmie** [comment]
We migrated from the Apollo Gateway to Apollo Router and I was surprised it's not the default. Is there a blocker, or it's just not high in the priorities?

**Comment by saravind-hotstar** [comment]
Is this support exists for subgraph query

**Comment by bnjjj** [comment]
Not yet in the router

**Comment by Geal** [comment]
Done in #2284
