### ISSUE TITLE
Create our own `ApolloServiceExt` trait to provide helpers

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#572]
Following https://github.com/apollographql/router/pull/558#pullrequestreview-898736974

We could create our own `ApolloServiceExt` trait and add the method `with_checkpoint` to be able to have something like `service.with_checkpoint(|req| ...)` and also add other helpers.

**Comment by abernix** [comment]
Is this improved with `ServiceBuilderExt`?

**Comment by abernix** [comment]
My claim is that we're good with `ServiceBuilderExt`, but happy to re-open if there's disagreement. 😸
