### ISSUE TITLE
Send cost complexity to coprocessor/rhai for custom enforcement

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#5738]
## Is your feature request related to a problem? Please describe.
We just launched our new [demand control](https://www.apollographql.com/docs/router/executing-operations/demand-control/#measure-cost-of-existing-operations) which calculates the cost of the incoming operations. We also support advanced telemetry for the operations to track the details.

For enforcing a max value we have a YAML option and maybe in the future we will have something like `@cost` to annotate specific fields and types with what the cost will be. However, for my company, deciding the max value may be dynamic based on the request values, like client headers.

I would like to have access to the current cost value in the coprocessor or Rhai scripts so I can block a request based on my own custom rules

## Describe the solution you'd like
Send the demand control `cost` value to a coprocessor or rhai script, probably most likely through the context and I could use other info like client id to implement my own rate limiting or leaky bucket approach.

## Describe alternatives you've considered
I could send the operation to a coprocessor and re-implement my own cost calculator but it would be much easier if I could use the already calculated value

**Comment by theJC** [comment]
Does https://github.com/apollographql/router/pull/5972 address this?

**Comment by smyrick** [comment]
Yes! Resolved in https://github.com/apollographql/router/pull/5972
