### ISSUE TITLE
ease of use: debug mode

### ISSUE THREAD

**Issue by cyberhck** [apollographql/router#5789]
Currently, if we wanted to use debug (heaptrack) mode on kubernetes, we have few issues:
- the file it writes to, doesn't have any identifier, so if there are multiple pods, they override the same file
- There's no easy way to specify that a container shouldn't be restarted inside the pod. (so that we get new pod if the current pod crashes)

## Describe alternatives you've considered
- writing our own charts and forking dockerfile ourselves, but this is unreasonable

If you guys are okay to change this, I'd like to send a PR that:
- let's user specify [pod lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)
- use `${hostname}` in the heaptrack file path

```[tasklist]
### Tasks
- [ ] add ability to specify pod lifecycle
- [ ] use ${hostname} in the filepath when using debug mode
```

**Comment by BrynCooke** [comment]
This all sounds reasonable. @garypen Do you agree?

**Comment by cyberhck** [comment]
if @garypen agrees, I want to create a PR for it.

**Comment by garypen** [comment]
@cyberhck That seems like a reasonable approach.
