### ISSUE TITLE
Router errors on queries that contains only __typename on root level that wrapped in fragment

### ISSUE THREAD

**Issue by IvanGoncharov** [apollographql/router#6154]
## Describe the bug
Queries like { __typename } works on router but if you wrap it in fragment like this `{ ... { __typename  } }` it produces an error:

> value retrieval failed: empty query plan. This behavior is unexpected and we suggest opening an issue to apollographql/router with a reproduction.

## To Reproduce

See test cases here:
https://github.com/apollographql/router/blob/7402a1b62fb7a08acf1f03149986771af0baf7f9/apollo-router/tests/integration/typename.rs#L74-L138

[ROUTER-749]: https://apollographql.atlassian.net/browse/ROUTER-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by DimaPF** [comment]
Hello. It appears that I've found a way to reproduce this issue or a similar one (at least in version 1.59.1). 
Router returns INTERNAL_SERVER_ERROR with “empty query plan” when all planned fields are excluded via @include(false) and only __typename remains.

When I send any requests like:
`mutation UpdateRoom($input: RoomUpdateDto!) {
  updateRoom(input: $input) @include(if: false){
    id
    name
  }
  __typename
}`
I got the next response:
`{
    "errors": [
        {
            "message": "value retrieval failed: empty query plan. This behavior is unexpected and we suggest opening an issue to apollographql/router with a reproduction.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}`

**Environment**:
Router version: v1.59.1
Federation/supergraph

**Additional context**:
Tried Apollo-Expose-Query-Plan: true, but environment doesn’t return extensions.queryPlan even for successful requests (likely plugin disabled)

**Comment by SimonSapin** [comment]
Hi

* Consider opening a new issue since it’s likely that no-one else will watch a resolved one. (I am not working on this anymore and will unsubscribe from this issue now.)
* I think what you’re running into is: there’s a "root `__typename` only" code path that may currently only apply to queries and maybe should also apply to mutations.
