### ISSUE TITLE
Schema Validation errors should not report as QueryPlannerErrors

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#617]
Since we're instantiating a complete QueryPlanner from a supergraph when we're planning a query that isn't cached, we end up reporting both "invalid schema" and "invalid query" errors as QueryPlannerErrors, which is unfortunate.

Moreover splitting both functions would allow us to ensure a Schema is valid at `startup || schema update`

**Comment by abernix** [comment]
The message was also prefixed with "Query planning error", which was particularly confusing.  It's worth noting that this might _not_ be the case anymore, after #443

**Comment by abernix** [comment]
@BrynCooke is going to validate if this is fixed by virtue of the #443 work.  If it's not done, then we'll just capture the errors as a different struct?
