### ISSUE TITLE
Change our default configuration name for compatibility with schemastore

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#619]
https://www.schemastore.org/json/ frovides a way for editors to discover and automatically download schema for yaml files.
Lots of editors support this without any intervention from users.

This does not eliminate the need to provide decent error messages when parsing yaml at runtime, but it does give the user a huge improvement in experience when editing such files. This is especially important for Yaml where indentation is super easy to get wrong, and even with a good error message it's difficult to spot how to fix a broken file.

Suggest 
`configuration.apollo.router.yaml`

**Comment by abernix** [comment]
This is done with #698.
