### ISSUE TITLE
Consider wrapping calls to `std::env`

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/router#634]
for context, in slack there was a conversation that went something like this:

> @BrynCooke:
> Anyone ever get `error: test failed, to rerun pass '-p apollo-router --lib'` but no actual info on the test that failed?

> @garypen:
> yes
> Is it because you have the APOLLO_KEY stuff set in your env?
> That will make tests fail like that.

This was _not_ in actuality the problem that Bryn ran into, but having your environment influence tests _is_ a footgun, and it's also something that we've solved in Rover.

In Rover we use a HashMap to store all of our environment variables and have a cfg!(test) conditional that sets the map to empty so your local env doesn't mess with your tests. There's a separate mechanism for modifying environment variables in tests as well. This makes it a bit more maintainable and testable, and doesn't require developers to carefully maintain a pristine environment for cargo to run their tests in.

Some important bits of code that can be reffered to can be found here:

here we initialize an empty map if we're running in tests: https://github.com/apollographql/rover/blob/main/src/utils/env.rs#L28
here's an enum containing all of the `APOLLO_*` style env vars: https://github.com/apollographql/rover/blob/main/src/utils/env.rs#L95
here's an example of a test setting an environment variable and making sure ith as the intended effect: https://github.com/apollographql/rover/blob/ff44aebc4dcbfba2831fca29335ef51bb2fe3225/src/utils/telemetry.rs
here's an example of reading an environment variable: https://github.com/apollographql/rover/blob/main/src/utils/telemetry.rs#L84

---

perhaps this is something that would benefit the router! perhaps there is a different design that you think would work better! I don't think I've done a great job of lazily querying for the environment variables - if y'all take this and improve it i'd love to share those improvements w/rover. it may even be worth its own open source repository.

**Comment by BrynCooke** [comment]
I think we're going to completely eliminate calls to `std::env` and go with structopt env handling.
This a couple of reasons for this:
1. We have put env variables in because a component was developed before out plugin architecture was finished. We can eliminate these by implementing the plugins and using the regular config mechanism. These evn variables should never have existed.
2. By using structopt env variables are discoverable. The user can see them in the router help command.

We still need to have a conversation around secrets.

**Comment by BrynCooke** [comment]
https://github.com/apollographql/router/pull/741/commits/84d48ad529c213cac5135bb4f7db71ce7a0a150a#diff-f157a81480ffeda854898c919ba73523c13c683c57532d5fa6545ef703846650R278-R291

This is still slightly orthogonal to the ticket text, which correctly states that for testing env variables need to be abstracted. Let's do our best to eliminate all env variables first though. I'm wondering if we aught to do some pre-processing on config loading. This would make things super clean.

**Comment by EverlastingBugstopper** [comment]
closing as won't do
