### ISSUE TITLE
Is there any provision to customise the Apollo router landing page

### ISSUE THREAD

**Issue by riginoommen** [apollographql/router#6425]
If the introspection is disabled is there any way to show a custom page for the api endpoints.

**Comment by goto-bus-stop** [comment]
No, neither the home page nor the sandbox page are intended for production use, and neither are configurable. If you really want to serve custom content at the root, I'd suggest putting something like nginx in front of the router, then you can point `/graphql` requests at the router and other requests can serve static content or whatever else you might want to host.
