### ISSUE TITLE
Telemetry: zipkin end to end test

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#654]
More than once have ended up in a position where we lost Tracing spans.

While test-span adds snapshots to the router spans, which allows us to track regressions, we still sometimes lose subgraph spans in our traces.

We should find a way to programmatically query jaeger or zipkin once we've run a query, so we can have an end to end test that fails if a regression occurs again.

**Comment by Geal** [comment]
jaeger is done, zipkin is next

**Comment by o0Ignition0o** [comment]
Is this a threat ? 🤣

**Comment by abernix** [comment]
This doesn't seem to be as much as a threat anymore and has been deferred for a while.  Let's re-open if we need.  Thanks!
