### ISSUE TITLE
Input object validation issue

### ISSUE THREAD

**Issue by milad-habibi** [apollographql/router#655]
Hi Router team,
There is a minor issue related to the lack of input object validation capability in the apollo-router-core crate.

**To Reproduce**
1. Use a schema which includes input objects for example,
```
input SearchFilter {
  keyword: KeywordFilter
  companies: CompanyFilter
  date: DateFilter
}
```
2. Run a query using that input object against the router endpoint and check the output.

**Expected behavior**
The router should be able to validate the input object.

**Output**
```
{
  "errors": [
    {
      "message": "Invalid type for variable: 'filter'",
      "locations": [],
      "path": null,
      "extensions": {
        "type": "ValidationInvalidTypeVariable",
        "name": "filter"
      }
    }
  ]
}
```

**Additional context**
The current implementation of the Schema struct doesn't include the input objects,
```
pub struct Schema {
    string: String,
    subtype_map: HashMap<String, HashSet<String>>,
    subgraphs: HashMap<String, String>,
    pub(crate) object_types: HashMap<String, ObjectType>,
    pub(crate) interfaces: HashMap<String, Interface>,
    pub(crate) custom_scalars: HashSet<String>,
    pub(crate) fragments: Fragments,
    pub(crate) enums: HashMap<String, HashSet<String>>,
    api_schema: Option<Box<Schema>>,
}
```
Also, the necessary validation arm should be added to the `validate_value` function.

**Comment by Geal** [comment]
thanks for the report, looking into it

**Comment by jorgexgb** [comment]
Hi router team, was this fixed in the `v0.9.3` release? Just curious since I'm also experiencing this issue in v0.9.3.

**Comment by o0Ignition0o** [comment]
Hey @jorgexgb,
The [corresponding pull request](https://github.com/apollographql/router/pull/658/files#diff-3bc44ed791f17958d00dcbcdff996a241de8da3f2f5b1a3226ebf161245c4da3) added tests; could the issue you're facing exhibit a corner case we haven't thought of?

If it's the case, could you please open an other issue, with steps to reproduce? that would be super helpful! 🙏

**Comment by jorgexgb** [comment]
Will do!
