### ISSUE TITLE
Studio Agent

### ISSUE THREAD

**Issue by abernix** [apollographql/router#66]
# Requirements

TBD.  An agent which communicates with Studio and acts as the foundation for operation (signature-based), field (shape) and latency (trace) stats to power Apollo Studio functionality.

## Relevant Subtasks / Links

These are likely components/candidates of this agent!

- [x] #442 
- [x] #67
- [ ] #70
- [x] https://github.com/apollographql/router/issues/127
- [ ] Tracing support (incl. Resolver timing; might be implemented via opentelemetry tracing or #74)

**Comment by Geal** [comment]
relevant links for  how data must be filtered for privacy reasons:
- https://www.apollographql.com/docs/studio/data-privacy/#what-data-does-apollo-server-send-to-apollo-studio
- https://www.apollographql.com/docs/studio/performance/#signature-algorithm

**Comment by garypen** [comment]
I'm working on three components of this at the moment:

- [ ] Adding a basic infrastructure to allow usage data to be transferred from the router to studio usage ingress
- [ ] Normalising queries to that statistics are reported accurately
- [ ] Figuring out which statistics to collect and how to present them in the required format

The first task has been prototyped fairly completely. There is still outstanding work relating to configuration and how best to integrate the work with the opentelemetry framework.
The second task is mainly relying on work which needs to be done in apollo-rs. @lrlna Is there a ticket for the semantic validation work that I can reference here?
The third task isn't started yet.

**Comment by lrlna** [comment]
@garypen yes, the overview ticket is apollographql/apollo-rs#144

**Comment by abernix** [comment]
@garypen Administratively: https://github.com/apollographql/router/issues/67 is currently marked as _Deferred_, though I think it's wound up / inclusive of the stuff you're working on.  Is that right?  (If _yes_, would it make sense to mark that more granular issue as "In Progress", update #309 to indicate that it closes that issue and keep this as a higher-level longer-term coordination issue?).

**Comment by abernix** [comment]
@garypen Ok, that's fair — I agree some issue grooming is in order.  I definitely understood that it was just Phase 1 that you were doing — it's absolutely true that phase doesn't include field usage reporting, I just forgot that. In that regard, I think the answer to my question above is merely "No" (and, in retrospect, I could have latched onto that — I was merely doing some cleaning up to make sure that PRs were closing issues.)

Looking at this particular issue, it's possible it's not the right match for what I was looking for, which is "the issue that #309 should close".

With that in mind, I think we're missing an issue for the Phase 1 work.  What do you think about:

1. Opening an issue that is just for the operation-based reporting / Phase 1 stuff, documenting what's in the doc.  We should communicate (publicly) what the scope of work is.
2. Add it to the board and add appropriate GH Project metadata to it — iteration, size, etc.
3. Edit #309 to indicate that it closes that new issue.  (It'll be necessary for the review to make sure it ticks the boxes, ya?)
4. Consider leaving this issue open as the umbrella issue that I think it is today — update it to convey the expected follow-up stuff (e.g., phase 2, etc.).  Alternatively, consider editing this to just cover the "Agent" part of it, if that's even interesting on its own.

Thoughts? (If you agree, feel free to go for it?)

**Comment by abernix** [comment]
Most of the items on this parent issue are closed, so I'll close this and leave the child issues to hold their weight in terms of follow-up items.
