### ISSUE TITLE
Integration tests: Make sure examples config don't go out of sync 

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#660]
We should write an integration / infrastructure test that iterates on each of the examples and makes sure any  `/**.config.yaml` is still parseable and valid.

We should consider that custom plugins will require us to "use" them before we try to parse the configuration though.

**Comment by abernix** [comment]
At the very least, we should compile our `examples/*` in CI to make sure that they're not broken.  We can also validate the YAML of those projects against the JSON schema from `./router --schema` output.
