### ISSUE TITLE
make subgraph response headers accessible to plugins

### ISSUE THREAD

**Issue by Geal** [apollographql/router#661]
plugins only have access to subgraph request headers, they cannot read what is coming back from the subgraph. We need it for use cases like cache keys: https://github.com/apollographql/router/issues/648

Implementation ideas:
- one key in the context that would be a list of subgraph responses. Each response has the headers and some basic metadata like error/success. This could be wasteful, if we never use the response headers
- response headers are only available to subgraph plugins. If we want to use them somewhere else, a subgraph plugin would have to explicitely take the header and put it in the context (as we do with header propagation) so that another plugin down the line can read it
- headers are stored as:
  - a map: wrong (headers can have duplicate names) but easy to manipulate
  - a list: right but harder to manipulate

**Comment by BrynCooke** [comment]
I'm not sure that we need to have anything special added by default. A caching plugin would be expected to hook into the subgraph and router services and can therefore decide what they need and maybe even to key calculation in upsert.

It's not caching, but this example illustrates the approach. 
https://github.com/apollographql/router/tree/main/examples/status-code-propagation

It could work for cache control headers quite nicely.

**Comment by Geal** [comment]
so this is done now, right?
