### ISSUE TITLE
Public API: have a pass at apollo-router and apollo-router-core

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#680]
Our public API is currently growing while we're iterating on our extensibility model.

Now would be a great time to take a step back and put intent behind what is public / pub(crate) and private.

Steps before a discussion would include opening the router and core docs and listing what is available.

**Comment by SimonSapin** [comment]
Closing in favor of https://github.com/apollographql/router/issues/1150 which has some more discussion.
