### ISSUE TITLE
Configuration containers should not be empty

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#683]
Some of our configuration containers only optional fields, or no fields at all.
This leads to confusing configuration. For instance, to enable Jaeger:

```yaml
telemetry: 
  opentelemetry: 
    jaeger: 
```

Suggestions:
* All containers should require at least one mandatory field with the exception of maps.
* If there's nothing to configure then one boolean field should be used called `enabled`

We need to audit all our config for this, and ideally add a test to flag this early, maybe in schema generation?

**Comment by bnjjj** [comment]
Adding more context and data coming from a discussion:

+ Get rid of `spaceport` wording in the configuration
+ Having a `disabled` flag on each plugin to disable it and by default it's set to `false`

**Comment by krisztian-sala** [comment]
Does this mean that the router currently supports Datadog? If yes, can you update the documentation with an example? Because currently there is only one with Jaeger

**Comment by BrynCooke** [comment]
@krisztian-sala Not currently. The example above is a desired final state. That being said, there are many people asking for Datadog support, so hopefully we can add support soon.

**Comment by krisztian-sala** [comment]
> @krisztian-sala Not currently. The example above is a desired final state. That being said, there are many people asking for Datadog support, so hopefully we can add support soon.

Thank you, that would be great :)

**Comment by BrynCooke** [comment]
@krisztian-sala Good news! Datadog support will be added in #782.
Unfortunately it's not going to make today's release, but will be in `preview.4` next week.

**Comment by krisztian-sala** [comment]
Awesome, thank you!
