### ISSUE TITLE
consider query deduplication off by default and documenting its availability

### ISSUE THREAD

**Issue by abernix** [apollographql/router#717]
Mostly to track a discussion that should happen.

We should at the very very least document that this behavior is on by default, but practically speaking this might be a very surprising change for those who are migrating from the Apollo Gateway.  These sorts of requests do have other state-changing properties to them (like tracking for analystics, etc.).

That's not to say this isn't incredibly valuable, but I think it should be opt-in rather than opt-out and it could be a plugin.

**Comment by nateql** [comment]
Was closed on the team board so I am closing it here.
