### ISSUE TITLE
Outbound header propagation

### ISSUE THREAD

**Issue by abernix** [apollographql/router#75]
Distinct from [Selective inbound header propagation #83](https://github.com/apollographql/router/issues/83), but for going back to the client (e.g., selectively picking headers from certain subgraphs to expose directly to the client, like a `Set-Cookie` header)

**Comment by abernix** [comment]
Closed as part of #303.  This should be possible now with the new header extension configuration stuff which is incoming!

**Comment by LockedThread** [comment]
You should add this in the documentation... there's only information on inbound header propagation.
