### ISSUE TITLE
Option to disable introspection and landing page

### ISSUE THREAD

**Issue by gordancso** [apollographql/router#757]
There should be 
- an option to disable introspection (similar to apollo-server, where setting `NODE_ENV` to `production` will switch off the introspection).
- Landing Page options, similar to this plugin (https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/)

**Comment by bnjjj** [comment]
About the introspection we merged a PR to disable it when needed yesterday https://github.com/apollographql/router/pull/749

**Comment by BrynCooke** [comment]
As this has been merged I'm gonna close this for now. We're expecting to do a release this week.
