### ISSUE TITLE
Router Record/Replay Plugin(s)

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#765]
# The problem

Early router adopters will try to compare gateway and router responses, and will identify queries and mutations where the router response doesn't quite match the gateways. Or where the response isn't what they would expect.

They will (hopefully!) get in touch with us, and we will start investigating together and try to reproduce the mismatch. So far it boils down to:
- Getting access to the relevant parts of the schema (so we can define a query plan)
- Figuring out what http request is sent to the router
- What http requests are sent to the subgraphs
- What http responses are received from the subgraphs
- What http response is sent from the router

Note by http requests / responses I mean anything from method, url, headers, extensions, body etc.

Once we receive all of this, we will try to set up a mock subgraph that will reply what the subgraphs did, and do all sorts of hacks to try to reproduce the behaviour.

# The Solution(s)

The proposed solution would be a plugin that allows us to:
- Record important steps mentioned above and store them in a file or a directory.
- Replay specific requests, so we can troubleshoot the router.

# Constraints

- Users should be able to decide whether a query shall be recorded or not
- Users should be able to run a live query or run the replayed one
- Some information such as the schema (that allows us to create a query plan) can be sensitive

# How can we implement this in rust?

We would need... a plugin!
Given there's quite a bit of work to do, we're going to go step by step:

## Step 1, watch incoming traffic for a specific header:
In the router_service part of our plugin, we will add a step on each incoming request that checks for the presence of specific headers, say "X-record-router-query" and "X-replay-router-query".

Once we have found one of these, we need to send the information to the other "hook points" of the request lifecycle. We will do so leveraging the Context!

Pseudocode:
```
If "X-record-router-query" {
	request.context().insert("router-record", true); // let the plugin know it should record something
}

If "X-replay-router-query" {
	request.context().insert("router-replay", true); // let the plugin know it should replay something
}
```

Ok so now in the `router_service` section, we have added a bit of `context` so that other _service steps will know whether they should so something or not. Let's split the following steps into two parts, one dealing with the record functionality, and the other one dealing with the replay functionality:

## Record:

There are four things we want to do in order to record what is happening in a query:
- Record the query received by the router
- Record the query plan (so we don't need the whole schema to replay a query)
- Record subgraph Requests and responses (so we will be able to mock then in the replay phase)
- Serialize and store each of the items (so the replay phase will be able to use them)

## Replay:

Now the Replay part will be kind of symmetrical to the Record part, we want to:
- Retrieve the Serialized data from the recorded query
- Restore the query plan instead of performing a new one
- Use a Mock mechanism to create Subgraph Services (kind of like what we do [in the benchmarks](https://github.com/apollographql/router/blob/209ce362824f82c8c613193aa3c343cc976e2f4c/apollo-router-benchmarks/benches/basic_composition.rs#L88)) that reply instead of making an actual http query

This is a rough draft, which I'll update once I have more time feel free to ping me if you would like to pair or to have more context!

If you would like to tackle parts of this and have no idea how, please ping me I'll be more than happy to walk it through with you.

**Comment by lennyburdette** [comment]
do you also want a record/replay plugin in the nodejs gateway? would you want to replay a request/response recorded by the gateway in the router?

**Comment by o0Ignition0o** [comment]
Wow that would be really cool!

Plus If we had a common structure for the serialized data, we would be able to generate / use it on the gateway and the router in a seamless way, which would be really helpful!

**Comment by abernix** [comment]
While we've hoped to have done this for a while, we're not going to get to this anytime soon.  We'll be happy to re-open this in due time, but that time is not now.

**Comment by Geal** [comment]
done in https://github.com/apollographql/router/commit/badaffdba245b1e26f2119e48dfc3084fde3b851
