### ISSUE TITLE
Router information

### ISSUE THREAD

**Issue by carlocorradini** [apollographql/router#793]
**Is your feature request related to a problem? Please describe.**
Obtain general information about the binary (e.g. version, rustc, and more???) via an information flag (e.g. `--version` or directly in `--help`).
Currently, the only way to get general information is to start the router, obtaining only the version and useless help messages (in this case).

**Describe the solution you'd like**
Add a flag to obtain information (e.g `--version`) or enhance `--help`.

**Additional context**
It is very useful when the installation is automated and in script contexts. E.g. `install.sh` script file in [supergraph-demo-fed2](https://github.com/apollographql/supergraph-demo-fed2).

**Comment by o0Ignition0o** [comment]
Thanks for filing this issue!

I feel like --version would be most convenient for scripting purposes, but it doesn't prevent us from doing both!

**Comment by carlocorradini** [comment]
@o0Ignition0o Awesome🤯🥳

**Comment by garypen** [comment]
#780 is going to improve the help message. I think it's worth having a `--version` flag, so this issue is now specifically addressing that requirement.
