### ISSUE TITLE
make a separate tracing structure for Studio reporting

### ISSUE THREAD

**Issue by Geal** [apollographql/router#795]
currently the query execution trace is generated using tracing spans. While the tracing infra is designed for that kind of use case, right now it is unreliable because it collides with other concerns like opentelemetry:
- opentelemetry sampling affects studio traces, some of them are not sent
- log level filters affect studio traces, we need to set `INFO` on `apollo-router` and `apollo-route-core`, otherwise they are not sent
- adding the graphql query to the root span's variables pollutes the logs in CLI

We should instead have a separate, smaller span structure that is activated or not depending on studio reporting, and entirely (except the root span created in the HTTP server) manipulated in the query planner execution

**Comment by bnjjj** [comment]
Also related to https://github.com/apollographql/router/issues/790 I think

**Comment by BrynCooke** [comment]
Can we use the otel metrics infra rather than tracing for this? Metrics are never sampled and the data feels like a metrics thing rather than a tracing thing.

**Comment by nateql** [comment]
Closing this ticket since it is closed on the project board.
