### ISSUE TITLE
Documenting the public API

### ISSUE THREAD

**Issue by garypen** [apollographql/router#799]
**Describe the solution you'd like**
If you build rust docs many of our `pub` modules, structs, etc... have no documentation. We should have minimal documentation for all the `pub` components and we should consider making some `pub` components private before GA if they aren't really for pub consumption.

**Describe alternatives you've considered**
No alternative really, we need to add the documentation.

**Additional context**
Improve usability of the various components and an important pre-cursor to releasing crates.

----

As of 2022-09-15, these files have `allow(missing_docs)` attributes that we should remove as we write new docs. See https://github.com/apollographql/router/issues/799#issuecomment-1217767779.

* [x] `apollo-router/src/configuration/mod.rs`
* [ ] `apollo-router/src/error.rs`
* [x] `apollo-router/src/graphql.rs`
* [x] `apollo-router/src/http_ext.rs`
* [ ] `apollo-router/src/json_ext.rs`
* [x] `apollo-router/src/layers/instrument.rs`
* [x] `apollo-router/src/layers/map_first_graphql_response.rs`
* [x] `apollo-router/src/layers/map_future_with_request_data.rs`
* [x] `apollo-router/src/layers/sync_checkpoint.rs`
* [ ] `apollo-router/src/lib.rs`
* [x] `apollo-router/src/plugin/serde.rs`
* [ ] `apollo-router/src/plugin/test/mock/subgraph.rs`
* [ ] `apollo-router/src/plugin/test/service.rs`
* [ ] `apollo-router/src/query_planner/mod.rs`
* [x] `apollo-router/src/request.rs` via https://github.com/apollographql/router/pull/1850
* [ ] `apollo-router/src/response.rs`
* [ ] `apollo-router/src/router.rs`
* [ ] `apollo-router/src/services/execution.rs`
* [ ] `apollo-router/src/services/query_planner.rs`
* [ ] `apollo-router/src/services/subgraph.rs`
* [ ] `apollo-router/src/services/supergraph.rs`
* [ ] `apollo-router/src/services/transport.rs`
* [x] `apollo-router/src/test_harness.rs`
* [x] `apollo-router/src/tracer.rs`

**Comment by SimonSapin** [comment]
https://github.com/apollographql/router/pull/1526 adds `#![warn(missing_docs)]` to the crate, and finer-grained `#![allow(missing_docs)]` or `#[allow(missing_docs)]` on modules or other items that are still missing documentation.

To make progress on this:

* Find an occurrence of `allow(missing_docs)` in the code base
* Remove it
* See new warning pointing to relevant items
* Write meaningful documentation
* Check what it looks like with `cargo doc --open`
* If needed (submitting a PR with only some warnings fixed), add `allow(missing_docs)` back either where it was or at more specific location(s).
* Submit PR

As of https://github.com/apollographql/router/pull/1526, exceptions exist in these files:

```
apollo-router/src/configuration/mod.rs
apollo-router/src/error.rs
apollo-router/src/graphql.rs
apollo-router/src/layers/cache.rs
apollo-router/src/layers/instrument.rs
apollo-router/src/layers/map_future_with_context.rs
apollo-router/src/layers/sync_checkpoint.rs
apollo-router/src/plugin/mod.rs
apollo-router/src/plugin/serde.rs
apollo-router/src/plugin/test/mock/subgraph.rs
apollo-router/src/plugin/test/service.rs
apollo-router/src/query_planner/mod.rs
apollo-router/src/request.rs
apollo-router/src/response.rs
apollo-router/src/router.rs
apollo-router/src/services/http_ext.rs
apollo-router/src/services/mod.rs
apollo-router/src/stages.rs
apollo-router/src/test_harness.rs
```

**Comment by garypen** [comment]
@apollographql/router This is a team goal for api:1.0, so let's crowd source this and write some documentation.

**Comment by SimonSapin** [comment]
Some existing doc-comments are used for `derive(Display)` but don’t render to something useful rustdoc. We can use `#[displaydoc("...")]` to have something different in each: https://docs.rs/displaydoc/latest/displaydoc/#details

**Comment by garypen** [comment]
sigh, sometimes keywords catch us out. re-opening.

**Comment by garypen** [comment]
Re-classifying as Todo.
