### ISSUE TITLE
Router returns empty response for graph

### ISSUE THREAD

**Issue by nikita-tkachov** [apollographql/router#812]
**Describe the bug**
When running a specific graph query, Apollo Router will return an empty response.
 
**To Reproduce**
1. Clone https://github.com/nikita-tkachov/sample-apollo-router-issues 
2. Run `docker-compose -f docker-compose.router.yaml up -d ` to run the router with the specific setup
3. Run the following query:
```
query MyClubsQuery {
  clubs {
    edges {
      node {
        id
        thumbnail {
          id
          type
        }
        posts {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```

4. The response from the router should be `{}`

**Expected behavior**
The same query, ran on the nodejs federation gateway instead of apollo router returns the correct response.

To see the correct response:
1. Run `docker-compose -f docker-compose.yaml up -d ` - this runs the nodejs federation gateway instead of the router
2. Run the same query
3. The following response (correct) appears:
```
{
  "data": {
    "clubs": {
      "edges": [
        {
          "node": {
            "id": "1234",
            "thumbnail": null,
            "posts": {
              "edges": [
                {
                  "node": {
                    "id": "512"
                  }
                },
                {
                  "node": {
                    "id": "4251"
                  }
                }
              ]
            }
          }
        },
        {
          "node": {
            "id": "123456",
            "thumbnail": null,
            "posts": {
              "edges": [
                {
                  "node": {
                    "id": "512"
                  }
                },
                {
                  "node": {
                    "id": "4251"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

**Desktop**
 - OS: Windows 11 + WSL2 (running everything here in WSL2)

**Additional context**
This is not my actual setup where I encountered this error, I run all my subgraphs in Go. However, I was able to reproduce this on a regular nodejs subgraph.

The subgraphs run federation v1, if I'm not mistaken.

**Comment by Geal** [comment]
so, looking at what happens here, it is missing data from some subgraphs. After all the queries, the aggregated response looks like this:
```json
{
  "data": {
    "clubs": {
      "edges": [
        {
          "node": {
            "__typename": "Club",
            "id": "1234",
            "thumbnail": null
          }
        },
        {
          "node": {
            "__typename": "Club",
            "id": "123456",
            "thumbnail": null
          }
        }
      ]
    }
  }
}
```

This fails response formatting because the `posts` field is not present while it should be non null, and since `node`, `edge` and `clubs` are non null too, this invalidates the entire response.

In the execution, I see a first query to `clubs`: `query MyClubsQuery__clubs__0{clubs{edges{node{__typename id thumbnail{__typename id}}}}}` with result:

```json
{
  "data": {
    "clubs": {
      "edges": [
        {
          "node": {
            "__typename": "Club",
            "id": "1234",
            "thumbnail": null
          }
        },
        {
          "node": {
            "__typename": "Club",
            "id": "123456",
            "thumbnail": null
          }
        }
      ]
    }
  }
}
```

then a query to `posts` `query MyClubsQuery__posts__1($representations:[_Any!]!){_entities(representations:$representatio
ns){...on Club{posts{edges{node{id}}}}}}` with variables `{"representations": Array([Object({"__typename": String("Club"), "id": String("1234")}), Object({"__typename": String("Club"), "id": String("123456")})])}` and result:
```json
{                           
  "data": {                 
    "_entities": [          
      {                     
        "posts": {          
          "edges": [        
            {               
              "node": {     
                "id": "512" 
              }             
            },              
            {               
              "node": {     
                "id": "4251"
              }            
            }              
          ]                
        }                  
      },                   
      {                    
        "posts": {         
          "edges": [       
            {              
              "node": {    
                "id": "512"
              }
            },
            {
              "node": {
                "id": "4251"
              }
            }
          ]
        }
      }
    ]
  }
}
```

So the issue is probably in JSON response merging
