### ISSUE TITLE
Add generated operationName to query params

### ISSUE THREAD

**Issue by kdawgwilk** [apollographql/router#814]
Router appears to generate operation names for subgraphs 
```json
{
  "params": {
     "query": "query <ORIGINAL_OP_NAME>_<SUBGRAPH_NAME>_0(...) { ... }",
     "variables": {}
   }
}
```
but it would be great if it also added the `operationName` to like apollo client does e.g.
```json
{
  "params": {
    "query": "query <ORIGINAL_OP_NAME>_<SUBGRAPH_NAME>_0(...) { ... }",
    "operationName": "<ORIGINAL_OP_NAME>_<SUBGRAPH_NAME>_0",
    "variables": {}
  }
}
```

**Comment by smyrick** [comment]
For reference, here is the feature PR that added this to the gateway: https://github.com/apollographql/federation/pull/1550

**Comment by BrynCooke** [comment]
This'll make it in to preview.5.
