### ISSUE TITLE
Out of order/Cache issue during resolution

### ISSUE THREAD

**Issue by neslinesli93** [apollographql/router#846]
**Describe the bug**
This issue is really weird to describe, and hard to reproduce. Basically, I'm trying to put the router in front of a web application that has a frontend that speaks graphql with an elixir (absinthe) backend. The frontend performs many concurrent graphql requests (5/6 at a time) at startup, then makes at most 2 requests at a time, usually just 1. Everything worked fine until version `v0.1.0-preview.2` of the router, but with preview 3 and 4 weird issues started to happen.

Basically some queries started returning empty response `{}`, and some other queries fail due to missing arguments. The way this happens is related to the state of the router: it always fails in the same ways, until the router is restarted. After a restart, it may happen that queries that previously failed start working, and new unrelated queries start failing. So it looks like a cache/resolution order problem, as if the router tried to resolve a new query using the resolution plan of the immediately previous query.

I've got a log of the router, launched with `--log trace`, and a `curl` that makes me reproduce the issue locally. As I said above, everytime I restart the router this happens with completely different queries, but there is a pattern. I'm sorry but I can't upload my webapp code, nor I was able to create a repo that reproduces the issue :(

**To Reproduce**
1. Start the router with a couple subgraphs, but perform queries that hit only one of them
2. Perform a query (`autorita`) that return a large set of items

```sh
curl 'http://gateway' \
  -H 'Content-Type: application/json' \
  --data-raw '{"query":"query {\n  autorita {\n    code\n    label\n  }\n}","variables":{}}' \
  --compressed \
  --insecure
```
3. The router returns `{}`
4. Looking at the logs, the router is using a query plan that's completely wrong: it's trying to resolve `autorita` field calling `ospedali`, which is a query that has been made before by the frontend of the webapp

```
{"timestamp":"2022-04-13T14:22:26.694775Z","level":"TRACE","fields":{"message":"subgraph fetch to our_service_name: operation = '{ospedali{id label provinceCode}}', variables = {}, response:\n{\n  \"data\": {\n    \"ospedali\": [\n      {\n        \"id\": \"123\",\n        \"label\": \"TEST\",\n        \"provinceCode\": \"TT\"\n      }\n    ]\n  }\n}"},"target":"apollo_router_core::query_planner::log","span":{"name":"fetch"},"spans":[{"method":"POST","uri":"/graphql","version":"HTTP/1.1","name":"request"},{"operation_name":"","query":"query {\n  autorita {\n    code\n    label\n  }\n}","name":"graphql_request"},{"name":"execute"},{"name":"fetch"}]}
```
5. In the end, the router has the json for `ospedali` and tries to match it with the resolution for `autorita`, which in the end produces and empty body. Not even an empty `data`, but really an empty json.

I've attached some logs, maybe they are useful: they start from the `curl` and end after the empty response from the router:
[log.txt](https://github.com/apollographql/router/files/8482613/log.txt)

**Expected behavior**
The router should not mix up resolution plans

**Comment by BrynCooke** [comment]
#768 is a candidate.

**Comment by o0Ignition0o** [comment]
Hi, thanks for filing this issue!

I think this happens in the way I've designed the query planner, I'll try to reproduce it and come up with a fix this week!

**Comment by o0Ignition0o** [comment]
I've added a test that reproduces this behavior in [the router bridge repository](https://github.com/apollographql/federation-rs/pull/104)

```
---- planner::tests::it_doesnt_race stdout ----
thread 'planner::tests::it_doesnt_race' panicked at 'assertion failed: `(left == right)`
  left: `Object({"kind": String("QueryPlan"), "node": Object({"kind": String("Fetch"), "serviceName": String("accounts"), "variableUsages": Array([]), "operation": String("{me{name{last}}}"), "operationKind": String("query")})})`,
 right: `Object({"kind": String("QueryPlan"), "node": Object({"kind": String("Fetch"), "serviceName": String("accounts"), "variableUsages": Array([]), "operation": String("{me{name{first last}}}"), "operationKind": String("query")})})`', router-bridge/src/planner.rs:525:21
```
