### ISSUE TITLE
Sending traces to Datadog agent

### ISSUE THREAD

**Issue by krisztian-sala** [apollographql/router#851]
**Describe the bug**
I deployed the version `v0.1.0-preview.4` to a Kubernetes cluster that has the Datadog Helm chart running.
I tried multiple different configurations for the router, but it can't send the traces to the agent.

**To Reproduce**
First I tried with the default setting for the endpoint:
```
...
   tracing:
    propagation:
      datadog: true
      trace_context: true
    datadog:
      endpoint: default
...
```
This is trying to send the traces to `http://127.0.0.1:8126/v0.5/traces`, but this is not working, because the DD agent is not running inside the pod, but as a daemonset. 

After, I changed the endpoint from `default` to `datadog.default` (service name: namespace), `http://datadog.default` and `http://datadog.default:8126`, but none of them worked.

The last one should work in theory, but checking the logs, the router is trying to send the traces to `http://datadog.default:8126//v0.5/traces` (notice the double slash after the port). I ran a curl and `http://datadog.default:8126/v0.5/traces` is accessible, ut the double slash version is not.

**Possible actions**
- Fix the bug, so it doesn't append 2 / characters at the end of the URL
- Improve the documentation with an example of a non-default endpoint URL
- Maybe improve the error messages as well, to make it easier to know what the problem is

**Comment by Geal** [comment]
thanks for the report! This is apparently caused by opentelemetry-datadog: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-datadog/src/exporter/mod.rs#L209

I'll open an issue there and make a small fix in the router

**Comment by krisztian-sala** [comment]
Also, the environment / namespace doesn't appear in the trace, even though I set it in the configuration:
`          service_namespace: "${DD_ENV:mynamespace}"
`

**Comment by col** [comment]
I'm also having issues sending traces to the agent. I think there may need to be some more actions taken as suggested by @krisztian-sala :
- Improve the documentation with an example of a non-default endpoint URL
- Maybe improve the error messages as well, to make it easier to know what the problem is

As this issue is closed I will open a new issue.
