### ISSUE TITLE
Port and the forwarded headers to set the scheme in http_request

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#852]
it would be good to look at the port and the forwarded headers to set the scheme, but let's leave that for a follow up PR

__Originally posted by @Geal in https://github.com/apollographql/router/pull/751#discussion_r848122694__

**Comment by abernix** [comment]
e.g., [`x-forwarded-proto`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), for example.

**Comment by bnjjj** [comment]
Discussed with @Geal about this issue. I'm not feeling confident to modify the original http request by using forwarded headers. It could produce some weird situations when we think the http request we're seeing in our plugin chains is what the router saw when accepting the request but in fact it's not. And if for example the user wants to know what was the shape of the original request he's still able to check the forwarded headers and do whatever he wants. I think it's better and less confusing to not modify the original request.
