### ISSUE TITLE
Follow the GraphQL spec about Response format

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#859]
After reading and digging a little bit into the GraphQL spec I discovered this part https://spec.graphql.org/October2021/#sec-Response and especially this part:

```
If an error was raised before execution begins, the data entry should not be present in the result.

If an error was raised during the execution that prevented a valid response, the data entry in the response should be null.
```

Could be interesting to check we're following these rules, and if we should follow them.

**Comment by abernix** [comment]
Let's also verify that we're not returning `data` in the event of validation or parsing stages?

**Comment by Geal** [comment]
there's a side question to that: how do we handle that behaviour from subgraphs. The code will be able to handle a data field absent or null, but should we have a different behaviour if the subgraph error was not an execution one?
