### ISSUE TITLE
jsonschema dependency requires features to build `apollo-router`

### ISSUE THREAD

**Issue by DoumanAsh** [apollographql/router#874]
Latest `jsonschema` version require to enable features to compile `apollo-router`
So probably would be good to add it by default in `jsonschema` pinned to 0.15.1 or add features required in Cargo.toml

```
jsonschema-0.15.2\src\resolver.rs:85:21
   |
85 | /                     compile_error!(
86 | |                         r#"the `reqwest` feature alone does not enable HTTP schema resolving anymore.
87 | | Use the `resolve-http` feature which enables `native-tls` as well;
88 | | or both `reqwest` and `rustls` features together, if you prefer rustls."#
89 | |                     );
   | |_____________________^
```

**Comment by garypen** [comment]
This is a bug in jsonschema 0.15.2. We will pin to 0.15.1 until the bug is resolved. See: https://github.com/Stranger6667/jsonschema-rs/issues/356 for more details.

**Comment by Stranger6667** [comment]
Hi @garypen

I am looking into fixing this, hopefully, it will be resolved in the next few days. Sorry for the complications.

**Comment by garypen** [comment]
> Hi @garypen
> 
> I am looking into fixing this, hopefully, it will be resolved in the next few days. Sorry for the complications.

@Stranger6667 . No problem and thanks for working on such a great crate. Let us know if you want us to test anything before you get your release ready.
