### ISSUE TITLE
Can PluggableRouterServiceBuilder create Sync service?

### ISSUE THREAD

**Issue by DoumanAsh** [apollographql/router#897]
Right now service is created with `BoxCloneService` which has `Clone`, but sadly not `Sync`
Would it be possible for it to be changed?
I know using `core` part is not intended use case, but lack of `Sync` makes it a bit difficult to use in multi threaded serves.

**Comment by abernix** [comment]
This is currently a constraint of Tower, so it's unlikely we'll be able to do anything about this.  If you can give us a concrete example of what you're trying to accomplish, we might be able to provide some guidance.

You may also want to consider the solution offered in https://github.com/apollographql/router/issues/657#issuecomment-1069151232 which utilizes `buffer`.  You may also appreciate [looking at our `buffered` method.](https://github.com/apollographql/router/blob/9a62ca16862340cc049d2119c2c790a6fffb0570/apollo-router-core/src/services/mod.rs#L690)

I'm going to close this for now, but happy to re-open with a use-case we can explore and discuss further.

**Comment by DoumanAsh** [comment]
@abernix As example I was embedding core router inside our app which uses axum
Below is my test example


```rust
async fn super_handler(supergraph: Extension<Arc<graphql_router::Schema>>, parts: http::request::Parts, req: axum::Json<GraphqlRequest>) -> axum::Json<GraphqlResponse> {
    let req = req.0;

    let user_subgraph = LocalGraphBuilder::new("user".to_owned(), user::schema);
    let product_subgraph =
        RemoteGraphBuilder::new("product".to_owned(), "http://127.0.0.1:9000/product".parse().unwrap());
    let review_subgraph = RemoteGraphBuilder::new("review".to_owned(), "http://127.0.0.1:9000/review".parse().unwrap());
    let mut router = GraphqlRouter::build(supergraph.0)
        .add_subgraph(user_subgraph)
        .add_subgraph(review_subgraph)
        .add_subgraph(product_subgraph)
        .finish()
        .await
        .expect("to create router");

    let request = apollo_router_core::http_compat::Request::from_parts(parts, req);
    match router.handle(request.into()).await {
        Ok(result) => match GraphqlResponse::try_from(result.response.into_body()) {
            Ok(response) => axum::Json(response),
            Err(error) => panic!("Cannot parse response: {}", error),
        },
        Err(error) => panic!("Unexpected error in router: {}", error),
    }
}
```

In axum you can use `Extension` to provide any `Clone`-able object as parameter to endpoint.
So my initial idea was to build RouterService outside of endpoint code and use `Extension` to share it, but unfortunately it requires object to be `Sync`-able.


P.s. `GraphqlRouter` is my wrapper for `PluggableRouterServiceBuilder`

```rust
#[derive(Clone)]
pub struct GraphqlRouter {
    pub schema: Arc<Schema>,
    service: tower::util::BoxCloneService<RouterRequest, RouterResponse, HandleError>,
}
````
