### ISSUE TITLE
Respect core specifications' `for: core__Purpose`

### ISSUE THREAD

**Issue by abernix** [apollographql/router#901]
Notably, we should support [this section of the core specification](https://specs.apollo.dev/core/v0.2/#@core/for) in the same way as we enforce it with Apollo Gateway.  This was originally introduced in https://github.com/apollographql/federation/pull/957 to the `@apollo/gateway`, but has since evolved in terms of implementation and it's worth looking at the current implementation (which may very well [rely on `core-schema-js`](https://github.com/apollographql/core-schema-js/))

**Comment by o0Ignition0o** [comment]
I think it got closed by https://github.com/apollographql/federation-rs/pull/111 @Geal feel free to reopen if I got this wrong

**Comment by Geal** [comment]
Yes this should be solved with the usage reporting PR that updates router-bridge
