### ISSUE TITLE
UX: display help when query planning on a previous generation supergraph

### ISSUE THREAD

**Issue by abernix** [apollographql/router#915]
Apollo Router uses the Federation 2 query planner, which is capable of query planning from both **pre-Federation 2** _and_ **Federation 2** supergraphs.

Currently, when loading a previous generation supergraph into the Router, if there is something notably incorrect with the supergraph schema which wasn't detected by the previous generation query planner (present only in the JavaScript `@apollo/gateway@0.x` series) but **is** — thanks to improved validations — detected by the Federation **2** query planner, the query planner implementation (and thus, the Router, which uses the query planner) is produces an error.  That error appears similar to the following but is dependent on the actual supergraph being loaded:

```
cannot create the router: couldn't build Router Service: query planning had errors: bridge errors: UNKNOWN: Cannot find type HornStyle in subgraph unicorns
```

This error is absolutely representative of a newly found _mistake_ in the existing relationships defined in subgraphs and is worth looking at.   Often, it is a small omission from an existing subgraph (e.g., missing `@key` directive, or `@requires` field-sets which are referring to fields that don't exist) and simple to adjust!

While there isn't much that the Router **itself** can do to point the user to the site of the mistake, Federation 2's composition (which is invoked through `rover supergraph compose`) does provide substantially better diagnostics and debugging information than its predecessor.

On account of that, we may want to make it clear to those running previous generation supergraphs that there's a diagnostics path which can help unblock them.   Previous generation supergraphs can be identified through the presence of `@join` directives referencing the `join/v0.1` specification (Federation 2 supergraphs will instead reference `join/v0.2`).

This issue proposes that we display a friendly message _in addition to the error message_ with the suggestion that the user try composition with Federation 2 to find the full error message:

```
For help with this error, try re-composing your subgraphs with Federation 2 in order to benefit from its improved error messaging and diagnostics.  You can then "backport" any adjustments you discover to your existing subgraphs, without needing to fully upgrade to Federation 2 at the current time.  For details, see: https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2/#configure-your-composition-method
```

Feel free to bikeshed this message!  We can make `https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2/#configure-your-composition-method` into a `go.apollo.dev/r/` short-link to make the message appear cleaner.

**Comment by abernix** [comment]
We now have https://github.com/apollographql/federation/pull/1796 upstream which should address this.  When that lands, we should discuss whether we want to add a test for it to prevent any regressions if we ever move the implementation.

**Comment by abernix** [comment]
Yes, let's write a small test just to make sure it's there: this is one of those things that could evolve over time in terms of the actual message.

**Comment by Geal** [comment]
looking more closely at https://github.com/apollographql/federation/pull/1796 the error message is implemented in `extractSubgraphsFromSupergraph` which we do not use yet, so it won't appear in the router

I was thinking of using it in the future to do response validation at the subgraph level (so I need the subgraph schema), but in the meantime it might be easier to manually detect the presence of a join 0.1 directive?
