### ISSUE TITLE
Doc: Using the router as a library

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#955]
Must cover:
* Basic setup
* Licence key considerations

**Comment by lennyburdette** [comment]
Questions I've had:

* What other dependencies besides apollo-router and apollo-router-core are necessary? There are several in the hello-world example: https://github.com/apollographql/router/blob/main/examples/hello-world/Cargo.toml
* Examples for including the router libs from different places. I eventually landed on this to get things working:
    ```rs
    apollo-router = { git = "https://github.com/apollographql/router", branch = "main" }
    apollo-router-core = { git = "https://github.com/apollographql/router", branch = "main" }
    ```
    but eventually we'd add crates.io references. 
* Some basics on how the `register_plugin!` macro works.

**Comment by lennyburdette** [comment]
Also, I'm guessing the docs.rs page will be a great resource for extension APIs, like the definitions of `RouterRequest`, `RouterResponse`, `SubgraphRequest`, `SubgraphResponse`, etc. Do those get published when crates are published?

**Comment by DoumanAsh** [comment]
I have comprehensive example for using `apollo-router-core` which covers own subgraph implementations and custom plugin https://github.com/DoumanAsh/graphql-router-example

**Comment by BrynCooke** [comment]
> Also, I'm guessing the docs.rs page will be a great resource for extension APIs, like the definitions of `RouterRequest`, `RouterResponse`, `SubgraphRequest`, `SubgraphResponse`, etc. Do those get published when crates are published?

Yes, but we'll not be publishing until we get nearer to 1.0. In particular we are considering merging the router and router-core crates. After that we may start publishing.

**Comment by DoumanAsh** [comment]
But that sounds like bad idea. `router` introduces tons of extra dependencies necessary to power up web server
Having separation of core is good for embedded users

**Comment by BrynCooke** [comment]
> I have comprehensive example for using `apollo-router-core` which covers own subgraph implementations and custom plugin https://github.com/DoumanAsh/graphql-router-example

Looks interesting! The ask from our users however is a little different. In particular many of them want to write Rust as a last resort. This means just creating the appropriate cargo toml and using the following:

```
fn main() -> Result<()> {
    apollo_router::main()
}
```
Plugins that are specified as dependencies are automatically discovered, and added to the configuration.

In the future we anticipate adding Subgraph pluggability via yaml, so at that point your example could at that point be adapted to use this model. Other types of subgraph could include rest adapters/database adapters.

**Comment by DoumanAsh** [comment]
using `apollo_router::main()` means that you cannot really embed it into own web server so I'm not sure how is it different from just deploying existing binary...

I would think that actual embedded use would incorporate router-core into existing web server

**Comment by BrynCooke** [comment]
We are not abandoning the embedded scenario. In particular lambda with tower support is interesting, but we want to bring the plugin yaml configuration and hot reload to embedded users.
 
I could imagine a future where hyper was a feature that could be excluded and `ApolloRouterBuilder` would allow building of a `tower::Service`.

**Comment by BrynCooke** [comment]
Also, it's not certain that the merge will happen, it's still only for consideration right now. The other advantage of keeping core separate is that it helps keep our code clean.

**Comment by DoumanAsh** [comment]
Another aspect that is currently lacking for truly embedded usage is to programmatically generate schema
In our use case we want to be able to upgrade/downgrade subgraph service any time so we're considering how to fetch and generate supergraph schema on fly.

Right now router itself has no means of that, so we probably need to just look up using `rover` as library but ideally it would be good to have it documented for embedded usage too
