### ISSUE TITLE
use subgraphs on starstuff in CI integration tests

### ISSUE THREAD

**Issue by Geal** [apollographql/router#997]
we have a complicated machinery to start and stop subgraphs from the federation demo for integration tests in CI, this increases build times, cache size, and overall tends to fail (#994).
Those subgraphs are already deployed on starstuff.dev: https://github.com/apollographql/router/blob/main/examples/graphql/supergraph.graphql

so we could use them directly in integration tests.

We need additional steps:
- deploy a gateway along with the subgraphs, so we can compare router and gateway in some tests
- the subgraphs should be redeployed in the demo is updated
- how will that affect the jager test? Do we need to deploy a jaeger somewhere too?

**Comment by o0Ignition0o** [comment]
We're still having one failing test because we re expecting some spans to end up in jaeger; so we might need to deploy it to starstuff!
